### ISSUE TITLE
In DMs and after posting, the associated icon gets a notification icon

### ISSUE THREAD

**Issue by thegamebegins25** [damus-io/damus#100]
After you make a post/send a dm, the home icon/dm icon receives a notification bubble. You shouldn't receive a notification for a post that you make. Please add an `if` statement so it won't send a notification if the author of the post is yourself.

I'm not very experienced with Swift/XCode (as I don't own a Mac), but if I was, I would definitely make a PR.

**Comment by jb55** [comment]
I believe this was fixed by

- #176
