### ISSUE TITLE
Fit custom zap menu in screen [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1015]
_what happens_

Custom zap menu jumps out of screen. I suspect this has to do with font size settings. See "zap type", and "make default" below:

![image](https://user-images.githubusercontent.com/64376233/234448775-68a021ed-3f32-43ac-a260-b42ce464739b.jpeg)

Related to custom zap menu PR https://github.com/damus-io/damus/pull/975 

@ericholguin

**Comment by ericholguin** [comment]
What phone?

**Comment by alltheseas** [comment]
12 mini
