### ISSUE TITLE
URL with parenthesis ")" is broken

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1027]
_what happens_
URL that ends in ) is broken
![image](https://user-images.githubusercontent.com/64376233/234737187-436ac1ea-59cb-4573-917b-fcb353f98093.jpeg)

![image](https://user-images.githubusercontent.com/64376233/234737195-79b15f85-5fc9-4168-99fc-a6543c94d324.jpeg)

Origin: damus.io/note1wzdzy32crfmpz6jusd8954zqr3zvy2wucm4p8r9pl0kxpfqmkedsllf720

@olheadinternet

**Comment by alltheseas** [comment]
Related to broken URL: https://github.com/damus-io/damus/issues/278

**Comment by alltheseas** [comment]
@kristapsk reported remains broken

cc @jb55 @joelklabo has a PR outstanding I believe

**Comment by jb55** [comment]
On Mon, Jul 31, 2023 at 01:55:08PM -0700, alltheseas wrote:
>@kristapsk reported remains broken
>
>cc @jb55 @joelklabo has a PR outstanding I believe

I'll have to dig that one up again...  we should merge it

**Comment by alltheseas** [comment]
> On Mon, Jul 31, 2023 at 01:55:08PM -0700, alltheseas wrote:
> >@kristapsk reported remains broken
> >
> >cc @jb55 @joelklabo has a PR outstanding I believe
> 
> I'll have to dig that one up again...  we should merge it
> 

https://github.com/damus-io/damus/pull/1063
