### ISSUE TITLE
User tag autocomplete message area blocks text input

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1038]
When attempting to autocomplete a username, the results overlay blocks the original message entry area. If a username is not found, it is very difficult to get back to the message field. Requires hitting the delete key many times until the npub is deleted completely. 

I suggest allowing more space for this so the user can correct mistakes in thier note entry field.
![IMG_5890](https://user-images.githubusercontent.com/3638467/235214366-7e07a036-eb85-4536-8b0c-062a0d6ed484.jpg)

**Comment by alltheseas** [comment]
Great suggestion. Recreated bug. Adding to backlog. https://user-images.githubusercontent.com/64376233/235231630-c36aaa9d-4e41-4e5e-8643-73e5c1b8bf92.MOV

**Comment by alltheseas** [comment]
@dmnyc is this resolved for you?

**Comment by dmnyc** [comment]
Yes, the display box size and position is no longer an issue, however another tagging issue appeared recently. 
https://github.com/damus-io/damus/issues/1544
