### ISSUE TITLE
Difficult to manually set zap amount

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1040]
In the latest Damus build featuring the new zap screen, it's difficult to edit the default zap amount without a visible cursor.

Could we have an (X) or Clear button to reset the amount and allow the user to input it without entering an amount on top of what's already on screen?

https://user-images.githubusercontent.com/3638467/235216847-ed0c9c5f-4413-40f6-914f-37c3e06ac3ba.mp4

**Comment by alltheseas** [comment]
@ericholguin what do you think of adding a clear button? 

@dmnyc there is an Eric outstanding PR that will add a <make default> button

**Comment by dmnyc** [comment]
Could we also please add more smaller denominations like 100 💯 and 1000 😄sats which would be much more useable than 1 million? Nobody is sending 1 million sats on a regular basis to need a preset for that.
@jb55 
![image](https://user-images.githubusercontent.com/3638467/235454811-9c911a64-d91c-4dc5-9fcc-989c304bae42.jpeg)

**Comment by jb55** [comment]
eventually we will just make these all customizable

**Comment by BenGWeeks** [comment]
FYI @sashapavlova @robagreda

**Comment by ericholguin** [comment]
Visible cursor was added
