### ISSUE TITLE
npub search fails on initial attempt, succeeds on subsequent attempt [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1044]
_what happens_
Sometimes when I search for a particular npub I have copied from elsewhere, on the first search attempt no results appear.
On a subsequent attempt npub appears.

https://user-images.githubusercontent.com/64376233/235260150-82c8c1e8-f66b-4c6a-95ea-16362b134f36.MOV

**Comment by gladiusKatana** [comment]
Just found _one_ solution - will post PR momentarily.  (It's just a multithreading issue or at least that's one way to remove the bug - see below. Also - bug may not occur as often when searching larger profiles eg. @Damus [npub18m76awca3y37hkvuneavuw6pjj4525fw90necxmadrvjg0sdy6qsngq955]

In case anyone reading this wants to replicate the issue, Here is a fresh npub (will also post it in PR; searching this throwaway account should ~always~ result in the bug : npub1j6rzjsn0pgvf85cfa32glnx7djmuk6t5pz4c3yrly370z2cvfhussmdg8y

The fix: 

in `SearchingEventView` / `handle_search` : 

```swift
        case .profile:
            find_event(state: state, evid: evid, search_type: search_type, find_from: nil) { _ in
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1 ) { // <-----
                    if state.profiles.lookup(id: evid) != nil {
                        self.search_state = .found_profile(evid)
                        return
                    } else {
                        self.search_state = .not_found
                    }
                } //<-----
            }
```
