### ISSUE TITLE
Relays Keep Reverting to Older Versions 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1052]
_bug report_
> my relay list in damus keeps reverting to an older version

_what should happen_
No relay reversion should take place

_context_
It could be that third party apps (for instance for key management, and/or other clients) interfere with Damus relay list.

See related feature request: Cache Relays https://github.com/damus-io/damus/issues/1054

https://damus.io/note1uhjgqj3f0c6gfmpe67d08u8japhc9fx2pdh90dqet00u66werhdsfntq4u

https://damus.io/note1tgqz7xh3aqvlu9epf8u4q3r6k588zesjavsnr9ts5yz65ssx0lls3xslc3

https://damus.io/note1tgqz7xh3aqvlu9epf8u4q3r6k588zesjavsnr9ts5yz65ssx0lls3xslc3

Bug Origin: Jeff

**Comment by alltheseas** [comment]
Old: https://github.com/damus-io/damus/issues/409

**Comment by alltheseas** [comment]
> For me this is really when I set the relays in the Nostore safari extension, the same as in my Damus client, that I stopped having the problem.  

-p2x

https://damus.io/note1gnxwu4h7vnfqkszdc8s4qst6su6weahephkgy7kr9g6y3yqjcxese0x00e

**Comment by alltheseas** [comment]
@bryanmontz is this addressed by your fix of the relay disconnect problem?

**Comment by alltheseas** [comment]
https://damus.io/note1tw5nxgxw6u4m3hpwhmc28ngyrh046uutjp20q7g78tqxscs4chusam0g29

> Is it only me or the relay issue continues to exist? I try to add a relay and remove all the default/recommended ones. Add some events, close the app after some time and reopen, the relay I set is gone and the default relays get added back. Tested with v1.6. Tried the other clients and they all work fine.

**Comment by alltheseas** [comment]
> The other clients used were Nostur, Plebstr, Snort. The relay it defaults to in Damus is nos.lol

**Comment by jb55** [comment]
On Thu, Nov 16, 2023 at 10:30:26PM -0800, alltheseas wrote:
>https://damus.io/note1tw5nxgxw6u4m3hpwhmc28ngyrh046uutjp20q7g78tqxscs4chusam0g29
>
>> Is it only me or the relay issue continues to exist? I try to add a
>> relay and remove all the default/recommended ones. Add some events,
>> close the app after some time and reopen, the relay I set is gone and
>> the default relays get added back. Tested with v1.6. Tried the other
>> clients and they all work fine.

The misunderstanding here is that the bootstrap relays are always used
to find the latest contact list, when it finds the list then it will
promptly disconnect from the bootstrap ones if its not on the contact
list.

This is fixed by #1734 where we will not require bootstrap relays to
fetch your latest contact list.

**Comment by alltheseas** [comment]
> On Thu, Nov 16, 2023 at 10:30:26PM -0800, alltheseas wrote:
> >https://damus.io/note1tw5nxgxw6u4m3hpwhmc28ngyrh046uutjp20q7g78tqxscs4chusam0g29
> >
> >> Is it only me or the relay issue continues to exist? I try to add a
> >> relay and remove all the default/recommended ones. Add some events,
> >> close the app after some time and reopen, the relay I set is gone and
> >> the default relays get added back. Tested with v1.6. Tried the other
> >> clients and they all work fine.
> 
> The misunderstanding here is that the bootstrap relays are always used
> to find the latest contact list, when it finds the list then it will
> promptly disconnect from the bootstrap ones if its not on the contact
> list.
> 
> This is fixed by #1734 where we will not require bootstrap relays to
> fetch your latest contact list.
> 
Is this one related? 


https://damus.io/note1tz3975q0mn7rkgwhjtdeau37t34zyj20dljxmh3lxxshmfvzlhgqj33xu0

> My relays keep disappearing from Damus, all of them. Sometimes this is fixed by signing out then back in, the 4 bootstrap relays will appear, then a few hours later back to 0 relays?

> This happening to anyone else? I'm using several other clients and they don't seem to be experiencing the same behavior. 

> am using Snort, Coracle, Primal, noStrudel at the moment. I may have signed into some specialty clients as well like Yakihonne or Listr recently as well. 

> I just wrote a script that pulls down my contact list from any discovered online relays and trying to do a bit of investigation of my own as it seems to be working fine for everyone else.

**Comment by alltheseas** [comment]
haven't heard of this bug in months
