### ISSUE TITLE
Cache Relays [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1054]
## User Story
As a frequent Damus user, I would like Damus to make sure that my relays are always saved, so that I do not lose my relays if I experience any event that may trigger a reversion of my relay list (bug, loss of connectivity, incompatibility with other apps etc).

### Acceptance Criteria
1.Damus caches relays list, and does not revert to older versions

See Relays Keep Reverting to Previous Version bug https://github.com/damus-io/damus/issues/1052

**Comment by alltheseas** [comment]
@bryanmontz is this addressed by your fix of the relay disconnect problem?

**Comment by alltheseas** [comment]
@jb55 does Damus currently cache relays?

**Comment by jb55** [comment]
On Fri, Sep 22, 2023 at 10:51:45AM -0700, alltheseas wrote:
>@jb55 does Damus currently cache relays?

yes, it will save your set as the default bootstrap relay set

**Comment by alltheseas** [comment]
Implemented
