### ISSUE TITLE
nostr:npub link does not render in Damus [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1070]
_what happens_
nostr:npub1etc.. does not render into a link in app

![image](https://user-images.githubusercontent.com/64376233/235977816-1fdb2f41-5809-40ea-9f92-d8eff66b6a32.jpeg)

https://damus.io/note1fr5yvrazdqwkp8c5nmyllu5ujepz9mf2msypsqay2cm0hcz62awsckl4sa

![image](https://user-images.githubusercontent.com/64376233/235978057-b23e3eab-192b-4847-b6c0-ef32ff736443.jpeg)

https://damus.io/note1lm5eyuakkarqchps89xtevjmrmevjyuznjlcvxqrfvmkqw63xukqmzfx99

_what I think should happen_
nostr:npub1etc.. *should* render into a tappable link in app

**Comment by alltheseas** [comment]
@tyiu PR https://github.com/damus-io/damus/pull/1130

**Comment by tyiu** [comment]
This is fixed but not by my PR referenced above.
