### ISSUE TITLE
Tagged npubs not rendering in 1.4.3(19)

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1077]
I saw the tagged npub in this post in timeline view but in subsequent views, it was missing and replaced with #[0]

Note:![image](https://user-images.githubusercontent.com/3638467/236243739-fc65cea8-1cee-493c-a40f-71e2b02d92ab.png)
note13e0r9mcfm97cvmqslfnyytrezn7fzpdceh95lpk8spk6rn5cxyzqpcmh7h

**Comment by dmnyc** [comment]
Another example:

note1wn7ncl98wqntj3dghlr237mve8z0nvfyxgx3xvztht9zl3avky4qj68mkj

![image](https://user-images.githubusercontent.com/3638467/236256901-3eb2bf51-7a51-4940-9922-c8d6beac153f.png)
![image](https://user-images.githubusercontent.com/3638467/236256920-7bc9587e-3435-4a41-baa9-99650fb45161.png)

**Comment by alltheseas** [comment]
Thanks @dmnyc I think Will is aware of this one, and if I'm not mistaken a fix is coming: 

https://damus.io/note1h4gqvezw4hgp9vag32lrjmsz79lleqeaqpczwmu3w66j2mahkncs3h8a44

Let's see if that fixes it

**Comment by jb55** [comment]
let me know if you see this in 20

**Comment by dmnyc** [comment]
Seems to be fixed!

**Comment by alltheseas** [comment]
So far so good - let's give it 24 hours of testing?

**Comment by alltheseas** [comment]
@dmnyc you still seeing the #[1]?

**Comment by dmnyc** [comment]
Nope - all good now!

**Comment by alltheseas** [comment]
Same here - if you're happy can you close issue 🙏
