### ISSUE TITLE
Some animated GIF images appear static

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1079]
Example note:
note193k4vadctnu6hhunr83saywxx6ah4ly38nq8uu2gstcc0xtt2t4q9runsd

This image plays normally in a browser, but on Damus 1.4.3(2) it appears static. 
 https://nostr.build/i/nostr.build_9cf3a56f4a15039c42726306069167a232cce2e27f9fc725b1f503f50b4877dc.gif

**Comment by dmnyc** [comment]
I had to toggle off and on animations in the settings. Somehow it got selectively deactivated. It's working for me now.

**Comment by alltheseas** [comment]
Possibly related to https://github.com/damus-io/damus/issues/1072

**Comment by dmnyc** [comment]
Attaching a video recording showing the issue and how I have to toggle the settings to fix it. @jb55 
https://nostr.build/p/nb7886.mp4

**Comment by alltheseas** [comment]
@dmnyc do you have reduce motion enabled in iOS settings?

**Comment by dmnyc** [comment]
Nope, just checked.

**Comment by alltheseas** [comment]
> No, that’s not it either

> If I copy a gif url from the internet displays as a still image

> If I download it to my phone and then upload it through Damus interface it displays correctly

https://damus.io/note1cmhx4dwxak0yj9nscaj3hmzw3vjvgrs5z0v3wmpx7k9fh9ukd2rssld8lm

**Comment by shawnyeager** [comment]
@dmnyc's temp fix works for me, too.

**Comment by joshuajiangdev** [comment]
Hmmm, cannot reproduce. Is there anyway to reproduce?

**Comment by dmnyc** [comment]
I’ve found it frequently happens after I post a note containing an link to
an animated GIF image on nostr.build. I wonder if the file size of the
initial image download could be an issue.

**Comment by shawnyeager** [comment]
I’m also using nostr.build, and while it’s an intermittent problem, size of the gif makes sense as the culprit. The next time it happens, I’ll be sure to capture the GIPHY link.

**Comment by dmnyc** [comment]
Here's an example I found.

https://damus.io/note1vd3phfh6y5pgca2tam6svtpyx2wzkmhf0276pqr4y6p27k5xs26q57r6lm

https://media.tenor.com/kiv30bAOYtEAAAAC/gandalf-yes.gif

**Comment by alltheseas** [comment]
The above gif works for me in damus. @dmnyc is it broken for you?

**Comment by alltheseas** [comment]
Are you on wifi or cell network when you try to load the example gif?

**Comment by dmnyc** [comment]
I was on wifi when it first happened. After resetting the animation setting it works now on cellular or wifi.

**Comment by dmnyc** [comment]
Here's a follow-on example:

note19cjuckj2s230xyv4ujq960c7rssfyqmuftj79mgmzk32rd2h4a8qxk5eyg

https://damus.io/note19cjuckj2s230xyv4ujq960c7rssfyqmuftj79mgmzk32rd2h4a8qxk5eyg

Screen capture:
https://nostr.build/p/nb9499.mov

**Comment by alltheseas** [comment]
Confirming the latest one is static for me

**Comment by alltheseas** [comment]
@dmnyc 

 gifs working for you with latest update?

**Comment by dmnyc** [comment]
Seems OK now @alltheseas 

https://damus.io/note10n03e93eknssnqyep5w3n5h704fyyu3d5cend9qlz40ngvuuep6sul7rq9

Let's keep this open another few days in case I find anything.
