### ISSUE TITLE
[Improvement] Pasting copied UserID / NoteID after "&" always inserts a space

### ISSUE THREAD

**Issue by kdmukai** [damus-io/damus#108]
On Mac, not sure about on iOS:

* Copy a UserID or NoteID.
* In a new post, reference the id with "&" and then paste in what you copied.
* A space char is always introduced between the "&" and the ID.
* A failed/not linked reference results if you're not careful.

The context menu's Copy UserID and Copy NoteID work fine; no leading space added. It's only when pasting in front of an ampersand.

**Comment by jb55** [comment]
weird, but you should be doing @note to reference a post. I'll try to fix the rendering of this so it's not so confusing. we shouldn't be showing hex anywhere

**Comment by kdmukai** [comment]
Just tested: Space char is only added after "&". Starting with "@" behaves as expected.

So I learned about the "&" references two days ago. Is that old info now?

**Comment by jb55** [comment]
I believe this is no longer relevant
