### ISSUE TITLE
Damus does not remember history of going from one profile to another

### ISSUE THREAD

**Issue by kristapsk** [damus-io/damus#1121]
If I go from main timeline to profile of person X (Alice), then from it go to profile of Y (Bob), when I tap back arrow from Bob, it does not go back to profile of Alice, as would be expected, but back to main timeline.

With v1.4.3.

**Comment by alltheseas** [comment]
Somewhat related to navigation returns to wrong spot in home feed https://github.com/damus-io/damus/issues/751

**Comment by alltheseas** [comment]
> If I go from main timeline to profile of person X (Alice), then from it go to profile of Y (Bob), when I tap back arrow from Bob, it does not go back to profile of Alice, as would be expected, but back to main timeline.
> 
> With v1.4.3.

@kristapsk can you kindly provide a screenrecord, so the devs have a visual manual to see each step, and recreate the issue 🙏

**Comment by alltheseas** [comment]
Works for me in following flow:
https://github.com/damus-io/damus/assets/64376233/a25fe417-b85a-4a37-967a-dbebf420f179

**Comment by alltheseas** [comment]
@kristapsk is this fixed for you?

If not, can you kindly provide a screen recording 🙏
