### ISSUE TITLE
Cannot connect to many working relays [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1132]
_what happens_

Consistently connecting to half of my relays. Relays are confirmed online per nostr.watch. Disconnecting from, and adding back relays fixes problem temporarily.

Boston wine:
> Since the last TestFlight update, whenever I open Damus I am only connected to 1/19 relays, and I need to restart the app at least once or twice to connect to the rest.

> Anyone else having this?

https://damus.io/note10raf6s7te0htpcld498q2kmru0vs08l45uft3lwr03ftyprmg7ss2adxsv

**Comment by alltheseas** [comment]
Boston: 

> Hey @jb55​ I’m still getting the 1/19 relays connected, at least 50% of the time I open Damus

https://damus.io/note1vsac7p52xeggxjhl7edvck0rgupfx75cmmnhch2smfszr0vcaqkqcqz84l

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/f1022665-2129-4a96-958c-657e124a569d)

https://damus.io/note1k2jtd085467vvcwkzp8cltnw3av0r53ntqfhwg45dfaw3nguexdqug0ku7

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/9f4b80e2-369f-403a-ba5e-ac308d168c6b)

https://damus.io/note15k7ax9cwwlv6whjw4wz7cwwhu488zy8hua8h2q9zj4527mkf9tvszxzjcm

**Comment by alltheseas** [comment]
Overlap/duplicate https://github.com/damus-io/damus/issues/1030

**Comment by alltheseas** [comment]
https://damus.io/note1s2aldeuhkt00pkgwf8hg0akr77rmpejphza56qe02jked8w3en4qcxanu4

**Comment by alltheseas** [comment]
Continued reports 

https://damus.io/note13vj3zrqjef2k4zs6clz6q5s42aqwn77lty6h4hu9gxzdcmseelvqfndek4

**Comment by alltheseas** [comment]
https://damus.io/note163ygnzqsf6hw9kmkuehqjw6myy74qdpa5kn5k9fxnxe2rr3svdmq9mh2lv

**Comment by alltheseas** [comment]
@bryanmontz recreated https://github.com/damus-io/damus/pull/1298

**Comment by dmnyc** [comment]
I've had the same issue with or without VPN.

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/issues/1589

**Comment by jb55** [comment]
how common is this? I rarely run into it.

**Comment by alltheseas** [comment]
Has not happened to me lately
