### ISSUE TITLE
At tag trouble when composing / cannot escape purple text after deleting mention

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1156]
@ tag delete trouble 

https://github.com/damus-io/damus/assets/64376233/9f941295-71b3-4a8f-9771-d18d053c8c55

Origin: @jeffthibault

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/issues/1280 is duplicate

**Comment by alltheseas** [comment]
https://damus.io/note1zmj8z3906rd5zmynuqwr8kqv6h794n7rtk9juff0qfvfym5wxglq8lhrpg

**Comment by kernelkind** [comment]
I can't replicate this issue

**Comment by alltheseas** [comment]
Neither can I, thanks
