### ISSUE TITLE
[Feature Request] Add view to see users that liked/boosted a post

### ISSUE THREAD

**Issue by jeffthibault** [damus-io/damus#116]
Useful feature in twitter. Would be nice to have in damus as well

**Comment by bebopkid** [comment]
I personally like that you can't see who liked a note but I know this is not shared by everyone :)

**Comment by olheadinternet** [comment]
i see how not showing directly on the note might be healthy. but i would like at least a notification that x liked y note. I don't want to send a note with just an emoji to poke my head out.

**Comment by bebopkid** [comment]
i like your idea of being able to see it somewhere but not on the note itself. where would this go? perhaps it just gets logged in notifications only?

**Comment by olheadinternet** [comment]
how legacy new media does this is
> Bebopkid liked your note
> then shows the body of the note in a a grey color in tiny text here so you can easily understand what they liked
