### ISSUE TITLE
Suhail broke the Photo Gallery [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1170]
_what happened_

Gallery breaks on transition to third image

See https://github.com/damus-io/damus/assets/64376233/37051990-4d01-408e-92aa-ddec154bb925

https://damus.io/note17ht939zjtv0yc3pm73tucpfkq98ru7ftr6l6qqjwnkkxal0sxdcsduzes9

Origin: @joelklabo

**Comment by BenGWeeks** [comment]
Possibly fixed with the new carousel.

**Comment by alltheseas** [comment]
Is this the new carousel PR: https://github.com/damus-io/damus/pull/1004

**Comment by BenGWeeks** [comment]
> Is this the new carousel PR: #1004

Yes, but this should be tested on a physical device. We need to give @jb55 instructions on how to get developers permissions to a development certificate so we can (more easily) test this locally on actual hardware.

**Comment by alltheseas** [comment]
This looks fixed. @BenGWeeks  is it working for you?

**Comment by alltheseas** [comment]
Duplicate? of https://github.com/damus-io/damus/issues/963
