### ISSUE TITLE
Global throttling events to one per pubkey (bounty!)

### ISSUE THREAD

**Issue by brugeman** [damus-io/damus#1189]
Global tab is only showing one event per pubkey, as written in the SearchHomeModel.

That might be a useful strategy for the raw global feed to limit the impact of a single spammer. However, it seems to do more harm than good for cases where global is limited by the user to some set of filtering relays - like paid relays, or curated feeds (i.e. wss://feeds.nostr.band/memes). 

I'd suggest adding a switch to turn-off this throttling, probably in the same screen where global relays are switched on and off.

**Comment by brugeman** [comment]
Adding a 100k sats bounty for a solution to this.

**Comment by alltheseas** [comment]
How do you make sure there are only memes on the meme relay?

**Comment by brugeman** [comment]
> How do you make sure there are only memes on the meme relay?

That feed is managed by a person, the list of seeds is here https://feeds.nostr.band
