### ISSUE TITLE
User remains logged in after explicitly logging out and closing app

### ISSUE THREAD

**Issue by jeffthibault** [damus-io/damus#12]
Steps to reproduce:

1. Logout of Damus (automatically returns to login/sign up page)
2. On login/sign up page, close the app (hold and swipe up from bottom of the screen)
3. Re-open Damus

The user is now logged in and shown their home page.

I would expect the user to be shown the login/sign up page because they explicitly logged out before closing the app.

**Comment by jb55** [comment]
Good point! I have never tested this flow haha. should be an easy fix.
