### ISSUE TITLE
Support for NIP-27 nostr:note format

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1205]
Would it be possible to support the use of nostr: formatted note IDs, so for example we can search and tag notes like this that are copied from clients like Primal?

nostr:note18u6egyzh3jv8yr2fcm33vcjhekqznts6sz9efqlzxpwm2q8868usrd5paq

**Comment by alltheseas** [comment]
Could you provide a noteID with the above format?

**Comment by alltheseas** [comment]
Can you also add NIP-27 to title 🙏  

https://github.com/nostr-protocol/nips/blob/master/27.md

**Comment by jb55** [comment]
these are already supported

**Comment by dmnyc** [comment]
Thanks!

**Comment by tyiu** [comment]
Clarification: Damus supports reading and formatting notes in NIP-27 format already, but I just opened a PR for writing notes in this format as well (instead of NIP-08 #[0] #[1] ... indexed mentions)
https://github.com/damus-io/damus/pull/1213

**Comment by jb55** [comment]
@tyiu I was using nostr:npub as a way to do non-tagged mentions. with #1213 I assume this wouldn't be possible anymore ?

**Comment by tyiu** [comment]
> @tyiu I was using nostr:npub as a way to do non-tagged mentions. with #1213 I assume this wouldn't be possible anymore ?

@jb55 Correct. Is that a blocker from me merging my pull request? Maybe what we actually need (separately) is a UI component for selecting who to tag. Similar to what happens with replies.
