### ISSUE TITLE
Hide nsec when logging in & add hide/show toggle [security][feature request]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1206]
## user story
As a Damus user who logs in with their nsec when switching between profiles, I would like the nsec field on the log in screen to be hidden by default (e.g. with ***), so that I can protect the security of my key in case other people are around me while I enter my nsec.

### acceptance criteria
1. When the user is on the login screen, when entering (typing, or pasting) in nsec123etc.. by default alphanumeric values are hidden with ***
2. There is an "eye" icon that when toggled reveals, or hides the nsec

Origin: Nostr Report

> “Was hoping you could add a feature to hide NSECs after they are typed into the login screen. There should be a little 👁️ to reveal the nsec if you want to see it. Logging back and forth from my personal account to NostrReport means that my nsec is visible on my screen for a short period of time. “

examples 

<img width="1378" alt="Screenshot 2023-05-30 at 2 08 58 PM" src="https://github.com/damus-io/damus/assets/64376233/02bc21b2-e5f4-4245-bf27-f7005818a852">

**Comment by alltheseas** [comment]
@robagreda @ericholguin

**Comment by cr0bar** [comment]
Fix raised under PR #1371
