### ISSUE TITLE
Cursor artifact appears below text when entering text after tagging someone

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1214]
After tagging a user, I entered some text and saw a blinking cursor artifact appear a few lines below the text I was entering. I was able to repeat this after closing the app and trying to type the message again.

https://github.com/damus-io/damus/assets/3638467/67c79aef-ea69-4826-b77b-4680c3395038

**Comment by alltheseas** [comment]
> Duplicate of #1210

Closing duplicate issue
