### ISSUE TITLE
Welcome page on app discussion

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1215]
Learn more about nostr takes users to nostr.com which might be overwhelming, maybe something closer to nostr.how or something even simpler.

Also, are the sentences going to have periods? I see sentence with a period, but then two sentences without them.

Maybe change "The go-to iOS nostr client" to "The first iOS nostr client" or something focused on nostr. Damus an iOS client, looks cleaner

next page can be "Welcome to Nostr"

**Comment by alltheseas** [comment]
Can you provide a link to the page you are referring to?

**Comment by punterwantsawhalepass** [comment]
link to the page? it's the first page in Damus, the "Let's get started!" page
