### ISSUE TITLE
Slow performance when tagging users in 1.5 (3)

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1219]
I've been running into some performance/lagging when tagging or deleting tags in the latest build. 

The process of entering the user's tag is slower than expected and can cause the wrong user to get tagged. When deleting a tag, the same issue persists. 

Screen capture attached. https://github.com/damus-io/damus/assets/3638467/6a01c15f-af2d-4508-bbad-68e5a55c7398

**Comment by alltheseas** [comment]
Which device and OS version are you running?

**Comment by dmnyc** [comment]
![image](https://github.com/damus-io/damus/assets/3638467/1a03385d-f2c8-40d5-b33d-20afacca6d84)
![image](https://github.com/damus-io/damus/assets/3638467/dba9c157-575a-400b-bd87-3041404444dc)

**Comment by dmnyc** [comment]
@alltheseas If that's the case (around 2K follows/followers) it sounds like there needs to be some optimization because I am definitely not the only one who would be affected. I've got around 24 relays at the moment.

**Comment by alltheseas** [comment]
I'm checking with devs if these two issues are related.

For reference here is the 'too many followers' issue: https://github.com/damus-io/damus/issues/1176

There is a technical solution to the above, which is not currently a priority.

**Comment by tyiu** [comment]
> I'm checking with devs if these two issues are related.
> 
> For reference here is the 'too many followers' issue: #1176
> 
> There is a technical solution to the above, which is not currently a priority.

The performance issue is caused by having too many followers, because Damus' code isn't optimized yet for user search on large lists. This can be fixed.

But it's unrelated to the other linked issue, which is caused by relay implementations not being able to handle above a certain threshold.

**Comment by alltheseas** [comment]
What's the PR link for this @tyiu ?
