### ISSUE TITLE
Your Following backed up on your iPhone

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1231]
Would it be possible to backup your following list to your iPhone via the Damus app? So in the event that using another client deletes some of your follows you could restore from your iPhone and follow everyone on that saved list again? Maybe even encrypted it in iCloud as an option?

**Comment by alltheseas** [comment]
Thanks for the feedback. Here is a general "backup my data" feature request, that includes contacts. https://github.com/damus-io/damus/issues/527

**Comment by punterwantsawhalepass** [comment]
🤙

**Comment by jb55** [comment]
yeah I want this

**Comment by alltheseas** [comment]
See #527
