### ISSUE TITLE
Videos sounds can play over each other

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1238]
If you start a video and enable the sound, you can then go to another video and start it. You will then have two videos sound playing at the same time, the first one and the second one you are now watching.

Cool feature :) but may be better for app to cut off first video sound from streaming when the second one starts.

**Comment by alltheseas** [comment]
From @dmnyc 

> What happens:
In the new video player, if the sound is on and the video scrolls out of frame in timeline view, the sound continues playing on a loop.

> What I think should happen:
Video should pause or mute if it is no longer visible on screen.

Example note:
note16dvkw4tur4t7qljvnkq4knuey74l525f70d3hmxzqnw3mqhu798q7kt6dr

**Comment by alltheseas** [comment]
From @BenGWeeks 

https://github.com/damus-io/damus/assets/64376233/3811777c-15e6-4890-835d-6107da78d8b2

**Comment by alltheseas** [comment]
https://damus.io/note1jdjdkh2xphnz0lajpxvz6jx4xq3ffeuhflfguz4wkne6gt4e6qcss8uycq

**Comment by gladiusKatana** [comment]
By the way, funny story, apparently one of the big centralized social media apps had this bug as well recently😅 (the person who told me that thought it "might have been facebook?" and that it was on the web...I'll mention it here if i find out which!)

**Comment by alltheseas** [comment]
This seems fixed 1.5 (8)
