### ISSUE TITLE
URLs do not link if preceded by an emoji character

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1268]
What currently happens:

In timeline view, the URL in this note appears unlinked.
However in expanded view, the link appears.

What I think should happen:

All links that begin with http:// or https:// should link, regardless of whether there is an emoji character preceding it.

Reference note:
note142k73khmve8qh326pajvdtznrgrvweyt3yz7gpsgrfu5wm3pwr6q8wa9rp
https://damus.io/note142k73khmve8qh326pajvdtznrgrvweyt3yz7gpsgrfu5wm3pwr6q8wa9rp

This issue is similar to a previous report regarding hashtags.
https://github.com/damus-io/damus/issues/350
![IMG_6949](https://github.com/damus-io/damus/assets/3638467/2557b547-ed56-4552-b06b-0ed0f84557f4)
![IMG_6950](https://github.com/damus-io/damus/assets/3638467/4960ceff-770e-4113-94ce-79efcf221b1a)

**Comment by jb55** [comment]
This should be fixed now
