### ISSUE TITLE
Invalid zap 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1270]
Bug appears after zapvertising update 1.5 (4). Note that previously rendered ok prior to 1.5 (4), now is displaying as pictured below:

![image](https://github.com/damus-io/damus/assets/64376233/9d385325-b800-4373-aae6-597d6777c5a6)

https://damus.io/note1n8ah5z5hfsc0cyg4zprw5denv8keuvqslagcjc6wjl2vyftkrtcquyrsw4

**Comment by alltheseas** [comment]
Now displays as
![image](https://github.com/damus-io/damus/assets/64376233/7c06467b-2dc1-4b2c-a9f3-8cb46b21e97f)

**Comment by alltheseas** [comment]
And now back to the original state

🤔🤔

![image](https://github.com/damus-io/damus/assets/64376233/f598c09b-da95-4ed3-8541-1f49ebbcbef3)

**Comment by alltheseas** [comment]
Aaand back to step 1 😅

![image](https://github.com/damus-io/damus/assets/64376233/eae66cd4-6313-494f-9ceb-8618bb36622f)

**Comment by alltheseas** [comment]
@tyiu 

> I suspect the bug is that it thinks quoted note events are zap events and isn’t able to parse properly

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/ff902088-1924-46ac-998f-ef8bff75bd67)

From @BenGWeeks 

note1js5r2509n2jdw0x50rsgvcevzqwtmq5q4swvfwryw3436g0urumsnx0d4q

**Comment by alltheseas** [comment]
https://damus.io/note1cvcxxe5xwhkawu29nlav8jg8jw8qjaqfk9nhh427cp4qjlkke6js8npr02

**Comment by alltheseas** [comment]
Removing zapvertising should remove this bug as well

**Comment by alltheseas** [comment]
Issue remains  ![image](https://github.com/damus-io/damus/assets/64376233/65f15d06-0ef2-4875-8024-1ef52cde4d7a)

https://damus.io/note1dpc84pau9vejg8j9jagk4q3d7vyefvgxn4yj0vf3a4vv95w2r64qvqzcy5

**Comment by jb55** [comment]
Should be fixed now
