### ISSUE TITLE
Onboarding: Suggest popular nostr accounts (profiles/npubs) to follow

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1272]
## User Story

As a newbie nostr user onboarding to damus, I would like to see a sampling of various profiles to follow, so that I have interesting content on my feed from the beginning.

### Acceptance criteria

1. List can be updated over time - i.e. new npubs added, or removed
2. When new user creates a npub/profile using Damus, before onboarding is concluded they are presented with the option to follow none, one, some, or all suggested profiles

_context_ 
This will precede input twitter account for nostr npub recommendations
https://github.com/damus-io/damus/issues/921

**Comment by alltheseas** [comment]
@joelklabo

**Comment by alltheseas** [comment]
@joelklabo do you need any help, or clarification with this 🙏

**Comment by jb55** [comment]
Its merged in master as a static list, but we probably want this list to be dynamic as a follow up issue

**Comment by alltheseas** [comment]
What does a dynamic list do? Allows perpetual updates to the list?

**Comment by jb55** [comment]
> What does a dynamic list do? Allows perpetual updates to the list? 

Just allows us to update it without pushing new app versions

**Comment by alltheseas** [comment]
@joelklabo @jb55 

What is the link to the list?
