### ISSUE TITLE
Feature Request - Add copy to clipboard button to NWC page

### ISSUE THREAD

**Issue by matthieu-00** [damus-io/damus#1273]
Damus supports NWC, allowing you to connect certain lightning-enabled wallets (such as Alby) to connect and take advantage of one-tap-zaps.

![IMG_6249](https://github.com/damus-io/damus/assets/111670064/645ffeff-3a98-4b63-b8c9-6ed0d6d6dedd)

The connection process is straight forward and can be done entirely from your iOS device. However, in a situation where the wallet connected to Damus runs out of sats or you are needing to refill it for a larger transaction, the process is a bit lengthy to process on the go. Attached is the current process if only using mobile and assuming one is not using a web browser.

https://github.com/damus-io/damus/assets/111670064/48f06a38-b64b-4f7a-b87a-0be0e4e10e09

I propose adding a copy button, similar to the option to copy your npub on the profile page. This would allow a user to quickly open the wallet page, copy their lightning address, paste it into a lightning wallet app (like Wallet of Satoshi) and refill their wallet that is connected to Damus.

**Comment by jb55** [comment]
On Fri, Jun 09, 2023 at 08:57:05PM -0700, Matt wrote:
>I propose adding a copy button, similar to the option to copy your npub on the profile page. This would allow a user to quickly open the wallet page, copy their lightning address, paste it into a lightning wallet app (like Wallet of Satoshi) and refill their wallet that is connected to Damus.

If you long-press the zap button on the profile you will can copy your lightning address

**Comment by matthieu-00** [comment]
> 
This works if your lightning address under your profile is the same as the NWC address. For this example, I use Alby for NWC and WoS LNURL - if I long-press the zap button, it copies my WoS address. Not the Alby address that I would want to refill.

**Comment by alltheseas** [comment]
@matthieu-00 ![image](https://github.com/damus-io/damus/assets/64376233/16ee1302-556f-4359-825b-aabed246d5dc)

Do current NWC options in damus resolve your feedback?
