### ISSUE TITLE
New Feature: Ability for a user to leave a particular Thread of conversation on Damus

### ISSUE THREAD

**Issue by scoder1747** [damus-io/damus#128]
Story:
I recently bumped into a thread of conversation going on between one user and gpt3 (the bot). I asked a message to gpt3, I received an answer, and then I got out. However, I keep on getting new Notifications for every exchange of replies inside that thread which was not related to any of queries or concern, and therefore it was annoying to me. I would have much appreciated if there was an option to leave the thread of a conversation at my discretion.

Thanks!

**Comment by bebopkid** [comment]
See also #118

**Comment by alltheseas** [comment]
@scoder1747 does the mute conversation @tyiu  rolled out feature close this ticket?
