### ISSUE TITLE
Investigate Zap Profile Flow [Zaps][UX][Experimental]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1289]
![Zap Profile Flow BIG ZAP BUTTON](https://github.com/damus-io/damus/assets/64376233/27071a55-44f0-406d-a420-fc77a5908f9b)

@robagreda

**Comment by alltheseas** [comment]
Option C: go to web store in browser

Origin:

**Comment by alltheseas** [comment]
Option D: halfway profile

https://damus.io/note1r5zxll4ar3aaywjzuk8yxjfms7tc2pa7vek4v237gu9vqr22caashfermc

Samson

**Comment by alltheseas** [comment]
E: hold tap note

Damus.io/note1sd8nzx5y2zfyxmkskjqjcsugcwe396dhx3ds6s5r84jt43t7ynlsdhfkmn

**Comment by alltheseas** [comment]
F: external service that zaps if detects likes

https://damus.io/note1k9vcjaangvuw5x66drt8pr2y9ww9cdauy6kx5rr0gq4qqla9d5ssjegn2v

**Comment by alltheseas** [comment]
The only requirement that is clear to me: profile must be visualized in the zap flow to associate zap with the profile (and disassociate zap with note) 

@jb55

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/f8fea819-8e00-4c17-955c-420943d39ffe)

Make onlyzaps icon next to PFP as tappable zap profile action.


Origin: Tanel

**Comment by alltheseas** [comment]
Apple arbiter update: as of June 26th there cannot be a shortcut to zap profiles in notes.

**Comment by jb55** [comment]
On Wed, Jun 14, 2023 at 09:15:04AM -0700, alltheseas wrote:
>The only requirement that is clear to me: profile must be visualized in the zap flow to associate zap with the profile (and disassociate zap with note)

the zap can't be initiated from the note, that was what I was told. I
think having custom zap amounts listed on the profile should be ok
though?

**Comment by alltheseas** [comment]
> On Wed, Jun 14, 2023 at 09:15:04AM -0700, alltheseas wrote: The only requirement that is clear to me: profile must be visualized in the zap flow to associate zap with the profile (and disassociate zap with note)
> the zap can't be initiated from the note, that was what I was told. I think having custom zap amounts listed on the profile should be ok though?

What do you think about initiating zap from another profile picture: https://github.com/damus-io/damus/issues/1289#issue-1755553464 ?

> I think having custom zap amounts listed on the profile should be ok though

I think so. I wonder what is the best possible UX for profile zap @robagreda @sashapavlova

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/dbb76623-e405-4c4a-800a-a52b36bae9da)

https://damus.io/note19x63w7zynwlyzhl4ksdt003eejkk85v9av5k9e2r4jsq07ewmexqquejxr

**Comment by alltheseas** [comment]
Uncle Bob Martin mobile-> desktop zap link

> just zapped @jb55 88 sats by using Damus on my iPhone to send myself this DM: "zap 88->jb55 hi there".

> This worked because more-speech, which I have running on my laptop, will do the zap for me if it recieves a DM from myself to myself (an auto-dm) with that message format. 

> It seems to me that every desktop client could be set up this way.  Then, when you use your phone you can DM yourself with a zap request and your desktop client will do the job for you.

> To make this easy Damus, and other mobile apps, could allow users to create message templates.  Something like: "zap {amount}-{user} {comment}".  Such a template could be invoked with a single button push.  It could pop up a dialog asking for the variables and then send it as a auto-dm.

https://damus.io/note1qq9hd4fzr8ezthy5cpcghwl0j8w5wzctvtfq209helr3cduzg9eqltvkur

**Comment by alltheseas** [comment]
Swipe right UI shortcut -> show profile view (perhaps partial screen) -> zap profile 

_questions_
1. Does Damus auto return to note view?
2. Does Damus toast (see https://github.com/damus-io/damus/issues/1315)

![image](https://github.com/damus-io/damus/assets/64376233/5b325ef5-3336-4efa-b78a-4d56d1a83309)

Origin: Signal & Rage

@jb55

**Comment by alltheseas** [comment]
Will mentions half press window for PFP tap without loading 1,000 notes

**Comment by alltheseas** [comment]
@jb55 mentioned he is working on other items. Removing Will from assigned column for time being.

@tyiu is interested, but does not have time currently.

**Comment by alltheseas** [comment]
Related 

https://github.com/damus-io/damus/issues/1391

**Comment by alltheseas** [comment]
See https://github.com/damus-io/damus/issues/1596
