### ISSUE TITLE
Add feedback/confirm UI for clear cache 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1301]
_what happens_
When I hit clear cache (settings -> appearance), I don't know if the button registered 

![image](https://github.com/damus-io/damus/assets/64376233/039e8d9a-ac4e-423a-9db7-0e2a8874cce9)

_suggestion_
If I hit clear cache button, provide confirmation: "Cache successfully cleared."

**Comment by danieldaquino** [comment]
Starting this alongside #1472

**Comment by danieldaquino** [comment]
**Sent a patch with testing report at:** https://groups.google.com/a/damus.io/g/patches/c/3KRAGsA3WYo
