### ISSUE TITLE
Feature: Ability to Scan Lightening Invoices and paste the Lightening ID in the Post and Chat.

### ISSUE THREAD

**Issue by scoder1747** [damus-io/damus#131]
This feature allows the user to Scan Lightening Invoices and paste the Lightening ID while tapping on the QR code button available on Post and Chat Views. Screenshots and Applicable Scenario below:

![IMG_7398](https://user-images.githubusercontent.com/120697811/209449814-96d388c9-ceb0-484b-aee7-cf0b1d4b3ffb.jpg)
![IMG_7399](https://user-images.githubusercontent.com/120697811/209449816-9a34fbca-6e10-4781-8b1e-d62bdff3aa02.jpg)

Applicable Scenario:
<img width="1076" alt="Screen Shot 2022-12-24 at 2 26 00 PM" src="https://user-images.githubusercontent.com/120697811/209449880-1eab8bec-238d-439c-968d-001f66c28ef0.png">

**Comment by hazeycode** [comment]
I made a QR capture view for a different purpose here: https://github.com/damus-io/damus/pull/671

The code QRCaptureView could be reused for this purpose also
