### ISSUE TITLE
Lag / freeze [bug][performance]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1312]
_what happens_
Media in feed sometimes causes a lag or freeze of Damus. The suspect is video auto-playback

https://damus.io/note1k60n0jqje370pyxjrzzge95uff4dj7cf977cesjaz6zpks2qe0hsrhg2ys

**Comment by gladiusKatana** [comment]
Just thinking out loud -- wonder if instantiating `play` to = false in `VideoPlayerModel`, then triggering it to auto-play using a scroll-position mechanism like the current _auto-pause_ mechanism, would help... 

But I haven't been able to replicate the bug (yet). Will update this message when I find anything

**Comment by jb55** [comment]
This should be fixed now
