### ISSUE TITLE
Bug: Damus allows post during photo upload

### ISSUE THREAD

**Issue by armstrys** [damus-io/damus#1317]
I think this one is pretty self explanatory. I had a photo upload that was going slow and managed to write my text and post before the upload processed. Instead of waiting for the upload the post just went without the photo.

Running on the 1.5 (6) on testflight

**Comment by alltheseas** [comment]
Technical question:

Is it possible to "freeze" post button until image is successfully uploaded?

**Comment by jb55** [comment]
I believe this is fixed now...
