### ISSUE TITLE
Your name and Usersname separate lines

### ISSUE THREAD

**Issue by csc0711** [damus-io/damus#133]
When “your name” and/or “Username” are too long it scrolls the text in two columns vs. dropping to separate lines for each. This appears disjointed and could look cleaner if the “username” dropped to separate line. 
![A5D7C25B-EE32-4DF0-BEAB-A99715636B72](https://user-images.githubusercontent.com/49574468/209453447-5c6f096a-1ec7-4753-9034-eb19de1d7b52.jpeg)

**Comment by ericholguin** [comment]
usernames are truncated
