### ISSUE TITLE
Explore multi-emoji option reactions

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1335]
https://github.com/damus-io/damus/assets/64376233/b2b093b9-e42b-41f0-8b01-872f8c5bf17a

@suhailsaqan @robagreda

**Comment by alltheseas** [comment]
cc @tonygiorgio 

@benthecarman

**Comment by benthecarman** [comment]
Yes!!!

**Comment by alltheseas** [comment]
@suhailsaqan update 

https://github.com/damus-io/damus/assets/64376233/074b7337-d2c9-4a0c-aa82-a975e0062c96

**Comment by alltheseas** [comment]
Tasks

1. Requires design review & design input @robagreda  ▢
2. Eng iteration (if any) ▢
3. Requires team Mutiny input & review ▢

**Comment by alltheseas** [comment]
@tyiu 

https://damus.io/note1d44nyh2rjm9elf62qj86u5j8pzh3cl36a6p92s6an7shavr9h7kqq8eugg

**Comment by jb55** [comment]
On Thu, Jun 29, 2023 at 01:34:56PM -0700, alltheseas wrote:
>Tasks
>3. Requires team Mutiny input & review ▢

?

**Comment by alltheseas** [comment]
> On Thu, Jun 29, 2023 at 01:34:56PM -0700, alltheseas wrote:
> >Tasks
> >3. Requires team Mutiny input & review ▢
> 
> ?
> 

Zapple pay fixes this
