### ISSUE TITLE
First note of a newly created profile draft contains #introductions

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1338]
## user story ##
As Damus maintainer, I would like to prompt all new users with a draft first introductions note, so that I can encourage user interaction aiming to increase Damus stickiness.

### acceptance criteria
1. New profiles immediately after profile creation are prompted with a draft introductions note (see design) to say hello to nostr

## design ##
![First post@3x](https://github.com/damus-io/damus/assets/64376233/ecf01fc7-d4fe-4cfe-bb41-186856875fab)

https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=1831-42734&mode=design&t=mPJbPNoXDmu5cAtR-0

_related_
excellent first note example https://github.com/damus-io/damus/issues/1232
@ericholguin 

origin:
https://damus.io/note1877w84dy4uulapa5l2u020efxvzfpyar8t5nun2w7393tpgxlmxqvhm99q

**Comment by danieldaquino** [comment]
Implemented this feature and sent a patch! All code, testing, discussion can be found here: https://groups.google.com/a/damus.io/g/patches/c/IkGzoxYS-Qw

I will try to implement a snapshot test for this and send it as a separate patch

**Comment by jb55** [comment]
On Sat, Oct 21, 2023 at 07:41:27PM -0700, William Casarin wrote:
>Closed #1338 as completed via bf43842590a0f62aafcd0f811d0634b396ab7f6e.

I wasn't able to test this. It would be good if we had a way to reset
the onboarding flag (dev mode feature) ?

**Comment by danieldaquino** [comment]
> It would be good if we had a way to reset the onboarding flag (dev mode feature) ?

@jb55, sent a quick patch to address your request! (https://groups.google.com/a/damus.io/g/patches/c/aVn_clP10ls)

**Comment by alltheseas** [comment]
> > It would be good if we had a way to reset the onboarding flag (dev mode feature) ?
> 
> 
> 
> @jb55, sent a quick patch to address your request! (https://groups.google.com/a/damus.io/g/patches/c/aVn_clP10ls)

https://github.com/damus-io/damus/issues/1637
