### ISSUE TITLE
iOS 17 long notes

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1349]
_what happens_

Sometimes does not load long notes

> yes it started happening when I upgraded to iOS17 beta 2

> I have to swipe lightly left to fix it

![image](https://github.com/damus-io/damus/assets/64376233/7cf8a680-ed42-464e-bf42-5e4f2c6672ab)

Origin: @BenGWeeks

**Comment by jb55** [comment]
On Thu, Jul 06, 2023 at 06:33:53AM -0700, alltheseas wrote:
>_what happens_
>
>Sometimes does not load long notes
>
>> yes it started happening when I upgraded to iOS17 beta 2
>
>> I have to swipe lightly left to fix it

latest iOS 17 beta update breaks things further. Now the keyboard is
cutting off things in DMs and posts. I really hope they are going to fix
this, otherwise we'll need to look into solutions.

**Comment by alltheseas** [comment]
Does this remain an issue in iOS 17 for you @cr0bar ?

**Comment by jb55** [comment]
not an issue anymore
