### ISSUE TITLE
Damus stop working properly after some time

### ISSUE THREAD

**Issue by snownoop** [damus-io/damus#1351]
I logged in with my nsec and all was ok, however in few hours i can't see my followings,relays, cant follow anyone or add/remove relay. Most of buttons are just not clickable/pressable.
Is there any solutions ?
Thanks in advance.
my npub is:
npub1cphren2tu9sq7408g6p4uap0ac0h4y6487rdkf0cqhzcmtnvtjlqz44wwn

my keys were generated using
https://hitony.com/nostrogen/

Here is screenshot of profile screen (can only see followers)

![damus](https://github.com/damus-io/damus/assets/4146589/4c56dbef-d2fb-44bf-8d5d-1e57e250e2e8)

**Comment by jb55** [comment]
>I logged in with my nsec and all was ok, however in few hours i can't see my followings,relays, cant follow anyone or add/remove relay. Most of buttons are just not clickable/pressable.
>Is there any solutions ?

Make sure you login with your nsec and not your npub. Most actions won't
be available if you logged in with your npub by accident.

**Comment by jb55** [comment]
oh nm, now looking at your screenshot it appears damus can't find a contact list. if it doesn't load a contact list it won't be able to follow anyone.

**Comment by snownoop** [comment]
@jb55 thanks.
Looks like Damus is working fine with my first created pub/priv key pairs with Damus itself.
The one i created on service i noticed above - is not working.
Ok i will just switch to my first created account.
Please look at what can be wrong with creating keys on https://hitony.com/nostrogen/

for now closing issue as it is not relevant for me.
