### ISSUE TITLE
Inconsistent pubkey format in compose, and reply note

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1354]
> Follow up to the screenshot above. It seems when you post a note using reply it’s using the hex version of the public key and when you manually type a note it’s using a bech32 version of the public key.

> Reply (2nd example in screenshot):

> {"content":"nostr:32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245 enjoying having the full fat #damus experience back again 😁","tags":[["t","damus"]],"id":"5ec9c226a5a77595257f79e620ab9b4f45d1cb89062b28a51982fc10fb6f6cb1","kind":1,"created_at":1688749391,"sig":"b5e46c45ed0d4fa0911a2adc32daa39d36ba705d704b45b928ed9d0698a45f6d26d50579be2b2845274b960cd77765b5893bf8462f029e20f187714027e4e311","pubkey":"f16ac67afff1340501cf27b7ebe9e3086fb62e97f044ba407e38b5d8425a73f2"}

> Note (first example in screenshot):

> {"id":"92cd5518c3ff6219216a49ca65ecfcf0d8102b9a78d7c057a86e4f3e37794f2e","pubkey":"f16ac67afff1340501cf27b7ebe9e3086fb62e97f044ba407e38b5d8425a73f2","tags":[["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["t","damus"]],"sig":"74e446959faff1afa8c7bbd1e8816304614951061e2e540715cc39797e22b4ad59f0ed22bbb5c45132c3125393937b905da0368105d8a5018f3804a0f56b8b7a","created_at":1688749417,"content":"nostr:npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s enjoying having the full fat #damus experience back again 😁","kind":1}

Origin: @cr0bar

**Comment by cr0bar** [comment]
Just raised a pull request for this one: https://github.com/damus-io/damus/pull/1355

**Comment by alltheseas** [comment]
> Just raised a pull request for this one: https://github.com/damus-io/damus/pull/1355

Nice! Can you join damus dev telegram and introduce yourself:

damus.io/devchat

**Comment by cr0bar** [comment]
Status should be updated to published to TestFlight.
