### ISSUE TITLE
Built-in options for LibreTranslate do not work

### ISSUE THREAD

**Issue by badonyx** [damus-io/damus#1356]
The built-in options do not work, but the same instances do work if I add them as a custom option (with the URI). 

Not very experienced with swift but it looks like the `userSettingsStore.libretranslate_url` is the relevant field but it only gets populated for custom servers.

https://github.com/damus-io/damus/blob/cf4131f86746a8116459b2ce468e2d7f918f3591/damus/Util/Translator.swift#L37

https://github.com/damus-io/damus/blob/cf4131f86746a8116459b2ce468e2d7f918f3591/damus/Views/Settings/TranslationSettingsView.swift#L37

**Comment by alltheseas** [comment]
Thank you. Potentially related to

https://github.com/damus-io/damus/issues/1348

@tyiu

**Comment by jb55** [comment]
On Sat, Jul 08, 2023 at 04:17:07PM -0700, alltheseas wrote:
>Thank you. Potentially related to
>
>https://github.com/damus-io/damus/issues/1348

I don't believe they are related. All of our preconfigured translators
have https prefixes.

**Comment by alltheseas** [comment]
Built-in options were removed by @tyiu due to low reliability. Closing this issue. See https://github.com/damus-io/damus/issues/1660
