### ISSUE TITLE
Damus does not verify p tag is correct on zaps

### ISSUE THREAD

**Issue by benthecarman** [damus-io/damus#1357]
Experienced this today from a bug with zapple pay. I zapped a note but the wrong profile was tagged in the zap receipt. The zap appeared on the note even though that user did not have a lnurl configured.

With this I can fake zap someone and just set the p tag to myself to guarantee that'll it'll still be valid.

This can be fixed by verifying the p tag is the same as the note's author

**Comment by jb55** [comment]
On Sat, Jul 08, 2023 at 07:48:42PM -0700, benthecarman wrote:
>Experienced this today from a bug with zapple pay. I zapped a note but
>the wrong profile was tagged in the zap receipt. The zap appeared on
>the note even though that user did not have a lnurl configured.
>
>With this I can fake zap someone and just set the p tag to myself to
>guarantee that'll it'll still be valid.

what do you mean fake zap someone? do you have a specific example?

are you referring to this issue? https://github.com/nostr-protocol/nips/pull/274

**Comment by benthecarman** [comment]
Did it to this note. Just made the p tag one I own but the e tag still your event. 

note1d75r7ez8gkejh92nfyaq6r20eklj4wdn8jvvngrljupcqc9rphmsuxyk8a

**Comment by jb55** [comment]
On Sat, Jul 08, 2023 at 08:29:48PM -0700, benthecarman wrote:
>Did it to this note. Just made the p tag one I own but the e tag still your event.
>
>note1d75r7ez8gkejh92nfyaq6r20eklj4wdn8jvvngrljupcqc9rphmsuxyk8a

oh nice catch!
