### ISSUE TITLE
Fix infinite hashtag rabbit hole

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1367]
_what happens_
In universe view, when searching for a hashtag, I can perpetually keep clicking on the same hashtag. 

https://github.com/damus-io/damus/assets/64376233/44bd603d-b26e-49ec-a8f6-9a42cad56a56

_what I think should happen_
If on a particular hashtag view, do not allow me to click on same hashtag.

**Comment by alltheseas** [comment]
@keeshux want to do this one next?

**Comment by keeshux** [comment]
> @keeshux want to do this one next?

I found out this is due to Route hashing/comparison. I'm about to send a patch.

**Comment by alltheseas** [comment]
> > @keeshux want to do this one next?
> 
> I found out this is due to Route hashing/comparison. I'm about to send a patch.

Great! What's your npub?

**Comment by keeshux** [comment]
> Great! What's your npub?

```
npub1vwcuc4q97vzsvmxsszwp4w5cs6qrqkqaygdypty93e3zpz5xw9usggpscr
```

Still a complete newcomer to Nostr, hence the dummy profile.

Why? :-)
