### ISSUE TITLE
Dev relay log: cannot open logs on green connected relay

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1369]
_what happens_
In relay menu, on a green connected relay I see a grey question mark, and cannot open the logs with dev mode on.

![image](https://github.com/damus-io/damus/assets/64376233/0355ebd9-d3a4-48e4-9d44-4f0f59be6bad)

**Comment by bryanmontz** [comment]
@alltheseas I was able to reproduce and fix this scenario. Is this how you reproduced it?

Go to Relays view.
Add a new relay, and don't leave the view.

At this point the relay is added and connected, but there's a question mark and you can't view the relay detail view, which contains the log while in developer mode.

Prior to the fix I'm about to send, I could back out of the Relays view, go back in, and then it would work.

**Comment by alltheseas** [comment]
> @alltheseas I was able to reproduce and fix this scenario. Is this how you reproduced it?
> 
> Go to Relays view. Add a new relay, and don't leave the view.
> 
> At this point the relay is added and connected, but there's a question mark and you can't view the relay detail view, which contains the log while in developer mode.
> 
> Prior to the fix I'm about to send, I could back out of the Relays view, go back in, and then it would work.

I did not have to add a new relay - I simply carried over whatever relays I was previously using.

**Comment by bryanmontz** [comment]
Hmm. Well then I fixed a related bug, and I'm not sure if it'll fix your issue or not.

**Comment by alltheseas** [comment]
Ok I will try after your update is merged.
