### ISSUE TITLE
Appearance prompts for initial set up

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1383]
During onboarding do prompts to select choices for Animations and Always show images

**Comment by alltheseas** [comment]
Onboarding is a balance between communicating key information, asking for input, and not overloading user with prompts and choices. 

In my view appearance optimizations are secondary. If user cares enough they will find these post onboarding.

**Comment by punterwantsawhalepass** [comment]
when user sees and taps their first blurred image on "Universe"

do

1. An Always show images pop-up [Yes/No]
or
2. Do a Would you like to see this photo? [Yes/No] [fyi: you can change this in settings info pop-up]
