### ISSUE TITLE
Client side mute list

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1384]
Many users will use one client or many. Having the mute list stay local might prevent a harassing party from knowing if they were muted since mute list are public.

**Comment by alltheseas** [comment]
Nip-51 mute list conversion request: https://github.com/damus-io/damus/issues/1025

Does the above close this issue?

**Comment by jb55** [comment]
On Fri, Jul 21, 2023 at 08:41:41PM -0700, punterwantsawhalepass wrote:
>Many users will use one client or many. Having the mute list stay local might prevent a harassing party from knowing if they were muted since mute list are public.

we can just use encrypted lists for this

**Comment by alltheseas** [comment]
Encrypted mute list feature request:

https://github.com/damus-io/damus/issues/510
