### ISSUE TITLE
Video sound plays over itself repeatedly [500k sats]

### ISSUE THREAD

**Issue by babonyx** [damus-io/damus#1386]
Sometimes the video sound track plays multiple times over itself, not synced with video, making it extremely difficult to consume video content with audio. When it happens it seems to start a new track every time the (un)mute button is pressed or when the note is focused from a feed or a profile. 

Example: video plays from the feed, unmute it so there is one audio track playing. Now tap the note to focus the thread and press the unmute button again since it’s muted now, and now there are two audio tracks playing out of sync with the video. When this happens the audio tracks continue playing if I swipe out/away from the note and if I go back it only spawns more audio tracks, or even continues playing over another video. Or sometimes they pause but continue playing again over the video when it plays again. 

Example profile where I can often reproduce this: npub19zscu28djwhapecs3hh9qj5kr89hahq6mlx50dsqf72x8xxqv06q8xzyhq

Version: 1.6 (7)

Related? #1238

**Comment by alltheseas** [comment]
Can you share a noteID?

**Comment by babonyx** [comment]
Added more information with an example profile. Currently this note reproduces the issue: note104r9t5jq5g66lwpgg7sp52sk0yj6v560ppyawq6xrm5qvxpf6hqs9z44aa

But I’m noticing it doesn’t seem to happen for an older note where it did happen before so there may be other factors involved like order/recency.

**Comment by babonyx** [comment]
Screen recording

placeholder

**Comment by shawnyeager** [comment]
I'll post a 250k sat bounty for a merged PR which fixes this bug.

**Comment by ajoly954** [comment]
I’ll match @shawnyeager with another 250k sat bounty.

**Comment by dmnyc** [comment]
I'll add another 100K to get UI controls on the video.

**Comment by alltheseas** [comment]
> I'll add another 100K to get UI controls on the video player.

Thanks @dmnyc - UI controls are  probably best to separate from the playback bug: https://github.com/damus-io/damus/issues/1530. Transferred your bounty post to this new issue.

**Comment by kroucis** [comment]
I may have a fix for this, is the bounty still available?

**Comment by alltheseas** [comment]
@bryanmontz did you submit a patch for this?

**Comment by bryanmontz** [comment]
No, but I spent a few hours on it. It's not easy. The main issue is that we're tracking the play and mute state of each video URL, but not separating those between the player on the feed and the player on the individual thread view. Plus we've got a third-party library making things way more complicated than they need to be.

So I abandoned trying to fix it in place and started on a simpler player. This should allow us to add player controls soon too (but in a separate task).

**Comment by kroucis** [comment]
> No, but I spent a few hours on it. It's not easy. The main issue is that we're tracking the play and mute state of each video URL, but not separating those between the player on the feed and the player on the individual thread view. Plus we've got a third-party library making things way more complicated than they need to be.
> 
> So I abandoned trying to fix it in place and started on a simpler player. This should allow us to add player controls soon too (but in a separate task).

I am already working on #1530, which is the UI for the video controls. How far along is your new video player project? I would expect that much of my work will be transferable because it is mostly just UI elements that can be pretty easily reconnected to a new player.

**Comment by bryanmontz** [comment]
I worked on it again this morning, and I'm getting very close. I replaced GSPlayer with a very small amount of code. It'll be easy to add to.

**Comment by jb55** [comment]
On Tue, Sep 05, 2023 at 07:27:12AM -0700, Bryan Montz wrote:
>I worked on it again this morning, and I'm getting very close. I replaced GSPlayer with a very small amount of code. It'll be easy to add to.

thanks, I didn't think we needed that.

**Comment by jb55** [comment]
Fixed in #1539

**Comment by bryanmontz** [comment]
> 

@ajoly954 This issue is fixed and closed.Thanks for the bounty pledge.

LNURL1DP68GURN8GHJ7AMPD3KX2AR0VEEKZAR0WD5XJTNRDAKJ7TNHV4KXCTTTDEHHWM30D3H82UNVWQHKWCTNWP5KUEMNDAUNSDQ7Y4KMJ

or

lnbc2500u1pj04q0vpp5k42k89p0f7xpsjz68c2c367sf96xnu6kksr8fvjggsxksxx0kp7qdqqcqzzsxqyz5vqsp5jcfmlg3jq4fqk8pgh9tvyzjxul7lmvvkz8jfjwedukq9jwk7vwes9qyyssqvpcpqudytk47yy9uaggf9wcluu8zd0tplgcwgqmghl5vnny4v0ypff2qzuawvekmfkpwxv0fjv5x4ng5psq3tgam644u2pxnxkxdjzsp3r3tg2

**Comment by ajoly954** [comment]
Done!

On September 7, 2023, ajoly954 ***@***.***> wrote:
>

@ajoly954 <https://github.com/ajoly954>
>  This issue is fixed and closed.Thanks for the bounty pledge.
>
> LNURL1DP68GURN8GHJ7AMPD3KX2AR0VEEKZAR0WD5XJTNRDAKJ7TNHV4KXCTTTDEHHWM30D3H82UNVWQHKWCTNWP5KUEMNDAUNSDQ7Y4KMJ
>
> or
>
> lnbc2500u1pj04q0vpp5k42k89p0f7xpsjz68c2c367sf96xnu6kksr8fvjggsxksxx0kp7qdqqcqzzsxqyz5vqsp5jcfmlg3jq4fqk8pgh9tvyzjxul7lmvvkz8jfjwedukq9jwk7vwes9qyyssqvpcpqudytk47yy9uaggf9wcluu8zd0tplgcwgqmghl5vnny4v0ypff2qzuawvekmfkpwxv0fjv5x4ng5psq3tgam644u2pxnxkxdjzsp3r3tg2
>

—
Reply to this email directly, view it on GitHub
<https://github.com/damus-io/damus/issues/1386#issuecomment-1710978567>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/ASF45Q235QH7GHIQ4XXOZXLXZJ45LANCNFSM6AAAAAA2T4YBII>.
You are receiving this because you were mentioned.Message ID: <damus-
***@***.***>
