### ISSUE TITLE
(enhancement) profile view posts/posts & replies

### ISSUE THREAD

**Issue by olheadinternet** [damus-io/damus#139]
would like to see posts / posts & replies come to profiles

I also propose a 3rd chat column for notes that appear in channels this way one doesn't feel inhibited by destroying their feed to have more robust and casual replies in channels. This proposed column would function like posts & replies, showing posts, replies, and chat.

It might be fun to be able to sort global this way as well. 

I also find myself trying to swipe left or right just generally on the timeline to go between post and replies, not sure if this would be annoying in practice, but just a multi-touch reflex i thought i would add.

**Comment by ericholguin** [comment]
This was added
