### ISSUE TITLE
Download follower count crashes Damus

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1394]
_what happens_
For profiles with high followers count, when downloading follower count, Damus crashes

https://damus.io/note1zsl64994kwztj6dgrrvlnlqheut4fdlkk25z4mpuc79p36dpgypqajl2zh

https://damus.io/note1pvpnnh05p0wjdt7kzvkdnnqq4wt52nzq4p2hf6pcqcd0w75rag7sy3hzh0

https://damus.io/note1t4h6tnstrffyap34n0yvxm39ch7vna69gjggm0qupx9dfnxrxffsuk6g28

https://damus.io/note1vy8sjkpg9nahvndr5tp9ud2j2x2wn5f68sus54xxqfzjf6el5euq4tux2p

**Comment by alltheseas** [comment]
Multiple users recreated issue. I
I cannot recreate crash.

Sersleepy video:

**Comment by jb55** [comment]
We should stop downloading contact lists here and switch to COUNT for relays that support that

**Comment by alltheseas** [comment]
Fiatjaf contacts download froze damus for me

**Comment by jb55** [comment]
On Mon, Jul 31, 2023 at 02:24:07PM -0700, alltheseas wrote:
>Fiatjaf contacts download froze damus for me

this should be fixed on the nostrdb branch. I was able to download 20k
contact lists on my user without much issue.

**Comment by alltheseas** [comment]
This is a repeat of https://github.com/damus-io/damus/issues/85. There is a bounty in the old issue @jb55

**Comment by jb55** [comment]
can you confirm if the freezing still happens on 1.6 (10) ?

**Comment by alltheseas** [comment]
Just loaded fiatjaf followers. It's faster. No freeze.
