### ISSUE TITLE
Negentropy syncing

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1407]
# Technical 

// I have no idea what this is, but nostrdb (https://github.com/damus-io/damus/issues/1406) enables this, and Will is planning work on this

**Comment by alltheseas** [comment]
@jb55 what is negentropy sync, and what are the benefits & unlocks of this?

**Comment by alltheseas** [comment]
negentropy sync - documentation set reconciliation - supported by damus relay (P Wuille does this)
give all contacts list that I dont have (for this query)
does magical reconciliation
efficient way
it follows that
with nostrdatabase - consistent follow counts will be possible

**Comment by jb55** [comment]
Training session with GPT4

https://chat.openai.com/share/00078bea-9349-477b-ba5d-e3c29a345449

**Comment by jb55** [comment]
duplicate of https://github.com/damus-io/nostrdb/issues/3

keeping issues in their respective repos for now

**Comment by alltheseas** [comment]
Didn't know there was a nostrdb repo - got it.
