### ISSUE TITLE
UTF support for hashtags

### ISSUE THREAD

**Issue by velram** [damus-io/damus#1411]
The hashtags for Non-English languages / Unicode characters isn't supported yet. 
I've tried with Tamil (South-Indian language) - UTF (unicode) character. 

Refer screenshot
![image](https://github.com/damus-io/damus/assets/2095609/0596e80d-59d1-45ab-9f36-abfbb9b0d074)

**Comment by alltheseas** [comment]
Can you provide the noteID? 


https://github.com/damus-io/damus/issues/949 I thought this was previously closed @jb55

**Comment by jb55** [comment]
It's fixed but for some reason they are not clickable on iOS16.

**Comment by alltheseas** [comment]
@velram let us know when you are able to test on iOS 17 🙏

**Comment by jb55** [comment]
On Tue, Aug 01, 2023 at 12:44:11PM -0700, alltheseas wrote:
>@velram let us know when you are able to test on iOS 17 🙏

we should still fix this for iOS16 which many people will be using for a
long time

**Comment by alltheseas** [comment]
https://damus.io/note1r0kvqgjmnqvpt4kyw7kx3cx2y0hdvvcrj3zaksxeyr9mjfw08awszup9xc

**Comment by alltheseas** [comment]
> On Tue, Aug 01, 2023 at 12:44:11PM -0700, alltheseas wrote: @velram let us know when you are able to test on iOS 17 🙏
> we should still fix this for iOS16 which many people will be using for a long time

Agree. It's in the backlog.

**Comment by danieldaquino** [comment]
I investigated this issue today, and found that the root cause seems to be on a `URL` constructor returning `nil` because it contains non-allowed characters, thus not attaching a link to the hashtags.

I sent a patch over the patches mailing list that hopefully is enough to resolve this issue 🙏, and added some unit test coverage to prevent future regressions. Patches and more details can be found at https://groups.google.com/a/damus.io/g/patches/c/QbG3G83ShfA

**Comment by jb55** [comment]
On Wed, Aug 02, 2023 at 08:48:57PM -0700, Daniel D’Aquino wrote:
>I investigated this issue today, and found that the root cause seems to be on a `URL` constructor returning `nil` because it contains non-allowed characters, thus not attaching a link to the hashtags.
>
>I sent a patch over the patches mailing list that hopefully is enough to resolve this issue 🙏, and added some unit test coverage to prevent future regressions. Patches and more details can be found at https://groups.google.com/a/damus.io/g/patches/c/QbG3G83ShfA

amazing, thank you. will check it out.
