### ISSUE TITLE
Do not show nsfw filter

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1412]
## user story
As a user browsing Damus, I do not want to see nsfw in my feed by default, so that I can manage my nostr experience. 

### acceptance criteria
1. User has an option to disable the nsfw tagged posts
2. New section in appearance for controlling content filtering settings allows for setting described in 1.
3. If user follows a certain hashtag (e.g. #grownostr), and the post also includes #nsfw, AND user has disabled nsfw posts from showing do *not* show post including nsfw
4. View nsfw should be disabled by default

https://damus.io/note18uu0sv9j2wkk4n7a8qm6qhflwavxv0nmk00v05xgu56npgw4yxhsegh4hr

**Comment by alltheseas** [comment]
Previous nsfw requests: 

NIP-36 https://github.com/damus-io/damus/issues/910
https://github.com/damus-io/damus/issues/73

**Comment by alltheseas** [comment]
Updated story and criteria per today's discussion @danieldaquino

**Comment by danieldaquino** [comment]
Thanks @alltheseas and @jb55, I am working on the simplified changes in the appearance tab.

I will post the draft I was working on before our meeting, just in case we want to reuse some of that work whenever we want to create a specialized settings page with more fine tuned controls at a later time.

![content-moderation-setting-page-draft](https://github.com/damus-io/damus/assets/24692108/b6c6d84c-30ca-4cdc-96f5-5ae852a9738b)

[content_moderation_setting_page_draft.patch](https://github.com/damus-io/damus/files/12652160/content_moderation_setting_page_draft.patch)

**Comment by alltheseas** [comment]
> Thanks @alltheseas and @jb55, I am working on the simplified changes in the appearance tab.
> 
> I will post the draft I was working on before our meeting, just in case we want to reuse some of that work whenever we want to create a specialized settings page with more fine tuned controls at a later time.
> 
> ![content-moderation-setting-page-draft](https://user-images.githubusercontent.com/24692108/268742187-b6c6d84c-30ca-4cdc-96f5-5ae852a9738b.png)
> 
> [content_moderation_setting_page_draft.patch](https://github.com/damus-io/damus/files/12652160/content_moderation_setting_page_draft.patch)

Sounds good. I added the fine tuned bit, as an incremental addition https://github.com/damus-io/damus/issues/1549 .

**Comment by danieldaquino** [comment]
Implemented feature!

Code patch, discussion, and testing report are all available on the commit patch send via email, which can be viewed here: https://groups.google.com/a/damus.io/g/patches/c/aAEpfgsUAro

Please let me know if any other changes are necessary. Thank you!

**Comment by danieldaquino** [comment]
@alltheseas let me know that we are not filtering nsfw posts from the hashtag view (The one with the Follow/Unfollow hashtag button at the top).

This is undesired behaviour, and I think I know how to fix this. I will do this soon

Tagging myself as a reminder: @danieldaquino

**Comment by jb55** [comment]
On Fri, Sep 22, 2023 at 11:33:06AM -0700, Daniel D’Aquino wrote:
>@alltheseas let me know that we are not filtering nsfw posts from the hashtag view (The one with the Follow/Unfollow hashtag button at the top).
>
>This is undesired behaviour, and I think I know how to fix this. I will do this soon

ah right! this is easy to forget. I've done this before.

**Comment by danieldaquino** [comment]
Sent a follow up patch to address the issue mentioned by @alltheseas: https://groups.google.com/a/damus.io/g/patches/c/TwrBVxSBXlM
