### ISSUE TITLE
nostr wallet connect: cannot paste string

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1417]
_what happens_
In Damus testflight 1.6 (7), when going to wallet -> attach wallet -> paste I cannot paste a NWC setup string

https://nostr.build/av/8f30c3d4d3310da3c61507f1927f59cf41e07cf827da94f750889933eeb06050.mov

https://damus.io/note19ea2rsjecen6jxmphjeyjywyf7mnrva4evh2c4cjsm24w4an90dqpfv5wu

origin: Boston

**Comment by jb55** [comment]
I believe this is fixed?
