### ISSUE TITLE
Why have goto statements instead of if statements here? Please EIL5

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1421]
https://github.com/damus-io/damus/blob/a9b4cfd4241f3d4a6fb2c1ee2e2ce1de33eae4d4/damus-c/talstr.c#L4

**Comment by alltheseas** [comment]
Can you kindly ask this question in the dev chat, so we can keep github for Damus issues

**Comment by punterwantsawhalepass** [comment]
Where's the dev chat?

**Comment by alltheseas** [comment]
https://t.me/damusdev

Migrating soon elsewhere

**Comment by punterwantsawhalepass** [comment]
Is simplex in the works?

**Comment by alltheseas** [comment]
Yes, DM for link

**Comment by punterwantsawhalepass** [comment]
found it, thank you
