### ISSUE TITLE
change buggyness to bugginess

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1428]

**Comment by alltheseas** [comment]
Where?

**Comment by jb55** [comment]
@punterwantsawhalepass please stop spamming the repo with incoherent issues or else you will be banned.

**Comment by punterwantsawhalepass** [comment]
> 
@alltheseas v1.6-8 changelog

@jb55 Where's a good place to send incoherent issues on things like spelling issues in releases, feature request, and documentation?
