### ISSUE TITLE
Multi emoji swipe difficulty

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1434]
Difficulty occurs around right hand side of emoji box. Sometimes results in vertical screen movement.

https://github.com/damus-io/damus/assets/64376233/4189ce44-d37f-478e-85ab-3984c1808fa6

Origin: @fishcakeday 

https://damus.io/note1kvl79gsdptxmwx6glarek758lekf2ckcw9vgz5z4wyhgcpje70uswv6e92

**Comment by jb55** [comment]
On Thu, Aug 03, 2023 at 10:17:37PM -0700, alltheseas wrote:
>https://github.com/damus-io/damus/assets/64376233/4189ce44-d37f-478e-85ab-3984c1808fa6
>
>Origin: @fishcakeday

confirmed, looks like the hit target needs to be bigger or something

**Comment by alltheseas** [comment]
@suhailsaqan is investigating
