### ISSUE TITLE
Nostr report posts disappeared/missing 1.6 (10)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1436]
https://damus.io/note1r8m0h7truxsyrqatq8tc32hw6vzq07creyjvmlcj7m6dup2rrvxqr65z74

**Comment by jb55** [comment]
added a test for this on the nostrdb side and no issues, will add a test
on the damus side...

**Comment by alltheseas** [comment]
Notes with character counts greater than 3967 are not displaying in 1.6 (10) on Testflight per Corn.

**Comment by jb55** [comment]
This should be fixed
