### ISSUE TITLE
*failed to decrypt content* appears in DMs

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1441]
![image](https://github.com/damus-io/damus/assets/64376233/b5b98317-1696-4ae6-9c50-ec34851f118b)

https://damus.io/note15vxwdjs4g6flczhu5s6dkeljmar92alp4rl6h02xvevuac35vlaq6fef7y

**Comment by alltheseas** [comment]
> we should just not show these

I thought we previously excluded failed to decrypt content from displaying. Is this a regression?

**Comment by jb55** [comment]
On Fri, Aug 04, 2023 at 10:15:16AM -0700, alltheseas wrote:
>> we should just not show these
>
>I thought we previously excluded failed to decrypt content from displaying. Is this a regression?

don't think we ever did

**Comment by alltheseas** [comment]
> On Fri, Aug 04, 2023 at 10:15:16AM -0700, alltheseas wrote:
> >> we should just not show these
> >
> >I thought we previously excluded failed to decrypt content from displaying. Is this a regression?
> 
> don't think we ever did
> 

Is it this outstanding PR: https://github.com/damus-io/damus/pull/1277

**Comment by alltheseas** [comment]
duplicate
