### ISSUE TITLE
Kind 3 event with "/" appended to relay URLs causes Damus to not connect to relays (Primal introduced conflict)

### ISSUE THREAD

**Issue by nmfretz** [damus-io/damus#1443]
A new [Kind 3](https://github.com/nostr-protocol/nips/blob/master/02.md) event was published for my pubkey that has `/` appended to all relay URLs. This causes Damus (iOS) to fail to connect to all relays:

<img src="https://github.com/damus-io/damus/assets/85373263/64853b69-5380-40d4-9ffd-cda66da78685" alt="relays-damus" width="50%"/>

The Kind 3 event is shown below (published as a result of using [Primal web app](https://github.com/PrimalHQ/primal-web-app)):
```
{
  content: '{"wss://freespeech.casa/":{"write":true,"read":true},"wss://relay.current.fyi/":{"write":true,"read":true},"wss://nostr.lu.ke/":{"write":true,"read":true},"wss://relay.snort.social/":{"write":true,"read":true},"wss://nos.lol/":{"write":true,"read":true},"wss://nostr.bitcoiner.social/":{"write":true,"read":true}}',
  created_at: 1690960688,
  id: '1b780ce993cf177dc3d54a618917759cd34cee139e2a24ba2f083548c9df4077',
  kind: 3,
  pubkey: 'def9a8b4d3eb250f40361430b37b7ae21eefc37ef8809286b75e157f6e628518',
  sig: 'd1e28869d9c3833160d4cfc787fbfbe3a76399c4c949aceec29c4bbfaf9a57b1c8b0fdd9bec72fb164192f6a4b48e72d106feb3c68aa5435ff26bda47562aa94',
  tags: [...
 }
 ```

I played around with Damus to see if I could get the relays to connect without publishing a new Kind 3 event. The following steps worked:
1. added new relay (wss://relay.damus.io)
2. restart app (it was necessary to first add a new relay)

<img src="https://github.com/damus-io/damus/assets/85373263/1a48d7c7-5608-4cb8-a4e4-bf0f325b212b" alt="relays-damus" width="50%"/>

I can then delete `wss://relay.damus.io` and the other relays remain connected.

<img src="https://github.com/damus-io/damus/assets/85373263/88914421-6fbb-441c-86b7-6b6c810aeef4" alt="relays-damus" width="50%"/>

Apologies if I have misunderstood what is happening.

**Comment by alltheseas** [comment]
Thanks for reporting. Cross-client use has a history of incompatibility. 

Not sure if related to another Primal associated bug. 

https://github.com/damus-io/damus/issues/1387

**Comment by nmfretz** [comment]
You're welcome. Let me know if I can help in any way.

**Comment by jb55** [comment]
Thanks for reminding me to deal with trailing slashes

**Comment by alltheseas** [comment]
> You're welcome. Let me know if I can help in any way.

Are you interested in contributing to Damus as a dev?

**Comment by nmfretz** [comment]
> Thanks for reminding me to deal with trailing slashes

@jb55 ya, I was doing some testing with our [Nostr Relay app on Umbrel](https://damus.io/note1y8hxpjqlaau7telrlexmdm4a3jfalmv2ysv2gh4ytqd0ysueapgsljh9lt) and was surprised when I saw trailing slashes come through when I signed on to Primal... It results in us connecting to each relay twice for a bit so I also have to deal with trailing slashes

> Are you interested in contributing to Damus as a dev?

Unfortunately I don't have the time for code contribution, but if you need help with recreating or testing this issue please let me know!
