### ISSUE TITLE
Provide Localized bootstrap relay(s) option upon app install/onboardinng 🇯🇵🌎🌍

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1447]
## user story (example Japan)
As a Japanese Damus user onboarding to Damus, I would like to have the Japanese relay(s) included in the Damus bootstrap relay list, so that I can jump into discussions in Japanese

### acceptance criteria 
1. Japanese users automatically have Japanese relay(s) included on their bootstrap list

(Future: Brazilian users have Brazilian users, and so on)

### implementation discussion
Not sure if there is a way to do this programmatically @tyiu.

Nostr.watch has relay geographies.

Japanese relay info can manually be added, and programmatic localized relay update can be done subsequently.

**Comment by alltheseas** [comment]
Japanese relay info:

https://scrapbox.io/nostr/awesome-nostr-japanese

**Comment by alltheseas** [comment]
@tyiu @jb55 maybe we can detect the user's keyboard language(s), and assign localized relays to them?

**Comment by tyiu** [comment]
> @tyiu @jb55 maybe we can detect the user's keyboard language(s), and assign localized relays to them?
> 
> Not sure what the privacy tradeoffs are here/ if this information is publicly broadcast by iOS users.

We should absolutely not use a user's keyboard language as an indication for anything. Them wanting to type with that keyboard language does not imply that they understand the language. I personally have several that I want to type in because I'm learning the languages and understand some words, but I do not understand them well enough.

There's a better explicit signal, which is the same one that's used by the auto translations feature already: using the list of preferred languages from iOS settings.

imo it should be opt-in and not automatic.

One way to do this could be to have a static list of relay suggestions (similar to how we have a static list of pubkeys to suggest to follow in onboarding). Damus could suggest the ones that match their language preferences:
https://github.com/nostr-protocol/nips/blob/master/11.md#community-preferences

**Comment by alltheseas** [comment]
> > @tyiu @jb55 maybe we can detect the user's keyboard language(s), and assign localized relays to them?
> 
> > 
> 
> > Not sure what the privacy tradeoffs are here/ if this information is publicly broadcast by iOS users.
> 
> 
> 
> We should absolutely not use a user's keyboard language as an indication for anything. Them wanting to type with that keyboard language does not imply that they understand the language. I personally have several that I want to type in because I'm learning the languages and understand some words, but I do not understand them well enough.
> 
> 
> 
> There's a better explicit signal, which is the same one that's used by the auto translations feature already: using the list of preferred languages from iOS settings.
> 
> 
> 
> imo it should be opt-in and not automatic.
> 
> 
> 
> One way to do this could be to have a static list of relay suggestions (similar to how we have a static list of pubkeys to suggest to follow in onboarding). Damus could suggest the ones that match their language preferences:
> 
> https://github.com/nostr-protocol/nips/blob/master/11.md#community-preferences

This is great feedback.

I suppose we could ask around various communities about localized language relays for the opt-in list you are describing.

**Comment by alltheseas** [comment]
https://damus.io/note1a9j6l6yxzy628hc68f0u6j4gjrj4mx4ehlph8eje8ktam9p2vkvqvd79zt

fyi @jb55 @danieldaquino this would be a nice add prior to Nostrasia

**Comment by alltheseas** [comment]
Japan 🇯🇵 relay list

> This list is the minimum required to interact with the Japanese people on (the) Nostr.

> wss://relay-jp.nostr.wirednet.jp
wss://yabu.me
wss://r.kojira.io

**Comment by alltheseas** [comment]
> using the list of preferred languages from iOS settings.

> imo it should be opt-in and not automatic.

> One way to do this could be to have a static list of relay suggestions (similar to how we have a static list of pubkeys to suggest to follow in onboarding). Damus could suggest the ones that match their language preferences:
https://github.com/nostr-protocol/nips/blob/master/11.md#community-preferences


Day one (1) suggested implementation:

1) detect during profile creation if preferred language is Japanese
2) if yes, prompt user to opt-in to Japanese relays "Damus detected that your preferred language is Japanese. Would you like to add the following Japanese only relays to your relay list?” (Translation pending to Japanese)
3) provide yes or no option, including the list of above relays
4) if no do nothing
5) if yes append Japanese relays to bootstrap relay list

**Comment by alltheseas** [comment]
> Damus は、あなたが使用している言語が "日本語" であると検出しました。"日本人" をフォローできるリレーのみをリレー一覧に追加しますか

> Quoted strings should be replaced to another languages or name of groups speaking the languages.

https://damus.io/note18q8q5rg4pcpxqw4263se94t9lzzdx0mmtn2hykzt94t2jmz0vhaq2qkr30

**Comment by alltheseas** [comment]
@tyiu you able to lend a hand prior to Nostrasia?

**Comment by alltheseas** [comment]
@danieldaquino @jb55  I propose this ticket to be added to the subsequent sprint 7 starting the following Monday Oct 30th. Nostrasia in 🗾 starts Nov. 1st. Ideally we have this one added at least to testflight by then 🙏.

**Comment by danieldaquino** [comment]
> @danieldaquino @jb55 I propose this ticket to be added to the subsequent sprint 7 starting the following Monday Oct 30th. Nostrasia in 🗾 🇯🇵 starts Nov. 1st. Ideally we have this one added at least to testflight by then 🙏.

@alltheseas, @jb55, would it make sense to bring this ticket into the current sprint and remove some lower priority items that haven't been worked on yet?

**Comment by alltheseas** [comment]
@danieldaquino I did not want to bring this up, as I prefer having a two week plan & commitment, but I think this makes sense due to my poor planning and the upcoming Nostrasia conference in 🇯🇵  

😅

**Comment by danieldaquino** [comment]
Started to work on this. To increase chances of getting this in before Nostrasia I will send two patches:
1. One where the JP relays are automatically added on the background if they detect the user has the Japanese locale setup on their phone _(Simpler changeset)_
2. A second one with a nicer UI prompt during onboarding, if the user has the Japanese locale setup on their phone. _(which I will work on after sending patch 1)_

I will focus on this today and get the patches sent ASAP to give @jb55 at least half of October 31st (in Japan time) to review, merge, and push a new Testflight version with patch 1 or 2 (hopefully 2)

**Comment by alltheseas** [comment]
> Started to work on this. To increase chances of getting this in before Nostrasia I will send two patches:
> 
> 1. One where the JP relays are automatically added on the background if they detect the user has the Japanese locale setup on their phone _(Simpler changeset)_
> 2. A second one with a nicer UI prompt during onboarding, if the user has the Japanese locale setup on their phone. _(which I will work on after sending patch 1)_
> 
> I will focus on this today and get the patches sent ASAP to give @jb55 at least half of October 31st (in Japan time) to review, merge, and push a new Testflight version with patch 1 or 2 (hopefully 2)

ありがとう、良かったです

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, I sent the patch for the simplified version of this feature _(along with all relevant info and testing)_ via email to patches@damus.io.

It can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/FvxA1Am90YY

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, I remember we discussed on a previous meeting that we might want to keep this feature simple by just having the Japanese regional relays being automatically loaded if the user's locale is JP.

In that case, do we want to close this ticket? Or is there any additional work we would still like to address in this one?

**Comment by alltheseas** [comment]
💯
