### ISSUE TITLE
Re-post attempt of note in thread re-posts parent note

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1448]
_what happens_
When I attempt to re-post a note in the thread of another note, Damus reposts the parent note, and not the note in thread I intended to re-post

https://nostr.build/av/d2f4b85aa02ffab100d939e19dff15b02084e87a9d591b1c160f39df8dcda6b2.mov

Note: 

Https://damus.io/note17l4kf3ay2ue45lrcdlrs60mfzdxp66mv702g25cunv40zfd4m4nq399j2s

Origin: Tanel

**Comment by alltheseas** [comment]
Reported broken in 1.6 (11)

https://damus.io/note15w62ft7xpzw3j3wayj0fw2smwdfcanpzrmlevfyds4r0gnyj6dtscenmmr

**Comment by jb55** [comment]
Fixed in build 12

**Comment by alltheseas** [comment]
Still reporting as broken

https://damus.io/note1zfuhspg8n4zvgu3dlk5kxmlwu333f62v3rek2ug2ft9qtxdcspls00jacg

**Comment by alltheseas** [comment]
Closing again. Original
Issue is fixed. There are potential new, related issues. Will create new tickets for these as I confirm.
