### ISSUE TITLE
Quick change from large to small font size crashes damus

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1451]
1.6 (10) 14ba33674b91

_what happens_
When I quickly change from large to small font size damus crashes

https://github.com/damus-io/damus/assets/64376233/d6271273-bd70-4009-bf49-8d02c124eaed

Origin: signal rage

**Comment by bryanmontz** [comment]
This is reproducible on an iOS 16 simulator. The problem is that the `UserSettingsStore` is not isolated to the MainActor, so when the writes and reads are happening rapidly, sometimes a race condition will hit and read and write will happen at the same time.

**Comment by jb55** [comment]
On Sat, Aug 05, 2023 at 07:00:47PM -0700, Bryan Montz wrote:
>This is reproducible on an iOS 16 simulator. The problem is that the
>`UserSettingsStore` is not isolated to the MainActor, so when the
>writes and reads are happening rapidly, sometimes a race condition will
>hit and read and write will happen at the same time.

I wonder if we're seeing similar crashes in the NavigationCooordinator
for the some reason? I will try isolating it to the main actor.

**Comment by jb55** [comment]
On Sun, Aug 06, 2023 at 07:17:27AM -0700, William Casarin wrote:
>On Sat, Aug 05, 2023 at 07:00:47PM -0700, Bryan Montz wrote:
>>This is reproducible on an iOS 16 simulator. The problem is that the
>>`UserSettingsStore` is not isolated to the MainActor, so when the
>>writes and reads are happening rapidly, sometimes a race condition will
>>hit and read and write will happen at the same time.
>
>I wonder if we're seeing similar crashes in the NavigationCooordinator
>for the some reason? I will try isolating it to the main actor.

didn't seem to help :(

**Comment by alltheseas** [comment]
I cannot recreate this bug anymore

**Comment by alltheseas** [comment]
Neither can original bug reporter
