### ISSUE TITLE
NIP-36 Content Warning support

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1458]
https://damus.io/note1qkueder5q9j2t85nufufrl2aj4pkp303wkmdppem6qtsft3kut5q4j9jd8

> Hello. I have one question. Among Japanese users, it is often talked about that damus does not support content-warning (NIP-36).
This is because when we want to set content-warning for we own content, there is little point in setting it if it is not effective with the current mainstream clients.
Can you tell me if this is intentionally not implemented in damus or if it simply does not exist yet?

**Comment by alltheseas** [comment]
Duplicate request https://github.com/damus-io/damus/issues/910
