### ISSUE TITLE
Edit profile issues

### ISSUE THREAD

**Issue by pors** [damus-io/damus#146]
The update to 0.1.8 (3) provided the possibility to edit your profile. Cool! :)

I had already set my pfp and name with another client. When I opened the new Damus release all profile data was gone.

Secondly, I tried to add my pfp again (with a link this time as Damus requires) but that doesn't work. The link is accepted, but the pfp is not set.

I'm @pors / npub18yyjg0g0pvgtxxf8urxl2d92t82l6xkjxgugh7zs4c7qzdk3t8rsrs2xde on nostr. Feel free to ask me more there as well.

**Comment by alltheseas** [comment]
@pors is this issue fixed for you?

**Comment by pors** [comment]
Yes, thanks
