### ISSUE TITLE
Multiple grey lines appear sometimes in profile view

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1462]
Unsure how to recreate. Occurs in 1.6 (11) iOS 16 

![image](https://github.com/damus-io/damus/assets/64376233/60f7ab91-d82a-4d2b-bca2-0fa61ef49a8f)

https://damus.io/note1rrat4jdxum9t6jvlkfya554e0jgux0y26mkqzgxfe7jg2asu9ndss77gnp

![image](https://github.com/damus-io/damus/assets/64376233/d9f3729e-5064-4150-ae8d-acbf9f6f4d48)

https://damus.io/note1msr8ljjlqy36rlm5dqvqmlfd4xd7cw209dc96la0z5aw3hkjae2qkqxmde

**Comment by jb55** [comment]
These are boosts failing to load I think...

**Comment by jb55** [comment]
Fixed in 7467a9d5b1380d8b200cdf4b11ae36520630b604
