### ISSUE TITLE
Investigate primal breaks damus relay list

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1466]
https://damus.io/note10lahc609y6j84t0xndfekxlcsl5nh6rqhdxkh4jlwp9xmwp5f27q4ahxj6

**Comment by jb55** [comment]
is this really a damus issue if primal wipes relay lists?

**Comment by alltheseas** [comment]
> is this really a damus issue if primal wipes relay lists?

I don't know the relay implementation details on either end. If you tell me this is a Primal issue we can close.

Just tagged Miljan to look on his end.

**Comment by alltheseas** [comment]
@mbrat1

**Comment by alltheseas** [comment]
https://damus.io/note1ehzlqqzq4scm3y2yv3xhf4c7qu55kljg9ks2vjsw6fsgd7uj0a8qrvg0w3

**Comment by alltheseas** [comment]
Closing issue, as is not caused by Damus
