### ISSUE TITLE
Frequent app crash on emoji selector

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1475]
When selecting an emoji response on a note from the reaction set, the app frequently crashes. 

Returning to the app, sometimes the response was recorded, occasionally it isn't. 

Problem has persisted since the feature launch, observed daily on 1.6 build 12.

**Comment by alltheseas** [comment]
@suhailsaqan

**Comment by alltheseas** [comment]
@dmnyc new #2204 emoji picker will be updated to 1.8. Let's test on 1.8, and re-open as needed.
