### ISSUE TITLE
Nostrscript error

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1482]
Error occurs when running zap nostrscript

![image](https://github.com/damus-io/damus/assets/64376233/75cb260e-3f51-477a-a73a-73e7aef6ea1a)

https://damus.io/note13pe0r7rvg32lfaqsde0qytgr3k4w90am8fkcvjnp4kpev4sndyas6n7pn8

1.6 (12) 7467a9d5b138

iOS 16.6 (20G75) (iPhone SE 2020)

**Comment by jb55** [comment]
Fixed in build 12 (7f313dcbd4f5cd2f0cb50a37643ccd7b82955b45)

**Comment by alltheseas** [comment]
What was the cause?

**Comment by jb55** [comment]
On Fri, Aug 18, 2023 at 10:05:07AM -0700, alltheseas wrote:
>What was the cause?

nostrscript was trying to allocate 1gb of virtual memory but iOS didn't
like that on phones with not that much memory
