### ISSUE TITLE
I can't make any posts

### ISSUE THREAD

**Issue by SandroLola** [damus-io/damus#1485]
I can't make any posts, I already logged out and after logging in again and this problem remains.

**Comment by alltheseas** [comment]
Are you logging in with your npub or nsec?

**Comment by SandroLola** [comment]
Yes. I've tried using other clients (I normally use Snort), I managed to make a post on Iris, but when I check on Snort in "Notes" my posts don't appear and apparently these posts don't appear for part of my followers. I didn't delete any relay...

**Comment by SandroLola** [comment]
Explaining better: in Snort, only the old posts appear, the new ones made in Iris, do not appear.

**Comment by alltheseas** [comment]
> Are you logging in with your npub or nsec?

When you are logging in with damus does the string you are logging in with begin with "npub"?

**Comment by SandroLola** [comment]
I logged in with my mnemonic (phrase)

**Comment by SandroLola** [comment]
I just tried to login in the following ways: nsec, npub, mnemonic and Nip-07.
I couldn't post it anyway...

**Comment by SandroLola** [comment]
In Iris I added some relays, but in Snort they don't show up to date, it only shows the ones I already had.
In Coracle, these relays appear in Iris.

**Comment by alltheseas** [comment]
Sorry, I not familiar with snort or coracle. Try asking on their github.

Damus does not support mnemonics. If you log in your npub you will not be able to post. 

You must use your nsec if you want to post on Damus.

Be aware that sometimes there are cross client compatibility issues.

**Comment by SandroLola** [comment]
Thank you very much!!
I'll look for Snort's channel!

**Comment by SandroLola** [comment]
Just one more question... How do I find my nsec?
I apologize for my silly questions, I'm a very newbie...

**Comment by alltheseas** [comment]
@v0l

https://github.com/v0l/snort

**Comment by alltheseas** [comment]
> Just one more question... How do I find my nsec?
> 
> I apologize for my silly questions, I'm a very newbie...

When you are creating a new profile in Damus, you are prompted to save your nsec during onboarding. 

If you are logged in on Damus

Settings -> Keys -> "secret account login key"
