### ISSUE TITLE
In tab zap notifications reported broken

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1486]
![image](https://github.com/damus-io/damus/assets/64376233/af36de75-0a81-4024-815d-e1d80624f359)
https://damus.io/note1mvw5rh6wmchrhe9agl73rpzrqzwsdrsvq7u5smw250vjenp32u2sqyz0gx

https://damus.io/note1d0qdnal5pd2td579cxfln7cfyg9h5gwwxyyee0a8uc5v54gakksqgu3lru

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/b261909f-52d6-4959-9c40-9679999c4718)

**Comment by jb55** [comment]
fixed in 006a6ef16fda1a16716c927a731e74a6d7c57ee7 already
