### ISSUE TITLE
Grey lines reappear

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1488]
https://damus.io/note1mjchfecpl07p0ss5fjnwj9k60tpgvuv95hv2gy45d43kpp9vukxsscv9y6

note1shqa7ye9f4ujw9kwu6s3gtex4wxyjnlzad8az27d50xhh8lzk7kqv3uvly

**Comment by jb55** [comment]
On Sat, Aug 19, 2023 at 06:48:29AM -0700, alltheseas wrote:
>https://damus.io/note1mjchfecpl07p0ss5fjnwj9k60tpgvuv95hv2gy45d43kpp9vukxsscv9y6
>
>note1shqa7ye9f4ujw9kwu6s3gtex4wxyjnlzad8az27d50xhh8lzk7kqv3uvly

so we fixed these in the sense of damus users generating them... but
other clients can still generate bad reposts. We need to render
spec-invalid reposts or maybe just not show them?

**Comment by alltheseas** [comment]
Ooff. 

I will create a new label "bugs caused by other clients".

It will help me keep track, even if we cant fix. 

I can also tag other team devs. 

Do you know which client caused this one in particular?

**Comment by alltheseas** [comment]
These are generated via a mastodon profile via mostr relay

![image](https://github.com/user-attachments/assets/536b62c3-9e7a-486b-849b-75c1f133ba9e)

note15je304arzet5stpsrkp0see8qtu0qgt48aqdpmqncpmyuwgv8dlq0nusdp

npub1fswqjjewpk8y2u5lhrj9hxu22eqg07cxd093g7m3ppmyup8qqwkqyqfc9a

**Comment by alltheseas** [comment]
Duplicate of https://github.com/damus-io/damus/issues/1722 ?
