### ISSUE TITLE
Image gallery formatting issue when many images are included in a single note

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1492]
I just discovered this one today. On the latest release of Damus 1.6 (15) I posted the following note:

note1lpk4yaea4zh37jy464k9qsmfn4nhmwt0xva9yaw7wthqvsp54sxqv58ja4

The linked note contained over 30 images. When this was displayed, it broke the margins. 

note1986sqz7zpmfjmfrp66m9yuyhlqyza3pslw0nnv84qf6dakc3njssz5px0q

Screenshot below:
![image](https://github.com/damus-io/damus/assets/3638467/330a8541-c066-428a-837a-c1bde6e87656)

**Comment by alltheseas** [comment]
Duplicate of https://github.com/damus-io/damus/issues/1295
