### ISSUE TITLE
Long form note does not render

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1493]
https://damus.io/note10ds7rdjejahxulpfa377jdphhgt0nfg0z6xfq58h23vvk22957hq72w2lw

Habla news nostr report does not render appears perpetually loading

**Comment by jb55** [comment]
On Sun, Aug 20, 2023 at 12:41:38PM -0700, alltheseas wrote:
>https://damus.io/note10ds7rdjejahxulpfa377jdphhgt0nfg0z6xfq58h23vvk22957hq72w2lw
>
>Habla news nostr report does not render appears perpetually loading

This note isn't on the damus relay, it's possible it was replaced? I
think the underying issue is that damus should be sharing the naddr link
instead of note link for replacable events.

**Comment by alltheseas** [comment]
> On Sun, Aug 20, 2023 at 12:41:38PM -0700, alltheseas wrote:
> >https://damus.io/note10ds7rdjejahxulpfa377jdphhgt0nfg0z6xfq58h23vvk22957hq72w2lw
> >
> >Habla news nostr report does not render appears perpetually loading
> 
> This note isn't on the damus relay, it's possible it was replaced? I
> think the underying issue is that damus should be sharing the naddr link
> instead of note link for replacable events.
> 
> 
Doc advised it was the original note:

![image](https://github.com/damus-io/damus/assets/64376233/158b561c-69a5-4cb6-9abf-9c5a62ebf944)

**Comment by jb55** [comment]
On Sun, Aug 20, 2023 at 03:56:10PM -0700, alltheseas wrote:
>> On Sun, Aug 20, 2023 at 12:41:38PM -0700, alltheseas wrote:
>> >https://damus.io/note10ds7rdjejahxulpfa377jdphhgt0nfg0z6xfq58h23vvk22957hq72w2lw
>> >
>> >Habla news nostr report does not render appears perpetually loading
>>
>> This note isn't on the damus relay, it's possible it was replaced? I
>> think the underying issue is that damus should be sharing the naddr link
>> instead of note link for replacable events.
>>
>>
>Doc advised it was the original note:
>
>![image](https://github.com/damus-io/damus/assets/64376233/158b561c-69a5-4cb6-9abf-9c5a62ebf944)

I don't see it on the damus relay, please advise which relay I can find this note at for debugging:

nostril query -i 42a3ac0b26b3b2e829329b3c315c1627e4787828c816b90782c3fe47afa5bf29 | nostcat wss://relay.damus.io

(42a3ac0b26b3b2e829329b3c315c1627e4787828c816b90782c3fe47afa5bf29 is note1g236czexkwews2fjnv7rzhqkylj8s7pgeqttjpuzc0ly0ta9hu5s8u2dg5, the id that is not loading)

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/1d1f6617-c89a-4ffd-acab-6406f570c8a6)

@jb55 

https://damus.io/note1rlpk6lcv7vxqcze8j3f0x9ak4kksdqw74rd9s3rxm2688kyhg5uswwh7wn

**Comment by jb55** [comment]
Can't reproduce
