### ISSUE TITLE
Automatically broadcast quote notes (quoted re-posts)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1495]
## user story
As a Damus user who is quoting a note, I would like Damus to automatically broadcast said note upon quote-note, so that my quote note can reach my followers, and other nostr network nostriches.

### acceptance criteria
1. if pleb quote notes a note (quote re-post), Damus automatically broadcasts said quote note

_comment_
Damus already does this when replying (may be issue for private relays; future problem)

**Comment by danieldaquino** [comment]
Starting to work on this one!

**Comment by danieldaquino** [comment]
## Patch

Sent a patch via email that fixes this issue. All code, testing documentation, and discussion can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/yGDKOaqpSpg
