### ISSUE TITLE
fix padding In reply focus view there is padding missing between profile picture and name

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1508]
Screenshot attached.
![image](https://github.com/damus-io/damus/assets/3638467/4deee292-bda4-4801-8a50-7d92c894f821)

Reference note ID:
note1wafkaua4ughw4gqvpgdmxcy8a2x3s4vcyshmw3emunsdvg3jr7zs7qmp0l

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/issues/1509
