### ISSUE TITLE
Optimized video transcoding before upload

### ISSUE THREAD

**Issue by fishcakeday** [damus-io/damus#1510]
We need to transcode videos to a web streamable MP4 with proper GOP spacing and key frame placed in the beginning of the file. This will allow videos to be playable immediately. Additionally, we need to reduce resolution that is sensible for social media playback, 480p being the best compromise.

**Comment by alltheseas** [comment]
Done

**Comment by jb55** [comment]
yeah we need this badly

**Comment by alltheseas** [comment]
@fishcakeday remind me ser, did you submit a patch for this?

cc @danieldaquino

**Comment by alltheseas** [comment]
> @danieldaquino is better equipped to implement it, but I could definitely suggest specific parameters. Sorry, but I am really short on time to work on this. Will be glad to review the code and suggest specifics if needed. Thanks.

Thanks ser, not suggesting you work on this.

**Comment by jb55** [comment]
Broke down all the tasks into our media optimization tracking ticket:

- #2214
