### ISSUE TITLE
Fix tenor gif render

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1512]
_what happens_

Tenor gif link does not render in Damus

note1t6zd28zvgtjasqyk3g8txvf9skkj52ulkqewwk8dz9utuxv8g5gqelnqs7

![image](https://github.com/damus-io/damus/assets/64376233/152f75e4-d1fc-43ab-9235-f14ef40248de)

**Comment by jerihass** [comment]
Either this is resolved [1.6 (17)], or maybe it has to do with the way it was linked?
Posting the URL for the gif itself seems to work: note1lsuxr3ezalwlryhk2cqa8cz37m6pkdjeq8fdp3j78xl4hgac07ys6eacct

![IMG_0618](https://github.com/damus-io/damus/assets/77637794/53f2985c-93d4-4451-a270-058ba0508076)

**Comment by alltheseas** [comment]
Appears resolved
