### ISSUE TITLE
Long-form event sharing link

### ISSUE THREAD

**Issue by armstrys** [damus-io/damus#1515]
_what happens_

Event sharing link on long-form note directs to snort, which current doesn't render long-form. On my phone it redirects to Damus, but on a phone without Damus snort in the browser just displays the event json. 

_suggestion_

Maybe long-forms can redirect to habla?

Example: https://damus.io/note1cqyed2386uqmsqwmyuqtsrvvudu4kgu77nwa6nys73cxl5xc26gser6esy

**Comment by alltheseas** [comment]
Great suggestion

**Comment by alltheseas** [comment]
See https://github.com/damus-io/damus/issues/1140

**Comment by alltheseas** [comment]
Damus.io now uses [notecrumbs](https://github.com/damus-io/notecrumbs) to render notes, including long form notes.

![Screenshot 2024-02-12 at 9 18 57 PM](https://github.com/damus-io/damus/assets/64376233/a4c9878d-b436-46e6-9fd0-5112e99fdd9b)



Specific long form note design is lacking https://github.com/damus-io/notecrumbs/issues/11
