### ISSUE TITLE
Hashtag contains linked punctuation

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1518]
At the end of the hashtag I included a … character which was not intended to be linked to the tag but Damus included it anyway. 

note ID:
note1a8y42nfmeyz4gnvmjxta8k2l8dzl4sa9y6m726aa976ludlzq56sjde5dg

![image](https://github.com/damus-io/damus/assets/3638467/3f9c3098-438b-4750-b440-8bede1efabb7)

**Comment by alltheseas** [comment]
Did you add a space between your intended hashtag and the subsequent characters?

**Comment by dmnyc** [comment]
No, but hashtags should never include punctuation. I put other punctuation
at the end like periods and exclamation marks and they don’t cause this
issue.

**Comment by alltheseas** [comment]
> I put other punctuation
at the end like periods and exclamation marks and they don’t cause this
issue.

On Damus? On Twitter?

**Comment by dmnyc** [comment]
Either one, but here’s an example.

The tag #zapathon is followed by a period but it’s not linked.

note1gcv2lskpdf4umthlfrjsqdtplvqmv8mpt3lzwaku405lcz9pnuysyf8sjz

**Comment by alltheseas** [comment]
Thanks, that helps.

**Comment by dmnyc** [comment]
Three periods as an ellipsis character … is what I believe caused the issue.

**Comment by dmnyc** [comment]
note12u7dx9gcm3tapau7ljqk7ymkc2lz7zkh0u3w85ndsed7s3kpl8ys943vz7

**Comment by jonmarrs** [comment]
Here are some examples of how hashtags are displayed with the patch I am proposing (https://github.com/jonmarrs/damus/commit/336215a78f51cfbb985d1cd86d4c5b52e3da1619).

<img width="350" alt="image" src="https://github.com/damus-io/damus/assets/40682667/564cbd19-3a95-443c-bb3e-89ae73ae029f">

<img width="349" alt="image" src="https://github.com/damus-io/damus/assets/40682667/267d2289-8406-4dd4-abce-ea72163a1c10">

<img width="353" alt="image" src="https://github.com/damus-io/damus/assets/40682667/3a8b2145-d831-4d4e-b5a4-deb4ec37d7d6">

<img width="352" alt="image" src="https://github.com/damus-io/damus/assets/40682667/705c1c06-97c8-4adc-9cc9-578d308ddde0">

Let me know if you would like me to run any other tests.

**Comment by jonmarrs** [comment]
> note12u7dx9gcm3tapau7ljqk7ymkc2lz7zkh0u3w85ndsed7s3kpl8ys943vz7

Here is how this note looks with my proposed code change:

<img width="340" alt="image" src="https://github.com/damus-io/damus/assets/40682667/6e77faaf-792e-4176-b9e0-d27c6f48cecc">

**Comment by dmnyc** [comment]
Yes, that’s the expected behavior.

**Comment by alltheseas** [comment]
> Here are some examples of how hashtags are displayed with the patch I am proposing ([jonmarrs@336215a](https://github.com/jonmarrs/damus/commit/336215a78f51cfbb985d1cd86d4c5b52e3da1619)).
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/40682667/264423469-564cbd19-3a95-443c-bb3e-89ae73ae029f.png"> <img alt="image" width="349" src="https://user-images.githubusercontent.com/40682667/264424533-267d2289-8406-4dd4-abce-ea72163a1c10.png"> <img alt="image" width="353" src="https://user-images.githubusercontent.com/40682667/264425119-3a8b2145-d831-4d4e-b5a4-deb4ec37d7d6.png"> <img alt="image" width="352" src="https://user-images.githubusercontent.com/40682667/264425550-705c1c06-97c8-4adc-9cc9-578d308ddde0.png">
> Let me know if you would like me to run any other tests.

Thanks @jonmarrs 

Have you reviewed the [contributing guidelines](https://github.com/damus-io/damus/blob/c71b0ee91688f4a975000e33b5dc37a0f0e74c6d/docs/CONTRIBUTING.md#L4)?

**Comment by dmnyc** [comment]
Looks perfect.

**Comment by alltheseas** [comment]
@jonmarrs if you join the dev chat, it can be helpful sometimes to ping questions with the other devs

https://simplex.chat/contact#/?v=1-4&smp=smp%3A%2F%2FenEkec4hlR3UtKx2NMpOUK_K4ZuDxjWBO1d9Y4YXVaA%3D%40smp14.simplex.im%2Fi_G-OJedYDl0fRlQbYjG0SUAn0cLmvzq%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAxVsOa6uphThfVq0u0uYRqNFZkv2W2UhoPR3lHnu0gAo%253D%26srv%3Daspkyu2sopsnizbyfabtsicikr2s4r3ti35jogbcekhm3fsoeyjvgrid.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%223imMonp-dw_d0-QIyXbRnQ%3D%3D%22%7D

**Comment by jonmarrs** [comment]
> Three periods as an ellipsis character … is what I believe caused the issue.

Just wanted to give a quick update. I've been looking at how "..." is encoded in Damus, and it is indeed being encoded as an ellipsis rather than three separate periods. Apparently the ellipsis is encoded in UTF-8 as 0xE2 0x80 0xA6 (https://www.compart.com/en/unicode/U+2026). So those three hex values (0xE2 0x80 0xA6) that encode the ellipsis are not being detected as punctuation.
<img width="1013" alt="image" src="https://github.com/damus-io/damus/assets/40682667/d6e68635-5aa1-4d06-8ee1-e18fd42d34e6">
Perhaps we should check for an ellipsis when parsing a hashtag.

**Comment by jb55** [comment]
On Thu, Aug 31, 2023 at 04:20:30PM -0700, Jon Marrs wrote:
>> Three periods as an ellipsis character … is what I believe caused the issue.
>
>Just wanted to give a quick update. I've been looking at how "..." is encoded in Damus, and it is indeed being encoded as an ellipsis rather than three separate periods. Apparently the ellipsis is encoded in UTF-8 as 0xE2 0x80 0xA6 (https://www.compart.com/en/unicode/U+2026). So those three hex values (0xE2 0x80 0xA6) that encode the ellipsis are not being detected as punctuation.
><img width="1013" alt="image" src="https://github.com/damus-io/damus/assets/40682667/d6e68635-5aa1-4d06-8ee1-e18fd42d34e6">
>Perhaps we should check for an ellipsis when parsing a hashtag.

yeah we might need to be smarter about checking punctuation, since utf-8
chars are allowed in hashtags and we definitely want to keep that.

**Comment by jonmarrs** [comment]
We could try to detect this block of unicode punctuation (https://www.compart.com/en/unicode/block/U+2000), which contains the ellipsis and other punctuation marks.
All these characters start with 0xE2, and the middle hex value is either 0x80 or 0x81.

**Comment by jonmarrs** [comment]
Here is my proposed solution for selectively filtering UTF-8 punctuation: https://github.com/damus-io/damus/compare/master...jonmarrs:damus:2023-08-hashtag-linked-punctuation

**Comment by jonmarrs** [comment]
My new code passes the hashtag test cases. UTF-8 characters are included in hashtags, but UTF-8 punctuation is filtered.
<img width="250" alt="image" src="https://github.com/damus-io/damus/assets/40682667/9f911a14-9bd2-4c53-aec8-1edf95a9c8cb">

**Comment by dmnyc** [comment]
Out of curiosity, is there any reason to include non-alphanumeric characters in hashtags?

**Comment by jonmarrs** [comment]
Looks like Twitter / X also leaves out currency symbols. 
<img width="187" alt="image" src="https://github.com/damus-io/damus/assets/40682667/396487fc-ef93-41f0-b7fb-16539d075a29">

**Comment by jonmarrs** [comment]
It seems like the overall strategy should be to decide which UTF-8 categories/blocks we want to filter out from hashtags.
Here is a list of unicode blocks: https://www.compart.com/en/unicode/block

Right now I am filtering out [General Punctuation](https://www.compart.com/en/unicode/block/U+2000).
I could also filter out [Currency Symbols](https://www.compart.com/en/unicode/block/U+20A0).
Anything else I should filter out?

<img width="533" alt="image" src="https://github.com/damus-io/damus/assets/40682667/fe0e70f0-836f-4572-8fc4-1c2b86c892a2">

**Comment by jonmarrs** [comment]
Here are some more test results.

Twitter: https://twitter.com/Martian_BTC/status/1697676619530506353?s=20
![image](https://github.com/damus-io/damus/assets/40682667/adafcfaa-ad74-4eea-9195-1ac49ef85d60)

Damus (iPhone app):
![image](https://github.com/damus-io/damus/assets/40682667/a03699dd-5e41-4b8b-9e7f-d5560831d62b)

My patch as it is now:
<img width="117" alt="image" src="https://github.com/damus-io/damus/assets/40682667/6362b3de-1b40-4d1a-9810-374aec9bb77f">

Clearly there are some inconsistencies. As far as I know, there is no ISO standard for hashtags. Should the goal be for Damus to replicate how Twitter/X handles hashtags as closely as possible?

**Comment by jb55** [comment]
>Clearly there are some inconsistencies. As far as I know, there is no ISO standard for hashtags. Should the goal be for Damus to replicate how Twitter/X handles hashtags as closely as possible?

probably, theirs works quite well.

**Comment by jonmarrs** [comment]
Please review my pull request (https://github.com/damus-io/damus/pull/1546), which I believe closes this issue.
