### ISSUE TITLE
Drop muted notes to the bottom of list of replies

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1522]
## user story
As a Damus user who is browsing a thread full of replies, I would like Damus to move muted notes to the very bottom of all the replies, so I can improve my signal to noise ratio when browsing.

### acceptance criteria

1. Automagically Damus moves notes from muted users to the bottom of reply threads, and
2. Automagically Damus moves muted notes to the bottom of reply threads.

origin: singal rage

**Comment by danieldaquino** [comment]
Implemented this change!

The code changes and testing report were send via email to patches@damus.io, and can be viewed here: https://groups.google.com/a/damus.io/g/patches/c/Hns58kH4FUU
