### ISSUE TITLE
Hold tap to preview status URL

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1523]
## user story
As a Damus user exploring status url box, I would like a way to preview the URL without clicking on it, so I have some indication of where the link leads.

### acceptance criteria 

1. User can tap hold on the status URL, and the url is displayed (see tap hold mechanism on zap icon)

Origin: Tanel

**Comment by jerihass** [comment]
This is implemented now: I can submit patch if people like it.


https://github.com/damus-io/damus/assets/77637794/cd6be38b-f2bb-426a-92d8-26a74dfc2f4c

**Comment by alltheseas** [comment]
@robagreda what do you think about this UX?

@jerihass have you reviewed https://github.com/damus-io/damus/blob/b1e0a6210987da97f0b3c66ce58ef85b6cb3c3d1/docs/CONTRIBUTING.md

**Comment by robagreda** [comment]
@alltheseas I like it, I like the separation of the link and the preview of the link. Really a useful thing.

**Comment by jerihass** [comment]
Submitted: https://groups.google.com/a/damus.io/g/patches/c/YTXT70flALc

**Comment by jb55** [comment]
On Thu, Sep 14, 2023 at 05:59:16AM -0700, jerihass wrote:
>Submitted: https://groups.google.com/a/damus.io/g/patches/c/YTXT70flALc

thanks! will check it out soon
