### ISSUE TITLE
Add video UI controls [100k sats]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1530]
## user story

As a Damus user who plays videos, I would like video player UI controls - pause, play, volume, full screen, play speed - so that I can better control videos to my preference.

### acceptance criteria
1. Can play & pause
2. Can change volume visually w/ vertical bar
3. Can change playback settings: 0.5, 0.75, 1.0, 1.25, 1.5, 2.0 playback speed
4. Can enter and exit fullscreen

<img width="501" alt="Screenshot 2023-09-02 at 5 08 08 PM" src="https://github.com/damus-io/damus/assets/64376233/84363cab-2f27-4432-a631-f78200f113c1">

<img width="45" alt="Screenshot 2023-09-02 at 5 08 21 PM" src="https://github.com/damus-io/damus/assets/64376233/8a3301f2-c6cd-411b-b1ac-1c436018e702">

<img width="253" alt="Screenshot 2023-09-02 at 5 08 16 PM" src="https://github.com/damus-io/damus/assets/64376233/18de1cfe-0c3f-4492-8bff-44e1bea003ce">

100k sats bounty by @dmnyc 

https://github.com/damus-io/damus/issues/1386#issuecomment-1703911184

**Comment by kroucis** [comment]
I am working on this feature now, is the bounty still available?

**Comment by alltheseas** [comment]
Yes

**Comment by alltheseas** [comment]
> What do you all think: should I wait on the fix until after the UI controls have been reviewed/merged, or try to craft a fix before the UI controls that might need to be changed because of the merge?

This is a @jb55 question. 

@bryanmontz is fixing the video player double playback bug, so I would recommend waiting until playback bug is fixed.

**Comment by alltheseas** [comment]
https://damus.io/note150m02jqsltz2la264k6d58saf8qaw2cz95x6yeayt6ugpwsgfalqf6m75e

**Comment by danieldaquino** [comment]
@jb55 @ericholguin @alltheseas following up on today's standup meeting, I will try to tackle this ticket first, and then work on other video support tickets.

Please let me know if there is another particular ticket that you think I should tackle before this one.

**Comment by danieldaquino** [comment]
@jb55 @alltheseas, I believe I am getting close to completing this one. I have a working draft which is mostly ready, but I still need to fix some minor details here and there.

This issue involves getting around some SwiftUI quirks, so I tried to make the best UX I could within SwiftUI's quirks. It is also familiar UX for those coming from Twitter or other social apps. Here is how it works:

1. Videos on the feed only have a mute/unmute button
2. When the user clicks on the video, they are taken to a full screen carousel view (similar to when you click on an image)
3. The full-screen carousel view now includes a short version of the note, for context and reading.
4. The full-screen carousel view shows all video playback controls.
5. If the carousel has multiple videos/images, the user can swipe between them normally as expected

Here is a short demo: https://drive.google.com/file/d/1r3JWZFljrzn8eriaZliQzX4fY0iYzecL/view?usp=sharing
I also sent a draft patch series: https://groups.google.com/a/damus.io/g/patches/c/6LQ5xVuJC_0

Please let me know if you think this is going in the right direction, or if you have any requests, suggestions, feedback, etc.

Thanks!

**Comment by jb55** [comment]
On Wed, Mar 13, 2024 at 05:32:08PM -0700, Daniel D’Aquino wrote:
>@jb55 @alltheseas, I believe I am getting close to completing this one. I have a working draft which is mostly ready, but I still need to fix some minor details here and there.
>
>This issue involves getting around some SwiftUI quirks, so I tried to make the best UX I could within SwiftUI's quirks. It is also familiar UX for those coming from Twitter or other social apps. Here is how it works:
>
>1. Videos on the feed only have a mute/unmute button
>2. When the user clicks on the video, they are taken to a full screen carousel view (similar to when you click on an image)
>3. The full-screen carousel view now includes a short version of the note, for context and reading.
>4. The full-screen carousel view shows all video playback controls.
>5. If the carousel has multiple videos/images, the user can swipe between them normally as expected
>
>Here is a short demo: https://drive.google.com/file/d/1r3JWZFljrzn8eriaZliQzX4fY0iYzecL/view?usp=sharing

this is slick! this is exactly what I had in mind.

**Comment by alltheseas** [comment]
🙏

**Comment by dmnyc** [comment]
Excellent, nice solution!

**Comment by danieldaquino** [comment]
@jb55, I fixed several minor issues I was seeing with the changes, did more thorough testing, and sent you the official (non-draft) patch series (https://groups.google.com/a/damus.io/g/patches/c/H0IYJJSgzX4)

Please let me know if you have any suggestions, concerns, or questions!


P.S. If the bounty is still up and these changes fulfill all criteria for the bounty, I believe it should be paid to Damus itself and not directly to me _(Since I made these changes during my usual work hours)_.

Thanks!

**Comment by jb55** [comment]
> P.S. If the bounty is still up and these changes fulfill all criteria for the bounty, I believe it should be paid to Damus itself and not directly to me _(Since I made these changes during my usual work hours)_.

it's fine if you collect the bounty, you did fix it after all.

**Comment by danieldaquino** [comment]
> > P.S. If the bounty is still up and these changes fulfill all criteria for the bounty, I believe it should be paid to Damus itself and not directly to me _(Since I made these changes during my usual work hours)_.
> 
> it's fine if you collect the bounty, you did fix it after all.

@dmnyc, if the changes made on the App Store 1.8 satisfy your criteria for the bounty, can you please redirect the bounty to @alltheseas instead (not me)?

I think he has his zaps redirected somewhere else though, it might be a good idea to double-check with him about the LN address.

Thank you very much 🙏

**Comment by dmnyc** [comment]
Sure thing! @alltheseas Let me know where you want me to send it. 🙌⚡️

**Comment by alltheseas** [comment]
Zap Daniel

**Comment by jb55** [comment]
On Wed, May 15, 2024 at 12:26:36PM GMT, alltheseas wrote:
>Zap Daniel

:+1:

**Comment by dmnyc** [comment]
![bounty](https://github.com/damus-io/damus/assets/3638467/69d245d0-2e92-4509-86a7-e1ec6b39fae1)

**Comment by danieldaquino** [comment]
Thank you @dmnyc!! Also thank you @alltheseas for mirroring the zap back to me ⚡️🪞😜
