### ISSUE TITLE
Cannot remove a relay

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1531]
_what happens_

In 1.6 (11) I cannot remove some relays. If I revert to 1.6(1) to 1.6(10) I can remove the relay

https://damus.io/note1ehzlqqzq4scm3y2yv3xhf4c7qu55kljg9ks2vjsw6fsgd7uj0a8qrvg0w3

https://damus.io/note1p8w7exj49upspfylukcv88v7en685fzrtsgxsnl7fz55tz4tps3qp09hnu

@ericholguin

**Comment by alltheseas** [comment]
@ericholguin can consistently recreate.

I recreated a few days back, and now I cannot recreate the same behavior.

**Comment by alltheseas** [comment]
https://damus.io/note14ypcs3mqjtd4l7tmwj4huzh7k2q4p6aymzyelyz9ukf5t5h35r8q3mgs5e

**Comment by githubbbie** [comment]
Cannot remove these top two relays... In latest Damus 1.6 (18)

![2023-09-22_12-21-cannot-remove-relay](https://github.com/damus-io/damus/assets/58287607/39355ae6-7f9a-41d9-940c-964bf03a0eec)

**Comment by githubbbie** [comment]
Trying the swipe left and click the red REMOVE icon.

**Comment by alltheseas** [comment]
@githubbbie have you used another client with your private key?

**Comment by jb55** [comment]
On Thu, Sep 21, 2023 at 09:23:33PM -0700, githubbbie wrote:
>Trying the swipe left and click the red REMOVE icon.

I have never been able to reproduce this. Has any dev run into this
issue? I can't fix it if I can't reproduce it.

**Comment by alltheseas** [comment]
@jb55 advised he is tackling this issue next. 

Thanks @fishcakeday 🙏

**Comment by alltheseas** [comment]
@danieldaquino picking up this issue from @jb55

**Comment by danieldaquino** [comment]
Thank you @fishcakeday for root causing the problem!

I was able to create a stable repro on my end to test changes against (based on @fishcakeday's information):

### Issue repro (using Damus alone)

**Device:** iPhone 14 Pro simulator
**iOS:** 17.0
**Damus:** Local build from `476f52562` with the following local change:
``` diff
diff --git a/damus/Views/AddRelayView.swift b/damus/Views/AddRelayView.swift
index 046cf7aa..427e0d2f 100644
--- a/damus/Views/AddRelayView.swift
+++ b/damus/Views/AddRelayView.swift
@@ -82,9 +82,11 @@ struct AddRelayView: View {
                     new_relay = "wss://" + new_relay
                 }
 
+                /*
                 if new_relay.hasSuffix("/") {
                     new_relay.removeLast();
                 }
+                */
 
                 guard let url = RelayURL(new_relay),
                       let ev = state.contacts.event,
```

**Steps:**
1. Remove all relays
2. Add `wss://relay.damus.io` relay **(without trailing slash)**. Shows up on the relay list.
3. Remove the Damus relay. Relay is removed successfully.
4. Add `wss://relay.damus.io/` relay **(with trailing slash)**. Shows up on the relay list after I go to the home view and back to the relay view
5. Remove the Damus relay. **Cannot remove relay, remove/disconnect actions are ignored.**

**Reproducibility:** 2 out of 2

**Comment by danieldaquino** [comment]
Working on a fix now

**Comment by danieldaquino** [comment]
I am having issues with the issue reproduction. My reproduction method seems to cause a desync between what is actually set as the relay list on nostr vs. what shows up on the UI. Furthermore, I am trying to repro the issue by using other Nostr clients to set the relay list, but I am getting inconsistencies between the relay list in Coracle+Snort vs. Damus.

**Comment by jb55** [comment]
On Fri, Sep 29, 2023 at 01:34:51PM -0700, Fishcake wrote:
>UI strips slashes, AFAIK, hence the problem in a first place. I can’t speak for other clients. You can sprinkle prints to see the progression

we need to not strip /'s, see https://github.com/nostr-protocol/nips/pull/801

**Comment by danieldaquino** [comment]
I think my concern is that although I do have a repro with similar symptoms, I am not sure whether it's the same situation other people are seeing, or if my repro is adding new problems due to my local hack.

My local hack to repro this is causing further problems and inconsistencies. It seems that my local chance causes a desync between the relay list used by the app itself, and what gets written into the contact list Nostr event.

However, adding a relay with a trailing slash is not usually possible from the Damus UI, so I was trying to get a more realistic repro that avoids these other issues that I am causing from my local hack.

@fishcakeday, do you know how you ended up with a relay containing a trailing slash in the first place? (Did you add that relay using another client? An older version of Damus?)

@jb55, would you like me to not strip trailing slashes when the user adds a relay from Damus, and work from there (i.e. solve the desync as well)?

**Comment by danieldaquino** [comment]
_(To elaborate on the inconsistencies introduced by my "repro hack", the relay list is inconsistent depending on whether I just added the relay, or navigated out and into the view, or restarted the app. Sometimes it shows the trailing slash relay, sometimes it doesn't.)_

**Comment by danieldaquino** [comment]
Thank you @fishcakeday for the info!

> Mine came from the older version. The inconsistencies you see are (as far as I understand) are from different relay lists on different relays. If you track the "output log" in the debug console of the Xcode, you'll notice that when the update happens, the new list with all your follows and relays is queued for posting to relays, but doesn't mean it is posted.

Great point! I will try leaving at least one relay constant and wait for the event to get flushed out to avoid inconsistencies.

> I haven't looked too deeply into where and how Damus caches that info, but I can tell you that my proposed patch works just fine.

That makes sense, and I thank you for providing the patch. I really value and appreciate it 🙏

The reason I am trying to get a stable repro is so that I can keep working on top of your proposed patch, ensure that it would work with `myrelay.com/v1`, `myrelay.com/v2` like you mentioned.

_(Unless I misunderstood what is expected of me in this ticket. @fishcakeday and @alltheseas, please advise if that's the case!)_

> I see what you are doing with your hack is just affecting the View and not the actual code that performs the removal.

True. My hack is not meant to fix the issue, it's just a way I found to see the issue on my end (which I will need to be able to test any changes I make)

**Comment by danieldaquino** [comment]
I was able to create a more stable repro on my end based on @fishcakeday's information above.

### Issue repro (using Damus alone, more stable than my previous repro)

**Device:** iPhone 14 Pro simulator
**iOS:** 17.0
**Damus:** Local build from `476f52562` with the following local change:
``` diff
diff --git a/damus/Views/AddRelayView.swift b/damus/Views/AddRelayView.swift
index 046cf7aa..427e0d2f 100644
--- a/damus/Views/AddRelayView.swift
+++ b/damus/Views/AddRelayView.swift
@@ -82,9 +82,11 @@ struct AddRelayView: View {
                     new_relay = "wss://" + new_relay
                 }
 
+                /*
                 if new_relay.hasSuffix("/") {
                     new_relay.removeLast();
                 }
+                */
 
                 guard let url = RelayURL(new_relay),
                       let ev = state.contacts.event,
```

**Steps:**
1. Remove all relays.
2. Add the Damus relay.
2. Add `wss://relay.snort.social/` relay **(with trailing slash)**. Shows up on the relay list.
3. Watch logs and wait for the relay list event to be sent out
4. Restart Damus (to help ensure the repro is stable)
5. Try removing the Snort relay. **Cannot remove relay, remove/disconnect actions are ignored.**

**Reproducibility:** 1 out of 1

**Comment by danieldaquino** [comment]
Created a patch to address this issue, and ensuring that URLs that are different (e.g. `/v1` and `/v2`) do not get removed at the same time.

I basically switched the relevant code to use `RelayURL`, which has built in mechanisms for checking equality that handles these edge cases.

I tried to refactor various `String` usages representing relay urls to `RelayURL`, but the changeset became enormous and too risky, so I reduced my changes to only the applicable code.

All relevant information, code, and testing reports can be found at: https://groups.google.com/a/damus.io/g/patches/c/we56gM69yg8

@alltheseas, @jb55, please let me know if you have questions or suggestions. Thank you everyone!

**Comment by alltheseas** [comment]
Duplicate https://github.com/damus-io/damus/issues/1052
