### ISSUE TITLE
Expand reaction emoji menu and allow user to set new emoji from note view

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1538]
Current experience:

Currently, the Damus reaction emoji selector is a small horizontal strip that is difficult to navigate, and the user often swipes outside the active area, causing the entire screen to move left or right between Notes, Notes & Replies, and the "Are you lost?" screen.

In addition, there is no way to set a new emoji reaction on a particular note without going into Settings > Reactions, which is an inefficient method.

Upgraded experience:

Observing how Amethyst handles this process by providing editable reaction emojis from within the note (though the UI is not as clean), Damus should redesign the feature as follows:

- Expand the size of the emoji palette to allow icons to appear in multiple rows
- Allow vertical scrolling, as opposed to horizontal scrolling to prevent accidental left-right swipes
- Add a persistent + icon to the emoji palette that allows a user to add a new custom emoji reaction from this view
- A delete option is not necessary from this screen, that can remain in the Settings

I have not created a design for this, but if requested, I could put something together.

Reference screenshots:
![image](https://github.com/damus-io/damus/assets/3638467/7f654a1f-744d-4045-a9b9-c0600d76cc3f)
![image](https://github.com/damus-io/damus/assets/3638467/6ba467cf-06d7-44b1-be5e-06d12a2a2b02)
![image](https://github.com/damus-io/damus/assets/3638467/9e71aeda-bab5-48c2-803d-7925198afdc5)

**Comment by alltheseas** [comment]
Amethyst has more functionality, and the emoji menu design is a sight for sore eyes.

I do like your suggestion of setting a custom emoji without going to settings.

How might we re-design the emoji experience @robagreda 

cc @suhailsaqan

**Comment by robagreda** [comment]
https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=3197%3A26783&mode=design&t=l0oCc4TAgLaHvim4-1


there you go! @alltheseas @suhailsaqan

**Comment by dmnyc** [comment]
@robagreda I have requested Figma edit access. Thank you.

**Comment by dmnyc** [comment]
Thanks, I did that. Will use it for now but I’d be happy to leave comments
in the original even if I don’t have edit access.

**Comment by robagreda** [comment]
@dmnyc I think you can leave comments right now without edit access, for the other thing @alltheseas is right, you should be able to duplicate it and explore variants :)

**Comment by robagreda** [comment]
Feel free to leave comments everywhere you want, that help us to improve the damus experience. thanks for your contributions.

**Comment by dmnyc** [comment]
Here's a suggestion for how the UI could be adjusted to prevent the horizontal scrolling issue. 

1. Display icons in rows with a maximum of 6 emojis per row. 

2. Add new rows as needed and limit to 3 rows before enabling vertical scroll to deal with overflow.

3. Always display the (+) icon as the last in the series. 

https://www.figma.com/file/JuqhyQpJaZdyPLEXJJQa1k/Damus-iOS-(%40dmnyc)?type=design&node-id=3402-27757&mode=design&t=tOrDYClwyQg81Lj0-4

**Comment by dmnyc** [comment]
Just curious to see if this is currently being worked on. The emoji selection is fairly cumbersome and it's easy to accidentally choose the wrong one or slide the screen out of view when scrolling.

**Comment by alltheseas** [comment]
> Just curious to see if this is currently being worked on. The emoji selection is fairly cumbersome and it's easy to accidentally choose the wrong one or slide the screen out of view when scrolling. 

We have 1.5 FTE devs and 500 things to work on. Haven't forgotten about this. 

Choosing to work on 5 things means not working on 495 other things.

You can help by:
1) submitting a patch/PR
2) posting a bounty 

🙏

**Comment by dmnyc** [comment]
I will post a 100K sat bounty for this.

**Comment by alltheseas** [comment]
@suhailsaqan

**Comment by jb55** [comment]
On Sun, Oct 29, 2023 at 07:49:09AM -0700, alltheseas wrote:
>> Just curious to see if this is currently being worked on. The emoji
>> selection is fairly cumbersome and it's easy to accidentally choose
>> the wrong one or slide the screen out of view when scrolling.

I'd rather this view be removed and we simply open an emoji keyboard for
custom reactions. I find the popup awkward.

Then we can even remove the reaction settings options. The emoji
keyboard already knows all of the most used emojis. Having to set
default emojis is cumbersome.

**Comment by dmnyc** [comment]
This would be even better! May still make sense to allow the user to set a
default but on long press the keyboard can open.

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/2176

**Comment by alltheseas** [comment]
#2204 emoji picker pending 1.8 update by @tyiu
