### ISSUE TITLE
Adding relays retains last relay in field

### ISSUE THREAD

**Issue by johndavies24** [damus-io/damus#154]
If you try to add multiple relays sequentially, the last relay added fills the field for adding a new one. Minor issue but not ideal. Also, as a normie it's confusing that the dot next to the relay switches between yellow and red yet somehow red is good. Seems like green should indicate a good relay.

Love the work, sorry I can't code and I can't describe how I break things!

**Comment by johndavies24** [comment]
Well after adding new relays now one is green lol. Red is extra confusing now because it was working before with all red relays. Whatevs, do with this issue as you please

**Comment by joelklabo** [comment]
This one should be closed now BTW.
