### ISSUE TITLE
iOS 17: fix freeze (symptom: return navigation from profile)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1552]
iOS 17 

Back arrow vs. swipe back

https://damus.io/note162rt4fctxepnj9cdtr9a82k7jtw3e33hj742ejly3q84tkwsfars4k9glr

Replicated by @TheSameCat2 https://damus.io/note12myx0lr3kj8sqeclg9ljklhzxk09xkcujc3v83726x06lddt683ql4levs

**Comment by alltheseas** [comment]
@jb55 @danieldaquino is it possible to replace the swipe code with the back arrow code when returning from profile?

**Comment by jb55** [comment]
On Fri, Sep 22, 2023 at 07:28:48AM -0700, alltheseas wrote:
>@jb55 @danieldaquino is it possible to replace the swipe code with the back arrow code when returning from profile?

I don't think this is the problem or the solution
