### ISSUE TITLE
Most recent reaction emoji not shown or selectable

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1557]
Version: 1.6 (18) 4377cf2

When a new reaction emoji is set, it doesn't appear at the end of the reaction emoji selector. There is a blank space that is not selectable. In order to use the desired new emoji, (🎃) an additional one would need to be added afterward. 
![image](https://github.com/damus-io/damus/assets/3638467/71c573b7-418c-4476-a8da-4657d7859744)
![image](https://github.com/damus-io/damus/assets/3638467/ea9ea109-cc39-49c8-9a6f-cebabecdfcff)
![image](https://github.com/damus-io/damus/assets/3638467/980df128-c98f-4323-a2ee-70a6f20c48e4)

**Comment by alltheseas** [comment]
@suhailsaqan

**Comment by jb55** [comment]
No longer an issue via

- #2204
