### ISSUE TITLE
Unable to reposition cursor in note where user tag appears

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1558]
Version: 1.6 (18) 4377cf2

As described in the title, I tagged a user and then could not reposition the cursor. It forced it to the end of the tag/note body. 

Screen capture:
https://video.nostr.build/11a1e2993967b8f2451ebf8e872da51e6b4a732cb462d2aece0752b828cdc7bd.mov

**Comment by danieldaquino** [comment]
Thank you for reporting, @dmnyc!

On top of this, I would like to mention this other report _(which seems to be the same issue, or very similar)_ https://damus.io/note18c7v05xkural7lfprh63s5kxgpcpn88ulmw8rjrdchv6tyze2f4sfhw0dp

**Comment by alltheseas** [comment]
@danieldaquino please also see https://github.com/damus-io/damus/issues/1521 - this may be an overlap, and/or duplicate.

**Comment by alltheseas** [comment]
Tangential to tagging user with emoji in name https://github.com/damus-io/damus/issues/1525

**Comment by alltheseas** [comment]
Behavior I observed 

When I compose a reply note
1) add one line of text, 
2) press enter,
3) add a second line of text,
4) place cursor at end of first line, and
5) press enter

the cursor appears after second line (not between first and second line text, as I would expect)

**Comment by alltheseas** [comment]
Also see tangential tagging bug https://github.com/damus-io/damus/issues/1544

**Comment by jb55** [comment]
On Mon, Sep 25, 2023 at 09:56:29AM -0700, Daniel D’Aquino wrote:
>Thank you for reporting, @dmnyc!
>
>On top of this, I would like to mention this other report _(which seems to be the same issue, or very similar)_ https://damus.io/note18c7v05xkural7lfprh63s5kxgpcpn88ulmw8rjrdchv6tyze2f4sfhw0dp

Is this a new regression? I think this started happening recently? Maybe
related to the recent post textedit view changes?

**Comment by danieldaquino** [comment]
> Is this a new regression? I think this started happening recently? Maybe related to the recent post textedit view changes?

@jb55, probably. I was playing with this _(and some of the refactoring we wanted to do on this text editor)_ earlier today, and I came up with something that seems to resolve this.

Not only it might fix this, but it also looks simpler, cleaner, and better. 

I should do more testing to make sure that it doesn't break other stuff though, before sending it over.

**Comment by dmnyc** [comment]
This could be related, but I also noticed that the initial cursor position is different when creating a note vs. closing and reopening the draft note. See these screenshots.
![image](https://github.com/damus-io/damus/assets/3638467/174ddcb9-9940-4c81-873f-c2b8e6ccbdba)
![image](https://github.com/damus-io/damus/assets/3638467/33f9c37b-4c1e-4bf7-96b8-0a6f7d3de0aa)

**Comment by jb55** [comment]
On Fri, Sep 29, 2023 at 09:16:48PM -0700, Daniel D’Aquino wrote:
>> Is this a new regression? I think this started happening recently? Maybe related to the recent post textedit view changes?
>
>@jb55, probably. I was playing with this _(and some of the refactoring we wanted to do on this text editor)_ earlier today, and I came up with something that seems to resolve this.
>
>Not only it might fix this, but it also looks simpler, cleaner, and better.
>
>I should do more testing to make sure that it doesn't break other stuff though, before sending it over.

thanks!

**Comment by alltheseas** [comment]
@danieldaquino may investigate property based testing. Will thinks it sounds complex, and large project.

**Comment by danieldaquino** [comment]
> @danieldaquino may investigate property based testing. Will thinks it sounds complex, and large project.

@alltheseas, I do agree this might be a more complex test to implement. It was mostly a suggestion I had of a way we could more provide a more thorough test coverage to the text editor.

I think the property-based testing for the text editor could be split into a separate ticket, so that we have more flexibility of when to tackle that.

**Comment by alltheseas** [comment]
👍

https://github.com/damus-io/damus/issues/1571

**Comment by danieldaquino** [comment]
Sent my patch over with full details at https://groups.google.com/a/damus.io/g/patches/c/QGYVNH-t3QI.

That patch fixes the issue in the description and brings many other improvements.

However, this did not address the other issues linked here, unfortunately. I believe they are separate issues.

Please let me know if there are any other questions or concerns. Thank you!

**Comment by jb55** [comment]
On Thu, Oct 05, 2023 at 07:43:14AM -0700, William Casarin wrote:
>looks like build 20 is missing these commits:
>
>ui: Improve UX around clearing cache
>composer: Make text editor more robust

I'll push these out now in build 21
