### ISSUE TITLE
Display name and username are very close together (at mention is missing)

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1559]
Version: 1.6 (18) 4377cf2

In note views, there should be more space between the display name and username. 
![image](https://github.com/damus-io/damus/assets/3638467/4f4c4e2c-99c3-4c0e-bfe3-a7f90e578902)
![image](https://github.com/damus-io/damus/assets/3638467/21d66e47-1359-4ec4-9643-b7910d8290e4)

**Comment by jb55** [comment]
yeah this is wrong, it should be showing @ next to the username. not sure where I broke this. Will fix.

**Comment by alltheseas** [comment]
1) add at sign (vertical at may break vertical layout due to presence of statuses)
2) fix spacing

**Comment by dmnyc** [comment]
This issue is still present in version 1.6 (20).

**Comment by danieldaquino** [comment]
I also see the issue present on the latest testflight build.

However when I run a local build on the tip of master the issue does not seem to be present.

@jb55, do you think the TestFlight build might have accidentally built on an older commit without the fix?

**Comment by jb55** [comment]
On Wed, Oct 04, 2023 at 03:54:14PM -0700, Daniel D’Aquino wrote:
>I also see the issue present on the latest testflight build.
>
>However when I run a local build on the tip of master the issue does not seem to be present.
>
>@jb55, do you think the TestFlight build might have accidentally built on an older commit without the fix?

was there ever a fix for this?

**Comment by danieldaquino** [comment]
> was there ever a fix for this? 

No, there was not, it was my bad. I meant to post this comment on #1558 🤦‍♂️

I will move the comment there. Please disregard my last comment here

**Comment by danieldaquino** [comment]
Sent a patch for this issue, alongside a snapshot test to cover this and a bit of additional testing infrastructure to make this possible.

Patch was sent via an alternative method discussed with @jb55 (since it contains a new binary file). More details can be found here: https://groups.google.com/a/damus.io/g/patches/c/NmmrWm8sx1c
