### ISSUE TITLE
Add suggested hashtags in universe view

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1569]
## user story

As a Damus user looking to see more content, when I am in universe view I would like a way to see suggested hashtags, so that I can find new content to follow.

### acceptance criteria
1. universe view contains suggested hashtags

_comment_
@danieldaquino mentions universe view can be spammy.

Will: in relay view -> go to see content from relay X.

**Comment by alltheseas** [comment]
Future: local aggregation of stats -> most popular hashtags of time period X

**Comment by alltheseas** [comment]
Example hashtags: https://github.com/damus-io/damus/issues/987#issuecomment-1637156300

**Comment by alltheseas** [comment]
Future: show top posts from a certain hashtag

**Comment by alltheseas** [comment]
@robagreda how might we design this story ? 

cc @danieldaquino

**Comment by danieldaquino** [comment]
Looks beautiful. Thank you @robagreda for the reference design!

**Comment by robagreda** [comment]
Let's gooo! @danieldaquino if you have any questions please let me know, we can hop on a quick call.

**Comment by danieldaquino** [comment]
I am starting to work on this issue now

**Comment by danieldaquino** [comment]
I sent a patch for this!

All details, code, screenshot, and testing were sent via email and can be viewed here: https://groups.google.com/a/damus.io/g/patches/c/gnj_ff_5icc

Please let me know if there are any concerns or suggestions. Thank you!

**Comment by alltheseas** [comment]
Let's see it in action and get feedback 💪
