### ISSUE TITLE
typing @ at the end of a note causes a crash

### ISSUE THREAD

**Issue by olheadinternet** [damus-io/damus#157]
reported on nostr: note133yk9fjs66xny5wtl9xh764nfsx76zr6kwxzl2mddveu23espcnsjlls99

confirmed and no note is written to relays

**Comment by joelklabo** [comment]
I haven't been able to reproduce this one. Have you? Anything else specific about the note?

**Comment by olheadinternet** [comment]
https://github.com/damus-io/damus/pull/158#issue-1511746383
