### ISSUE TITLE
Xcode cloud (iCloud) CI

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1572]
This should make CI and TestFlight deploys easier in theory? I will look into this.

**Comment by jb55** [comment]
On Mon, Oct 02, 2023 at 12:06:58PM -0700, William Casarin wrote:
>This should make CI and TestFlight deploys easier in theory? I will look into this.

I looked into this. xcloud cloud option in xcode keeps prompting me to add a remote repo but its not working. not a promising start.

**Comment by alltheseas** [comment]
@jb55 commits icloud CI for sprint 8

**Comment by jb55** [comment]
On Mon, Nov 13, 2023 at 09:12:44AM -0800, alltheseas wrote:
>@jb55 commits icloud CI for sprint 8

This is done now!

**Comment by alltheseas** [comment]
> On Mon, Nov 13, 2023 at 09:12:44AM -0800, alltheseas wrote: @jb55 commits icloud CI for sprint 8
> This is done now!

💪 

Let me know if you want some variety and break from nostrdb, and I'll suggest a few more issues.
