### ISSUE TITLE
When in thread do not skip back to top post

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1580]
> when hitting the Back button in a thread, you go back to the last post you clicked on instead of all the way out to the original post. Love you guys.

https://damus.io/note16j8fy4wv37vngawmvvrfpxau89ul33ut28fe7dqxqdd80fe9y8ssr92nyj

**Comment by alltheseas** [comment]
@danieldaquino adding this one as high priority to the sprint. This one trails Fix Clear cache in terms of priority.

**Comment by danieldaquino** [comment]
Sounds good @alltheseas, I will start this one next

**Comment by danieldaquino** [comment]
### Repro

**Result:** ISSUE REPRODUCED

**Device:** iPhone 13 Mini
**iOS:** 17.0.3
**Damus:** `b1c7ef9bd9033c0da2ad2d27e2e34abbd4fdc160`
**Steps:**

1. Scroll down the home feed a bit
2. Click on one of the posts
3. Click on the home tab button at the bottom left.

**Desired behavior:** 
1. First click on home button should go to home view but not scroll to top
2. Clicking on home button should only scroll to top when user is already at the root home feed view

**Current behavior:** Clicking on home button scrolls to top on step 3 (shouldn't have)

**Comment by danieldaquino** [comment]
working on a fix

**Comment by danieldaquino** [comment]
## Patch

Created a fix for the issue. All info, code, and testing reports were sent via email, and can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/B5EaaYJJiTo

@jb55, please let me know if you have any suggestions or concerns. Thank you!
