### ISSUE TITLE
Broken link caused by closed parentheses character at the end of a URL

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1583]
In this comment by Yeghro, a URL for yakihonne.com was automatically appended inside a set of parentheses:

@note1jpgujv6v0p3kja477h52dcwx5wht493fql9ywmlczmlvew2pttmqcdfz97

When it was rendered in Damus, the closed parentheses was included in the hyperlink, causing the link out to fail.

https://yakihonne.com/article/naddr1qqsksar5wpen5te0wd6xzcmtv4ezumn9waej76t5v4khxtejxu6rwwf5qgswum4p82uluhz2dr40nvdrflspffntgqghc58w9fs57nx6jkdkuaqrqsqqqa28c5k9f3)

The closed parentheses should be excluded from the link so the URL can be followed.
![IMG_C40EC9D05262-1](https://github.com/damus-io/damus/assets/3638467/f455ff09-8be1-4af7-83ae-d1ee1aab64ac)

**Comment by alltheseas** [comment]
Duplicate https://github.com/damus-io/damus/issues/1548
