### ISSUE TITLE
giphy GIF does not auto render

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1590]
https://damus.io/note1rvaf8zvht3wm4l52yu3ecyl5qeadccazk94j6nppdtrfmvuzga4s8um8ap

_what happens_
URL is displayed, and the animation is not displayed 

![image](https://github.com/damus-io/damus/assets/64376233/dc943505-7c5e-44ce-b173-95c94a077cbb)

_what I expect to happen_
I expect Damus to render the linked animation in app without me taking any action

**Comment by alltheseas** [comment]
@fishcakeday does gif in note above render for you?

**Comment by danieldaquino** [comment]
Experimented a bit to see if I can find any patterns. So far:
- Posting a GIF on my own test account seems to show the gif
- Seeing the GIF from an account I follow seems to show the gif
- Seeing the post from universe search view where I do not follow the author seems to _not_ show the gif.

I need to do more testing to make sense of what's happening

**Comment by alltheseas** [comment]
Appears fixed on 1.9 Testflight
