### ISSUE TITLE
DMs have an extra line break at the end

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1599]
Low priority, but DMs haven't gotten an upgrade in a while. I would like to suggest removing the line break at the end of each note to save on screen space.
![image](https://github.com/damus-io/damus/assets/3638467/b8487256-9c30-46e7-a8b6-5c2a1569434c)

**Comment by alltheseas** [comment]
http://git.jb55.com/damus/commit/8a20e5845ef49c6c777b37f6b710abf0ca0deebc.html
