### ISSUE TITLE
Pull to Refresh Global Feed on macOS not working

### ISSUE THREAD

**Issue by leesalminen** [damus-io/damus#160]
macOS 12.6.1 (21G217)
Damus version 0.1.8 (4) from TestFlight

1.) Open damus
2.) navigate to Global feed
3.) Pull down on feed
4.) Nothing Happens

Expected behavior: refresh data when pulling down on feed

Note: is working OK for me on iOS.

**Comment by dmnyc** [comment]
Why is there not a PTR function in the main timeline also?

**Comment by jb55** [comment]
On Wed, May 31, 2023 at 02:59:00PM -0700, Maybe: Daniel ?️ wrote:
>Why is there not a PTR function in the main timeline also?

Universe feed is not realtime.

**Comment by alltheseas** [comment]
> macOS 12.6.1 (21G217) Damus version 0.1.8 (4) from TestFlight
> 
> 1.) Open damus 2.) navigate to Global feed 3.) Pull down on feed 4.) Nothing Happens
> 
> Expected behavior: refresh data when pulling down on feed
> 
> Note: is working OK for me on iOS.

Works fine on MacOS 13 Damus 1.7
