### ISSUE TITLE
Fix profile stutter on refresh

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1609]
> Small note in 1.6 on TestFlight.
When viewing someone’s profile and I pull down it doesn’t do that cool bounce/snap animation during refresh for me. it just jitters like crazy while pulling, not sure if it is just me though.

https://damus.io/note1tsjcr6lns7jnun0m909mlknjs7t6jl4xtj3rds943hvnjfvrv0nqk9njls

17.0.3 on iPhone 14 pro

**Comment by jb55** [comment]
haven't seen this in awhile
