### ISSUE TITLE
Uppercase E tag

### ISSUE THREAD

**Issue by arthurfranca** [damus-io/damus#1610]
@jb55 I'm trying to get your opinion on issue [#812](https://github.com/nostr-protocol/nips/issues/812) of NIP repo.

On a nutshell, you can see on the issue that many client authors agreed to add an `E` tag referencing the id of the event one is replying to (both on root replies and reply replies). This allows for some clients to opt-in for lazy loading replies using the following filter: `["REQ", "dkldsaj", { kinds: [1], #E: ["<root id>"], limit: 5 }]`. Then using the same filter with "until" field.

I'm asking you if you can add the `E` tag to Damus when creating reply events (everything else doesn't change, to keep backwards compatibility).

**Comment by jb55** [comment]
On Sun, Oct 15, 2023 at 10:47:00AM -0700, arthurfranca wrote:
>@jb55 I'm trying to get your opinion on issue [#812](https://github.com/nostr-protocol/nips/issues/812) of NIP repo.
>
>On a nutshell, you can see on the issue that many client authors agreed to add an `E` tag referencing the id of the event one is replying to (both on root replies and reply replies). This allows for some clients to opt-in for lazy loading replies using the following filter: `["REQ", "dkldsaj", { kinds: [1], #E: ["<root id>"], limit: 5 }]`. Then using the same filter with "until" field.
>
>I'm asking you if you can add the `E` tag to Damus when creating reply events (everything else doesn't change, to keep backwards compatibility).

I have never needed to lazy-load a thread, most threads are small enough that loading the entire thread works just fine. Is there a situation where you needed to do this? What client are you working on?

**Comment by jb55** [comment]
On Mon, Oct 16, 2023 at 07:16:28AM -0700, arthurfranca wrote:
>I want to save bandwidth by lazy loading replies using "infinite scroll" feature. Although currently most threads are small, sometimes the user won't scroll down much, so there is no need to load the entire thread at once. Without the `E` tag, I would have to filter out client-side many events that are not direct replies, which ideally would be filtered out relay-side.
>
>I'm building a kind-1 focused web client probably just for the brazilian market (fetch just PT language notes) where any saved bandwidth would be great. For example, I'm also trying to first count likes with NIP-45 COUNT message instead of fetching all like events and counting them client-side.

this seems like a premature optimization. do you load images? because
those would be 1000x more bandwidth intensive.

generally you should try not to implement features that requires
everyone else to change their clients.

**Comment by arthurfranca** [comment]
I'm loading images up to a size limit. 

Amethyst, Coracle, Gossip and Snort already agreed to add the `E` tag. NIP-10 markers weren't the best idea because they can't be used to filter events. Your client is the one with the larger user base so with your help we can add this small "fix" to NIP-10 while keeping backwards compatibility.

**Comment by jb55** [comment]
On Tue, Oct 17, 2023 at 06:11:32PM -0700, arthurfranca wrote:
>I'm loading images up to a size limit.
>
>Amethyst, Coracle, Gossip and Snort already agreed to add the `E` tag. NIP-10 markers weren't the best idea because they can't be used to filter events. Your client is the one with the larger user base so with your help we can add this small "fix" to NIP-10 while keeping backwards compatibility.

has this been spec'd?

**Comment by arthurfranca** [comment]
Not yet. Just waiting for your decision before opening a PR. But basically its just an `E` tag without marker referencing the event one is replying to, no matter if replying to a root or to another reply event. Other `e` tags stay the same as usual.

Discussion took place at [#812 issue](https://github.com/nostr-protocol/nips/issues/812) on the NIP repo.

**Comment by arthurfranca** [comment]
Opened a PR editing NIP-10 [here](https://github.com/nostr-protocol/nips/pull/830)
