### ISSUE TITLE
Note ellipsis hit box is tapped accidentally during scrolling

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1630]
_what happens_
When scrolling through feed I accidentally hit the ellipsis note hit box, and accidentally add a bookmark, or mute a conversation

_what causes this_
Hit box was increased, as previously it was too small and often did not register https://github.com/damus-io/damus/issues/1454

note1qt9gakzg88wazvk30heh9zuzgzweyguqc9v7paat0whdrrk4a9csz0xj6d

**Comment by jb55** [comment]
On Fri, Oct 20, 2023 at 01:48:25PM -0700, alltheseas wrote:
>_what happens_
>When scrolling through feed I accidentally hit the ellipsis note hit box, and accidentally add a bookmark, or mute a conversation
>
>_what causes this_
>Hit box was increased, as previously it was too small and often did not register
>
>note1qt9gakzg88wazvk30heh9zuzgzweyguqc9v7paat0whdrrk4a9csz0xj6d

just need to decrease it by about half of what it was increased to. let's try that.

**Comment by alltheseas** [comment]
Closing unless we hear further custome feedback - improved since hitbox reduction update.
