### ISSUE TITLE
Zap menu custom value capability not intuitive

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1632]
https://damus.io/note1zyek0c2rxlsxuz3xr4df7kdq7f9euqc5pzwxk4n3cqm2955vpn4smjjapj

![image](https://github.com/damus-io/damus/assets/64376233/51a87ef3-0136-4771-b9c0-86f4956af490)

![image](https://github.com/damus-io/damus/assets/64376233/a09429d6-e5af-45c9-a7ba-63b90411f0e4)

**Comment by alltheseas** [comment]
Tipkit https://developer.apple.com/videos/play/wwdc2023/10229?time=0

**Comment by ericholguin** [comment]
Keypad now opens by default when this menu is shown
