### ISSUE TITLE
Convert profile card zap button to one tap zap

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1634]
https://damus.io/note16m5xs93sd0e99wp3kpdk92cv8ajd3an5qr3tfxazlayx8zzekusq8k6s38

**Comment by danieldaquino** [comment]
@TheSameCat2 suggested perhaps we should still allow custom amounts on long press

**Comment by danieldaquino** [comment]
@jb55 reminded me that we should add a follow button to the profile action sheet too

**Comment by alltheseas** [comment]
> @TheSameCat2 suggested perhaps we should still allow custom amounts on long press

What do yall think of displaying the full LN address (if the profile has one) under the npub with a copy button

**Comment by alltheseas** [comment]
> @jb55 reminded me that we should add a follow button to the profile action sheet too

https://github.com/damus-io/damus/issues/1636
