### ISSUE TITLE
Cannot clear keyboard in status screen

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1646]
_what happens_
I cannot clear the keyboard in the status view. Bottom row of settings - status expiry - is out of sight. 

iPhone 12 mini 1.6 (24).

@ericholguin 

![image](https://github.com/damus-io/damus/assets/64376233/cdcaa4e3-f82d-455f-adce-27cdc553709d)

**Comment by benthecarman** [comment]
This can be closed now, however similar issues persist throughout the settings
