### ISSUE TITLE
Hide 'Suggested Hashtags'

### ISSUE THREAD

**Issue by crimsonleaf363** [damus-io/damus#1649]
### **Problem**

- 'Suggested Hashtags' takes up a significant amount of screen real estate in 'Universe'.

### **Proposed Solution(s)**

- Add a toggle button in Settings > Search/Universe. Users can hide the 'Suggested Hashtags' section when they aren't interested in seeing it. This could create more space for other features or an improved view of the notes in 'Universe'. 

- Create an dropdown menu, so users can control how much screen real estate is taken up by 'Suggested Hashtags'.

**Comment by alltheseas** [comment]
Did you try tapping twice on the universe icon?

**Comment by jb55** [comment]
On Tue, Oct 24, 2023 at 10:23:14AM -0700, alltheseas wrote:
>Did you try tapping twice on the universe icon?

that does something?

**Comment by jb55** [comment]
On Tue, Oct 24, 2023 at 06:32:31PM -0700, William Casarin wrote:
>On Tue, Oct 24, 2023 at 10:23:14AM -0700, alltheseas wrote:
>>Did you try tapping twice on the universe icon?
>
>that does something?

oh neat it scrolls down to posts. didn't notice that.

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/assets/64376233/6eb041ff-a349-4b6f-ae60-c3876727421c

**Comment by crimsonleaf363** [comment]
> Did you try tapping twice on the universe icon?

I didn't before opening this issue. How did you find this feature?

**Comment by alltheseas** [comment]
fyi @jb55 this is a bonus point add to current sprint - see https://github.com/damus-io/damus/pull/1789

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/9a93610a-4397-4540-8ed5-549310a38ee7)

Fixed on 1.7
