### ISSUE TITLE
Review translation services onboarding 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1660]
Problem A: Many Japanese users only join Japanese relays, because they don't feel comfortable or don't have knowledge of other languages (e.g. English etc).

Problem B: Many Japanese users are not aware that there are multiple built-in language translation options in Damus.

How might we better onboard Japanese (and other) users to be aware of, and try out language translation services on Damus?

How might we point to no-account/no-KYC paid translation services?

**Comment by jb55** [comment]
purple translate should solve this ?

**Comment by alltheseas** [comment]
Yes, and Vanessa should post about this in Japanese in Japanese time zones once purple is launched on AppStore
