### ISSUE TITLE
Image carousel is broken (and later self fixes)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1693]
_what happens_

Both @tyiu and I experienced a broken image carousel when opening a note with multiple images. When opening same note subsequently the carousel works.

Need recreation.

**Comment by alltheseas** [comment]
Appears broken https://damus.io/note13v5xzyf5gzsq67k8g26a89tu7u2knvg2lfakvtfh8psckndd7arq6f4mrf


https://damus.io/note1lzm8626nd957yestwudv50kzquvraxl9md80y4ncxtakyjerreyqdwww8u

**Comment by alltheseas** [comment]
@danieldaquino @jb55 if y'all also can't scroll the carousel, I would bump this up to a higher priority to whatever you are working on as may affect many other Damus users.

**Comment by alltheseas** [comment]
Carousel works for signal &rage

**Comment by kernelkind** [comment]
Is this issue still relevant? The carousel works fine for me

**Comment by alltheseas** [comment]
Tested above links, and no issues observed currently

**Comment by alltheseas** [comment]
The "needs recreation" labels mean that if we don't know how to reproduce, we have less confidence in closing an issue. 

I can close and re-open if needed.
