### ISSUE TITLE
Add 🇹🇭 Thai Relays to Relay Bootstrap List if Preferred Language set to 🇹🇭

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1698]
### 🇹🇭 Relay List
wss://relay.siamstr.com
wss://relay.zerosatoshi.xyz
wss://th2.nostr.earnkrub.xyz
wss://teemie1-relay.duckdns.org

https://damus.io/note1gx49ruq0p7z8pvfaee07nneymuq4pcjeljwzk5xkaaltsg6z6dms3ppc8l

## Builds on
https://github.com/damus-io/damus/issues/1447

**Comment by alltheseas** [comment]
@jb55 @danieldaquino 

Bonus Thai onboarding request:

Auto-follow the #siamstr hashtag for folks with Thai set as preferred language.

**Comment by danieldaquino** [comment]
Sent patch here! https://groups.google.com/a/damus.io/g/patches/c/Dyw6RCp-Q3s

**Note:** I have just blindly copied and pasted the relay list given. I did not do any testing on the quality of relays themselves or connectivity (especially given that some of them might be geo-restricted).
