### ISSUE TITLE
Too heavy REQ for kind 0

### ISSUE THREAD

**Issue by mattn** [damus-io/damus#1699]
I don't have iOS and I don't use Damus but it seems that Damus send kind-0 REQ include all follow's pubkeys. I suggest that Damus separate to some REQs.

https://gist.github.com/mattn/c0a07f726fd240e977a962ad8efdf0c4

**Comment by jb55** [comment]
On Sun, Nov 12, 2023 at 07:03:59AM -0800, mattn wrote:
>I don't have iOS and I don't use Damus but it seems that Damus send
>kind-0 REQ include all follow's pubkeys. I suggest that Damus separate
>to some REQs.

This should be fixed on latest testflight. Once damus recieves a profile it
will save a "last fetched" time. Then it will try to fetch less and less
profiles over time based on a profile cache timeout.
