### ISSUE TITLE
Push notifications: Unfurl profile names in push notifications

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1703]
When push notifications are sent to the client, the raw nostr event is sent along with it.

However, for privacy and logistical purposes, no information is sent about the profiles associated with the pubkeys in the event _(The notification relay might not even have that information)_

It is the client's responsibility to unfurl that info.

**Acceptance criteria:**
- [ ] During client-side interception and formatting of push notifications (See `NotificationService.swift`), replace pubkeys with actual profile display names.

**Notes:**
- The notification extension that performs this work is almost completely separated from the rest of the app.
- The extension only has up to about 30 seconds to return the modified push notification content ([source](https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications))
- The notification extension process is limited to about 24MB of memory ([source](https://stackoverflow.com/questions/50764003/what-memory-limit-for-apple-notifications-service-extension))
- The way we can share data between the main app and the extension is via an app group.
- Please read comments #67 for more context in the notes above, and potential approaches to this.

**Comment by danieldaquino** [comment]
@jb55 I have a working patch for this, but if I try to unify all of `HomeModel.swift` with the extension I might be able to close a lot of other push notification tickets at once. If I don't, I risk implementing a lot of duplicated logic for other tickets.

I will save a copy of my current patch just in case things get hairy, but I will take a stab at refactoring all of `HomeModel.swift` to work with push notifications instead of doing these tickets one by one. (It might be faster in total)

**Comment by jb55** [comment]
On Fri, Nov 24, 2023 at 03:18:29PM -0800, Daniel D’Aquino wrote:
>@jb55 I have a working patch for this, but if I try to unify all of
>`HomeModel.swift` with the extension I might be able to close a lot of
>other push notification tickets at once. If I don't, I risk
>implementing a lot of duplicated logic for other tickets.

>I will save a copy of my current patch just in case things get hairy,
>but I will take a stab at refactoring all of `HomeModel.swift` to work
>with push notifications instead of doing these tickets one by one. (It
>might be faster in total)

not quite sure what you mean but I'll wait and see!

**Comment by danieldaquino** [comment]
@jb55, great news, my plan seems to have worked!

I implemented the above, and preliminary testing shows that it is either completely or very close to done.

Now, the testing I have done is not yet commensurate with the size of the changeset, so I will do more thorough testing and refine/fix things as appropriate on Monday before sending the patch over. But once I do that, we will be able to close all of these at once:
- https://github.com/damus-io/damus/issues/1702
- https://github.com/damus-io/damus/issues/1703
- https://github.com/damus-io/damus/issues/1705
- https://github.com/damus-io/damus/issues/1764


**I published my drafts over here for now (if you want to take a peek):**
https://github.com/damus-io/damus/compare/master...danieldaquino:damus:1703-push_notification_reuse_local_notification_logic-v1

**Comment by danieldaquino** [comment]
@jb55, sent the patches! All info was sent via email (Can be viewed here as well: https://groups.google.com/a/damus.io/g/patches/c/ZjwL8Dq256I)

**Comment by danieldaquino** [comment]
Sent the accompanying `strfry-push-notify` change via email (https://groups.google.com/a/damus.io/g/patches/c/nFmRRBMWmGw)
