### ISSUE TITLE
Push notifications: Suppress push notifications from muted users or threads

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1705]
**Acceptance criteria:** Intercept and suppress push notifications from profiles or threads which have been muted by the user.

We already do this for local notifications, but we need to bring in the same (or similar) logic to push notifications.

To accomplish this, the same notes and complications as the ones listed in https://github.com/damus-io/damus/issues/1703 apply.

**Comment by jb55** [comment]
On Mon, Nov 13, 2023 at 10:33:45AM -0800, Daniel D’Aquino wrote:
>**Acceptance criteria:** Intercept and suppress push notifications from
>profiles or threads which have been muted by the user.
>
>We already do this for local notifications, but we need to bring in the
>same (or similar) logic to push notifications.
>
>To accomplish this, the same notes and complications as the ones listed
>in https://github.com/damus-io/damus/issues/1703 apply.

Seems like we'll need nostrdb for this since it will require querying
our local mutelist event. Only downside at the moment is that we don't
have a kind/pubkey index yet but that won't be too difficult to add.

We could also just store our mute list as an array of pubkeys in
UserSettings as a quick workaround, since muted threads is already
stored this way (array of ids).

Did we determine if settings is accessible without a shared app
container?

**Comment by danieldaquino** [comment]
> Did we determine if settings is accessible without a shared app
container?

From what I read it seems like we need to use a shared defaults object for the app group (e.g. `let sharedDefaults = UserDefaults(suiteName: "group.com.damus")`). But I will test it to confirm

But passing info through this shared defaults object should be straightforward. 

I will test to check the info above

**Comment by danieldaquino** [comment]
@jb55, I tested the info on previous comment. It seems to be the case. Here is what I saw on the debugger:

### From the Damus app target

Reading `UserDefaults.standard`:
```
(lldb) print UserDefaults.standard.string(forKey: "pubkey")
(String?) some {
  _guts = {
    _object = (_countAndFlagsBits = 13835058055282163776, _object = "6ad8931a841cec04cbca74e81623953558546e96a0b27841ab44aa15ace04949")
  }
}
```

Setting value in the shared `UserDefaults`
```
(lldb) print UserDefaults(suiteName: "group.com.damus")?.set(UserDefaults.standard.string(forKey: "pubkey") ?? "", forKey: "pubkey")
(Void?) some
```

### From the notification service extension target

Reading `UserDefaults.standard`:
```
(lldb) print UserDefaults.standard.string(forKey: "pubkey")
(String?) nil
```

Reading the shared `UserDefaults`:
```
(lldb) print UserDefaults(suiteName: "group.com.damus")?.string( forKey: "pubkey")
(String?) "6ad8931a841cec04cbca74e81623953558546e96a0b27841ab44aa15ace04949"
```


In conclusion, we can use `UserDefaults` to share data, but only this shared one (the `standard` one we normally use is not available from the extension context)
