### ISSUE TITLE
Push notifications: Update privacy policy

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1706]
To make push notifications possible, we have to collect the user's device token and associate it with their pubkey identity.

We will likely need to update the privacy policy to mention this.

**Comment by jb55** [comment]
On Mon, Nov 13, 2023 at 10:36:47AM -0800, Daniel D’Aquino wrote:
>To make push notifications possible, we have to collect the user's device token and associate it with their pubkey identity.
>
>We will likely need to update the privacy policy to mention this.

good point!

**Comment by jb55** [comment]
device token doesn't have any association with an apple id, its a random string. all we really know is that a certain user is using damus, which we already know via the auto-follow on the damus account. I'm closing this until someone makes a convincing argument otherwise.
