### ISSUE TITLE
Tags with dashes in them aren't correctly detected

### ISSUE THREAD

**Issue by boreq** [damus-io/damus#1712]
I sometimes use dashes in tags to make them more readable. I noticed that Damus incorrectly parses my tags e.g. `#nos-dev-diary` using only the part before the first dash so that the tag ends up being cut off to e.g. `#nos`. I can't find a NIP that specifically defines what the expected behaviour here is (e.g. what characters are allowed in tags) unfortunately.

Example, I specifically posted the event linked below from Damus to illustrate the problem:

<img width="977" alt="Screenshot 2023-11-14 at 09 56 29" src="https://github.com/damus-io/damus/assets/1935975/e47877f9-e227-41ed-8a3e-143d8d8b4a3e">

```
{
  "id": "621d7491cc5bf846f3684e4a0dbd2209baf495d9dcee0e6cb948794d7d761ec1",
  "pubkey": "e731ca427c18059d66636ddfaeeeb15012bc2db3cdd27b9e4cade5057a6e82ed",
  "created_at": 1699953274,
  "kind": 1,
  "tags": [
    [
      "t",
      "nos"
    ],
    [
      "t",
      "nostrica"
    ]
  ],
  "content": "This is a #nos-dev-diary from a mostly-backend-developer.\n\nNot much progress as I got sick after #nostrica but I landed a couple of improvements to https://tweeter.nos.social/. It is cool to see people use it!\n\n- tweets now contain https://njump.com/  links to the associated events\n- it will now avoid cutting links in half when shortening notes\n- it correctly detects nostr nevent/npub/note links and translates them to https://njump.com/ links\n- fixed a bunch of backend bugs so it should be more reliable\n\nIf you have bug reports, feedback or any other suggestions post them here or create an issue. The service is open source of course. I try to translate all feedback to issues so that it doesn’t get lost.\n\nhttps://github.com/planetary-social/nos-crossposting-service/issues\n\nPlans for the near future:\n- investigate why purple pages sometimes doesn’t return events in response to queries, this makes the service struggle after restarts (this is how the service grabs your relays)\n- resume work on a crawler-like service that will feed events into our other services e.g. the service that generates push notifications, the service that tries to analyse content reports using AI etc, we could also spin up an alternative to purple pages on top of that service",
  "sig": "74bcb85eafc59896648681f0367614269b09af8cfd01b46c48de88872f8e7bcfa6676f0ccd02590f9f736528c7bd972a0bc609aff71469aa59c6dd6c5cf8ea58"
}
```

https://njump.me/nevent1qqsxy8t5j8x9h7zx7d5yujsdh53qnwh5jhvaemswdju5s72d04mpasglps5w9

**Comment by jb55** [comment]
On Tue, Nov 14, 2023 at 01:20:02AM -0800, Filip Borkiewicz wrote:
>I sometimes use dashes in tags to make them more readable. I noticed
>that Damus incorrectly parses my tags e.g. `#nos-dev-diary` using only
>the part before the first dash so that the tag ends up being cut off to
>e.g. `#nos`. I can't find a NIP that specifically defines what the
>expected behaviour here is (e.g. what characters are allowed in tags)
>unfortunately.

It breaks at punctuation, I believe `-` is considered punctuation which makes sense to me.

**Comment by boreq** [comment]
All right, I will think about documenting this in some NIPS.

**Comment by jb55** [comment]
On Tue, Nov 21, 2023 at 12:04:47PM -0800, Filip Borkiewicz wrote:
>All right, I will think about documenting this in some NIPS.

should definitely clarify this in a hashtag NIP
