### ISSUE TITLE
Prune nostrdb

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1714]
We need a way to prune nostrdb so that users don't suffer unbounded storage growth.

Tasks:

- [x] https://github.com/damus-io/damus/issues/1713
- [ ] https://github.com/damus-io/damus/issues/1715

**Comment by alltheseas** [comment]
Related to cache growth issue https://github.com/damus-io/damus/issues/1689

**Comment by alltheseas** [comment]
https://damus.io/note1sgv8wsf6t8fpr5e0hm6zvl288jqxn0kss9l9aezx8mp3hutmy9fs4s7qk2

**Comment by alltheseas** [comment]
> https://damus.io/note1sgv8wsf6t8fpr5e0hm6zvl288jqxn0kss9l9aezx8mp3hutmy9fs4s7qk2

@jb55 reminder to prune

**Comment by jb55** [comment]
closing in favor of #1715
