### ISSUE TITLE
Move to kind 10000 for mute lists

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1718]
Seems like there is growing consensus that we should be using this because there is a lot of fragmentation with mute lists:

https://github.com/nostr-protocol/nips/pull/880

**Comment by fishcharlie** [comment]
I'm gonna take this one since it feels like a prerequisite for #856. As part of [NIP-51](https://github.com/nostr-protocol/nips/blob/master/51.md) there is an option for "word" which will greatly help with #856. Otherwise it'll lead to a lot of fragmentation within Damus.

cc/ @alltheseas & @jb55

**Comment by jb55** [comment]
On Sun, Jan 07, 2024 at 01:35:47PM -0800, Charlie Fish wrote:
>I'm gonna take this one since it feels like a prerequisite for #856. As part of [NIP-51](https://github.com/nostr-protocol/nips/blob/master/51.md) there is an option for "word" which will greatly help with #856. Otherwise it'll lead to a lot of fragmentation within Damus.

makes sense! thanks!

**Comment by fishcharlie** [comment]
https://groups.google.com/a/damus.io/g/patches/c/gy7WlaGYRKE
