### ISSUE TITLE
Heart reaction cut off on small screens

### ISSUE THREAD

**Issue by karnagebitcoin** [damus-io/damus#1728]
iphone 2020 SE 

The heart reaction is cut off slightly on the right, see screenshot:

![IMG_1222](https://github.com/damus-io/damus/assets/131526701/a4fce12a-a9cf-4522-b288-0e9c4308061a)

**Comment by alltheseas** [comment]
smol phone @ericholguin

**Comment by shawnyeager** [comment]
Same on iPhone 15 Pro Max. 

![image](https://github.com/damus-io/damus/assets/980297/1191c476-5abc-4c86-aad8-767349535179)
