### ISSUE TITLE
Onboarding flow repeats after closing and reopening app

### ISSUE THREAD

**Issue by johnshenio** [damus-io/damus#1732]
Iphone 12 pro
iOS 17.1.1

https://github.com/damus-io/damus/assets/60067978/501a66ce-eff4-4bc9-8543-b6c22f919744

**Comment by jb55** [comment]
I noticed sometimes settings take some time to "stick". For example, the
zap nostrscript sometimes doesn't work. I wonder why that is.

**Comment by alltheseas** [comment]
I wonder if this is related to the dev mode trigger onboarding setting

**Comment by alltheseas** [comment]
@johnshenio 

Can you confirm your setting?


![image](https://github.com/damus-io/damus/assets/64376233/0df733bc-69d7-4a2d-b49e-5dd9ad0c1797)

**Comment by alltheseas** [comment]
Maybe 'always show onboarding' setting should be off by default

cc @danieldaquino

**Comment by danieldaquino** [comment]
@alltheseas, that setting is already set to be "off" by default.

I wonder if this is related to _(or a consequence of)_ #1726

**Comment by johnshenio** [comment]
oh by bad, it was on. sorry

**Comment by alltheseas** [comment]
> oh by bad, it was on. sorry 

@johnshenio did you turn this on manually?

**Comment by alltheseas** [comment]
> @alltheseas, that setting is already set to be "off" by default.
> 
> 
> 
> I wonder if this is related to _(or a consequence of)_ #1726
> 
> 
> 
> 
> 
> 

You and Will know better than me. 

It was on when I updated to the latest version. I don't remember turning this on. I do have poor memory sometimes though.

**Comment by johnshenio** [comment]
most likely, and I probably didn't realize it

**Comment by alltheseas** [comment]
for consideration for next sprint @jb55 @danieldaquino 

update static follow suggest list to dynamic (so non-technical folk can update this without your help) https://github.com/damus-io/damus/issues/1395
to follow: update suggested follows https://github.com/damus-io/damus/issues/1429

**Comment by alltheseas** [comment]
@danieldaquino https://damus.io/note1cq6ehgugl2g37tnpq5gzjzh9j6xy7y5ra83pn4ax8erzegke7q0snm4ymv

**Comment by danieldaquino** [comment]
> @danieldaquino https://damus.io/note1cq6ehgugl2g37tnpq5gzjzh9j6xy7y5ra83pn4ax8erzegke7q0snm4ymv

@alltheseas, that's interesting. 

I suspect that what happened there was that she probably had the older App store version (which did not have the Onboarding view with "Who to follow"/"First post"), and when she upgraded to 1.6, the "onboarding" flag was still set to "unseen", causing those onboarding views to be shown.

I imagine she should only see that Onboarding view once right after upgrading. I will ask her if she had only seen it once or if she is seeing it multiple times to help us with this ticket.
