### ISSUE TITLE
Setup push notification relay

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1733]
Now that we have push notification support I need to set this up on our server

**Comment by jb55** [comment]
Everything is in place for this now, adding it to the sprint

**Comment by danieldaquino** [comment]
While working on this, I ended up needing to do a big detour as I realized our current implementation does not handle APNS server authentication properly.

After much research and debugging, I was able to get JWT token authentication working between our relay and the real Apple APNS server _(I previously relied on getting a JSON payload from a mock APNS server and pasting it to an APNS test tool)_, so I got the full communication pipeline from relay to on-device push notification working.

However, I still need to clean up some code as I needed to do some substantial changes.

**Comment by jb55** [comment]
On Wed, Jun 26, 2024 at 04:36:58PM GMT, Daniel D’Aquino wrote:
>While working on this, I ended up needing to do a big detour as I realized our current implementation does not handle APNS server authentication properly.
>
>After much research and debugging, I was able to get JWT token authentication working between our relay and the real Apple APNS server _(I previously relied on getting a JSON payload from a mock APNS server and pasting it to an APNS test tool)_, so I got the full communication pipeline from relay to on-device push notification working.
>
>However, I still need to clean up some code as I needed to do some substantial changes.

sounds good, thanks for the update!

**Comment by danieldaquino** [comment]
Sent the patch to get APNS authentication working! https://groups.google.com/a/damus.io/g/patches/c/w8qnQYiylsA

@jb55 please let me know if any improvements to the patch are needed! Thank you!

**Comment by danieldaquino** [comment]
@jb55 Sent a simple damus iOS app patch to point to the current device token server: https://groups.google.com/a/damus.io/g/patches/c/n99vO4d8ES8

I also setup other things required in the server to get this up and running.
