### ISSUE TITLE
Preview redesign (Add support for long form note cover image)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1742]
https://damus.io/note1d8svffscyg3gkkt6wuqkvnv3qylyzucesh7thku5xkshz7ccpszscwa47h

**Comment by alltheseas** [comment]
@ericholguin has PR

**Comment by alltheseas** [comment]
@robagreda how might we distinguish between:

URL previews ( go to browser app if you click), and Long-form note previews (that stay in app if you click)

**Comment by jb55** [comment]
Related ticket for the other request:

- https://github.com/damus-io/damus/issues/1563
