### ISSUE TITLE
Push notifications: Get NostrDB working under the extension target

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1744]
To be able to implement some of the features for push notifications, we need to be able to get some information from NostrDB

**Acceptance criteria:**
- We should be able to query NostrDB information from the `DamusNotificationService` extension target

**This is a technical requirement for:**
- #1703 
- #1705

**Comment by danieldaquino** [comment]
@jb55, w00t!

Got the notification extension to build with NostrDB, and got it to successfully print a profile name!
<img width="600" alt="Screenshot 2023-11-20 at 12 07 22" src="https://github.com/damus-io/damus/assets/24692108/20d9333f-bfed-490e-86d8-07a1d41575e6">

I will clean-up my changes and send a patch soon.

**Comment by jb55** [comment]
On Mon, Nov 20, 2023 at 12:11:35PM -0800, Daniel D’Aquino wrote:
>@jb55, w00t!
>
>Got the notification extension to build with NostrDB, and got it to successfully print a profile name!
><img width="600" alt="Screenshot 2023-11-20 at 12 07 22" src="https://github.com/damus-io/damus/assets/24692108/20d9333f-bfed-490e-86d8-07a1d41575e6">

let's gooo

**Comment by danieldaquino** [comment]
Finished cleaning up, formatting, and testing the changes.

I sent a patch with all code, notes, and test reports via email to patches@damus.io! The email can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/vETgsm3yLkY

Please let me know if there are any concerns or suggestions.

Thank you!
