### ISSUE TITLE
Push notifications: Add time-based controls to strfry-push-notify

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1746]
To make the stryfry-push-notify DB easier to manage and purge over a long period of time, we should be able to tell which entries are new and which ones are older.

**Acceptance criteria:**
- Add timestamps to database entries in `strfry-push-notify`
- Skip notifying any Nostr event older than 1 week _(or any reasonable timeframe)_

**Comment by jb55** [comment]
On Mon, Nov 20, 2023 at 11:16:20PM -0800, Daniel D’Aquino wrote:
>To make the stryfry-push-notify DB easier to manage and purge over a
>long period of time, we should be able to tell which entries are new
>and which ones are older.
>
>**Acceptance criteria:**
>- Add timestamps to database entries in `strfry-push-notify`

I noticed this and was going to suggest it. good call.

>- Skip notifying any Nostr event older than 1 week _(or any reasonable timeframe)_

makes sense

**Comment by danieldaquino** [comment]
Sent patch!

https://groups.google.com/a/damus.io/g/patches/c/IAwBWBgF3QQ
