### ISSUE TITLE
German language relays

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1750]
## relays

wss://nostr.einundzwanzig.space 
wss://nostr.cercatrova.me
wss://at.nostrworks.com
wss://ftp.halifax.rwth-aachen.de/nostr
wss://nostr.bitcoinplebs.de
wss://theforrest.nostr1.com

## follows
a list of 300+ follows of German profiles 
https://listr.lol/npub1d0enakaludyvruzdndcgl4glkcqyfpvp9tdtf8cawzkskekhcu2sq9xlas/30000/naddr1qq4xc6tnw3ez6en9vdjx2e3kvgknger9xvkngwp3v5kkzvphvgkn2d348psnwc3kv4jrqeqpp4mhxue69uhkummn9ekx7mqzyp4lx0kmhl353s0sfkdhpr74r7mqq3y9sy4d4dylr4c26zmx6lr32qcyqqq82vq7x059u

## communities (this feature is not supported by Damus)

https://satellite.earth/n/Germanstuff/npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq

related to
https://github.com/damus-io/damus/issues/1447 Japanese relay bootstrap

**Comment by danieldaquino** [comment]
Sent patch here! https://groups.google.com/a/damus.io/g/patches/c/Dyw6RCp-Q3s

**Note:** I have just blindly copied and pasted the relay list given. I did not do any testing on the quality of relays themselves or connectivity (especially given that some of them might be geo-restricted).
