### ISSUE TITLE
Add subscription/recurring btc/sats donation in Damus app 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1755]
## apple fiat subscription ticket 
https://github.com/damus-io/damus/issues/1422

## subscribe in app using btc/sats user story
As a satisfied Damus user who would like to support the Damus team in app, I would like a way to "subscribe" in the Damus app with sats, so that I can support the Damus team in app maintenance & development.

### acceptance criteria
1. On the Damus iOS app, I can find and click on a "subscribe" button 
3. I can see preset subscription amounts: $5, $10, $20, $30, $50, $100 in both USD, and sats (see satsperusd https://bitbo.io/)
4. I can set a custom subscription amount
5. I can optionally provide my npub, or choose to donate anonymously
6. For Damus internal records it should be clear that the donation originated from website subscriptions
7. Subscribers receive ⭐️

### Apple fee
How does Damus handle apple fee requirements for "in app purchases"?

### Future consideration/how might we
Subscribers could get access to Damus Purple / subscriber premium features https://github.com/damus-io/damus/issues/659

### related to

Damus purple #659 
Recurring donation on website #1754

**Comment by alltheseas** [comment]
Must in app Damus subscription take place via apple pay @jb55 ?

**Comment by jb55** [comment]
On Tue, Nov 21, 2023 at 10:30:08AM -0800, alltheseas wrote:
>Must in app Damus subscription take place via apple pay @jb55 ?

In-app must yes, but you can leave the app if you want non-applepay subscriptions

**Comment by alltheseas** [comment]
https://medium.com/@Sergey.Zhuravel/in-app-purchases-in-ios-part-3-testing-purchases-in-testflight-sandbox-and-locally-in-xcode-3dec999986e1 @danieldaquino

**Comment by danieldaquino** [comment]
> https://medium.com/@Sergey.Zhuravel/in-app-purchases-in-ios-part-3-testing-purchases-in-testflight-sandbox-and-locally-in-xcode-3dec999986e1

Thanks, this is very handy! Apple has docs on those, but it's spread in a bunch of different places. It's nice to have a single guide from start to finish.

**Comment by alltheseas** [comment]
Sats not possible in app in iOS due to Tim Apple. Migrating this to Android.  https://github.com/damus-io/android/issues/66
