### ISSUE TITLE
Convert profile from npub to nprofile

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1770]
https://github.com/nostr-protocol/nips/blob/master/27.md

**Comment by alltheseas** [comment]
Nprofile works

nprofile1qqsrhuxx8l9ex335q7he0f09aej04zpazpl0ne2cgukyawd24mayt8gpyfmhxue69uhkummnw3ez6an9wf5kv6t9vsh8wetvd3hhyer9wghxuet5fmsq8j

![image](https://github.com/damus-io/damus/assets/64376233/0fc9da98-5b3f-4a2b-b9fc-9cb0bda41388)

**Comment by jb55** [comment]
I think we still need to add this to search though

**Comment by alltheseas** [comment]
> I think we still need to add this to search though

yes, added here: https://github.com/damus-io/damus/issues/1841

**Comment by alltheseas** [comment]
Nprofile renders in DMs
