### ISSUE TITLE
Add UI confirmation post NWC paste string

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1775]
> when you enable camera access it does work, but since many users likely have the NWC string on their iPhone clipboard (ex: from Mutiny), they would use the "Paste" button rather than the camera.

> Pasting the string does work, but the app gives no indication that it was successful (and just remains on the camera screen). You have to hit the back button to see that it was pasted and then confirm the connection.

> After "paste", there should either be a success message and prompt to go to the confirmation screen, or (better still) it should automatically redirect to the confirmation.

From @boston-wine

**Comment by ericholguin** [comment]
This sounds like an issue with the old design. We don't have the paste option in the camera anymore.

**Comment by alltheseas** [comment]
What happens is I tap on the paste button?

1.9

![image](https://github.com/damus-io/damus/assets/64376233/ec5a0f29-f6a3-4465-8ec0-c56afcbf3c1d)

**Comment by ericholguin** [comment]
You're taken to this screen
![IMG_63D693CC17DE-1](https://github.com/damus-io/damus/assets/14004132/6131176a-ea38-4afa-af96-df37d703a491)

**Comment by alltheseas** [comment]
Ok. So there is no need for this UI confirmation?

**Comment by ericholguin** [comment]
No it already goes to the confirmation page I posted above or if it is not a nwc address it will alert that it is not.
