### ISSUE TITLE
Recognize cashu redeem code

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1788]
_what happens_
Very long cashu gibberish string is displayed

_what could happen_
Damus recognizes cashu redeem string, shows
-the amount
-a "redeem" button, 
-copy string button

_suggested initial approach_

1) Cashu: prefixed link are detected
2) an invoice-like "redeem" button appears instead of gibberish characters
3) if tap on redeem, cashu: opens default cashu wallet
4) there is a copy string button adjacent to redeem
5) list amount (sats)

https://damus.io/note17ek90arl9y6vmut6t48d7kfgp9rfdx0c0x9wflyq6v4shvg46ddsh0gud2

![image](https://github.com/damus-io/damus/assets/64376233/6f19cca2-9c26-4fa2-928c-aa98a7dd8b1a)

**Comment by KKA11010** [comment]
Also a "open in wallet" button. It provides the best possible UX.

Mobile cashu wallets support deep links "cashu:token" or cashu://token"

They claim the token and lets you spend it again without melting to your LN wallet.

**Comment by KKA11010** [comment]
> > Also a "open in wallet" button. It provides the best possible UX.
> > 
> > Mobile cashu wallets support deep links "cashu:token" or cashu://token"
> > 
> > They claim the token and lets you spend it again without melting to your LN wallet.
> 
> If there were a redeem button, is there any other place it would take you other than a wallet with the cashu: prefix?

The redeem button (in Amethyst at least) immediatly melts the token to your LN wallet where a deep link with a cashu: prefix lets you claim the ecash without melting.

**Comment by KKA11010** [comment]
Some thoughts on how the user can interact with an inline Ecash

1. Redeem via Lightning within the Nostr client.
2. Redeem into Ecash wallet without melting
3. Display QR so user can redeem by scanning

**Comment by alltheseas** [comment]
https://damus.io/note1aqy9x9fcnqrvfxpndlhd2msmkcp5e34jsmrt3wu3yk3p4zq6mkcszl87q8

**Comment by alltheseas** [comment]
> I think decrypt with nsec key and copy to cashu wallet. @dr. calle 👁️⚡👁️ posted NUT-11 https://github.com/cashubtc/nuts/blob/main/11.md which makes most sense for Nostr usage.

https://github.com/cashubtc/nuts/blob/main/11.md

**Comment by alltheseas** [comment]
Redeem directly flow and video walk through

https://damus.io/note1pu2z35csmyjg8fq9uuxdjumuh8ufeusrz0psgyxf0a074kpcyf7skty8x2

https://video.nostr.build/bad2b8a13ff2cf976f4af699b669355bf462ad1c04755be0bf3cf9798a1adc4a.mp4

**Comment by alltheseas** [comment]
@KKA11010 in the cashu link is there a source/server/mint name that can be displayed? Is it desirable to display this?
