### ISSUE TITLE
Support naddr format

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1806]
https://damus.io/note17wuzfta4phaj6uxcqwgjewmk7fle2t7gvreutuza44hdm2v440jsk0ed68

![image](https://github.com/damus-io/damus/assets/64376233/2724fb8b-367d-40c2-97f5-a1185cec539b)

**Comment by alltheseas** [comment]
Related nprofile https://github.com/damus-io/damus/issues/1770

**Comment by alltheseas** [comment]
This one remains open @kernelkind @jb55 @danieldaquino

**Comment by danieldaquino** [comment]
@alltheseas, should this take priority over Damus Purple work? If so, I can jump into this on Friday

**Comment by alltheseas** [comment]
> @alltheseas, should this take priority over Damus Purple work? If so, I can jump into this on Friday

If you are being held up by and waiting for Apple fiat pay permissions go for it!

If there remains Purple work this can be part of the next sequence of improvements 🙏

**Comment by jb55** [comment]
On Wed, Dec 27, 2023 at 04:41:35PM -0800, Daniel D’Aquino wrote:
>@alltheseas, should this take priority over Damus Purple work? If so, I can jump into this on Friday

nope. I personally thing naddr's are one of the worst things added to nostr. obviously we have to support it at this point, but it's not priority.
