### ISSUE TITLE
Tapping Zap button does nothing

### ISSUE THREAD

**Issue by fishcharlie** [damus-io/damus#1808]
When I try to tap the Zap button on a post, nothing happens. No error message, no information about how to complete the Zap, etc.

Hard to tell what is going wrong here since there is no error message or anything.

**Comment by jb55** [comment]
On Mon, Dec 11, 2023 at 05:45:22AM -0800, Charlie Fish wrote:
>When I try to tap the Zap button on a post, nothing happens. No error
>message, no information about how to complete the Zap, etc.
>
>Hard to tell what is going wrong here since there is no error message or anything.

Apple does not allow me to make this button clickable. Use a free
platform like android to zap posts.
