### ISSUE TITLE
Polish Damus Purple support

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1814]
## Acceptance criteria

- [X] ~~Show user that apple takes X%/Y$ of each in app apple pay donation~~ _(Not allowed by Apple's AppStore guidelines)_
- [X] ~~Optimize views to look good on all devices/screens~~ Delegated to https://github.com/damus-io/damus/issues/1847
- [X] ~~Mention that first 1,000 annual subscribers will receive "Nº 1", "Nº 2" subscriber numbers~~ Requirement cancelled after discussion in #1873 patches
- [ ] Polish subscription mechanism so that it registers with the server immediately after subscribing (without having to restart the app)
- [x] Add "learn more about damus purple" which takes the user to the website

**Comment by jb55** [comment]
On Mon, Dec 11, 2023 at 12:57:31PM -0800, Daniel D’Aquino wrote:
>## Acceptance criteria
>
>- [ ] Show user that apple takes X%/Y$ of each in app apple pay donation

this is technically not allowed by appstore guidelines

**Comment by danieldaquino** [comment]
> > - [ ] Show user that apple takes X%/Y$ of each in app apple pay donation
>
> this is technically not allowed by appstore guidelines

I also had a feeling this acceptance criteria item would be controversial with Apple. Thanks for confirming, I will cross it out.

**Comment by jb55** [comment]
On Wed, Dec 13, 2023 at 09:52:04AM -0800, Daniel D’Aquino wrote:
>>> - [ ] Show user that apple takes X%/Y$ of each in app apple pay donation
>>
>> this is technically not allowed by appstore guidelines
>
>I also had a feeling this acceptance criteria item would be
>controversial with Apple. Thanks for confirming, I will cross it out.

Here's another interesting thing that I thought you could do but can't.
Letting users know about other subscription options (lightning):

"Apple currently prevents apps from letting users know about a
purchasing method other than the App Store's in-app purchase system
within their apps, although it does allow developers to inform customers
by email. Now"

I learned this from an article I read today:

https://www.macrumors.com/2023/12/13/eu-plans-to-end-apple-anti-steering-rule/

Apparently EU/spotify are suing apple for this.

"Spotify has argued that being unable to let iPhone users know about
other payment options is anticompetitive."

**Comment by danieldaquino** [comment]
> On Wed, Dec 13, 2023 at 09:52:04AM -0800, Daniel D’Aquino wrote: >> - [ ] Show user that apple takes X%/Y$ of each in app apple pay donation > > this is technically not allowed by appstore guidelines I also had a feeling this acceptance criteria item would be controversial with Apple. Thanks for confirming, I will cross it out.
> Here's another interesting thing that I thought you could do but can't. Letting users know about other subscription options (lightning): "Apple currently prevents apps from letting users know about a purchasing method other than the App Store's in-app purchase system within their apps, although it does allow developers to inform customers by email. Now" I learned this from an article I read today: https://www.macrumors.com/2023/12/13/eu-plans-to-end-apple-anti-steering-rule/ Apparently EU/spotify are suing apple for this. "Spotify has argued that being unable to let iPhone users know about other payment options is anticompetitive."

@jb55, yes, I remember reading or hearing about this rule a while back.

There is an alternative though. **When we present the benefits of Damus Purple to the user on the app, we could place a link saying "Learn more about Damus Purple" which them to a page on our website. In that page we can present alternative payment methods** (because Damus is not only limited to iOS)

Whenever I think of this, I think [OpenPhone](https://openphone.com) is probably a good similar example. They offer their paid services via in-app subscriptions on their iOS app, but they also provide different payment options if the user signs up through their website. Apple cannot stop them from offering users different payment methods on their website (after all, some users might not even use iOS at all)

**Comment by jb55** [comment]
Do we have to collect their email for the in-app purchase? And can therefore, inform them about lightning option once they show interest…what about our “users” informing them about the option available on our website?

**Comment by jb55** [comment]
On Wed, Dec 13, 2023 at 10:41:19AM -0800, Daniel D’Aquino wrote:
>There is an alternative though. **When we present the benefits of Damus
>Purple to the user on the app, we could place a link saying "Learn more
>about Damus Purple" which them to a page on our website. In that page
>we can present alternative payment methods** (because Damus is not only
>limited to iOS)

good call. I like the "learn more about damus purple" approach. let's do that.

**Comment by danieldaquino** [comment]
> good call. I like the "learn more about damus purple" approach. let's do that.

Added it to the acceptance criteria!

**Comment by danieldaquino** [comment]
@alltheseas, @jb55, the only remaining item on the acceptance criteria (_Polish subscription mechanism so that it registers with the server immediately after subscribing (without having to restart the app_) is only relevant for Apple in-app purchases.

Perhaps we can either move this ticket to a future release milestone or split that item into a separate ticket and close this one?

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/issues/1948
