### ISSUE TITLE
Damus Purple Subscription: Add support for localized strings

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1816]
When developing drafts for the purple view (See `DamusPurpleView.swift` and `DamusPurpleWelcomeView.swift`), I forgot to add localized strings.

This task tracks replacing string literals with localizable strings

## Development notes

If you need to access the experimental Purple feature, please follow these guidelines:

1. You can run this on the iOS simulator, to simplify work. That will also set you up in the Xcode development in-app purchase environment (Where no real money is spent, purchases are simulated)
2. To enable the purple feature: Go to settings -> Developer settings -> Turn developer mode ON, as well as "experimental purple support"
3. You will then see the "Purple" option appear on the side menu.

**Comment by alltheseas** [comment]
@kernelkind here is an initial purple ticket for your consideration
