### ISSUE TITLE
Replace reaction emoji selector with default iOS emoji keyboard

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1821]
Current experience:

To set a custom reaction emoji users must navigate to settings to add them individually, and then return to the note they want to react to, and scroll horizontally until they find it. This causes numerous UX challenges including swiping to different view modes or selecting the wrong reaction emoji in the narrow scrolling widget.

Proposed solution:

Remove this feature entirely and replace it with a long-press option on the emoji that allows the user to select the desired emoji directly from the default iOS emoji keyboard.

A single tap would simply trigger the default emoji 🤙 / ❤️ etc.  which can still be configured in settings. 

Linked issue: https://github.com/damus-io/damus/issues/1538

**Comment by alltheseas** [comment]
#2204 update planned in 1.8
