### ISSUE TITLE
Release hotfix (Onboarding fix)

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1822]
I am opening this ticket as a placeholder to log progress on the hotfix release, or to open discussions about it if necessary

This release will include the onboarding fix (https://github.com/damus-io/damus/issues/1726)

**Comment by danieldaquino** [comment]
Created a hotfix release branch here: https://github.com/damus-io/damus/commits/release_hotfix_onboarding_fix_1726/

This branch effectively gets the App Store release version 1.6 (29) and cherry picks the onboarding fix.

**Comment by danieldaquino** [comment]
## Updates

1. Made version bump to 1.6.1 (30) commit
2. Performed a quick sanity check of the version on a physical iPhone _(More details below)_. NO ISSUES FOUND
3. Built app for archiving under the "release" scheme. BUILD SUCCESSFUL
4. Performed automated preliminary App Store Connect validation. Validation PASSED
5. Updated changelog
6. Uploaded build to App Store Connect
7. Published updated release branch (https://github.com/damus-io/damus/commits/release_hotfix_onboarding_fix_1726/)

### Test details

**PASS**
    
**Device:** iPhone 13 mini _(physical device)_
**iOS:** 17.2
**Damus:** 1.6.1 (30) (`2ece2eecd9f31669f7932c0f1b3f553d2daf3729`)
**Build scheme:** "Release"
**Setting:** "Always show onboarding" is set to ON
**Coverage:**
1. Clicking "post" on onboarding post view publishes the post and dismisses the view. PASS
2. Clicking "cancel" on onboarding post view dismisses the view without publishing. PASS
3. Dragging the onboarding post view down dismisses the view without publishing. PASS
4. Making a normal post (I replied to a thread) still publishes the post and dismisses the normal post view sheet. PASS

**Extra sanity check coverage:**
1. Scroll down the feed
2. React to a few posts
3. Switch to different tabs
4. Check version reported by the app matches the version

CC: @jb55, please let me know if anything looks incorrect or missing so far. I will work on the remaining items

**Comment by danieldaquino** [comment]
## CI/CD check

1.6.1 (30) failing NostrScriptsTests, but looking at other build test info, it seems to be preexisting and not introduced by the changes done in this ticket.

- v1.6 (29): https://github.com/damus-io/damus/runs/18722174514
- v1.6.1 (30): https://github.com/damus-io/damus/runs/19694624361

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, submitted version 1.6.1 for review!

**Comment by danieldaquino** [comment]
Added tag to the release commit: https://github.com/damus-io/damus/releases/tag/v1.6.1-30

**Comment by jb55** [comment]
On Fri, Dec 15, 2023 at 02:01:33PM -0800, Daniel D’Aquino wrote:
>## CI/CD check
>
>1.6.1 (30) failing NostrScriptsTests, but looking at other build test info, it seems to be preexisting and not introduced by the changes done in this ticket.

There's a flaky test on only one of the devices, I don't know how to
debug for it though...
