### ISSUE TITLE
Damus is unable to be found on the Google Play Store 

### ISSUE THREAD

**Issue by derekross** [damus-io/damus#1824]
Device: Google Pixel 7 Pro

OS: Android 14 UQ1A.231205.015

Region: US

Language: English 

When I search on the Google Play Store for Damus, I can't find the app. Please fix this at your earliest convenience. Thanks.

**Comment by alltheseas** [comment]
Play store is another rugpull waiting to happen. Android version strength is APK will be available, as will FOSS app store Damus Android (obtainium etc).

See https://github.com/damus-io/android

Send sats for development here https://damus.io/android/
