### ISSUE TITLE
Design image note previews for external to nostr internet (e.g. Twitter)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1828]
@robagreda @karnagebitcoin Will is working on opengraph note previews for external to nostr sharing. A PNG is generated. See non-designed engineering prototype example below.

<img width="600" alt="image" src="https://github.com/damus-io/damus/assets/64376233/54c0bcd2-8fd1-46a0-902c-4682ed1b965b">

https://damus.io/note18y3rnmf4g8vdrtk5d3s2kp3ccckz84elqshfy79r8pnaca9kvf3sdmzvlr

cc @jb55 @danieldaquino 

Open questions:
1) what should the preview image look like (see current rendering above)? 
2) iOS flow -> open Damus, or prompt Damus installation?
3) Android flow -> is recommending Android app installation the best experience? Should Damus instead point to a web client that does not require installation? Damus Android will not be ready before we implement this feature. 
4) MacOS/windows/Linux web flow -> what does this look like? There is a MacOS Damus app. The MacOS Damus experience in my view lacks polish and attention, as team has been focused on iOS. 

### related

https://github.com/damus-io/damus/issues/959
https://github.com/damus-io/damus/issues/1140
https://github.com/damus-io/damus/issues/1139

**Comment by karnagebitcoin** [comment]
what can be rendered in the image, just note text? Or can we add pfps, display names?

**Comment by karnagebitcoin** [comment]
started some ideas here, but will add more: https://www.figma.com/file/MQPGcqPc19xELLpCZ2F01q/Cover-image-ideas?type=design&node-id=0%3A1&mode=design&t=8yi2SOOjQOiVP077-1

**Comment by karnagebitcoin** [comment]
![Uploading CleanShot 2023-12-19 at 16.59.01@2x.png…]()
Test

**Comment by alltheseas** [comment]
> Or can we add pfps, display names

Yes

> at the very least we need a call to action or a full URL like damus.io so people know where to go

@jb55 is it possible to make the PNG preview also a clickable URL?

**Comment by jb55** [comment]
there will be a PNG preview that will be embedded in clients like twitter, facebook, etc. when the link is clicked we will also need an html/css preview as well.

In the PNG we can have anything as well, images, profile names, etc:

![](https://cdn.jb55.com/s/nevent1qqsrjg3ea565rkx34m2xcc9tqcuvvtpr6ulsgt5j0z3nse7uwjmxycczyqewrqnkx4zsaweutf739s0cu7et29zrntqs5elw70vlm8zudr3y24dzxaz.png)

![](https://cdn.jb55.com/s/npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s.png)

as you can tell I'm still in the "programmer design" phase as I get this all working.

**Comment by jb55** [comment]
> ![CleanShot 2023-12-19 at 16 59 01@2x](https://private-user-images.githubusercontent.com/131526701/291516766-f2384478-a8f9-42a5-9af0-38dfa233ac76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDU4MTgsIm5iZiI6MTcwMzAwNTUxOCwicGF0aCI6Ii8xMzE1MjY3MDEvMjkxNTE2NzY2LWYyMzg0NDc4LWE4ZjktNDJhNS05YWYwLTM4ZGZhMjMzYWM3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNzA1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWQ5MzFjZGFmOWUwM2RmODI5YWM0N2Q1ZGVjNjQ1ZmI3ZDIyMTkzOTE2NTI2NDllYTlhMGJjMzA4OTQwY2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZFxbe5L01UXHvIP936cHO4SSyOxTpUY7OfHEMRBjO-0)Test

looks awesome.

**Comment by karnagebitcoin** [comment]
Good to know, I will play around with displaying PFPs and names too and or images

**Comment by jb55** [comment]
slowly getting there...

![](https://cdn.jb55.com/s/nevent1qqswxp8dx2zs4pgskyyx2f8nqveky7rczf0y64d5wdx0qkk2wu6cuagk5xmdg.png)

**Comment by alltheseas** [comment]
Say the purpose feature is twofold: to act as both a funnel for Damus, and nostr (e.g. for Android, web users). 

Should we say something like: 

"Published by Damus on nostr"
"Shared with Damus and 💜 on nostr"

**Comment by danieldaquino** [comment]
> ![](https://camo.githubusercontent.com/0be4e0cdbfcec914fa01328313bac4d5c1876ef9e5d7e9d694729d47b1085f84/68747470733a2f2f63646e2e6a6235352e636f6d2f732f6e6576656e7431717173777870386478327a73347067736b7979783266386e7176656b793772637a6630793634643577647830716b6b32777536637561676b35786d64672e706e67)

I love how this is turning out! 🤩

**Comment by jb55** [comment]
On Fri, Dec 22, 2023 at 10:51:14AM -0800, Daniel D’Aquino wrote:
>> ![](https://camo.githubusercontent.com/0be4e0cdbfcec914fa01328313bac4d5c1876ef9e5d7e9d694729d47b1085f84/68747470733a2f2f63646e2e6a6235352e636f6d2f732f6e6576656e7431717173777870386478327a73347067736b7979783266386e7176656b793772637a6630793634643577647830716b6b32777536637561676b35786d64672e706e67)
>
>I love how this is turning out! 🤩

here's the latest design :D

https://purple.damus.io/nevent1qqstj0wgdgplzypp5fjlg5vdr9mcex5me7elhcvh2trk0836y69q9cgsn6gzr.png

**Comment by alltheseas** [comment]
> On Fri, Dec 22, 2023 at 10:51:14AM -0800, Daniel D’Aquino wrote:
> >> ![](https://camo.githubusercontent.com/0be4e0cdbfcec914fa01328313bac4d5c1876ef9e5d7e9d694729d47b1085f84/68747470733a2f2f63646e2e6a6235352e636f6d2f732f6e6576656e7431717173777870386478327a73347067736b7979783266386e7176656b793772637a6630793634643577647830716b6b32777536637561676b35786d64672e706e67)
> >
> >I love how this is turning out! 🤩
> 
> here's the latest design :D
> 
> https://purple.damus.io/nevent1qqstj0wgdgplzypp5fjlg5vdr9mcex5me7elhcvh2trk0836y69q9cgsn6gzr.png
> 

Looking great!

(How) might we add an indication of nostr?

**Comment by jb55** [comment]
On Sat, Dec 23, 2023 at 09:52:40AM -0800, alltheseas wrote:
>> On Fri, Dec 22, 2023 at 10:51:14AM -0800, Daniel D’Aquino wrote:
>> >> ![](https://camo.githubusercontent.com/0be4e0cdbfcec914fa01328313bac4d5c1876ef9e5d7e9d694729d47b1085f84/68747470733a2f2f63646e2e6a6235352e636f6d2f732f6e6576656e7431717173777870386478327a73347067736b7979783266386e7176656b793772637a6630793634643577647830716b6b32777536637561676b35786d64672e706e67)
>> >
>> >I love how this is turning out! 🤩
>>
>> here's the latest design :D
>>
>> https://purple.damus.io/nevent1qqstj0wgdgplzypp5fjlg5vdr9mcex5me7elhcvh2trk0836y69q9cgsn6gzr.png
>>
>
>Looking great!
>
>(How) might we add an indication of nostr?

could say discuss on nostr?

**Comment by karnagebitcoin** [comment]
> On Sat, Dec 23, 2023 at 09:52:40AM -0800, alltheseas wrote: > On Fri, Dec 22, 2023 at 10:51:14AM -0800, Daniel D’Aquino wrote: > >> ![](https://camo.githubusercontent.com/0be4e0cdbfcec914fa01328313bac4d5c1876ef9e5d7e9d694729d47b1085f84/68747470733a2f2f63646e2e6a6235352e636f6d2f732f6e6576656e7431717173777870386478327a73347067736b7979783266386e7176656b793772637a6630793634643577647830716b6b32777536637561676b35786d64672e706e67) > > > >I love how this is turning out! 🤩 > > here's the latest design :D > > https://purple.damus.io/nevent1qqstj0wgdgplzypp5fjlg5vdr9mcex5me7elhcvh2trk0836y69q9cgsn6gzr.png > Looking great! (How) might we add an indication of nostr?
> could say discuss on nostr?

Does the protocol need to be advertised?

**Comment by alltheseas** [comment]
> Does the protocol need to be advertised?

I suppose we know when we are using the internet. We know when we are using email.

Hardly no one knows about nostr protocol, or Damus. 

It's fine for Damus brand to continue to build.

I'm wondering if there is benefit for mentioning both, and implying Damus is sweet, AND nostr is bigger than Damus.

Is that too much to get across in a note preview? 

If its decided nostr is mentioned, how might the reader learn more about nostr? Would they even care if presented with 
1) a PFP
2) a note
3) a Damus mention

Maybe that's a lot going already.

**Comment by alltheseas** [comment]
https://damus.io/note1yfseuhd7plcpch0m44mffhvauk66agzhxsc86g8svaaquxr7q7wshr4gaq

**Comment by karnagebitcoin** [comment]
> https://damus.io/note1yfseuhd7plcpch0m44mffhvauk66agzhxsc86g8svaaquxr7q7wshr4gaq

ok, maybe the note can say "Discuss on Nostr"?

**Comment by alltheseas** [comment]
https://github.com/damus-io/notecrumbs WIP
