### ISSUE TITLE
Comma separated URLs not parsed correctly

### ISSUE THREAD

**Issue by kernelkind** [damus-io/damus#1833]
Example: note18qctpn07cx2lteahud3rm5dw0fjw69jpk6pfz7qtdg7lkwld0r4qdd2h6m

There are two comma separated links: `https://github.com/nostr-protocol/nips/blob/master/44.md` and `https://github.com/paulmillr/nip44`. But the parser is incorrectly adding the comma which separates them to the URL so the first URL is parsed as `https://github.com/nostr-protocol/nips/blob/master/44.md,`. 

When the user clicks on the link, they are directed to the URL with the comma in it, and the web page gives a 404 error.

When entering the text segment `https://github.com/nostr-protocol/nips/blob/master/44.md, https://github.com/paulmillr/nip44` into a competing site like twitter, it correctly parses the URLs to not include the comma.

Related issue #1638

**Comment by paulmillr** [comment]
It's worth noting that it's not just "comma". It's comma, followed by a space, which is definitely invalid.

**Comment by alltheseas** [comment]
@kernelkind see also prefix, suffix related URL ticket

https://github.com/damus-io/damus/issues/278
