### ISSUE TITLE
Hook up Purple translation service to Damus app

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1836]

**Comment by danieldaquino** [comment]
@jb55, have you implemented a draft for this when you were drafting the damus api server? (Just checking if there is something I can use, or if I should start from scratch)

**Comment by jb55** [comment]
On Fri, Dec 22, 2023 at 02:19:31PM -0800, Daniel D’Aquino wrote:
>@jb55, have you implemented a draft for this when you were drafting the damus api server? (Just checking if there is something I can use, or if I should start from scratch)

ah no I didn't start on that yet

**Comment by danieldaquino** [comment]
> On Fri, Dec 22, 2023 at 02:19:31PM -0800, Daniel D’Aquino wrote: @jb55, have you implemented a draft for this when you were drafting the damus api server? (Just checking if there is something I can use, or if I should start from scratch)
> ah no I didn't start on that yet

No worries! I will see if I can get that part done while we wait for the sandbox environment to be activated

**Comment by danieldaquino** [comment]
I started this one yesterday alongside https://github.com/damus-io/api/issues/1!

**Comment by danieldaquino** [comment]
Sent patches for this!
- https://groups.google.com/a/damus.io/g/patches/c/rfBy2EaOojM
- https://groups.google.com/a/damus.io/g/patches/c/spNbBD4ujIw
