### ISSUE TITLE
Laggy performance, crash

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1837]
https://damus.io/note17eqhmxz5623x0yagevmexpytszv4va3xva955unnm0zc0g086azqy6rxau

https://damus.io/note17eqhmxz5623x0yagevmexpytszv4va3xva955unnm0zc0g086azqy6rxau

iOS 17.1.2
TestFlight Damus 1.6 (28)

are there any known bugs that cause Damus to crash on the home feed? It’s becoming pretty unbearable on my phone (iPhone 12 mini). The app will start getting laggy, slowly grind to a stop, and then crash after being unresponsive for about a minute. It happens a couple times a day within a couple minutes of opening the app. 

I’ve submitted a few crash reports and can provide the associated email via DM if that’s helpful

Worth noting that I don’t know the exact steps to reproduce, but I have tried uninstalling and reinstalling the app

App crashed while writing that note :( even the keyboard and everything gets super buggy. I suppose it’s also possible there is something wrong with my iOS, but I haven’t seen this happen in other apps yet

**Comment by alltheseas** [comment]
@jb55 @danieldaquino can yall see this in the iOS crash logs?

**Comment by alltheseas** [comment]
> @jb55 @danieldaquino can yall see this in the iOS crash logs? 

I shared email of the issue submitter privately with yall

**Comment by danieldaquino** [comment]
> @jb55 @danieldaquino can yall see this in the iOS crash logs?

I see some crash reports that matches the description. Not 100% sure they come from the same person, but those seem to closely match the description written in this ticket

**Comment by alltheseas** [comment]
> > @jb55 @danieldaquino can yall see this in the iOS crash logs?
> 
> 
> 
> I see some crash reports that matches the description. Not 100% sure they come from the same person, but those seem to closely match the description written in this ticket

Check TG for email of user

**Comment by alltheseas** [comment]
Is this an issue affecting many, or with potential to affect many damus users?

**Comment by jb55** [comment]
I will test your account now

**Comment by jb55** [comment]
I'm not seeing anything when I log in with your account, can you confirm your current app version?

**Comment by alltheseas** [comment]
Thanks for the follow up 🙏
