### ISSUE TITLE
Search for naddr

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1842]
In universe view, when I paste an naddr

E.g. naddr1qqxnzdesxgerxdp58yenyvejqgswrlemlh2wgqc4jkds3d8ueqj9a2j3gcm7r48v9tskdd6rxsd7rtcrqsqqqa28wdzn0j

I should see said result

Instead, I see

![image](https://github.com/damus-io/damus/assets/64376233/0ef4eb19-d8c5-49c2-b238-3b2a14b8311d)

Related to https://github.com/damus-io/damus/issues/1806

**Comment by alltheseas** [comment]
One more @jb55 @kernelkind @danieldaquino

**Comment by kernelkind** [comment]
I added this feature already, this should be closed @alltheseas
