### ISSUE TITLE
Convert user public key from npub to nprofile in ellipsis menu and share menu

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1844]
![image](https://github.com/damus-io/damus/assets/64376233/639de0ef-2a1c-48cd-ba5d-f0eee4b287a0)

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/f6c2e3f7-da18-4584-895c-3e1758bb4507)

**Comment by kernelkind** [comment]
@alltheseas Should the user still see the `npub` section in the user's profile? Or should it be an `nprofile` as well?

**Comment by alltheseas** [comment]
> @alltheseas Should the user still see the `npub` section in the user's profile? Or should it be an `nprofile` as well?

Great question. I havent established consensus on this yet.

Recommend you defer this one for now. 

Will tag you in 1-2 other tickets for your consideration.

Are you in the dev chat?

damus.io/devchat

**Comment by jb55** [comment]
On Thu, Dec 28, 2023 at 07:38:04AM -0800, alltheseas wrote:
>> @alltheseas Should the user still see the `npub` section in the
>> user's profile? Or should it be an `nprofile` as well?

nprofile is for sharing (https://damus.io/nprofile...), npub should probably stay as is?
