### ISSUE TITLE
Render nevent in DMs

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1845]
![image](https://github.com/damus-io/damus/assets/64376233/824481f9-4de5-4da5-9994-5315319ce6bf)

nevent1qqsvtlpxrtgpf4rfvfcwkpdknj6mjukqftqvvuj29q42y3h5hsg64ycpqqpzqd5k8lv

Builds on https://github.com/damus-io/damus/issues/909

@kernelkind

**Comment by kernelkind** [comment]
This is what a different nevent looks like in DMs:
<img width="509" alt="image" src="https://github.com/damus-io/damus/assets/8139906/ff8f1cc9-3f47-4afb-bb48-3a981a1b836a">
`nevent1qqsvkyhk69gp4awxlnmwra6kw3jksm0v0zgdtmra092xzgwyf9lldvs5nhqaq`

**Comment by kernelkind** [comment]
I have a patch series I'm actively working on that will fix this issue, among others

**Comment by kernelkind** [comment]
This was fixed in 3056ab9bfb8e601900598927ef0b7870d2e19ade @alltheseas
