### ISSUE TITLE
More finite zap receipt notifications

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1853]
_what happens_

Post apple note zap ban, I cannot see who zapped me what in notifications view. I see one jumbled group zap. 

![image](https://github.com/damus-io/damus/assets/64376233/276af67b-bf52-4c3c-9963-cf185d72bc3d)

_HMW_

How might we design more finite zap notifications? 

### related 
Zap history https://github.com/damus-io/damus/issues/1409

**Comment by jb55** [comment]
I want to tackle this soon, adding to sprint

**Comment by alltheseas** [comment]
this is per note on 1.10
