### ISSUE TITLE
Nostr:npub not rendering

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1872]
![image](https://github.com/damus-io/damus/assets/64376233/bb561f86-3d92-45ea-84d2-8159cc6085d8)

https://damus.io/note1a4r0h5wqf7enrz6vzesn3m0csdznx5jq7cjujvvg4fjj57t5kzjshqx3y7

**Comment by jb55** [comment]
npub1dhvlm7aumyhy60mlv3lemk4newny4uwkdc9ahcskk4lvatytq4vq60lcq6up is an invalid checksum.

I think they meant to do npub1dhvlm7aumyhy60mlv3lemk4newny4uwkdc9ahcskk4lvatytq4vq60lcq6 up

this might happen when they are backspacing and come up right next to the text. we should figure out how to make this impossible to do.
