### ISSUE TITLE
Add ordinal number labels to Purple subscribers (1st subscriber, 2nd, etc)

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1873]
## Acceptance criteria

- [ ] The database should keep track of who signed up first, second, etc
- [ ] We should show those numbers somewhere in the UI as part of their badge (This could possibly be split into a separate task if we are short on time)

**Comment by danieldaquino** [comment]
@jb55, sent two patches your way for this ticket!

- backend: https://groups.google.com/a/damus.io/g/patches/c/IsmwE_RZyJs
- iOS app: https://groups.google.com/a/damus.io/g/patches/c/jaiIVPWbXCk

Please let me know if you have any suggestions or questions.

Thank you!

CC: @alltheseas 

**Here are some screenshots for easy visualization:**

![Screenshot 2024-01-22 at 21 20 08](https://github.com/damus-io/damus/assets/24692108/826f9753-fbbc-4b4b-8d0a-1328cebf243c)
![Simulator Screenshot - iPhone 15 Pro - 2024-01-22 at 21 10 40](https://github.com/damus-io/damus/assets/24692108/edbab47b-a32a-4e0c-a04c-f4539e374e2e)
![Simulator Screenshot - iPhone 15 - 2024-01-22 at 21 19 12](https://github.com/damus-io/damus/assets/24692108/157784d2-aec4-477b-b0ed-dcccf08992e5)
![Simulator Screenshot - iPhone 15 - 2024-01-22 at 21 45 12](https://github.com/damus-io/damus/assets/24692108/ce3349e5-9aa3-405a-af92-4799854c5904)

**Comment by jb55** [comment]
On Mon, Jan 22, 2024 at 09:47:36PM -0800, Daniel D’Aquino wrote:
>@jb55, sent two patches your way for this ticket!
>
>- backend: https://groups.google.com/a/damus.io/g/patches/c/IsmwE_RZyJs
>- iOS app: https://groups.google.com/a/damus.io/g/patches/c/jaiIVPWbXCk
>
>Please let me know if you have any suggestions or questions.
>
>Thank you!
>
>CC: @alltheseas
>
>**Here are some screenshots for easy visualization:**
>
>![Screenshot 2024-01-22 at 21 20 08](https://github.com/damus-io/damus/assets/24692108/826f9753-fbbc-4b4b-8d0a-1328cebf243c)

we probably don't need to show them inline on each post, let's just add
it to the profile screens

**Comment by jb55** [comment]
On Tue, Jan 23, 2024 at 12:22:53PM -0800, William Casarin wrote:
>we probably don't need to show them inline on each post, let's just add
>it to the profile screens

To be clear, the star is ok, but the number is a bit weird. Let's have
stars on the post and star+number on profile pages.

**Comment by danieldaquino** [comment]
> On Tue, Jan 23, 2024 at 12:22:53PM -0800, William Casarin wrote: we probably don't need to show them inline on each post, let's just add it to the profile screens
> To be clear, the star is ok, but the number is a bit weird. Let's have stars on the post and star+number on profile pages.

Sounds good, I will send the updated patch

**Comment by alltheseas** [comment]
As I read this, I realize it would be a useful feature to ask all Damus subscribers input on a given question - for instance, what do yall think of feature X?

Counter to the usefulness, tagging a list of many people may be spammy.

**Comment by danieldaquino** [comment]
Sent updated patches addressing concerns:
- Backend: https://groups.google.com/a/damus.io/g/patches/c/zLgbNTPYAIk
- iOS app: https://groups.google.com/a/damus.io/g/patches/c/zXxU6mVabP4

@jb55, please let me know if those look good to go. Thanks!
