### ISSUE TITLE
Plan out Purple testing on TestFlight

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1874]
This task is to plan out the best way to perform release testing on Purple using TestFlight

## Notes

According to https://developer.apple.com/in-app-purchase/:
> In‑app purchases in TestFlight use the sandbox environment, so they’re free to testers and don’t carry over into production once your app is released on the App Store.

Another useful page: https://developer.apple.com/documentation/storekit/in-app_purchase/testing_at_all_stages_of_development_with_xcode_and_the_sandbox

**Comment by danieldaquino** [comment]
@alltheseas, @jb55, I have not-so-great news: TestFlight uses the Sandbox purchase environment, which means we are unable to charge real money via in-app purchases on TestFlight.

According to https://developer.apple.com/in-app-purchase/:

> In‑app purchases in TestFlight use the sandbox environment, so they’re free to testers and don’t carry over into production once your app is released on the App Store.

We need to think about how we will manage this. I will post here if I think of a good plan. Options that come to my mind right now:
- Limit TestFlight Purple access to select tester groups that already paying purple customers
- Disable Purple in-app purchasing altogether on TestFlight
- Create some staging test environment where people can do in-app purchases via the Sandbox, but they do not get the paid benefits of Purple

**Comment by alltheseas** [comment]
That's not good.

 If we cannot test real payments, we should have a manual way to fix things that didn't go well. 

For instance, say a payment goes through on payment side, but is not credited by our system. What manual tools do we have for 
0) seeing who paid what, and/or
1) adding credit/subscription time manually, andoror
2) returning funds?

Suggested order of operations:

1) iOS Enable sandbox (fake funds; at least for fiat side) for testflight. 
Web: We can quietly test the website without revealing the payment link.
2) When we enable on AppStore, could we find a way to feature flag/gate this feature for a very close group that tests real payments before everyone else? 

cc @jb55

**Comment by danieldaquino** [comment]
@alltheseas, I generally agree with your approach. A few thoughts:

Suggested order of operations:

> iOS Enable sandbox (fake funds for fiat side) for TestFlight.

To avoid having fake fiat payments allow access to the real Damus Purple, I can think that one solution would be to add a developer setting that switches between the real server (requiring real payments), and a test server that accepts fake TestFlight payments (with limited functionality)

(Although I imagine there are other ways to go about this)

> Web: We can quietly test the website without revealing the payment link. A selected few subscribed profiles can generate some buzz around purple.

Agree!

> When we enable subscribe via fiat on iOS/AppStore, could we find a way to feature flag/gate this feature for a very close group that tests real payments before everyone else.

That would be great, I wonder if it could cause controversy with Apple's review team though. Their docs seem to indicate that the Sandbox is what gets used for testing

> Once we confirm that fiat rails are working fine, we can make the announcement, and release to all.


I am doing a deeper dive into their documentation to find out the good ways to proceed

**Comment by danieldaquino** [comment]
> > iOS Enable sandbox (fake funds for fiat side) for TestFlight.
> 
> To avoid having fake fiat payments allow access to the real Damus Purple, I can think that one solution would be to add a developer setting that switches between the real server (requiring real payments), and a test server that accepts fake TestFlight payments (with limited functionality)

@jb55, for this one, do you think it is easy to setup a separate test server running the Purple server code (connected to a mock translator, like we do with `npm run dev`)?

I think that having a separate test server, and making sandbox/Testflight IAP purchases go through it might be the best way.
- **Advantages:** 
    - Simpler logic (compared to handling real/test accounts on the same production server)
    - Same code paths being tested (compared to handling real/test accounts on the same production server)
    - If spinning up a server is not an issue, it's the easiest way too
- **Disadvantage:** There is not much of an incentive for beta testers to test, and there is a friction for people to test it. In this solution, I would imagine only contributors and other volunteers would want to go through changing developer settings and making mock purchases.

> > When we enable subscribe via fiat on iOS/AppStore, could we find a way to feature flag/gate this feature for a very close group that tests real payments before everyone else.
> 
> That would be great, I wonder if it could cause controversy with Apple's review team though. Their docs seem to indicate that the Sandbox is what gets used for testing
> 

@jb55, @alltheseas, from what I am reading, it seems that the Sandbox and the real environment are basically the same from our perspective. The only thing that changes is that Apple will process real payments on the latter. But almost all code paths in our end are the same. The only exception I know of is the Apple URL we verify receipts against. Apple has one server for sandbox receipts, and one for real receipts. 

Therefore, a good coverage on the sandbox would cover most or all of the logic in production.

Perhaps the feature flag in this case could be something that disables new purchases and/or the feature itself, in the case of an emergency? So more of an emergency stop, rather than an opt-in flag?

Sources:
- https://developer.apple.com/documentation/storekit/in-app_purchase/testing_at_all_stages_of_development_with_xcode_and_the_sandbox
- https://medium.com/@Sergey.Zhuravel/in-app-purchases-in-ios-part-3-testing-purchases-in-testflight-sandbox-and-locally-in-xcode-3dec999986e1

**Comment by danieldaquino** [comment]
> so like a staging environment for the api? Could definitely do that.

Awesome! Thank you!
