### ISSUE TITLE
Don't allow duplicate relays

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1877]
Users should not be able to add the same relay twice.

Sometimes they will add them with minor syntax differences, such as:

wss://nos.lol
and
wss://nos.lol/

Damus should detect when a user is adding a relay they already have set and reject it.

**Comment by alltheseas** [comment]
I think this is a duplicate. @jb55 I dont think we have pushed out the trailing slash duplicate relay check yet, correct?

https://github.com/damus-io/damus/issues/1766#issuecomment-1866208996

**Comment by jb55** [comment]
On Sat, Jan 13, 2024 at 08:49:20AM -0800, alltheseas wrote:
>I think this is a duplicate. @jb55 I dont think we have pushed out the
>trailing slash duplicate relay check yet, correct?

I think there was work done at a surface level but there's multiple
areas where this is a problem. We just need to fix it by having this
duplicate checking and filtering logic all in one place.

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/157aada6-0980-4e8d-a2e0-f42eaf61f25d)

fixed 1.9 testflight
