### ISSUE TITLE
Rearrange mute conversation action in menu

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1878]
_what happens_

When I want to tap bookmark, I might accidentally tap mute conversation

_suggestion_

Move mute conversation below "Broadcast" button

https://damus.io/note1rhwf27eersp8qcnuemwmh9zpg5f6yq4qe4wsescnps65vp26nfus4c637c

**Comment by jb55** [comment]
On Sat, Jan 13, 2024 at 08:51:30AM -0800, alltheseas wrote:
>_what happens_
>
>When I want to tap bookmark, I might accidentally tap mute conversation

I do this all the time, it's annoying 😅
