### ISSUE TITLE
Poor performance with large size GIFs

### ISSUE THREAD

**Issue by OlegAba** [damus-io/damus#188]
Profile pictures that use large file size images (mostly GIFs) cause very poor performance - scrolling lag. Look at the video below for profile @npub1gpppr3hfwcl5njxqmp3zumaly9j4pd6gvapywsq2y5n7p7278fus6nz7l5 who uses a 65MB image. The Kingfisher library has a downsampling modifier. Unfortunately, it does not work for [animated images](https://github.com/onevcat/Kingfisher/issues/1940) . I think the best approach would be to not animate any images over a byte limit (100KB?). 

https://user-images.githubusercontent.com/19398259/210023069-9aa51f74-c484-49bf-8e87-ef9de22a9916.mov

**Comment by jb55** [comment]
Yes we should do that
