### ISSUE TITLE
Indicate which notes are coming from Threads, Fediverse etc

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1885]
How might we indicate which notes are coming from Threads, Fediverse etc

### related
indicate which (nostr) relays a note was seen on https://github.com/damus-io/damus/issues/1029

**Comment by alltheseas** [comment]
@alexgleason added some NIP to help add additional helpful info for non-nostr profiles

**Comment by alexgleason** [comment]
[NIP-48](https://github.com/nostr-protocol/nips/blob/master/48.md)

**Comment by alltheseas** [comment]
@robagreda @ericholguin 👀

**Comment by jb55** [comment]
https://github.com/nostr-protocol/nips/blob/master/48.md

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/7cc3968e-9c1e-4b9f-a4d7-235097411f64)

**Comment by alltheseas** [comment]
@ericholguin activitypub shows on feed. However, if I tap on a note I dont see activitypub. What do you think about displaying activitypub in note view?

![image](https://github.com/damus-io/damus/assets/64376233/ee5bf464-3280-4893-bda9-ebc96f34b7e4)

![image](https://github.com/damus-io/damus/assets/64376233/aae2b5d8-784f-4ed8-b81e-60f8304e69c8)

**Comment by jb55** [comment]
this is done in 1.7

**Comment by jb55** [comment]
On Sat, Mar 02, 2024 at 12:45:06AM -0800, alltheseas wrote:
>@ericholguin activitypub shows on feed. However, if I tap on a note I
>dont see activitypub. What do you think about displaying activitypub in
>note view?

let's open a new issue for this
