### ISSUE TITLE
testflight full + installation docs?

### ISSUE THREAD

**Issue by dtdannen** [damus-io/damus#189]
I tried to install the app via testflight and it says the beta is full. To get the app on my MacOS - can I just compile it from source? I'm a bit new to mac development so if there's an obvious step to compile Swift, please let me know. In any case, I'd recommend adding compilation instructions.

**Comment by leesalminen** [comment]
1- clone repo locally
2- open `damus.xcodeproj` with Xcode on your Mac
3- in the top-middle of the screen where you can select a build target, select `My Mac`
4- Click the "play" icon in the top left to build & launch

Unsure if you need to pay Apple their $99/year to become an Apple developer. Probably though, Apple likes their $99.

**Comment by thomasRademaker** [comment]
you will need an apple developer account to build locally to your Mac. And then you will need to select the `Damus` target and change the `Team` and `Bundle Identifier` to your team and a unique bundle id

**Comment by dtdannen** [comment]
Awesome, thanks for explaining - any chance when you think the Damus mobile app might be launched fully, outside testflight?

**Comment by leesalminen** [comment]
hey @dtdannen from what I understand, @jb55 has now submitted Damus to Apple for review and launch in the App Store for the general public. Assuming they don't reject it, it should be live in the next couple days.

**Comment by dtdannen** [comment]
Wonderful, thanks for the update. Do you think it's worth it to put the 4 steps by @leesalminen in the README or other docs somewhere? Or is it too obvious for mac folks. That's the only thing left that I can think of to prevent closing this issue.

**Comment by Sure33** [comment]
Do we have any news about the App Store launch?

**Comment by alltheseas** [comment]
https://apps.apple.com/us/app/damus/id1628663131
