### ISSUE TITLE
Prepare Damus Purple screen without Apple IAP support

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1899]
We might not have IAP (In-app Purchase) support for the first version since we are waiting on something from Apple Developer support.

This task is to tweak the Purple view and ensure it looks coherent even with no IAP support.

## Acceptance criteria

- [x] Add account info to the view coming from the server
- [x] Add translation setup view to Damus Purple onboarding to make it more obvious
- [x] Add translation setup logic to the LN flow as well
- [x] Make DamusPurpleView update to the account info as soon as user finishes purchase
- [x] Include support email address on the error screen

**Comment by danieldaquino** [comment]
This is essentially done, just have to format the patch!

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, on Friday I was working on some changes to the main Purple screen (in iOS) to make it more coherent with the way things will work on the upcoming release (IAP support disabled, focus on LN purchase flow)

I still need to clean up the code patches a bit and formally test things, but to help speed up review, I can share some images of what I have, to give you a chance to review them before I send the patches:

## Scenario 1: User has no Purple account.

This is what they would see:

![Simulator Screenshot - iPhone 15 - 2024-01-28 at 14 33 18](https://github.com/damus-io/damus/assets/24692108/f8a1b2b5-5797-475f-b6df-6d6c8c5fbb4e)

The view mostly looks the same, except the In-app purchase buttons are hidden, and the link mentions that Purple is coming soon, inviting the user to learn more on the website (damus.io)

## Scenario 2: User has an active Purple account.

This is what they would see:

![Simulator Screenshot - iPhone 15 Pro - 2024-01-26 at 19 44 43](https://github.com/damus-io/damus/assets/24692108/1f84bfba-1002-45ac-8fe2-04de7d542422)

This is a brand new view that shows them the status of their account, some useful info (straight from the server, which is the source of truth), and an instruction mentioning they can manage billing or top-up their account on the website.

## Scenario 4: User has a Purple account, but it is expired

This is (roughly) what they would see (This is just a SwiftUI preview without the nice purple background):

![Screenshot 2024-01-28 at 14 42 06](https://github.com/damus-io/damus/assets/24692108/76abb84e-20c2-42cf-9c73-a18f86f115a4)

## Scenario 5: There is an error getting information from the Purple server

This one shouldn't be common, but if for whatever reason there is a failure in getting account info (e.g. if the server is down), they would see something like this:

![Simulator Screenshot - iPhone 15 Pro - 2024-01-26 at 19 56 44](https://github.com/damus-io/damus/assets/24692108/00dd5b00-054e-4ae6-9ab7-2f3e871ec15f)

## Next steps

I will clean up the code, re-test, and send the patch on Monday, but please let me know if you have any requests or suggestions on the UI/UX design portion.

Thank you!

**Comment by jb55** [comment]
This looks great! I was wondering about this when I was testing the
staging purple flow after getting an account via lightning. Excited for
this!

**Comment by alltheseas** [comment]
Looks good! I would be specific, instead of saying "please contact support". 

Is there a support at damus email @jb55 ?

**Comment by alltheseas** [comment]
If there is no support at damus email, just add "contact Vanessa" npub1h50pnxqw9jg7dhr906fvy4mze2yzawf895jhnc3p7qmljdugm6gsrurqev

**Comment by jb55** [comment]
On Sun, Jan 28, 2024 at 08:16:52PM -0800, alltheseas wrote:
>If there is no support at damus email [..]

***@***.***

**Comment by jb55** [comment]
stupid email response filtering...

support@damus.io

**Comment by danieldaquino** [comment]
Done! Here are my updates on this ticket today:

-  Add translation setup view to Damus Purple onboarding to make it more obvious (Unlock translations)
-  Add translation setup logic to the LN flow as well
-  Make DamusPurpleView update to the account info as soon as user finishes purchase
-  Include support email address on the error screen


Here is a demo video of the whole flow with the updated iOS views, which I tested on a real device and on the staging environment: https://drive.google.com/file/d/18S6H7ARYc5nbzMo4OxEQTb7uYosm3xlS/view?usp=sharing

Details, code, testing, etc, were all sent as a patch series via email (Can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/G54pOQvU9c0)

@jb55, @alltheseas, sorry for sending this later than anticipated, there were many changes involved to make it all fit together as best as it can, but please let me know if this is good!
