### ISSUE TITLE
Freeze and crash during Damus update to 1.7 on devices with low disk space available

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1912]
## Summary

Some users are reporting that they are seeing Damus freeze or become very slow once they update to 1.7 (2) on TestFlight.

Some crash reports from these users indicate that they are running low on disk space (usually less than 800MB).

The root cause is not certain, but I believe the app is crashing due to a lack of disk space during NostrDB migration from the individual app container to the shared container.

## Preconditions

**iOS:** 17
**Damus:** During upgrade from 1.6 to 1.7 (2)
**Disk space available:** Between 500MB and 800MB (roughly)

**Comment by danieldaquino** [comment]
**Related tickets:**
- #1619
- #1554

**Possible solutions:**
- Detect disk space available before migration, and start a new NostrDB from scratch on the new container if there is no disk space
- Trigger the NostrDB migration only when the user opts-in the Push notifications feature, and prevent them from doing so if there isn’t enough disk space

**Possible improvements to avoid this type of situation:**
- Limit NostrDB space usage to a fraction (Maybe 1/2) of the storage available to the app, and purge notes more aggressively when running low on disk space

**Comment by danieldaquino** [comment]
We received one report of similar symptoms, but no apparent lack of storage space on their device.

**Comment by alltheseas** [comment]
> We received one report of similar symptoms, but no apparent lack of storage space on their device.

https://github.com/damus-io/damus/issues/1913

**Comment by danieldaquino** [comment]
Another thought: I looked again at the file container migration code, and there are error catchers in place to fail smoothly in case the file operation fails

This reduces the chance of the container migration issue hypothesis. Unless it is failing in an indirect way (e.g. operation takes too long, hangs the app for a long time, and some kind of iOS watchdog kills the app)

**Comment by alltheseas** [comment]
1.7 (3) does not crash for me

**Comment by danieldaquino** [comment]
@alltheseas, thank you for checking! 

Since the crashes might not have been caused by low storage space, and the crash is being addressed on a separate ticket, maybe we can close this ticket, and work on low-storage handling improvements under https://github.com/damus-io/damus/issues/1619?

**Comment by alltheseas** [comment]
Agree

Closing
