### ISSUE TITLE
Version 1.7 adds an extra space after user tags when punctuation is added.

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1915]
I believe this is a new bug. 

After tagging a user and using backspace to add punctuation (in this case a period and a comma), Damus automatically adds a space after the tag before the punctuation. 

This issue was not present in V 1.6.

Reference note:

note13gdvkvptj84d7792cgrdw4mq7nupkltwrypn0y7dtrz4fg7h4qts0q25ym
![image](https://github.com/damus-io/damus/assets/3638467/47c2b7a5-3ab3-49a8-9ddb-fae7f0aebcc3)

**Comment by jb55** [comment]
> I believe this is a new bug. 
> 
> After tagging a user and using backspace to add punctuation (in this case a period and a comma), Damus automatically adds a space after the tag before the punctuation. 
> 
> This issue was not present in V 1.6.
> 
> Reference note:
> 
> note13gdvkvptj84d7792cgrdw4mq7nupkltwrypn0y7dtrz4fg7h4qts0q25ym
> ![image](https://github.com/damus-io/damus/assets/3638467/47c2b7a5-3ab3-49a8-9ddb-fae7f0aebcc3)

I believe @kernelkind added this to fix many issues with people adding text adjacent to mentions

**Comment by kernelkind** [comment]
Ah, yes this was introduced by one of my changes. I see now that the fix was too simplistic, instead of just adding a space it should always allow users to add text right after a mention, just make sure the link gets created properly.

The commit can be reverted and I'll resubmit it. Commit af75eed83a2a1dd0eb33a0a27ded71c9f44dacbd I believe

**Comment by kernelkind** [comment]
I submitted a patch that would fix this issue if we didn't want to drop https://github.com/damus-io/damus/commit/af75eed83a2a1dd0eb33a0a27ded71c9f44dacbd

https://groups.google.com/a/damus.io/g/patches/c/HSQRcB_ZFpM/m/vp2z5XzIAAAJ
