### ISSUE TITLE
1.7 GIF not rendering

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1917]
https://damus.io/note14q0e3tghpzn78x8208vrwpvyp92g4m9m3ah6yk8l0shlpye9ra6qaf2syj

> Hmmm 🤔 @seth is right. Links just aren’t showing up the same. Previous to the update I’d just see the gif I posted not the link.

**Comment by jb55** [comment]
what are the steps to reproduce?

**Comment by alltheseas** [comment]
I asked the bug submitter. 

I cannot currently recreate as I'm on the freeze crash 1.7 loop.

**Comment by alltheseas** [comment]
> I just copy and pasted the link to a gif in a note. It previously would have just shown the gif. Now it’s just showing the link. I can try another gif.

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/b2d24fec-ab02-4c2c-b17c-b3dd6451bb7f)

Cannot recreate

**Comment by kernelkind** [comment]
I think the user might have accidentally omitted the `giphy.gif` at the end of the URL. The content of their message is as follows: `"content": "Let me test this out. \n\nhttps://giphy.com/gifs/pbsnature-africa-hippo-hippos-JoPd4j1FLdmheyqLHC"`. When submitting a post with the url `https://media1.giphy.com/media/JoPd4j1FLdmheyqLHC/giphy.gif` the gif works as intended

**Comment by alltheseas** [comment]
Does it make sense to auto add the missing giphy.gif?

**Comment by jb55** [comment]
On Thu, Jan 25, 2024 at 04:16:00PM -0800, alltheseas wrote:
>Does it make sense to auto add the missing giphy.gif?

our image detection could be a lot more advanced. when pulling a link,
we could try to download it, or at least detect the image from the
Content-Type in the response from the server.

If we do download it, which I think would be a good idea, then we could
hash and blurhash it, get its dimensions, etc. Then we could store this
information in the metadata like we do for uploaded images. This makes
timelines less janky and improves loading on poor connections.

**Comment by alltheseas** [comment]
When you say download, is this some Damus service (is this what a CDN is?) or the local client?

**Comment by jb55** [comment]
client would download the image when you paste a link.

**Comment by alltheseas** [comment]
no longer an issue afaia
