### ISSUE TITLE
Multi image upload only uploads first image

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1923]
> another bug I noticed is that uploading multiple images only ever uploads the first image it is weird.

> Hello @jb55 , there is a bug after the latest Damus update 1.7 (2) via TestFlight. No matter which folder I select photos from, only the first selected photo is displayed, no matter which photos you subsequently select. Could you please forward this 🙏

https://damus.io/note1693gger9mt404x248g7hcmduwj402fxt5vpa859p2r85dakejkas6qexw3

**Comment by jb55** [comment]
Should be fixed in build 5

**Comment by alltheseas** [comment]
Tested - works fine on build 5
