### ISSUE TITLE
Notecrumbs damus.io broken formatting in Brave browser

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1925]
Brave 1.61.120
MacOS 13.6.3

https://damus.io/note1us8pgca6zgvufxramm07cukte4vhw06eu0jst6hud5tjecn3ehvqryhd0p
<img width="1154" alt="Screenshot 2024-01-26 at 10 14 04 AM" src="https://github.com/damus-io/damus/assets/64376233/06d118a1-2d46-4d16-8b6a-4e93b2076953">

**Comment by alltheseas** [comment]
Experienced the same on mobile brave browser.

However refreshing the page fixed the (lack of) wrap text formatting.

**Comment by jb55** [comment]
On Fri, Jan 26, 2024 at 12:58:28PM -0800, alltheseas wrote:
>Experienced the same on mobile brave browser.
>
>However refreshing the page fixed the (lack of) wrap text formatting.

oh interesting, I think I know what's wrong then. thanks for the tip.

**Comment by jb55** [comment]
maybe we should put these issues over at https://github.com/damus-io/notecrumbs instead ?

**Comment by alltheseas** [comment]
Agree. Didnt see there is a separate repo
