### ISSUE TITLE
Cannot post or react 1.7

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1928]
https://damus.io/nevent1qqsfd9chljussnf7k7kjmvfgmgrhr9y232pszjkdn9z6nuwtmxfq56cpz4mhxue69uhhyetvv9ujuerpd46hxtnfduhszxthwden5te0dehhxarj9enx2erfwejhyum99e48qtcprpmhxue69uhkummnw3ezu6r0d3ukyetp9e3k7mf0qy08wumn8ghj7mnjv4kxz7fddfczucedwd6x2mrvv9ezumn9wshsz8nhwden5te0dehhxarj9e3k7mtsd9kx2tt9wfex7u3wdejhgtcpy9mhxue69uhhyetvv9uj66ns9ehx7um5wgh8w6tjv4jxuet59e48qtcprdmhxue69uhkuun9d3shjtnr94ehgetvd3shytnwv46z7qgjwaehxw309aezu6m0df5hycfwd9hj7qg7waehxw309aex2mrp0yhxummnw3ezuamfwfjkgmn9wshx5up0qy0hwumn8ghj7mn0wd68yttjv4kxz7fwdehkkmm5v9ex7tnrdakj7qgwwaehxw309aukzcn49ekk2tcwvudhh

https://damus.io/nevent1qqsd9uzrzd88eq66yztwnfe69dzycfwnsf8nfc8xgxq39n6k6ea7fygpgdmhxw309ue8qcntwphxgansv4jkymr2vemx5ethxesh2ufkxdkxuer6wda8zmnww33hgdtpw9nx6ct6wdkx2un60pjnwdttv9jzummwd9hkuqgkwaehxw309aex2mrp0yhxummnw3ezucnpdejqzxthwden5te0wfjkccte9ehx7um5wf5kx6pwd3skueqprfmhxue69uhhyetvv9ujumn0wd68yurvv438xtnrdaksz8rhwden5te0dehhxarj9ekh2arfdeuhwctvd3jhgtnrdakszynhwden5te0danxvcmgv95kutnsw43qz8thwden5te0dehhxarj94c82c3wwajkcmr0wfjx2u3wdejhgqghwaehxw309ahx7um5wghxuct4wsh8xmmrd9skcqghwaehxw309ahx7um5wghxvmt59emkj73wvf5h5qgswaehxw309ahx7um5wgh8w6twv5qs7amnwvaz7tmwdaehgu3wd4hk6qgkwaehxw309aex2mrp0yhxummnw3ezu6twvehszxthwden5te0ddhx7um5wghxuet4w3exjmn99e3k7mgpp4mhxue69uhkummn9ekx7mqpzdmhxue69uhhyetvv9ukzcnvv5hx7un8qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdsq3jamnwvaz7tmsw4exzanfv3sjumn0wd68ytnvv9hxgqg6waehxw309aex2mrp0yhx7unpdenk2urfd3kzuer9wcq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qg4waehxw309ajkgetw9ehx7um5wghxcctwvsqkuamnwvaz7tmgw368que69uhkv6tvw3jhytnwdaehgu3wwa5kuef0dec82c33v948vdmdxvexkvrrwpnh56rpxve8zum6wd5rxvp5w96hx6nkwamk6ctkw4enqar5dd685mryd4eng7r6w4eh2en5wpcx50mzwfhkzerrv9ehg0t5wf6k2qgewaehxw309ahx7um5wgh8qmr9vf3ksctfdchx7un8ez2zqe

https://damus.io/nevent1qqs2y9zz94nt6kqrf42v9ruwqje78pvaadl5amxm3y8tdydjfj5654qpp4mhxue69uhkummn9ekx7mqpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3qamnwvaz7tmwdaehgu3wwa5kuegprpmhxw309akk7mnpvshx5c34x5hxxmmd8gurqwpsqy2hwumn8ghj7etyv4hzumn0wd68ytnvv9hxgqg4waehxw309aex2mrp0yhx6mmnw3ezuur4vg079m2j

**Comment by jb55** [comment]
this seems unlikely. maybe they are logged in with their npub ?

**Comment by alltheseas** [comment]
I just asked him to test for this

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/9bc1cfc1-9ac7-4cb6-81d6-363eddc55bcc)

**Comment by jb55** [comment]
I wonder if this is an account with no relays set? I can't think of anything else.

**Comment by alltheseas** [comment]
I see 4 and 11 relays on his two profiles

**Comment by jb55** [comment]
then without more details I can't really debug this

**Comment by alltheseas** [comment]
Appears fixed

![image](https://github.com/damus-io/damus/assets/64376233/e2f305e9-ff84-4f24-8f1f-6ad2259ea99b)
