### ISSUE TITLE
Link previews dont render

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1932]
_what happens_
Damus user expects to see link preview, and they do not see a preview

https://damus.io/nevent1qqsymynecsc75ky5aes7qcegj0sqaeux7vs2r0flzq0zhfdy399q6csprdmhxue69uhkummnw3ezuumhd9ehxtt9de5kwmtp9e3ksqgawaehxw309ahx7um5wgkhqatz9emk2mrvdaexgetj9ehx2aqpzpmhxue69uhnzdps9enrw73wd9hsz9nhwden5te0wfjkccte9ehx7um5wghxyctwvsq3camnwvaz7tmwdaehgu3wd46hg6tw09mkzmrvv46zucm0d5q3qamnwvaz7tmwdaehgu3wwa5kuegpr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq3samnwvaz7tmswf5hvct5v5h8yety9enkytnwv46qzynhwden5te0wp6hyurvv4cxzeewv4esz9thwden5te0wfjkccte9ejxzmt4wvhxjme0qy28wumn8ghj7un9d3shjctzd3jjummjvuhsz8rhwden5te0dehhxarj9e3xjarrda5kuetj9eek7cmfv9kqzxrhwden5te0wfjkccte9eek2mnywd68ytnrdakj7qgewaehxw309ac82unpwe5kgcfwdehhxarj9ekxzmnyqyd8wumn8ghj7un9d3shjtnwdaehgunfvd5x2uewdaexwqg5waehxw309ae8xtnwdaehgu3d0qhxxmmdqyf8wumn8ghj7mmxve3ksctfdch8qatzqyt8wumn8ghj7un9d3shjtnswf5k6ctv9ehx2aqpz4mhxue69uhhyetvv9ujumt0wd68ytnsw43qz8mhwden5te0dehhxarj94ex2mrp0yhxummtda6xzun09e3k7mf0qyvhwumn8ghj7mn0wd68ytn6v43x2er9v5hxxmr0w4jqzrthwden5te0dehhxtnvdakqz9rhwden5te0wfjkccte9ejxzmt4wvhxjmcpz4mhxue69uhk2er9dchxummnw3ezumrpdejqzxthwden5te0dehhxarj9e4k7mrvd9jx2u3w0puh5tcppemhxue69uhhxur0wfjjuamnqyv8wumn8ghj7un9d3shjtnwdaehgunfvdsjucm0d5q3gamnwvaz7tmwdaehgu3wdau8gu3wv3jhvqgcwaehxw309aex2mrp0yh8xmn0wf6zuum0vd5kzmqppemhxue69uhkummn9ekx7mp0qyghwumn8ghj7mn0wd68ytnhd9hx2tcpzdmhxue69uhhyetvv9ukzcnvv5hx7un8qythwumn8ghj7un9d3shjtnrw4e8yetwwshxv7tf5hsyeu

![image](https://github.com/damus-io/damus/assets/64376233/5adb47b3-68e1-4985-a135-20877d4809a1)

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqs04yqple39exnmlf3jx6sedkfvckcx5j4x5g6ptc24pm3gu64vl0gpzpmhxue69uhkummnw3ezuamfdejsz9thwden5te0v4jx2m3wdehhxarj9ekxzmnyqyw8wumn8ghj7mn0wd68ytndw46xjmnewaskcmr9wshxxmmdqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hszrthwden5te0dehhxtnvdakqz9thwden5te0wfjkccte9ekk7um5wgh8qatzq9n8wumn8ghj7enfd36x2u3wdehhxarj9emkjmn99ah8qatzx9e85eeexeax5ctkvashgumcx43ksvnkwe68zdrpw3shgmrex4e8verhw9nk5upsw468sae5x4ax27nwweuhzenyddu8veflvfex7ctyvdshxapaw3e82egmn8hhx

![image](https://github.com/damus-io/damus/assets/64376233/1ebe6ec0-823a-40fb-a686-6fdbfc6d0f58)

https://damus.io/note1l2gqrlnztjd8h7nryd4pjmvje3dsdf92dg35zhs42rhz3e42e77s5t8ce9

**Comment by alltheseas** [comment]
Recreated ![image](https://github.com/damus-io/damus/assets/64376233/1e7c64aa-46dd-4d91-8a43-75664cf8e470)

**Comment by jb55** [comment]
On Sat, Jan 27, 2024 at 06:14:43PM -0800, alltheseas wrote:
>Recreated ![image](https://github.com/damus-io/damus/assets/64376233/1e7c64aa-46dd-4d91-8a43-75664cf8e470)

definitely looks like a regression. will bisect.
