### ISSUE TITLE
Add note: "Purple only available for Testflight users. Warning: testing in production"

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1937]
@jb55 
@danieldaquino

**Comment by danieldaquino** [comment]
@alltheseas, would this be placed on the website checkout page? _(Makes sense to me)_

Or did you have some other place in mind?

**Comment by alltheseas** [comment]
I would place it both in checkout, and somewhere on the purple landing page as well 🙏

**Comment by jb55** [comment]
On Mon, Jan 29, 2024 at 10:56:40AM -0800, Daniel D’Aquino wrote:
>@alltheseas, would this be placed on the website checkout page? _(Makes sense to me)_
>
>Or did you have some other place in mind?

yeah needs to be on checkout page for now

**Comment by jb55** [comment]
On Mon, Jan 29, 2024 at 11:01:57AM -0800, William Casarin wrote:
>On Mon, Jan 29, 2024 at 10:56:40AM -0800, Daniel D’Aquino wrote:
>>@alltheseas, would this be placed on the website checkout page? _(Makes sense to me)_
>>
>>Or did you have some other place in mind?
>
>yeah needs to be on checkout page for now

we should also have a testflight link probably?

**Comment by danieldaquino** [comment]
@alltheseas @jb55, how about these messages?

![Screenshot 2024-01-30 at 14 06 32](https://github.com/damus-io/damus/assets/24692108/9227da2f-4fbf-4ec3-9fe7-91a9899abf95)
![Screenshot 2024-01-30 at 14 06 52](https://github.com/damus-io/damus/assets/24692108/8a4b06ee-7d72-40d1-a2e5-8ecdabab174d)

**Comment by alltheseas** [comment]
Where does contact us lead?

**Comment by danieldaquino** [comment]
On Tue, Jan 30, 2024 at 14:32, alltheseas ***@***.***(mailto:On Tue, Jan 30, 2024 at 14:32, alltheseas <<a href=)> wrote:

> Where does contact us lead?

***@***.***

(support “at” damus.io)

**Comment by alltheseas** [comment]
Sounds good. Does Vanessa have access to this email @jb55

**Comment by jb55** [comment]
yes, its a group
