### ISSUE TITLE
cannot save profile edit 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1943]
caused solely by Damus

https://damus.io/nevent1qqsrnv62vkj6rsk0xhljuv2zm7pusqpwv5wnx92wmx8jzzrfzg2uhyspz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3kamnwvaz7tmjv4kxz7fwdaexzmn8v4cxjmrv9ejx2a30qyxhwumn8ghj7mn0wvhxcmmvqyt8wumn8ghj7un9d3shjtnswf5k6ctv9ehx2aqpr3mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mgprpmhxue69uhhyetvv9ujuumwdae8gtnnda3kjctv4c3j8c

https://damus.io/nevent1qqs0xxrhzxayegdtr0eh23kxze37dfr4ww8euvazhvrgcngt9y73k4gpr3mhxue69uhkummnw3ezuumgv9mku7t9v9nk2u3wdejhgtcpr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qg4waehxw309ajkgetw9ehx7um5wghxcctwvsq3camnwvaz7tmjv4kxz7fwvf5hgcm0d9h8qctjdvhxxmmd9uq3vamnwvaz7tmndpshwm3wdehhxarjxyhxxmmdqyg8wumn8ghj7mn0wd68ytnhd9hx2qgcwaehxw309anxjmr5v4ezumn0wd68ytnhd9hx2tcpp4mhxue69uhkummn9ekx7mqpr4mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mf0l9t2xx

**Comment by alltheseas** [comment]
https://github.com/nostrability/nostrability/issues/12

**Comment by jb55** [comment]
On Tue, Jan 30, 2024 at 05:19:25AM -0800, alltheseas wrote:
>Unclear if caused solely by Damus

it is solely damus

**Comment by alltheseas** [comment]
Recreated on my profile, which I can no longer appear to edit.

**Comment by alltheseas** [comment]
updated profile not visible from self POV. Updated profile is visible from other profile POV.

https://damus.io/nevent1qqsypwl38eezclsuxqfjkck92rracjjjyrl23rqzycvf3f7myetu0pspr3mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mgpz3mhxue69uhhyetvv9ujuerpd46hxtnfduqs6amnwvaz7tmwdaejumr0dsq3samnwvaz7tmjv4kxz7fwwdhx7un59eek7cmfv9kq06e5z3

**Comment by alltheseas** [comment]
@fishcakeday suggests nostrdb issue

**Comment by alltheseas** [comment]
Cannot save PFP change

https://damus.io/nevent1qqsrglv8a64ukn2syjek4jyrm29rq5splpkru3a3x7774rufw2cnxkgpramhxue69uhkummnw3ez6un9d3shjtnwda4k7arpwfhjucm0d5hsz9thwden5te0v4jx2m3wdehhxarj9ekxzmnyqyt8wumn8ghj7ct5d3shxtnwdaehgu3wd3skueqprdmhxue69uhhyetvv9ujumn0wd68yurvv438xtnrdakj7ze6w7u
