### ISSUE TITLE
Notes loading on startup screen take too long 1.7

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1947]
_what happens_

Post 1.7 nostrdb update it takes longer for notes to load on initial Damus timeline screen.

> Can you tell me why this is the typical landing page for Notes, and Notes and Replies?  I have to go to Universal timeline to see the Nostr feed of old. I have 11 relays, and wouldn’t know which ones to disconnect in order to improve the timeline loading properly.   

![image](https://github.com/damus-io/damus/assets/64376233/e985d04d-1692-4eb4-b771-eae9e5b3fd97)

> It should load instantly, something else is wrong

https://damus.io/nevent1qqsf2qhltqa8ke4a5t4gajcvp0rsyaqvsuxvnzlyfq0sazc7dgsv7dcpzpmhxue69uhkummnw3ezuamfdejszrthwden5te0dehhxtnvdakqzymhwden5te0wfjkcctev93xcefwdaexwqg4waehxw309ajkgetw9ehx7um5wghxcctwvsq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qghwaehxw309aex2mrp0yhxxatjwfjkuapwveukjyefgcm

**Comment by jb55** [comment]
On Tue, Jan 30, 2024 at 07:20:34AM -0800, alltheseas wrote:
>Post 1.7 nostrdb update it takes longer for notes to load on initial Damus timeline screen.

citation needed

**Comment by alltheseas** [comment]
https://damus.io/note1j5p07kp60dntmgh23m9scz78qf6qepcvex97gjqlp693u63qeumselyunn

**Comment by alltheseas** [comment]
Just followed up with bug reporter if this is fixed on latest build

**Comment by alltheseas** [comment]
I experience this problem on iOS 18 damus 1.10

**Comment by alltheseas** [comment]
This seems to have been fixed on

1.10.1 (1) f92509fd
