### ISSUE TITLE
IAP Purple: Polish subscription mechanism so that it registers with the server immediately after subscribing (without having to restart the app

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1948]

**Comment by danieldaquino** [comment]
Good news, I just realized that I already implemented a fix for this and made sure it works during https://github.com/damus-io/damus/issues/1815

More specifically, this was fix on this commit: https://github.com/damus-io/damus/commit/4a4a58c7b57b972b2a45f39a559b93df833e582e

Closing
