### ISSUE TITLE
Investigate flow: open purple on website, and scan QR with phone

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1949]
@danieldaquino have you tested this flow?

This is what I did when testing purple subscription

**Comment by danieldaquino** [comment]
@alltheseas, following up on this, I believe the problem you were facing is that the Damus version you were running did not have the address of the staging or production server yet

However, I can imagine some people running a slightly older Testflight version might end up in a similar situation if they tried. If someone reports a similar issue after the release, the fix will most likely be to ask them to upgrade the Damus TestFlight version
