### ISSUE TITLE
Dont filter my own media

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1955]
![image](https://github.com/damus-io/damus/assets/64376233/0c1f830e-d36e-47ff-b960-f8f7f50c01b5)

**Comment by jb55** [comment]
isn't this option for reducing bandwidth? It's not for filtering other people's stuff.

**Comment by alltheseas** [comment]
> isn't this option for reducing bandwidth? It's not for filtering other people's stuff.

Fair.

I looked through the lens of reducing nsfw images.
