### ISSUE TITLE
Purple: dont translate when not foreign language

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1959]
https://t.me/damusdev/6708

Translation apostrophe hell

cc @tyiu 

![image](https://github.com/damus-io/damus/assets/64376233/c406b87c-a25c-4f68-9dcc-3d942e345e1c)

**Comment by kernelkind** [comment]
I don't think there's much we can do about this particular issue. `NLLanguageRecognizer` predicts that the language is `nl` incorrectly. For more perspective, I changed the max hypotheses to 3:
```
([NLLanguage : Double]) 3 key/value pairs {
  [0] = {
    key = 0x00000001ec8c41d8 "nl"
    value = 0.61679202318191528
  }
  [1] = {
    key = 0x00000001ec8c41f8 "en"
    value = 0.19107812643051147
  }
  [2] = {
    key = 0x00000001ec8c45f8 "sk"
    value = 0.029981246218085289
  }
}
```

This occurs in `NdbNote.noteLanguage(...)`

**Comment by tyiu** [comment]
The note in the screenshot can be found at https://damus.io/nevent1qqsqd6u3n3vn8r3lah98cynf50lj79l3s35u0ef4fjkk3h5z869lr6qpr9mhxue69uhhqatjv9mxjerp9ehx7um5wghxcctwvsqjrc4v5ss8wumn8ghj7mn0wd68yttsw43zuam9d3kx7unyv4ezumn9wsqkvamnwvaz7tmxd9k8getj9ehx7um5wgh8w6twv5hkuur4vgchyarvw93kzwrjxesh27tpwu6kudtgxdkr2dpjxfjx6drnwfun2er6vejk2dpk8ymxvut98penvut8w4jxkuehv348genn8a38ymmpv33kzum58468yat9qyg8wumn8ghj7mn0wd68ytnhd9hx2ts9q3j

**Comment by kernelkind** [comment]
Should be closed by https://github.com/damus-io/damus/commit/58326f679e3fb5b19c0bce667bdc7ea75066813a

**Comment by alltheseas** [comment]
> Should be closed by https://github.com/damus-io/damus/commit/58326f679e3fb5b19c0bce667bdc7ea75066813a

Is this merged in Testflight yet? Let's keep open until merged in latest Testflight

**Comment by alltheseas** [comment]
@semisol does your service fix this?

cc @jb55
