### ISSUE TITLE
YouTube preview failed to display

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#1977]
In the following note:

note1spf3tl8rdrls6d9wfmgh374zn88e4cpuefnyph26f6a90czqg6psvawl0w

The YouTube preview did not display for me on Damus. I can still see it on other clients, however.

Damus:
![IMG_2B5D634E7F23-1](https://github.com/damus-io/damus/assets/3638467/d9324e03-23b7-4b06-b8c0-f7d548ceb4a6)

Primal:
![IMG_C80C78E79025-1](https://github.com/damus-io/damus/assets/3638467/c9ec6d32-be1e-4f11-9e56-530066378a63)

**Comment by jb55** [comment]
are you on build 9 ?

**Comment by alltheseas** [comment]
@dmnyc can you send a screenshot of your appearance > images settings

**Comment by dmnyc** [comment]
![IMG_5E27091E9C96-1](https://github.com/damus-io/damus/assets/3638467/ec361a70-2e2a-4b32-9172-f281e0c22d8e)

**Comment by dmnyc** [comment]
> are you on build 9 ?

I was on build 8. Just updated to 9 and I can see it correctly. Thanks.
![IMG_9517AA135017-1](https://github.com/damus-io/damus/assets/3638467/031b2cd4-ac69-43bc-8b26-33cccae96ae4)
