### ISSUE TITLE
other profiles npub and PFP disappear

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1982]
_what happens_

PFP, and npub disappear from profiles I already follow. Sometimes this fixes on its' own. Unclear what causes this (could be nostrdb).

![image](https://github.com/damus-io/damus/assets/64376233/db4be04b-cb32-4cdb-86de-b7757bff54c0)

https://damus.io/nevent1qqs9jd570jmc9cjuwtr8wqlfjqunl2ltau0pzlr27tpuyprtxkffxtgstst0g

**Comment by alltheseas** [comment]
Two people confirmed that restarting Damus fixes missing profile info.

**Comment by jb55** [comment]
this is related to opening and closing of nostrdb. I have noticed a few occasions where it remains closed, not sure why yet.

**Comment by alltheseas** [comment]
remains an open issue in 1.7 build 11

https://damus.io/nevent1qqsp6mea0kms34p3ufrjtesyactmqh2clnnhh5suk7k0jld6crp3dlqpz3mhxue69uhkummnw3ezummcw3ezuer9wcqs7amnwvaz7tmwdaehgu3wd4hk6qgewaehxw309ac82unpwe5kgcfwdehhxarj9ekxzmnyqy28wumn8ghj7un9d3shjtnwdaehgu3wvfnsuhxjq9

**Comment by jb55** [comment]
On Tue, Feb 13, 2024 at 09:10:55AM -0800, alltheseas wrote:
> remains an open issue in 1.7 build 11
>
>https://damus.io/nevent1qqsp6mea0kms34p3ufrjtesyactmqh2clnnhh5suk7k0jld6crp3dlqpz3mhxue69uhkummnw3ezummcw3ezuer9wcqs7amnwvaz7tmwdaehgu3wd4hk6qgewaehxw309ac82unpwe5kgcfwdehhxarj9ekxzmnyqy28wumn8ghj7un9d3shjtnwdaehgu3wvfnsuhxjq9

If you want to more accurately define this issue:

Damus is now in a shared data container with the notification extension,
and you can't hold file locks on shared containers, so we have to close
nostrdb when putting damus into the background. When damus comes into
the foreground, we have to re-open nostrdb. If the UI renders before
nostrdb has re-opened, then the transaction will fail and the profile
will fail to render.

I'm not sure how to fix this yet, we need some way to block the main
thread until nostrdb is finished opening.

**Comment by alltheseas** [comment]
Does this we should start benchmarking nostrdb load times, to measure changes against?

**Comment by jb55** [comment]
On Tue, Feb 13, 2024 at 12:15:33PM -0800, alltheseas wrote:
>Does this we should start benchmarking nostrdb load times, to measure changes against?

Not really, nostrdb load time should be in the nanosecond range since it
just spawns some threads and mmap's the database. We just need to figure
out how to ensure that it loads before swiftui does any rendering.
