### ISSUE TITLE
Change server to use `listinvoices` instead of `waitinvoice` RPC command

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1983]
use invoice command (as opposed to wait invoice)
doesn't hold open

**Comment by jb55** [comment]
listinvoices

args: {"invstring": "invstring=bolt11"}
results: { invoices: [] }

should return 1 result with the invoice with the status set to `paid`,
otherwise the status will be `expired` or `unpaid`.

**Comment by danieldaquino** [comment]
> listinvoices args: {"invstring": "invstring=bolt11"} results: { invoices: [] } should return 1 result with the invoice with the status set to `paid`, otherwise the status will be `expired` or `unpaid`.

Thank you @jb55 for this. I tried implementing changes to use `listinvoices` earlier today (It was also relevant to some of the LN flow hardening work), but it seems that the LN rune of `ln.damus.io` only allows `invoice` and `waitinvoice`. Can you please double-check the LN node configuration?

**Comment by alltheseas** [comment]
lower in priority than most other 1.7 purple items, as apple permission not required.

@danieldaquino : change wait invoice to list invoice.

Also make this CoreLN plugin. 

Add:

- [ ] CLN plugin to notify server once invoice is paid.

**Comment by alltheseas** [comment]
How to test on production:

see invoice, and simulate payment.

Doesn't have to be plugin. Can be script. Whenever invoices is seen (waitanyinvoice). Only works for paid invoices, unclear if can be tested without a paid invoice. 

dda: Can this script be run on server?
w: can be one msat (less than sat)

@jb55 to provide @danieldaquino code in theory to test how sats are seen on server

**Comment by danieldaquino** [comment]
Found a tool that might help with Lightning network testing: https://github.com/scaling-lightning/scaling-lightning

**Comment by danieldaquino** [comment]
(https://github.com/damus-io/damus/issues/2035)

**Comment by jb55** [comment]
On Wed, Mar 06, 2024 at 11:25:54AM -0800, Daniel D’Aquino wrote:
>Found a tool that might help with Lightning network testing: https://github.com/scaling-lightning/scaling-lightning

Testing the lightning network is way out of the scope of anything we will be doing 

This ticket is more of an issue with proxying lightning over websockets,
there must be a subtle websocket bug in some browsers or something.

**Comment by jb55** [comment]
Closing because I forget if this is still an issue
