### ISSUE TITLE
Update Purple website to include supported languages (via DeepL)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1989]
For instance, Thai language is not supported

https://support.deepl.com/hc/en-us/articles/360019925219-Languages-included-in-DeepL-Pro

**Comment by alltheseas** [comment]
WEbsite lower priority than IAP/Apple permmissioned items

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, sent [a patch](https://groups.google.com/a/damus.io/g/patches/c/E6ejN2b_LBE) for this one! I summarized the info from DeepL to avoid verbosity.

Here is how it looks like:

<img width="1199" alt="Screenshot 2024-03-06 at 16 18 58" src="https://github.com/damus-io/damus/assets/24692108/30d0439a-e424-4026-8572-b71b82a16e00">

Please let me know if any changes are needed. Thank you!
