### ISSUE TITLE
subscribe to thread / conversation and be notified of every new message in that specific conversation

### ISSUE THREAD

**Issue by bitcoinuser** [damus-io/damus#199]
Hi,

Contrary to this feature request https://github.com/damus-io/damus/issues/128  I would like too see an option to subscribe to a conversation and be notified of every new message in that specific conversation. 
Many times I find an interesting post that I would like to follow the conversation, but I don't see an option to be notified of all messages people replied in that specific conversation.
Obs. I would like to subscribe to be notified, but without be necessary to post anything in the conversation that I intend to follow.

**Comment by olheadinternet** [comment]
similar too https://github.com/damus-io/damus/issues/144

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqstp70yylf8svd86ruyphn9ltymdz26lafrnc5f3dmkd3fvxe0g49cprfmhxue69uhhyetvv9ujumn0wd68y6trdpjhxtn0wfnszymhwden5te0wfjkcctev93xcefwdaexwqgkwaehxw309aex2mrp0yhxummnw3ezucnpdejqzyrhwden5te0dehhxarj9emkjmn9qydhwumn8ghj7un9d3shjtn0wfskuem9wp5kcmpwv3jhvtcpzamhxue69uhkv6tvw3jhytnwdaehgu3wwa5kuegpz4mhxue69uhk2er9dchxummnw3ezumrpdejqzxthwden5te0dehhxarj9ecxcetzvd5xz6tw9ehhyecprpmhxue69uhhwetvvdhk6efwdehhxarj9emkjmn9qyv8wumn8ghj7un9d3shjtnwdaehgunpw35jucm0d5q3wamnwvaz7tmrwfjkzarj9ehx7um5wgh8w6twv5qkvamnwvaz7tmxd9k8getj9ehx7um5wgh8w6twv5hkuur4vgcngut68ye82etywscxzwr2w3jns6n3vumrx6njxden2cmr8yukxet2xvmx56pc8qeh5dn5wpexcafnx5682ut3v5e8zv3k8a38ymmpv33kzum58468yat9qyvhwumn8ghj7mn0wd68ytn5dpjhxctdv43kzapwd9hszxmhwden5te0wfjkccte9ehx7um5wfcxcetzwvhxxmmd9uq5xamn8ghj7vnsvf4hqmnywecx2etzd34xvan2v4mnvct4wymrxmrwv3a8x7n3deh8gcm5x4shzendv9a8xmr9wfa8sefhx44kzepwdahxjmmwqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hszrthwden5te0dehhxtnvdakqzyrhwden5te0xy6rqtnxxaazu6t02fxwez

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqsxcys8gt9ykq8ae532kxn6seckqgqmrxf5cg0glcamrmwh273qxmqpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqg5waehxw309aex2mrp0yhxgctdw4eju6t0qyv8wumn8ghj7am9d33k7mt99ehx7um5wgh8w6twv5q3qamnwvaz7tmwdaehgu3wwa5kueglsmkjk

**Comment by alltheseas** [comment]
-subscribe to thread could take place under ellipsis menu
-where are all subscribed/followed notes listed?

**Comment by jb55** [comment]
to be added with:

- #1419
