### ISSUE TITLE
Failed transaction flow (f/k/a IAP payment flow hardening)

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1992]
**Items to improve robustness of the IAP payment flow:**

- [x] Test sending expired or invalid Apple IAP receipts to the server to ensure it rejects
- [x] Test renewal behavior
- [x] Test mixing IAP purchases with LN purchases
- [x] Test sending a receipt reserved to a different account to the server
- [x] Failed transaction flow

**Comment by danieldaquino** [comment]
## Renewal behavior manual test

**PASS**

**Device:** iPhone 13 Mini (physical device)
**iOS:** 17.3
**Damus:** `ffc9441f9837743720046b19139e9188b1e7e637` (An unpublished version which is equivalent to `da82663634ae269776b0778be399abd29e650c1d`)
**damus-api:** `9194e63f0c8525da3330d2896ee48caf0b68b686` (Unpublished version, will send in a few minutes)
**Setup:**
- Sandbox account with Purple IAP purchase already setup
- Connected to local server (but using a copy of staging db, since that has my sandbox purchase info and it's a PITA to reset the IAP sandbox)
- Sandbox test renewal rate set to 5 minutes (meaning, it's a "5-minute" subscription, the expiry is 5 minutes into the future, and it auto-renews every 5 minutes)
- Real IAP receipt verification setup (i.e. NO `MOCK_VERIFY`)

**Steps:**
1. Open app
2. Observe server logs. Make sure I see a call to `/accounts/.../apple-iap/app-store-receipt` with status code HTTP 200. PASS
2. Should show the account screen, with expiry date set to today (because it only lasts 5 minutes). PASS
3. Leave the app open for more than 5 minutes and monitor server logs. 
4. After about 5 minutes you should see another call to `/accounts/.../apple-iap/app-store-receipt` with HTTP response 200. PASS
5. Go to the purple screen again. Should show the account screen, account ACTIVE, with expiry date set to today. PASS
6. Close the app for more than 5 minutes.
7. Reopen app.
8. You should see another call to `/accounts/.../apple-iap/app-store-receipt` with HTTP response 200 on the server. PASS
9. Go to the purple screen again. Should show the account screen, account ACTIVE, with expiry date set to today. PASS
10. Click on manage
11. Cancel subscription.
12. Should still be active (not expire immediately). PASS
12. Close app and wait for another 5 minutes
13. Reopen, go to the purple screen. Should show the account is EXPIRED. PASS

CC @jb55 @alltheseas, I want to automate this test if I have time, but regardless I am documenting my manual test on it since this functionality is very important

**Comment by danieldaquino** [comment]
@jb55 @alltheseas, I sent a patchset of various hardening changes for review (https://groups.google.com/a/damus.io/g/patches/c/sfueT4ztGjA)

There are still more on the works! I will send more once I have them ready.

**Comment by danieldaquino** [comment]
Patch sent for more debug and testing tooling: https://groups.google.com/a/damus.io/g/patches/c/9LBS5KLelZ0

**Comment by alltheseas** [comment]
Deferring 
- [ ] "Ask to buy" flow
- [ ] Test issuing two StoreKit purchase actions one after the other (to verify StoreKit purchases are idempotent)
- [ ] Test refund flows

**Comment by danieldaquino** [comment]
Tested failed transactions. It works in the same way as a user who unsubscribed. They will basically have Damus Purple until their next billing cycle and then they become expired. Apple handles the showing of the message that indicates a billing problem.
