### ISSUE TITLE
Cache Apple root certificates

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#1999]
From a patch discussion

> ```diff
> +/**
> + * Reads all certificate files from a directory.
> + *
> + * @param {string} directory - The directory containing certificate files.
> + * @returns {Buffer[]} An array of certificate file contents.
> + */
> +function readCertificateFiles(directory) {
> +    const files = fs.readdirSync(directory);
> +    return files.map((fileName) => fs.readFileSync(`${directory}/${fileName}`));
> +}
> ```
> 
> Calling readFileSync can block the nodejs eventloop and reduce the
> overall performance of the api server. Ideally we would only do this
> once and cache it in memory, otherwise switch them to async read calls.
>
> No need to resend this series, we can make it a follow-up commit.

**Comment by alltheseas** [comment]
Is this required for IAP or push notifications?

**Comment by danieldaquino** [comment]
> Is this required for IAP or push notifications?

For IAP

I have a draft that should address this, I will send it in my next patch series
