### ISSUE TITLE
My home page is empty

### ISSUE THREAD

**Issue by Piste** [damus-io/damus#2]
iOS 15.5, damus 0.1.1 (1)
Signed in with private hex key
I can see my posts in the search tab

**Comment by jb55** [comment]
can you post your pubkey? it's possible your contact list and profile is on another relay that damus doesn't know about.

**Comment by Piste** [comment]
> can you post your pubkey? it's possible your contact list and profile is on another relay that damus doesn't know about.

d789ef9cf20920c8a26492face6bb787896a6ebc10fb96c6d42d61b11a0f7b91

**Comment by Piste** [comment]
I've not had this issue again. Closing.
