### ISSUE TITLE
Missing emoji reaction selections in modal

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#2005]
Bug observed:

When trying to use emoji reactions, usually the last one or two in the list fail to load after scrolling several times to the end of the list. This is not new to the latest build but has been happening for a while. 

Screenshots below. 
![image](https://github.com/damus-io/damus/assets/3638467/0875bd91-5486-4d40-92f0-454de3decdbb)
![image](https://github.com/damus-io/damus/assets/3638467/ad10220c-4b01-4e7d-a378-f4c41f21514d)

**Comment by alltheseas** [comment]
@suhailsaqan

**Comment by alltheseas** [comment]
#2204 should fix this?

cc @tyiu @danieldaquino @jb55
