### ISSUE TITLE
Space breaks mention suggestion menu

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2008]
![image](https://github.com/damus-io/damus/assets/64376233/8ca05271-232f-4465-9766-ecd286970653)

![image](https://github.com/damus-io/damus/assets/64376233/88208ef3-9a8b-4f09-bedc-1a6f7da5eb5e)

@kernelkind

**Comment by kernelkind** [comment]
https://github.com/damus-io/damus/issues/1721#issuecomment-1880373326

This is intended

**Comment by jb55** [comment]
On Fri, Feb 16, 2024 at 11:37:05AM -0800, kernelkind wrote:
>https://github.com/damus-io/damus/issues/1721#issuecomment-1880373326
>
>This is intended

There's been times where I've wanted this. Maybe we should support it
somehow, like an explicit suggestion-close interaction.

**Comment by kernelkind** [comment]
https://github.com/damus-io/damus/blob/ab529c43eb296437d96e70844451e03e1bd0f14b/damus/Views/TextViewWrapper.swift#L151

we could remove the space here and add a button to the `UserSearch` view to dismiss it if it's not relevant

**Comment by alltheseas** [comment]
Two spaces to exit?

**Comment by alltheseas** [comment]
@jb55 you good with two spaces to exit solution?

**Comment by jb55** [comment]
that makes sense to me

**Comment by alltheseas** [comment]
@kernelkind you got this one?

**Comment by kernelkind** [comment]
It's not as trivial as comparing the last two characters of 'text' to "  " in `TextViewWrapper` like I thought it might because when the user is typing, the selected range is one char so text and lastChar end up being the same.

I'm not spending much time on iOS anymore, so I won't be working on this issue

**Comment by alltheseas** [comment]
@seankibler you up for this one ser 👀

**Comment by seankibler** [comment]
Yeah, I'll have a go at it.

**Comment by danieldaquino** [comment]
Sent a PR! https://github.com/damus-io/damus/pull/2385

@jb55 @alltheseas Please let me know if you have any questions or concerns!

**Comment by alltheseas** [comment]
Thank you - this one has been a thorn in the backside for quite a while. It is noticed by many end users.
