### ISSUE TITLE
Purple: resubscribe flow is currently not considered, and can be confusing

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2013]
### what happens

As a current Damus purple subscriber, it's not clear when attempting to add time to my Damus purple subscription:

1) you have an existing purple subscription
2) you are adding time to existing purple subscription

### implementation discussion / possibilities

> dont take to blank check out page
> take to check out page related to their existing purple account

### related to 

notification of impending purple expiration https://github.com/damus-io/damus/issues/1973

###

time sensitive - ideally done before expiry of the first month

**Comment by danieldaquino** [comment]
Made changes on the iOS side to support this, pushed them to this branch: https://github.com/damus-io/damus/commits/v1.7-madeira-release/

I will also need to make some changes on the checkout page on the website to accompany it (this is still to be done)

**Comment by danieldaquino** [comment]
Sent patches! https://groups.google.com/a/damus.io/g/patches/c/NZZVvGZ346Q

**Some screenshots of the renewal flow on mobile:**
![screenshots-purple-website](https://github.com/damus-io/damus/assets/24692108/88c88907-f998-4de6-b45f-533a00d60482)

In the end, when they are taken to the app, they see a sheet with their account info to further confirm successful renewal

**Note:** The yellow robohash belongs to a test account, it's not a loading error

**More screenshots (on desktop):**
![Screenshot 2024-03-01 at 19 12 35](https://github.com/damus-io/damus/assets/24692108/9444f3d8-03d5-4499-8845-0d4f2548a2e8)
![Screenshot 2024-03-01 at 19 12 47](https://github.com/damus-io/damus/assets/24692108/3c7b28cd-b80a-442e-aa8e-f40eb04cb1a7)
![Screenshot 2024-03-01 at 19 13 30](https://github.com/damus-io/damus/assets/24692108/44dbd003-9ebb-4aea-bcc4-11ce12e0ec88)
![Screenshot 2024-03-01 at 19 14 17](https://github.com/damus-io/damus/assets/24692108/e00475a7-9120-4089-b517-50fd3431a678)

cc @jb55 @alltheseas please let me know if any changes are needed!

**Comment by jb55** [comment]
On Fri, Mar 01, 2024 at 07:31:20PM -0800, Daniel D’Aquino wrote:
>Sent patches! https://groups.google.com/a/damus.io/g/patches/c/NZZVvGZ346Q
>
>**Some screenshots of the renewal flow on mobile:**
>![screenshots-purple-website](https://github.com/damus-io/damus/assets/24692108/88c88907-f998-4de6-b45f-533a00d60482)
>
>In the end, when they are taken to the app, they see a sheet with their
>account info to further confirm successful renewal

looks good! it's live now

**Comment by danieldaquino** [comment]
iOS changes were merged into the release and master branches
Website changes were pushed into the release made and published to production and staging.

@jb55, can I merge the release branch on the website repo into the master branch?

**Comment by jb55** [comment]
On Wed, Mar 06, 2024 at 10:09:53AM -0800, Daniel D’Aquino wrote:
>iOS changes were merged into the release and master branches
>Website changes were pushed into the release made and published to production and staging.
>
>@jb55, can I merge the release branch on the website repo into the master branch?

I didn't even know we had different branches on the website repo

**Comment by jb55** [comment]
On Thu, Mar 07, 2024 at 02:10:02AM -0800, William Casarin wrote:
>On Wed, Mar 06, 2024 at 10:09:53AM -0800, Daniel D’Aquino wrote:
>>iOS changes were merged into the release and master branches
>>Website changes were pushed into the release made and published to production and staging.
>>
>>@jb55, can I merge the release branch on the website repo into the master branch?
>
>I didn't even know we had different branches on the website repo

I merged the language info with the release branch and pushed to prod!

**Comment by danieldaquino** [comment]
> On Mar 11, 2024, at 07:18, William Casarin ***@***.***> wrote:
>
> On Thu, Mar 07, 2024 at 02:10:02AM -0800, William Casarin wrote:
>>On Wed, Mar 06, 2024 at 10:09:53AM -0800, Daniel D’Aquino wrote:
>>>iOS changes were merged into the release and master branches
>>>Website changes were pushed into the release made and published to production and staging.
>>>
>>>@jb55, can I merge the release branch on the website repo into the master branch?
>>
>>I didn't even know we had different branches on the website repo
>
> I merged the language info with the release branch and pushed to prod!

Thank you for this. Has this merge been pushed to the Github repo? On Github I see `master` being 1 commit ahead and 4 commits behind `release_madeira_2024_03`, and master does not yet seem to include changes that were on the release branch.

https://github.com/damus-io/website/branches
[website.png]

[Branches · damus-io/website](https://github.com/damus-io/website/branches)
[github.com](https://github.com/damus-io/website/branches)

**Comment by jb55** [comment]
On Tue, Mar 12, 2024 at 01:50:23AM -0700, William Casarin wrote:
>On Mon, Mar 11, 2024 at 07:10:50AM -0700, Daniel D’Aquino wrote:
>>> On Mar 11, 2024, at 07:18, William Casarin ***@***.***> wrote:
>>>
>>> On Thu, Mar 07, 2024 at 02:10:02AM -0800, William Casarin wrote:
>>>>On Wed, Mar 06, 2024 at 10:09:53AM -0800, Daniel D’Aquino wrote:
>>>>>iOS changes were merged into the release and master branches
>>>>>Website changes were pushed into the release made and published to production and staging.
>>>>>
>>>>>@jb55, can I merge the release branch on the website repo into the master branch?
>>>>
>>>>I didn't even know we had different branches on the website repo
>>>
>>> I merged the language info with the release branch and pushed to prod!
>>
>>Thank you for this. Has this merge been pushed to the Github repo? On Github I see `master` being 1 commit ahead and 4 commits behind `release_madeira_2024_03`, and master does not yet seem to include changes that were on the release branch.
>
>I just realized I merged a different branch that was out of sync, but
>that wasn't the release branch.

I actually did push it, but just to git.jb55.com instead of github. fixed now.
