### ISSUE TITLE
Missing reply

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2022]
https://damus.io/nevent1qqswwwpuw98u5yal6pan6wdqmvk2xteumpdnr2k0xpcrhs9zxe78ghspz9mhxue69uhkummnw3ezuamfdejj7qgewaehxw309amk2mrrdakk2tnwdaehgu3wwa5kuef0qy2hwumn8ghj7un9d3shjtnyv9kh2uewd9hj7qgawaehxw309ahx7um5wghx6at5d9h8jampd3kx2apwvdhk6tchkd7rj

**Comment by alltheseas** [comment]
Related to https://github.com/nostrability/nostrability/issues/20

Usually preceding replies are missing. However, in this report a subsequent reply is missing.

**Comment by alltheseas** [comment]
missing reply on damus post primal nip-10 update

Cc @tyiu 

![image](https://github.com/damus-io/damus/assets/64376233/676e9a9c-4db9-4c0d-9eaa-aadc23071096)

![image](https://github.com/damus-io/damus/assets/64376233/925a6b74-d788-435d-b342-5ea8b281e77c)

note12gwfjjw59xw2qu752dz03xkd8rp5a3h4c7h0w58cgm2g0ghcy0us6f7hkc

https://damus.io/nevent1qqsz9zagz4w0hd0z85scqupf8s36gg68yxfam3dz84sku9md929t3cgpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq32amnwvaz7tmwdaehgu3wd45kcmm49ekx7mqpr9mhxue69uhhyetvv9ujuam9d3kx7unyv4ezumn9wsq3vamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny009xfz

**Comment by jb55** [comment]
On Mon, May 06, 2024 at 01:02:45PM GMT, alltheseas wrote:
>missing reply on damus post primal nip-10 update
>
>Cc @tyiu
>
>![image](https://github.com/damus-io/damus/assets/64376233/676e9a9c-4db9-4c0d-9eaa-aadc23071096)
>
>![image](https://github.com/damus-io/damus/assets/64376233/925a6b74-d788-435d-b342-5ea8b281e77c)
>
>note12gwfjjw59xw2qu752dz03xkd8rp5a3h4c7h0w58cgm2g0ghcy0us6f7hkc
>
>https://damus.io/nevent1qqsz9zagz4w0hd0z85scqupf8s36gg68yxfam3dz84sku9md929t3cgpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq32amnwvaz7tmwdaehgu3wd45kcmm49ekx7mqpr9mhxue69uhhyetvv9ujuam9d3kx7unyv4ezumn9wsq3vamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny009xfz

we really don't know if these are from primal or from other clients
though, or even older primal versions, or if the primal update didn't
work.

I think the way forward here is to just get more test cases in the nip10
marker PR and push that out (ideally for 1.8)

**Comment by alltheseas** [comment]
> we really don't know if these are from primal or from other clients
though, or even older primal versions, or if the primal update didn't
work.

I asked the bug reporter for this info oncemore.

> I think the way forward here is to just get more test cases in the nip10
marker PR and push that out (ideally for 1.8)

Tagging NIP-10 update as likely suspect https://github.com/damus-io/damus/issues/528

**Comment by jb55** [comment]
fixed by https://github.com/damus-io/damus/pull/2241
