### ISSUE TITLE
v1.7 RC2 Madeira release App Store submission

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2026]
Tracker for the iOS release process

**Comment by danieldaquino** [comment]
Pushed release branch with all remaining changes: https://github.com/damus-io/damus/commits/v1.7-madeira-release/

**Comment by danieldaquino** [comment]
- Performed version bump to `v1.7(11)`
- Created and pushed `v1.7-rc2` tag

**Comment by danieldaquino** [comment]
CI/CD tests passed

**Comment by danieldaquino** [comment]
Updated changelog: f6a295dcda660eb3203ca1bb49d7dd024e84b48a

**Comment by danieldaquino** [comment]
Built app for archiving under the "release" scheme.

- Build successful
- Preliminary App Store package checks passed

**Comment by danieldaquino** [comment]
Uploaded build to App Store connect

**Comment by danieldaquino** [comment]
**Note:** On App Store connect, v1.7 RC2 is being called build "12". I believe it's because there is a build 11 that has been submitted, thus Apple bumped the build number to avoid naming conflicts

**Comment by jb55** [comment]
On Thu, Feb 29, 2024 at 12:34:50AM -0800, Daniel D’Aquino wrote:
>Added app for review!
>
>Selected these options:
>- Manually release after app is accepted
>- Phased release (This will make auto-updates only kick-in for users
>after 7 days). This will be helpful for a soft launch

phased might be idea to catch any issues. didn't know that was a
possibility.

>I still need to submit the In-app subscription offerings for review
>separately. I will need to add some screenshots and more info. I will
>continue this on Friday.

awesome, thanks!

**Comment by danieldaquino** [comment]
App Store review team approved
