### ISSUE TITLE
Fake Jacks pop up before real Jack when mentioning on compose note

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2030]
_what happens_ 

When I compose a note, and I want to tag Jack, I type AT and jack, I see a bunch of Jack imposters or other Jacks. I follow Jack.

_what I expect to happen_

I expect to see the Jack profile I follow first on the suggested npub list when I mention during compose note.

![image](https://github.com/damus-io/damus/assets/64376233/eb40fda6-89f9-4c44-96a8-e51bf4df4205)

**Comment by jb55** [comment]
On Sat, Mar 02, 2024 at 05:05:03AM -0800, alltheseas wrote:
>_what happens_
>
>When I compose a note, and I want to tag Jack, I type AT and jack, I see a bunch of Jack imposters or other Jacks. I follow Jack.
>
>_what I expect to happen_
>
>I expect to see the Jack profile I follow first on the suggested npub list when I mention during compose note.
>
>![image](https://github.com/damus-io/damus/assets/64376233/eb40fda6-89f9-4c44-96a8-e51bf4df4205)

I think this is the same issue as the search result count being too limited?

**Comment by alltheseas** [comment]
I am not 100% sure.

When I type another name I follow, they are not top of results

![image](https://github.com/damus-io/damus/assets/64376233/a916f478-0542-48e9-a04a-6a61aa31f9fa)

Feels like a regression - thought we had sorted this. @kernelkind was this your patch?

**Comment by kernelkind** [comment]
> Feels like a regression - thought we had sorted this. @kernelkind was this your patch?

Search in `PostView` occurs in `Ndb.search_profile`, which calls `ndb_search_profile` in `nostrdb.c`, neither of which I've touched.

**Comment by alltheseas** [comment]
Both autocompletion, and search view are affected

![image](https://github.com/damus-io/damus/assets/64376233/a9d38748-216b-4864-ac96-d47dac547bca)

![image](https://github.com/damus-io/damus/assets/64376233/eafe14b8-065f-4bd1-b993-443706ea6f5e)

**Comment by alltheseas** [comment]
Fixed!
