### ISSUE TITLE
I have an idea about decentralized social platforms, and I'm not sure if it's feasible.

### ISSUE THREAD

**Issue by qsgy** [damus-io/damus#2031]
http://www.syytech.club:8181/docs/mindoc/qzxh
Perhaps the solution I described may not be directly applicable to Damus, but the core idea of using trust networks to determine what messages people receive is crucial. The details can be refined continuously.

**Comment by alltheseas** [comment]
Please be specific with feature requests.

Have you used Damus or nostr?
