### ISSUE TITLE
In note view, show fediverse, threads label

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2033]
Currently notes from activitypub are displayed in scroll view. See https://github.com/damus-io/damus/issues/1885#issuecomment-1974747464.

## user story

As a Damus user examining notes, if I am in note view, I would like to see if a note is from activitypub, or threads in note view.

### acceptance criteria
1. in note view, notes from activitypub should have the acitvitypub label
2.in note view, notes from threads should have the threads label

**Comment by alltheseas** [comment]
@ericholguin @jb55 I dont see the fediverse acrivitypub label in thread view

![image](https://github.com/damus-io/damus/assets/64376233/91bf5abe-cd92-4cef-9097-76fe5074e02c)

![image](https://github.com/damus-io/damus/assets/64376233/22f3becf-fa53-4431-96ef-fc5b5c04f739)

I'm on latest appstore build 1.7.2 (1)

**Comment by alltheseas** [comment]
https://damus.io/npub1p6452a6qhpjm55u4w5hwda9ujnu3s4j63587v8wdcya4qruyq6esfmergf

https://damus.io/nevent1qqs9vyqspxp935pu5a64gy4xa57xmdheesvz2n5qt5rxvh33t0vum3qpzemhxue69uhkzarvv9ejumn0wd68ytnvv9hxgqg0waehxw309ahx7um5wghx6mmdqyghwumn8ghj7mn0wd68ytnvw5hxkegpp4mhxue69uhkummn9ekx7mq7h8prp

**Comment by ericholguin** [comment]
I believe that’s only on master and did not make it to app store or testflight

From: alltheseas ***@***.***>
Date: Monday, March 18, 2024 at 19:04
To: damus-io/damus ***@***.***>
Cc: Eric Holguin ***@***.***>, Mention ***@***.***>
Subject: Re: [damus-io/damus] In note view, show fediverse, threads label (Issue #2033)

@ericholguin<https://github.com/ericholguin> @jb55<https://github.com/jb55> I dont see the fediverse acrivitypub label in thread view

1A23A255-7784-4A00-9DBC-D07433ED65F8.jpeg (view on web)<https://github.com/damus-io/damus/assets/64376233/91bf5abe-cd92-4cef-9097-76fe5074e02c>

58CBEA68-C1D0-4C4B-A7AE-ED03947D79F3.jpeg (view on web)<https://github.com/damus-io/damus/assets/64376233/22f3becf-fa53-4431-96ef-fc5b5c04f739>

I'm on latest appstore build 1.7.2 (1)

**Comment by alltheseas** [comment]
My bad, thanks! Closed.

**Comment by jb55** [comment]
On Mon, Mar 18, 2024 at 06:04:12PM -0700, alltheseas wrote:
>@ericholguin @jb55 I dont see the fediverse acrivitypub label in thread view
>
>![image](https://github.com/damus-io/damus/assets/64376233/91bf5abe-cd92-4cef-9097-76fe5074e02c)
>
>![image](https://github.com/damus-io/damus/assets/64376233/22f3becf-fa53-4431-96ef-fc5b5c04f739)
>
>I'm on latest appstore build 1.7.2 (1)

This is why I would like to get a testflight out...
