### ISSUE TITLE
Search UI Redesign

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2046]
When scrolling after doing a note search, it doesn't hide the keyboard like we do in the global search view. We still need to refactor these views so they are the same, but in the meantime this is very annoying to me.

**Comment by jb55** [comment]
cc @ericholguin I can't remember who figured out how to do this in the origin search view

**Comment by ericholguin** [comment]
I used a state variable. Will also add that to the home search view.

**Comment by alltheseas** [comment]
Related: https://github.com/damus-io/damus/issues/2116

**Comment by jb55** [comment]
New tracking issue is:

- https://github.com/damus-io/damus/issues/2205
