### ISSUE TITLE
Feature request: Add an option to hide specific kind of messages on my timeline and conversations

### ISSUE THREAD

**Issue by bitcoinuser** [damus-io/damus#205]
Hi,

I follow Jack Dorsey and I don't want to miss what he posts on Damus, but I hate when he posts or reply with things like: Only an emoji or with just one word like: Wow, Yes, 100%.
I would like to be able to NOT see these kind of messages on my timeline/conversations.

Thanks

**Comment by jb55** [comment]
Mute words is in but needs fixed. Tracking muting bugs here:

- #2159 
- https://github.com/damus-io/damus/issues/2222
