### ISSUE TITLE
Join fedimint

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2050]
## user story

As a Damus user who would like a "just works" way of interacting with BTC/LN networks, I would like to be able to join a fedimint in Damus, so that I can send and/or receive sats.

### acceptance criteria.

1. There is a method to join a single fedimint in Damus

**Comment by jb55** [comment]
The priority would be just use our fedimint to start, joining a
different fedimint is so much further down the line. Not many people are
event running fedimints at the moment. This is also way too advanced for
99.99% of people.

The whole point of the fedimint is to have a default thing that just
works and is somewhat safe from rugging.

Plus it's not as simple as switching to random mints, unless there is a
way to setup a lightning address for receiving zaps that works across
mints, which is the entire point of doing this is the first place
(non-custodial receiving of zaps while the user's non-custodial wallet
is offline).

**Comment by kernelkind** [comment]
Is the damus use-case of Hermes *only* for receiving zaps while the user's non-custodial wallet is offline? I think it could make sense for users to hold their ecash instead of automatically converting them to sats to their external wallet on their next re-connect. That way, if two users are both in the Damus federation, they can do an internal payment just with ecash (if I'm understanding this correctly) and have no transaction fees

**Comment by alltheseas** [comment]
> Is the damus use-case of Hermes _only_ for receiving zaps while the user's non-custodial wallet is offline? I think it could make sense for users to hold their ecash instead of automatically converting them to sats to their external wallet on their next re-connect. That way, if two users are both in the Damus federation, they can do an internal payment just with ecash (if I'm understanding this correctly) and have no transaction fees

Here is the motivation @kernelkind: https://github.com/damus-io/damus/issues/1623

Requirements:
1) The user must be able to send, and receive sats
2) Cannot be rugpulled by a single person
3) User has a LN address automatically generated
4) NWC is supported
5) On every new Damus install, everything is pre-configured

Regarding e-cash, the normie person who just joined from FB, Tiktok couldn't care less if under the hood e-cash, nuts, or something else is used. All that matters is ability to send & receive sats.
It should "just work", and it should be automatically (or as much as possible) set up. 

Any transaction is handled under the hood by whatever solution you, and Will choose. If in the same federation probably e-cash makes sense. If in different federations, or if sending to a non-federation then LN.

**Comment by alltheseas** [comment]
> they can do an internal payment just with ecash (if I'm understanding this correctly) and have no transaction fees

There are costs to running a federation. There will be transaction fees. See Fedi.

**Comment by jb55** [comment]
On Thu, Mar 14, 2024 at 11:34:10AM -0700, kernelkind wrote:
>Is the damus use-case of Hermes *only* for receiving zaps while the
>user's non-custodial wallet is offline? I think it could make sense for
>users to hold their ecash instead of automatically converting them to
>sats to their external wallet on their next re-connect. That way, if
>two users are both in the Damus federation, they can do an internal
>payment just with ecash (if I'm understanding this correctly) and have
>no transaction fees

The auto-converting thing could happen at a certain threshold like how
alby does it. Exchanging esats within a federation between damus users
is a good idea, but not sure how that would work wrt. zaps. Maybe our
zapper could just lie about it being a real lightning txn, or maybe we
need ecash zaps in that case, or maybe even a simpler zap spec.
