### ISSUE TITLE
Set up lightning address Fedimint

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2052]
## user story

As a Damus user who has joined a Fedimint, I would like an easy to way to generate a LN address, so that other nostriches may easily zap me.

### acceptance criteria
1. there is a method to generate a LN address, and
2. associate above LN address with a Fedimint, so that zaps are received to the fedimint, and
3. user receives notifications in Damus of zaps upon set up of NWC #2051

**Comment by alltheseas** [comment]
Mutiny is building this currently

**Comment by kernelkind** [comment]
See https://github.com/Kodylow/hermes
