### ISSUE TITLE
See fedimint recommendations via WOT

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2053]
## user story

As a Damus user who is considering joining a Fedimint, I would like to see social proof regarding a Fedimint, so that I can that I can assuage my own FUD regarding joining a new to me Fedimint.

### acceptance criteria

1. Damus user can see which of their follows have recommended a Fedimint

### implementation possibility

This _could_ happen via [NIP-89](https://github.com/nostr-protocol/nips/blob/master/89.md)

### example (mockup via Mutiny)
https://private-user-images.githubusercontent.com/64376233/312122813-a4ea4480-327a-4854-a4c2-162e423c23d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjA4NzQsIm5iZiI6MTcxMDQyMDU3NCwicGF0aCI6Ii82NDM3NjIzMy8zMTIxMjI4MTMtYTRlYTQ0ODAtMzI3YS00ODU0LWE0YzItMTYyZTQyM2MyM2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OTkwNTYyNDVhOGI1NGFmYjMzZDU4Y2M0Y2JmOWQ0NzA1MmQzNWI4ZGZiYjM2N2Y2ZGU1NWYxNjYwNTUzOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLjDR9CbJpCKYAvM5egy_MtyrNz1eibb_BoVMbZwCa8

### related

See NWC x WOT ticket (wallet centric, not Fedimint explcit)
https://github.com/damus-io/damus/issues/2039

**Comment by kernelkind** [comment]
We also need to publicly see who the guardians of the federation are, so people can determine beforehand if they trust the federation

**Comment by alltheseas** [comment]
> We also need to publicly see who the guardians of the federation are, so people can determine beforehand if they trust the federation

Let's discuss this in our next call. There are tradeoffs.

**Comment by jb55** [comment]
On Thu, Mar 14, 2024 at 11:50:58AM -0700, kernelkind wrote:
>We also need to publicly see who the guardians of the federation are,
>so people can determine beforehand if they trust the federation

Why? All users care about is a working wallet. They don't care about how
it works. The entire point of the fedimint is to have a wallet that just
works and is not in single custody.

More advanced things like switching federations will be v2 or v3. It's
not the MVP.

I feel like all of these WoT and fedimint switching issues are a huge
distraction at the moment. Just getting it working is already difficult
enough.

There are lots of details like how zaps will work is what we need to
focus on for the MVP.

**Comment by kernelkind** [comment]
> On Thu, Mar 14, 2024 at 11:50:58AM -0700, kernelkind wrote: We also need to publicly see who the guardians of the federation are, so people can determine beforehand if they trust the federation
> Why? All users care about is a working wallet. They don't care about how it works. The entire point of the fedimint is to have a wallet that just works and is not in single custody. 

If the number of malicious guardians exceeds the maximum faulty number for the federation, they can do many unwanted things like deny valid ecash and generate new ecash from thin air, things a user would not want to occur.

> There are lots of details like how zaps will work is what we need to focus on for the MVP.

I agree that we should focus our efforts on MVP

> More advanced things like switching federations will be v2 or v3. It's not the MVP. I feel like all of these WoT and fedimint switching issues are a huge distraction at the moment. Just getting it working is already difficult enough.

Agree, WoT and fedimint switching are 'nice to haves', not MVP. But we should have some rudimentary way of showing users who the guardians of the federation are, so if they end up performing maliciously, they can be held accountable. I definitely don't think any guardian for the Damus federation would actually be malicious, but I think it helps instill trust for users.
