### ISSUE TITLE
Follows label cuts off on small screens

### ISSUE THREAD

**Issue by karnagebitcoin** [damus-io/damus#2062]
Possible solution is to move it below PFP or below the name. iPhone SE 2020 4.7inch 
![image](https://github.com/damus-io/damus/assets/131526701/d85a6325-2a27-4b74-b7b4-b1124179ce15)
![image](https://github.com/damus-io/damus/assets/131526701/c70d5e86-e4d3-4f18-8624-333395233479)

**Comment by alltheseas** [comment]
Repeat of https://github.com/damus-io/damus/issues/1729
