### ISSUE TITLE
Damus purple testflight invite codes

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2065]
We need a page on our site that gives testflight invite codes to purple users in preparation for the next testflight release.

Questions:

- How do we reset testflight users, maybe we create a new testing group somehow?
- Can we use the verification step in damus as-is or do we need to modify it ?

**Comment by alltheseas** [comment]
> Can we use the verification step in damus as-is or do we need to modify it ?

-new damus-OTP keys, and npub
-NIP-05 on damus.io domain
-additional badge, that cannot be forged 
-something official looking

-can also extend new badge to damus devs

**Comment by alltheseas** [comment]
damus contributor badge defined here https://github.com/damus-io/damus/issues/2069

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, I have done some research and testing on how TestFlight invites work. Here is what I discovered:
1. We can open up spots and get new people on TestFlight by removing existing TestFlight testers. Furthermore, we can filter by testers who accepted the invitation but never installed any TestFlight versions (inactive testers)
2. In terms of methods of adding testers, there does not seem to be a way to provide individual TestFlight invite codes. I found only two ways we can add testers:
    1. Providing a TestFlight public URL. This is easier and more private for the users, but we are limited in terms of controlling where the link goes. It would be hard to strictly enforce it
    2. Inviting users by email. This is easier to enforce, but a bit less private for users and would require a manual process to add users to the TestFlight.
    3. Or perhaps a hybrid method, where the email method is the standard, but we have an extra testing group where we can manually increase the count limit by one and send the invite link anytime someone requests it

Which method do you prefer?

**Comment by danieldaquino** [comment]
Here are some useful Apple links on what I described above:
- https://developer.apple.com/help/app-store-connect/test-a-beta-version/delete-testers-from-testflight
- https://developer.apple.com/help/app-store-connect/test-a-beta-version/invite-external-testers

**Comment by alltheseas** [comment]
> we can filter by testers who accepted the invitation but never installed any TestFlight versions (inactive testers)

If you can remove inactive users, that's a solution. 

If more spots are needed beyond the purged inactive testflight user list, we could make testflight increasingly a purple only benefit. Is this possible?

> who accepted the invitation but never installed any TestFlight versions (inactive testers)

I never understood this - I thought Damus collected no data. Therefore, if a user opted out of data sharing, how would we know who is inactive? Perhaps TestFlight has a different setup than AppStore?

> public URL

If we are trying to control for purple only subscribers being in TestFlight, I would advise against a public URL.

> ii. email invite
> iii. hybrid

I am indifferent - whatever is least complex from dev, and operations perspective. 

Ideally Damus never has to store, or even handle email addresses from a privacy perspective.

**Comment by danieldaquino** [comment]
> > who accepted the invitation but never installed any TestFlight versions (inactive testers)
> 
> I never understood this - I thought Damus collected no data. Therefore, if a user opted out of data sharing, how would we know who is inactive? Perhaps TestFlight has a different setup than AppStore?

Damus itself doesn't collect such data, this data collected automatically by Apple through TestFlight/AppStore. Furthermore, we don't really know who the testers coming from public links are, they just appear as "Anonymous" on the TestFlight interface. We can just access some basic attributes like whether or not the anonymous tester has installed any Damus TestFlight versions, and use that to filter which testers to keep/exclude.

> > public URL
> 
> If we are trying to control for purple only subscribers being in TestFlight, I would advise against a public URL.
> 
> > ii. email invite
> > iii. hybrid
> 
> I am indifferent - whatever is least complex from dev, and operations perspective.
> 
> Ideally Damus never has to store, or even handle email addresses from a privacy perspective.

Yeah, I share a similar sentiment. It would be nice if Apple provided a way to better control who has access without having to give out their emails. The public link is the simplest and most private way, but we have to trust our users won't just share the URL

**Comment by danieldaquino** [comment]
Actually, there might be a 4th option. We can use the public URL, but setup something in the Damus code that prevents the app from working unless the user is logged in to an account that has Purple

**Comment by alltheseas** [comment]
> Actually, there might be a 4th option. We can use the public URL, but setup something in the Damus code that prevents the app from working unless the user is logged in to an account that has Purple

👀

**Comment by jb55** [comment]
On Fri, Mar 22, 2024 at 11:59:58AM -0700, Daniel D’Aquino wrote:
>@jb55, @alltheseas, I have done some research and testing on how TestFlight invites work. Here is what I discovered:
>1. We can open up spots and get new people on TestFlight by removing existing TestFlight testers. Furthermore, we can filter by testers who accepted the invitation but never installed any TestFlight versions (inactive testers)
>2. In terms of methods of adding testers, there does not seem to be a way to provide individual TestFlight invite codes. I found only two ways we can add testers:
>    1. Providing a TestFlight public URL. This is easier and more private for the users, but we are limited in terms of controlling where the link goes. It would be hard to strictly enforce it
>    2. Inviting users by email. This is easier to enforce, but a bit less private for users and would require a manual process to add users to the TestFlight.
>    3. Or perhaps a hybrid method, where the email method is the standard, but we have an extra testing group where we can manually increase the count limit by one and send the invite link anytime someone requests it
>
>Which method do you prefer?

 From what I under the way mutiny did it was just a code/public urc. It's
not super private by any means but we can maybe change the code each
new testflight.

**Comment by jb55** [comment]
On Fri, Mar 22, 2024 at 12:01:15PM -0700, Daniel D’Aquino wrote:
>Here are some useful Apple links on what I described above:
>- https://developer.apple.com/help/app-store-connect/test-a-beta-version/delete-testers-from-testflight
>- https://developer.apple.com/help/app-store-connect/test-a-beta-version/invite-external-testers

let's try to delete all of the current testflight users, we need to a do
a complete reset before the new invite links.

**Comment by danieldaquino** [comment]
> From what I under the way mutiny did it was just a code/public urc. It's not super private by any means but we can maybe change the code each new testflight.

I looked into how to change the TestFlight URL, and the only way I found was to delete a test group and create another. We can try that, at least until we find a better way

I will get the mechanisms to securely share that URL working

**Comment by alltheseas** [comment]
@danieldaquino consider could specify which profile /npub OTP code is coming from in case user wants to verify

**Comment by alltheseas** [comment]
@danieldaquino I remember from your last screenshare user was on the browser, in the purple testflight flow. 

At one point in you had a screen to the effect of "here is your OTP, check your DMs to verify your npub".

My minor comment here is that on the website browser, immediately after the "here is your OTP" message, you could specify "this DM is coming from npub123..." as to allow paranoid purple users to verify they are corresponding with the official/correct npub in DMs.

**Comment by danieldaquino** [comment]
Oh I see, that makes sense. Thanks, I will do that!

**Comment by alltheseas** [comment]
Sorry for the confusion 😅. Please ask me if my ramblings are unclear, which is not an unlikely occurrance.

**Comment by danieldaquino** [comment]
@jb55, I sent the patches!

- damus-api: https://groups.google.com/a/damus.io/g/patches/c/e1kX0LaHMhY
- damus-website: https://groups.google.com/a/damus.io/g/patches/c/2hxhvTS7KjU

I tried to clean up and test these patches as thoroughly as possible, but it's quite big, so please let me know if I forgot anything. 😅

Thank you!

**Comment by alltheseas** [comment]
There's an OTP issue if profile is not stored on damus relay. Sjors, and sikto

**Comment by danieldaquino** [comment]
@alltheseas, also, if we have all remaining issues related to this tracked in other tickets, I believe this ticket can be closed (I believe the acceptance criteria of this has been fulfilled, and changes are live)

**Comment by jb55** [comment]
Follow ups here:

- #2164

**Comment by jb55** [comment]
Other than that small bug it seems to be working great! Thanks!

Maybe we can deprecate this eventually when we have something in-app
