### ISSUE TITLE
Damus user cannot follow new ppl

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2075]
Https://damus.io/note1p0ckss640yr9025fc92mddrfhfcwrhnchwh4s02c8fvmzz76kf2qs0fdcg

No idea the cause, or how to recreate

**Comment by javiermadueno** [comment]
Same here. When pressing the Follow button it seems everything is correct. But after a while, if you access to the same profile I can see I’m not follow it

**Comment by jb55** [comment]
Let's make sure there isn't a confounding issue here, like the slashes on relays which prevents relay updates in general. Can you make posts?

**Comment by alltheseas** [comment]
> Same here. When pressing the Follow button it seems everything is correct. But after a while, if you access to the same profile I can see I’m not follow it

Whats your npub?

Which other apps have you used? Did you create your keys with Damus?

**Comment by javiermadueno** [comment]
Is the first time I use Nostr so everything was creating with Damus. My npub is npub1ht4ut6283kpp33skw8vwh4ct2csj9x4vawztwt9q70rd5rkavtesw94uyu

**Comment by alltheseas** [comment]
Javi, it appears your profile was not successfully formed. I cannot see your relay list. 

There is an unhappy path where if you are creating your profile on a poor internet connection, you are stuck in onboarding hell. 

![image](https://github.com/damus-io/damus/assets/64376233/73a47a9b-b7ee-434f-affb-f9377a9659f7)

We will have a fix for this in newer versions.

The current solution is to create a new keypair under a stable wifi / internet connection.

If you'd like you can optionally "delete" your current keys. 

Apologies

**Comment by javiermadueno** [comment]
Many thanks! I will do that!

**Comment by alltheseas** [comment]
Linked OP in first comment has a relay list. This means it's likely a separate issue than Javi's.

**Comment by javiermadueno** [comment]
Creating a new key solved the issue. Many thanks one more time and thanks for the hard work

**Comment by alltheseas** [comment]
see https://github.com/damus-io/damus/issues/2057
