### ISSUE TITLE
NIP-05 Identifier verification method

### ISSUE THREAD

**Issue by BenGWeeks** [damus-io/damus#209]
It would be great to implement a NIP-05 identifier verification method (assume it's not there already). The UI could then call this to display a specific badge (if applicable).

**Comment by 0xtlt** [comment]
Seems to be done 🤔

**Comment by BenGWeeks** [comment]
Yeah - was beaten to it :-)

**Comment by BenGWeeks** [comment]
@0xtlt @jb55 Are your NIP-05 identify badges loading correctly in dev? Mine can be very slow to load and now getting EXC_BAD_ACCESS (suggests out of memory) on line 594 of HomeModel.

**Comment by BenGWeeks** [comment]
Not sure why contacts.events was nil, but added check to validate for this (`if contacts.event != nil {}`).
