### ISSUE TITLE
Cannot use Damus on wifi

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2092]
_what happens_

> Hey guys. I’m having technical difficulties with Damus and can’t figure out what the problem is.

> Suddenly out of nowhere Damus stopped loading my feed when I’m on my home wifi. Works over 5G fine. Everything else works on wifi. 

> It’s just happening on my primary phone. I can access a different account on another phone on the same network with no problem.

> 17.3.1 running latest Damus TF

npub1aeh2zw4elewy5682lxc6xnlqzjnxksq303gwu2npfaxd49vmde6qcq4nwx

**Comment by jb55** [comment]
considering only one user is having this issue, this is probably just a DNS issue on their network.
