### ISSUE TITLE
Add haptic feedback upon 100% image upload

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2094]
## Suggestion

Upon 100% of media upload, add haptic feedback (in addition to the current progress bar).

### inspiration

telegram haptic feedback on media upload

**Comment by seankibler** [comment]
I'm taking a look at this. I just got a development environment set up. I'm inexperienced in Swift and iOS development but this seems to be a very approachable feature to implement.

**Comment by alltheseas** [comment]
> I'm taking a look at this. I just got a development environment set up and I've been reading over related source code. I'm inexperienced in Swift and iOS development but this looks to be a very approachable feature to implement.

LFG 🔥

Check out zap vibration in the codebase. This already is implemented. 

Also check out contributing.md when you have a chance for dev best practices💪

**Comment by alltheseas** [comment]
Confirmed works on 1.9 TestFlight
