### ISSUE TITLE
Demarcate where search results end

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2119]
There is no demarcation of where the search results end, and where the regular timeline begins.

**Comment by alltheseas** [comment]
> This is fixed in the latest resdesign by @ericholguin

**Comment by jb55** [comment]
this is not true, but maybe we could make it more clear. But ideally this issue would go away entirely once we implement:

- #2209

**Comment by alltheseas** [comment]
![image](https://github.com/user-attachments/assets/ee146a79-3f6d-4de9-bea8-5c0d01c219bd)

Current implementation

**Comment by alltheseas** [comment]
1.11 search keyword view does not load notes if keyword not found
