### ISSUE TITLE
Hyperlinks (disappear from body of text)

### ISSUE THREAD

**Issue by olheadinternet** [damus-io/damus#212]
as seen in the following example, would love the hyperlinks to still appear in the body of the text so each link has context.

personally i'm not sure previews should be renders for notes with more than 1 link... and same goes for note mentions. Just let the text do it's thing. 

note1q3pykf527s45v8x3yqv0rsnvjz6seug8s7pp2jjazpayn4vyvrxqtzd0x7

![IMG_0397](https://user-images.githubusercontent.com/56426913/210193643-58ab680d-33a3-479d-829c-1e5ee9eb1b74.png)

**Comment by jb55** [comment]
this should be fixed now

**Comment by olheadinternet** [comment]
thank you!
