### ISSUE TITLE
Feature Request / Idea: Increase screen real estate by hiding the top bar and note button on scroll

### ISSUE THREAD

**Issue by karnagebitcoin** [damus-io/damus#2122]
Demo (set browser mode to phone): https://playground-8ca0bb.webflow.io/scroll

As a Damus user who is using Damus daily, I would like to test out the idea of having more screen real estate when browsing, so that I can see more notes by freeing up elements that are not used frequently.

**Is your feature request related to a problem? Please describe.**
Not a problem - but I do use a small phone where the UI takes up 25% of the real estate. This could be minimized to zero just with clever timing of hiding the top and bottom elements, see demo.

** When does this problem happen? **

**Describe the solution you'd like**
I've already mocked up the desired behavior, see demo.

**Describe alternatives you've considered**
Bigger phone.

**Additional context**
I'd be curious to see what the team thinks of this!

**Comment by jb55** [comment]
On Thu, Apr 04, 2024 at 05:29:07PM GMT, Karnage wrote:
>Demo (set browser mode to phone): https://playground-8ca0bb.webflow.io/scroll
>
>Not a problem - but I do use a small phone where the UI takes up 25% of
>the real estate. This could be minimized to zero just with clever
>timing of hiding the top and bottom elements, see demo.

I had a branch attempting to do this at one point but I'm too much of a
SwiftUI noob to make it work right. Would love of someone else took a
stab at it

**Comment by alltheseas** [comment]
> I had a branch attempting to do this at one point but I'm too much of a SwiftUI noob to make it work right. Would love of someone else took a stab at it

@ericholguin official issue meme

![helpmeeric](https://github.com/damus-io/damus/assets/64376233/5adb92d9-a961-4f5e-8c11-8c93019f5882)

**Comment by alltheseas** [comment]
1.11
