### ISSUE TITLE
Thai Auto-translate for purple subscribers

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2125]
## user story

As a Damus purple user, I would like to have Thai language support, so that I may interact with more nostriches.

### acceptance criteria

1. Damus can detect Thai language
2. If purple subscriber, notes are auto-translated from Thai to native language, or 
3. from foreign language to Thai if Thai is the preferred language

### implementation & context

1) DeepL is currently utilized for Purple subscribers. DeepL does not support Thai, and the timeline is not currently clear for Thai support. 
2) Google has priced translation APIs that support Thai.
3) Google translation should _only_ translate to/from Thai, and no other language pairs to constrain API translation costs.

**Comment by alltheseas** [comment]
DeepL is the best translator. Google cloud is remote second best. Microsoft & amazon follow. 

google cloud pricing https://cloud.google.com/translate/pricing

> With the Google Translate API, you strictly pay based on your usage. After your first 500,000 characters each month, you’ll pay $20 per million characters. 


microsoft azure pricing https://azure.microsoft.com/en-us/products/ai-services/ai-translator#Pricing

**Comment by alltheseas** [comment]
according to this post, GPT3.5 has a good performance/price  https://community.openai.com/t/which-api-for-translation/553000

**Comment by alltheseas** [comment]
DeepL pricing ![Screenshot from 2024-04-08 13-13-42](https://github.com/damus-io/damus/assets/64376233/4d5416da-9f1e-475d-a4a8-ffbb883e8908)

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqswlxgjcmw3fnjp5ek98z9hf4cdwhz7azjfv2syw44ruxugnfq28hgpzemhxue69uhhyetvv9ujuurjd9kkzmpwdejhgqgewaehxw309aex2mrp09jhytnxd9shg6npvchxxmmdqyvhwumn8ghj7mn0wd68ytn5dpjhxctdv43kzapwd9hszxmhwden5te0vd58y6tnw3cxjmrv9ehx7um5wgcjucm0d5a0l2h6

**Comment by alltheseas** [comment]
does this update need an appstore/testflight push or is it all API side @jb55 @semisol ?

**Comment by jb55** [comment]
On Thu, Apr 25, 2024 at 12:10:16PM -0700, alltheseas wrote:
>does this update need an appstore/testflight push or is it all API side @jb55 @semisol ?

It doesn't need an appstore push, it should be working now for everyone.
