### ISSUE TITLE
Bug: smol phone video controls covered by note in full mode

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2138]
Reported by karnage:

https://damus.io/nevent1qqsqhud2lc90qptdfgglpn0mkzf59pmzdav76pq6use6r0mh3qcfptqpzpmhxue69uhkummnw3ezuamfdejsz9thwden5te0v4jx2m3wdehhxarj9ekxzmnyqyw8wumn8ghj7mn0wd68ytndw46xjmnewaskcmr9wshxxmmdqyxhwumn8ghj7mn0wvhxcmmv25q43g

"Heads up: smol phone video controls covered by note in full mode"

cc @danieldaquino

**Comment by karnagebitcoin** [comment]
![IMG_3489](https://github.com/damus-io/damus/assets/131526701/6591a92c-af85-4c6a-a804-d031da83172c)

**Comment by danieldaquino** [comment]
Thanks for reporting this!

@karnagebitcoin, if you want a quick workaround while we don't have a fix, you can try clicking around the top of the screen, above the video player, to make the note disappear and thus make the scrubbing controls clickable.

**Comment by karnagebitcoin** [comment]
> Thanks for reporting this!
> 
> @karnagebitcoin, if you want a quick workaround while we don't have a fix, you can try clicking around the top of the screen, above the video player, to make the note disappear and thus make the scrubbing controls clickable.

Thanks! I'm in no rush or anything.

**Comment by danieldaquino** [comment]
> what's stopping us from positioning the video above the note ?

You mean instead of having the note content as an overlay (ZStack), we make a VStack with the note text on the bottom?
