### ISSUE TITLE
1.9 wipes mute list (likely due to other clients)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2144]
**What happens**

When I update to 1.9 Testflight my mute list is broken

https://damus.io/note1mw43qujda0s6vaxvdkew0k50yldcp8xsunrw8yq8qzwa4fkf9vqqqrnts7

**Comment by alltheseas** [comment]
Mute list still visible on older build

https://image.nostr.build/e0b56b38b146f5ee26a2be7ff4ed3c72b8c1d8a22f0ba7fa22451666e36a96c1.png

**Comment by jb55** [comment]
On Mon, Apr 15, 2024 at 07:05:38AM -0700, alltheseas wrote:
>Mute list still visible on older build
>
>https://image.nostr.build/e0b56b38b146f5ee26a2be7ff4ed3c72b8c1d8a22f0ba7fa22451666e36a96c1.png

sounds like its not getting migrated properly ...

**Comment by alltheseas** [comment]
Related https://github.com/damus-io/damus/issues/856

**Comment by alltheseas** [comment]
theory of edge case: mute list created by other client, and created by damus -> only part of mute list is imported to 1.9

Is it possible to merge both lists?

**Comment by jb55** [comment]
I think the only reasonable thing left to do here is to support:

- #1880 

Any other weird edge cases are probably caused by existing mutelists from other clients, and merging old and new lists is probably way too complicated and not going to be relevant to 99% of users.
