### ISSUE TITLE
Update to latest version of NIP-10 (nip-10 other client updates might cause trouble)

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2145]
Team is anticipating trouble, as discussed between @danieldaquino and @jb55 on @tyiu changes to Primal

**Comment by alltheseas** [comment]
@tyiu commit https://github.com/PrimalHQ/primal-ios-app/commit/dbefe05c821b7c94a9e61f1051467789b91906c5

**Comment by alltheseas** [comment]
"Thank you! Although we should really update lol" - @jb55 on @tyiu update on Primal repo of NIP-10 to be backwards compatible

**Comment by alltheseas** [comment]
@tyiu how much work would it be to apply the same nip-10 patch to damus?

cc @danieldaquino @jb55

**Comment by alltheseas** [comment]
Lmk how many candles orders its worth to you @tyiu

**Comment by alltheseas** [comment]
@jb55 is nip-10 update published to testflight?

**Comment by jb55** [comment]
On Tue, Apr 30, 2024 at 07:23:25PM GMT, alltheseas wrote:
>@jb55 is nip-10 update published to testflight?

It's still an open PR:

- https://github.com/damus-io/damus/pull/2190

1. I still want to add a testcase I hit on the android side:

https://github.com/damus-io/nostrdb-rs/blob/99d8296fcba5957245ed883e2f3b1c0d1cb16397/src/util/nip10.rs#L436

2. Ideally we would support adding nip10 markers when replying to threads which isn't done yet

**Comment by alltheseas** [comment]
duplicate https://github.com/damus-io/damus/issues/528

**Comment by jb55** [comment]
Closing because dup of:

- #528

Trying to get our issue numbers down a bit :sweat_smile:
