### ISSUE TITLE
Purple members missing star on testflight after renewal

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2149]
**What happens**
Aftrr I subscribe I am missing the star

**What I expect to happen**
I expect to have a purple sub star

**Link to noteID, npub**

https://damus.io/nevent1qqsw0y0qlnfa4nhn8epgkk8uw73pz3qnxpv9kejr5a9zagvyz9p6e5cpz3mhxue69uhhyetvv9ujumn0wd68ytnzvuq3camnwvaz7tmwdaehgu3wd46hg6tw09mkzmrvv46zucm0d5q3wamnwvaz7tmjv4kxz7fwwpkx2cnnw3ezucm0d5q3yamnwvaz7tm0venxx6rpd9hzuur4vgjvhvhl

https://damus.io/nevent1qqswxvz8syrjyw3lcpnsf72xa4tutysd4sp3ejncvpw4fan60ydd6qqpz4mhxue69uhkummnw3ezu6twdaehgcfwvd3szxrhwden5te0wfjkccte9ehx7umhdpjhyefwvdhk6qgawaehxw309ahx7um5wgkhqatz9emk2mrvdaexgetj9ehx2aqppamhxue69uhkummnw3ezumt0d5485gge

**Screenshots/video recording**

** Versions **
Damus version: 

@danieldaquino

**Comment by Hakkadaikon** [comment]
damus version: 1.9 (1) 90c68fed
iOS version: 17.4.1
 
1.  I registered Damus Purple for 1 month.
2. It was about to expire, so I went to iOS's Settings -> Subscriptions -> Purple and purchased Purple Yearly.
3. Even after renewing my subscription, I received a notification from Damus that the expiration date was approaching, and once the one-month deadline passed, the star mark disappeared.
If you select the Purple tab from Damus, the Purple deadline was the deadline before you extended it. (expired account)

Even if I change the Damus Purple subscription in the iOS settings, it doesn't seem to be reflected in Damus.

**Comment by danieldaquino** [comment]
Hi @Hakkadaikon, I am sorry to hear that.

If it's feasible, can you please try downgrading to the App Store version of Damus, and use it for a few hours, to see if the renewal activates with our servers? (You can always upgrade back to the TestFlight version again if needed)

_(There are some differences between TestFlight and App Store, so I would like to check if that could be the source of the issue)_

**Comment by Hakkadaikon** [comment]
version: 1.7.2 (1) 669ca0d91c9c

In the case of the App store version, there seems to be a star mark.

![image](https://github.com/damus-io/damus/assets/57866935/1485d827-cec5-4582-984a-ea5e09def087)

**Comment by danieldaquino** [comment]
Thank you very much @Hakkadaikon! I believe if you upgrade to the TestFlight version again (1.9), the star will still be there. Can you please confirm when you have a chance?

**Comment by Hakkadaikon** [comment]
version: 1.9 (1) 90c68fed

The stars are back, thank you!

**Comment by danieldaquino** [comment]
Thanks @Hakkadaikon for confirming!

**Comment by jb55** [comment]
so this is only an issue for 1.7 testflight or will this happen for anyone who purchases a subscription on the current testflight ?

**Comment by danieldaquino** [comment]
> so this is only an issue for 1.7 testflight or will this happen for anyone who purchases a subscription on the current testflight ?

This should affect all TestFlight versions. I am not worried much about initial purchases as Sandbox purchases will not charge real money, but I am worried about automatic renewals. It looks like automatic renewals are affected if the user is using TestFlight.

**Comment by jb55** [comment]
is there a way to make testflight not use the sandbox environment? this seems pretty bad.

**Comment by jb55** [comment]
Notes on this issue from our meeting:

- The sandbox environment on testflight is not able to fetch and send the correct IAP receipts to the purple server, so it can't verify the renewal

To fix this, we may need to write a script that periodically checks for new IAP transactions from apple after an account has expired on the server, so that the purple star can be automatically re-added even if the user has not opened the app

**Comment by alltheseas** [comment]
Doesn't need iOS update

**Comment by alltheseas** [comment]
is this still an issue @danieldaquino

**Comment by danieldaquino** [comment]
> is this still an issue @danieldaquino

@alltheseas, thanks for bringing this up, this is fixed now by this commit: damus-io/api@2620ad8a2c5cb13730c4f7d8627995a3c0778eb0 (also tracked at https://github.com/damus-io/api/issues/6)

Closing ticket
