### ISSUE TITLE
NIP96 Image Uploader

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2153]
It would be nice to support uploads this way, as there are many compatible hosts:

https://github.com/aljazceru/awesome-nostr?tab=readme-ov-file#nip-96-file-storage-servers

**Comment by alltheseas** [comment]
duplicate of https://github.com/damus-io/damus/issues/1564

**Comment by alltheseas** [comment]
@jb55 I'll close this one in favor of #1564

**Comment by jb55** [comment]
On Tue, Apr 16, 2024 at 02:01:32PM GMT, alltheseas wrote:
>duplicate of https://github.com/damus-io/damus/issues/1564

thanks i was lookin for that
