### ISSUE TITLE
How does Damus handle recognizing, importing, reconciling mute lists generated in another nostr app?

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2155]
**What happens**
Reported: when I generate a mute list in Nos social, and I bring my keys with me to Damus, I dont carry over my mute list.

**What I expect to happen**
I expect logging in to Damus with a mute list created in another client to carry over my mute list to Damus.

**Link to noteID, npub**

_questions_
Is mute list on damus local?

**Comment by jb55** [comment]
On Wed, Apr 17, 2024 at 07:29:40AM GMT, alltheseas wrote:
>**What happens**
>Reported: when I generate a mute list in Nos social, and I bring my keys with me to Damus, I dont carry over my mute list.
>
>**What I expect to happen**
>I expect logging in to Damus with a mute list created in another client to carry over my mute list to Damus.
>
>**Link to noteID, npub**
>
>_questions_
>Is mute list on damus local?

no.

It's supposed to migrate old lists to the new format, but I'm not sure
we're handling encrypted mutelists yet. charlie did all this code and
now he's gone, so I don't know the state of it. This is a testflight
issue atm, appstore does not have this new mute code.

**Comment by alltheseas** [comment]
Let me test. 

Reported by Linda here:

https://njump.me/note1vvmcagef07x3pk7xc3dlej58vgl3rv0873nax70ndqdl6507punsl32yc5

**Comment by alltheseas** [comment]
Damus 1.9 (1) 90c68fed
Nos social 0.1.10 (238)
