### ISSUE TITLE
Word muting is broken

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2159]
I have not been able to get word mutes working with the new mute overhaul.

Let's make sure we add tests!

**Comment by danieldaquino** [comment]
Tested this and it is 100% broken on my end as well.

Will mentioned we might want to add this to 1.8. I agree with that idea, so I added this to the 1.8 milestone for now _(given the feature is 100% broken)_

@alltheseas @jb55, do you have any objections to this?

**Comment by jb55** [comment]
nope!

**Comment by alltheseas** [comment]
agree

**Comment by alltheseas** [comment]
see #1880

**Comment by alltheseas** [comment]
see #1934

**Comment by alltheseas** [comment]
See issues with mute label https://github.com/damus-io/damus/issues?q=is%3Aopen+is%3Aissue+label%3Amute

**Comment by alltheseas** [comment]
see potential mute list hang/performance issue https://github.com/damus-io/damus/issues/2146

**Comment by danieldaquino** [comment]
Sent a basic fix draft: https://groups.google.com/a/damus.io/g/patches/c/hfDnKV3eLGo

@alltheseas @jb55, I was not 100% thorough with the above to give us flexibility to refine only as much as we need or as much as time allows us. Please advise how much refinement you'd like!

**Comment by alltheseas** [comment]
> Sent a basic fix draft: https://groups.google.com/a/damus.io/g/patches/c/hfDnKV3eLGo
> 
> @alltheseas @jb55, I was not 100% thorough with the above to give us flexibility to refine only as much as we need or as much as time allows us. Please advise how much refinement you'd like!

Basic fix is a yuge update, thanks Daniel. Is temp muting excluded from 1.8 as we have not verified it works?

**Comment by danieldaquino** [comment]
> Is temp muting excluded from 1.8 as we have not verified it works?

Not necessarily excluded _(it could be working)_, I am just not familiar with it yet and I haven't tested if my changes break it (or if it was working before)

I think I should test it if we have time
