### ISSUE TITLE
Bug: Few users report difficulty in logging in to their Purple account on the website

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2164]
**What happens**
From an email conversation:
> There is one remaining issue where if their profile is not found
then it will fail to give them an OTP code. It should probably still
work even if the profile is not fetched? Otherwise we can try adding
wss://purplepag.es/ as a relay to look for profiles.

**What I expect to happen**
All users should get their OTP codes

**Link to noteID, npub**
Unknown/undefined

**Screenshots/video recording**
Unknown/undefined

** Versions **
Damus version: N/A
Operating system version: N/A
Device: Unknown
Damus website: `c88bd9432024c15b4c001db74700d06adaa3ef95`

**Steps To Reproduce**
Unknown/undefined

**Additional context**

**Comment by danieldaquino** [comment]
Relevant pieces of code

```tsx
// Load the profile when the pubkey changes
  useEffect(() => {
    if (pubkey) {
      fetchProfile()
      fetchAccountInfo()
    }
  }, [pubkey])
```

```tsx
{existingAccountInfo !== null && !otpSent && (
            <Button variant="default" className="w-full" onClick={() => beginLogin()}>Continue</Button>
)}
```

@jb55, I apologize if you already gave me this info, but do those users report:
- not seeing the "continue" button at all,
- an unresponsive "continue" button, or
- No OTP codes on their DMs?

**Comment by jb55** [comment]
> an unresponsive "continue" button

yes, I tested it on other people's accounts. the continue button did nothing.

I did not confirm if they received a code or not

**Comment by jb55** [comment]
an easy way to test this just to use an empty relay with a subscribers account ?

**Comment by danieldaquino** [comment]
I will start working on this now!

**Comment by danieldaquino** [comment]
@jb55, fixed this and sent the patch over email!

(https://groups.google.com/a/damus.io/g/patches/c/a4w1BqPRqLI)

Please let me know if you have any questions or concerns, thanks!
