### ISSUE TITLE
Test mutelist migration

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2166]
Let's make sure we're properly migrating our mutelist from 30000 to 10000

**Comment by alltheseas** [comment]
See https://github.com/damus-io/damus/issues/2155#issuecomment-2063585260

**Comment by jb55** [comment]
to be more specific here, I'm wondering if migration from kind 30000 -> kind 10000 works. this is more of an old-damus-mutelist-to-new-damus-mutelist test

**Comment by alltheseas** [comment]
Got you. I see I still have a huge mutelist on 1.9. Muted profiles remain muted

**Comment by jb55** [comment]
hmm ok honestly that's all I wanted to hear, so I'll close this

**Comment by alltheseas** [comment]
Cool. I did not (and don't know how to) verify what the list type is in 1.9.
