### ISSUE TITLE
Post nostrDB performance optimization: event verification sampling

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2168]
Consider:

> nostr clients always have this tension between:

> ✅ verifying signatures (bad performance)
🙃 "trust me bro" (no checking)

> I INTRODUCE TO YOU... FRACTIONS! 😂

> Next version of NDK is shipping with SO many performance tricks and improvements that I have zero chance of remembering what they were when I write the release notes.

> But one of them is that.. fractions.

> Developers will be able to configure a ratio of events to verify on a per-relay basis. For example, you could say "only verify 10% of events coming from each relay"

> The cool part is that I can also compare signatures coming from different relays for the same event so evil relays can be detected even faster and kicked out.

> I will make it possible later to save state of the "reputation" each client perceives of a relay, so that a client can start talking to a new relay with a higher ratio (e.g. 1.0 = "verify everything") and slowly transition to trusting the relay more (i.e. verify 1% of events).

![image](https://github.com/damus-io/damus/assets/64376233/e1b8eca5-fac6-4df3-b511-671e08fe1c48)

https://damus.io/nevent1qqs9njjy0rsvvjw0kfv8w7f9vf2fn0jh0hl58tupkrs6ap8ndt836fc4n2cte

**Comment by jb55** [comment]
what pablo is describing is much slower than how nostrdb currently does it and is overcomplicated. nostrdb is so fast the verification isn't really noticable anymore. nostrdb is also smart enough to not parse and check notes that are already in the DB.
