### ISSUE TITLE
❤️ to 🤙

### ISSUE THREAD

**Issue by elidyweaver** [damus-io/damus#217]
# Switching from ❤️ to 🤙
![nostr-emoji-version-1](https://user-images.githubusercontent.com/119618812/210253105-6341efce-32a5-4991-8d02-3690b79a4a59.png)

Hello everyone. I'm working on adding a muted emoji of "jack's nostr welcome" to the likes button. 

Working [Figma File](https://www.figma.com/file/f2xhDQVpfeV46UA0Hrpt7e/design-explorations?node-id=3%3A2&t=8rWdnyXR4uTIAJ0T-1)

Near future:
I'm in the process of setting up a PR to upload necessary files. 
Figuring out details & specs. 

![emoji-nostr(3)](https://user-images.githubusercontent.com/119618812/210253099-186ee153-41e3-4874-bbdb-4b94f64c7720.png)

**Comment by jb55** [comment]
looks good!

**Comment by elidyweaver** [comment]
Opened PR #226 
Uploading image variations:
solid & outline 
black & white
20x20 pixels, @2x & @3x 

![nostr-hello](https://user-images.githubusercontent.com/119618812/210302981-61809cc3-8ac6-419c-abb4-c1b2c542b8f8.png)

I haven't made any changes to the code. 
If any adjustments are needed, please let me know.

**Comment by bebopkid** [comment]
Updated in last version

**Comment by elidyweaver** [comment]
> Updated in last version

Thank you so much.
