### ISSUE TITLE
Repost-style highlights

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2173]
Ideally highlights would have an appearance similar to the way we currently do reposts:

- "Bob highlighted alice's note"
- "Alice highlighted a web snippet"

Where the PFP for web snippet would either be the favicon or a simple `WWW` if there is none. The username could just be the hostname.

Ideally the web snippet would be clickable:

- https://github.com/damus-io/damus/issues/2172

Perhaps the snippet should also be in a quote block?

- #2175

**Comment by alltheseas** [comment]
Consider: how does this relate to opt out of re-posts feature request #2133

**Comment by jb55** [comment]
advised by @ericholguin that it didn't look good.
