### ISSUE TITLE
Tabbar switching doesn't work when on Following, Followers, and Relays pages

### ISSUE THREAD

**Issue by ericholguin** [damus-io/damus#219]
When you are on the Following, Followers, or Relays page from your profile and try switching views from the tab bar the view doesn't change until you click the back button. You can select Home, DMs, Global, or Notifications and they will highlight but not take you to the view and exit out of the current page.

**Comment by BenGWeeks** [comment]
Oh yeah! Well spotted.

**Comment by ericholguin** [comment]
Fixed
