### ISSUE TITLE
emoji picker

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2204]
merge emoji picker to 1.8

https://github.com/damus-io/damus/pull/2176

**Comment by alltheseas** [comment]
@danieldaquino

**Comment by danieldaquino** [comment]
Commit of interest: ae2f4848

**Comment by danieldaquino** [comment]
Cherry picked ae2f484 to the 1.8 release branch, fixed a trivial merge conflict manually, and did a quick smoke test.

Fix is now available on [release branch](https://github.com/damus-io/damus/commits/v1.8_relay_fix_and_video_player/) as 3842a02

Closing!

**Comment by jb55** [comment]
thanks!
