### ISSUE TITLE
Debug elsat's account

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2206]
Needed to look into fixing:

- #2194 

After debugging, we should add a test case:

- #2207 

[npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5](https://njump.me/npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5)

**Comment by jb55** [comment]
Debugged by @danieldaquino , fix landed in 1.9 (6)

**Comment by alltheseas** [comment]
So far so good on 1.9 (6) 

Thanks @danieldaquino
