### ISSUE TITLE
Add test case for large contact list

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2207]
In order to determine what is happening with 

- #2194 

We need to take elsat's account and add it as a testcase.

Steps to test:

- [ ] Send subscriptions to relays on relay list
- [ ] See how long it takes to send request and receive responses
- [ ] Do we get responses at all? If not why not? What is the response message?

**Comment by danieldaquino** [comment]
> Do we get responses at all? If not why not? What is the response message?

From investigating #2194, I found that we get responses to our subscription requests. This is the response message I have seen:

```
["NOTICE","ERROR: bad req: total filter items too large"]
```

**Comment by danieldaquino** [comment]
@jb55 The hard part of this is that we would depend on a relay connection to perform the test.

What do you have in mind for testing that relay connection? Perhaps we can try setting up some form of test strfry relay? 

It'd be nice if we can spawn a test relay during the test, but probably not straightforward. Another option would be to setup a strfry test relay instance that is always available for testing, an instance where we can somehow maintain a consistent/controllable test environment (e.g. always revert back to a certain DB state, to avoid having constantly changing feeds)

**Comment by alltheseas** [comment]
See related discussion https://github.com/nostr-protocol/nips/issues/1179

In there it was mentioned @semisol had a large database useful for testing

**Comment by jb55** [comment]
Should be fixed
