### ISSUE TITLE
nip10: single reply tag should be considerd reply-to-root

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2234]
I noticed an alex gleason post that was like this, make sure to handle it properly.

**Comment by jb55** [comment]
We should also add a case for a single root tag...

**Comment by alltheseas** [comment]
> I noticed an alex gleason post that was like this, make sure to handle it properly.

noteID?

**Comment by jb55** [comment]
while this is explicitly against the nip10 spec, we should treat it the same as a single root tag. I have some initial tests for this and fix coming soon.

**Comment by jb55** [comment]
Fixed in https://github.com/damus-io/damus/pull/2241
