### ISSUE TITLE
Cannot boot up MacOS

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2257]
<img width="291" alt="Screenshot 2024-05-15 at 10 43 23 AM" src="https://github.com/damus-io/damus/assets/64376233/003b9dc3-aa10-496d-b870-a93e19498f0c">

how can I troubleshoot?

MacOS 13.6.3

**Comment by jb55** [comment]
On Wed, May 15, 2024 at 08:44:15AM GMT, alltheseas wrote:
><img width="291" alt="Screenshot 2024-05-15 at 10 43 23 AM" src="https://github.com/damus-io/damus/assets/64376233/003b9dc3-aa10-496d-b870-a93e19498f0c">
>
>how can I troubleshoot?
>
>MacOS 13.6.3

this is weird, is this M1,M2 ?

**Comment by alltheseas** [comment]
M1

**Comment by alltheseas** [comment]
I think it might have been an expired testflight issue. Jut downloaded from appstore and it works fine. 1.8
