### ISSUE TITLE
self hosted Blossom video does not load

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2280]
**What happens**
Blossom hosted mp4 video does not load in damus. Amethyst users report works fine 

https://damus.io/nevent1qqsdnaac4zgcrnacdfpfwncq0egkhu806ajevwchs40va2ulha68yvg2yvkwp

**Comment by alltheseas** [comment]
Mp4 Link does not work in browser

**Comment by alltheseas** [comment]
@0xtrr advises

> The Blossom spec requires blossom server implementations to accept a file extension on the end of the hash in the url

> "The endpoint MUST accept an optional file extension in the URL. ie. .pdf, .png, etc"

> https://github.com/hzrd149/blossom/blob/master/buds/01.md#get-sha256---get-blob

https://damus.io/nevent1qqsf59vewdr50fmuy0s6zheywsdg0g0ccfxlhzl5levehqkjalyzgsc5ntwq6

**Comment by 0xtrr** [comment]
> Mp4 Link does not work in browser

The video works perfectly well in my Brave web browser on my Macbook Pro.

The URL:

https://blossom.oxtr.dev/f1393991c1a242f14b934eab1af9df00e828a532b94e88d24bd811e15abbc7ae.mp4

**Comment by jb55** [comment]
On Mon, May 27, 2024 at 12:45:02PM GMT, alltheseas wrote:
>Mp4 Link does not work in browser

works for me

**Comment by jb55** [comment]
On Mon, May 27, 2024 at 02:05:16PM GMT, William Casarin wrote:
>On Mon, May 27, 2024 at 12:45:02PM GMT, alltheseas wrote:
>>Mp4 Link does not work in browser
>
>works for me

(in the browser)

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqs85fqs8wztrdap48awy3hqpwrh6a5htmt44k4jjcrr6q687l80rfqpramhxue69uhkzarvv9ejumn0wd68ytnvv9hxgtmfdemx76trv4eszyrhwden5te0dehhxarj9ekxzmnyqy2hwumn8ghj7etyv4hzumn0wd68ytnvv9hxgqgcwaehxw309aex2mrp0yhxummnwa5x2un99e3k7mgpz3mhxue69uhhyetvv9ujuerpd46hxtnfdupzpvkkwr098vnkj8qvxsqzykm9cddzd5rqjw7vg86gllr3uzg8l822hhzzjm

> Damus still won’t play videos served from my Blossom server. Do you know why? Anything I can help with?

**Comment by alltheseas** [comment]
@jb55 advises

> Guessing its not encoded with the right pixel format -pix_fmt yuv420p with baseline profile. Thats the most common reason videos don’t play.

@0xtrr is this a your server fix, or is it an upstream blossom server fix?

**Comment by alltheseas** [comment]
cc @hzrd149

**Comment by 0xtrr** [comment]
It has nothing to do with the Blossom protocol or the server implementation, it's just how the video has been encoded in the first place. I'm no expert on file containers or encodings but I find it odd that it's playable everywhere else but not on iPhone.

I don't know if this helps but for this particular video, I downloaded it from Twitter using [yt-dlp](https://github.com/yt-dlp/yt-dlp) with the following command:
```
yt-dlp -f http-832 -o "%(id)s.%(ext)s" https://x.com/Cobratate/status/1832295110521881065
```

Available formats was:
```
ID                     EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC       VBR ACODEC      ABR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-32000-Audio  mp4 audio only │ ~136.41KiB   32k m3u8  │ audio only       unknown     32k Audio
hls-audio-64000-Audio  mp4 audio only │ ~272.83KiB   64k m3u8  │ audio only       unknown     64k Audio
hls-audio-128000-Audio mp4 audio only │ ~545.66KiB  128k m3u8  │ audio only       unknown    128k Audio
http-288               mp4 480x270    │ ≈  1.20MiB  288k https │ unknown          unknown
hls-192                mp4 480x270    │ ~821.54KiB  193k m3u8  │ avc1.4D4015 193k video only
http-832               mp4 640x360    │ ≈  3.46MiB  832k https │ unknown          unknown
hls-311                mp4 640x360    │ ~  1.30MiB  312k m3u8  │ avc1.4D401E 312k video only
http-2176              mp4 1280x720   │ ≈  9.06MiB 2176k https │ unknown          unknown
hls-638                mp4 1280x720   │ ~  2.66MiB  638k m3u8  │ avc1.640020 638k video only
```

**Comment by alltheseas** [comment]
@fishcakeday do you have guidance?

**Comment by jb55** [comment]
this is a video encoding issue, there's not much we can do on our end for videos which are not encoded for maximum compatibility
