### ISSUE TITLE
Notifications do not work

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2284]
**What happens**
I do not receive notifications, despite having notifications on in damus settings. 

https://damus.io/nevent1qqsrze25r9l4waqx4qr32eznalh89ljj2plfx5zl9tgehr88jzcme3qpz3mhxue69uhhyetvv9ujumn0wd68ytnzvuq3camnwvaz7tmwdaehgu3wvf5hgcm0d9hx2u3wwdhkx6tpdsq35amnwvaz7tmwdaehgu3wdaexzmn8v4cxjmrv9ejx2aspz3mhxue69uhhyetvv9ujuerpd46hxtnfduzmsvc9

npub1tdewu5xk7ydz68tgc6mk4gq7hyty6s5uakf6w3amr5z9lse3rqnqsekx8c

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqszu8gjzgu5ewy64mqygat73fxvpe8y0pvmkhkulh736u6tde7chuqlqy5dm

Third report

**Comment by jb55** [comment]
I assume people mean push notifications, which is true there are none yet

**Comment by alltheseas** [comment]
> I assume people mean push notifications, which is true there are none yet

"Little red notification dot on the bell icon in #Damus Purple seems to be not working lately"

**Comment by jb55** [comment]
On Sat, Jun 01, 2024 at 04:55:04AM GMT, alltheseas wrote:
>> I assume people mean push notifications, which is true there are none yet
>
>"Little red notification dot on the bell icon in #Damus Purple seems to be not working lately"

bizarre...

**Comment by alltheseas** [comment]
> Little red notification dot on the bell icon in #Damus Purple seems to be not working lately

Follow up:

> I don’t seem to see the banner drop-down anymore despite that being setup in iOS settings - the dot/badge kinda resurfaced just this minute. Perhaps a more temperamental issue than a direct bug 🤷🏻‍♂️

**Comment by alltheseas** [comment]
> **What happens**
> I do not receive notifications, despite having notifications on in damus settings. 
> 
> https://damus.io/nevent1qqsrze25r9l4waqx4qr32eznalh89ljj2plfx5zl9tgehr88jzcme3qpz3mhxue69uhhyetvv9ujumn0wd68ytnzvuq3camnwvaz7tmwdaehgu3wvf5hgcm0d9hx2u3wwdhkx6tpdsq35amnwvaz7tmwdaehgu3wdaexzmn8v4cxjmrv9ejx2aspz3mhxue69uhhyetvv9ujuerpd46hxtnfduzmsvc9
> 
> npub1tdewu5xk7ydz68tgc6mk4gq7hyty6s5uakf6w3amr5z9lse3rqnqsekx8c

Follow up:

> iOS 17.5.1
Damus 1.9 (5) 52aefc8d6480

> Notifications started working a day or two ago? So I’m not sure what/if anything changed.

**Comment by alltheseas** [comment]
Seems like some persistence or relay availability issue that self resolved. Closing for now

cc @danieldaquino

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/8207189b-dba9-4c32-bf0d-aa75ba2cc184)

No idea how to reproduce. Received report of local notification not working, and bell dot working.

**Comment by alltheseas** [comment]
> Seems to be working ok now. I have background refresh off so that might be affecting stuff. TestFlight Damus Purple version 1.9 (6) - reminds me, I should get around to renewing the subscription).
