### ISSUE TITLE
emoji picker parts not hide properly

### ISSUE THREAD

**Issue by ikanoasi10** [damus-io/damus#2286]
**What happens**
1. hold the reaction button to display the emoji picker.
2. hold the emoji displayed in the emoji picker.
3. hold and tap outside the modal to close the picker.
4. part of the picker remains permanently. 

<img width="150" src="https://github.com/damus-io/damus/assets/67615583/8a897d13-61f1-4e33-ac20-0311e15ee533" />
<img width="150" src="https://github.com/damus-io/damus/assets/67615583/7f8edc7c-1d38-4a8a-9562-8c72cbadc990" />
<img width="150" src="https://github.com/damus-io/damus/assets/67615583/22baceab-71dd-4c5f-b545-1a7090beedfb" />

It will continue to be displayed and can be made to look like the following:
<img width="150" src="https://github.com/damus-io/damus/assets/67615583/f4959784-e050-4dee-8cd2-c8777f9018c2" />

Damus version: 1.8 (2) 16f51c0423d5
Operating system version: iOS 17.5.1
Device: iPhone 14 Pro

**Comment by alltheseas** [comment]
Thank you for the detailed report.

@tyiu

**Comment by tyiu** [comment]
Thanks! I'm working on moving  away to using a different emoji component that should hopefully be less buggy.
