### ISSUE TITLE
purple login is broken

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2296]
**What happens**
> look like purple login is broken. seem to hit `Error sending OTP via relay wss://nostr.land: Error: blocked: pay on https://nostr.land for access` on the server

from @jb55 

> remove nostr.land might be quick fix

> damus relay rate limiting purple
> Will advised fixed/exception

**Comment by jb55** [comment]
removed nostr.land and nostr.wine... looks like its fixed now
