### ISSUE TITLE
A way to filter out replies in the home timeline

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#23]
Sometimes it gets too chatty.

**Comment by jcarucci27** [comment]
@jb55 I'm taking a stab at this. What I can't figure out right now is how to tell if a given event is a reply and thus should be filtered. But I'm damn close. Check out https://github.com/jcarucci27/damus/commit/9a7f009f88355fb8d0da84ebca605f8819cd228e most specifically line 119 where I think a filter on your events may do the trick.

**Comment by jb55** [comment]
On Wed, Aug 10, 2022 at 05:25:35PM -0700, jcarucci27 wrote:
> What I can't figure out right now is how to tell if a given event is a reply and thus should be filtered.

I'm reworking some of this logic now, I will test this soon

**Comment by jb55** [comment]
lol wtf, I sent the previous message a month ago.
