### ISSUE TITLE
Fix shrug "¯_(ツ)_/¯ "

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#231]
"¯\_(ツ)_/¯" is still not rendering right on the app.

**Comment by BenGWeeks** [comment]
Sorry, what should it do?

@note1c9exuyame634fyd0xjvcemgeptsc7fa0mn7s7tpuzdfm6m7ydnesr96vq7

**Comment by lionello** [comment]
Fixed by #238

**Comment by punterwantsawhalepass** [comment]
🤙
