### ISSUE TITLE
Damus wipes mute list

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2311]
**What happens**
Damus wipes my mute list.

**What I expect to happen**
I dont expect my mute list to get wiped. 

**Link to noteID, npub**

https://damus.io/nevent1qqsxarnxelxm8gz48qdtsv3qg2f6e2wgca2yfl3xvgag9cmtgc7areslw0zf7

https://github.com/nostrability/nostrability/issues/47

**Additional context**
Might be related to:
-mute keyword update
-paging certain relays that do not store mute lists (purple pages)

**Comment by karnagebitcoin** [comment]
Can confirm, happening to me as well.

**Comment by alltheseas** [comment]
This is most likely caused by Zapstream, and/or snort
