### ISSUE TITLE
Merge notification settings and enable push notification filtering

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2324]
- [x] Replace the current "Local notifications" setting with just "Notifications"
- [ ] Use entitlement (lol wen) to filter notifications locally

We could also just not send notifications depending on some setting associated with the device token. We just need to figure out where we would store that? 

We could use the API, but then the relay would have to make a request to the API to get these settings. We really wouldn't want the push notification server to hit the api every time it needed to send a notification.

At this point we would need some kind of caching mechanism would could get out of date. This is horrendously ugly. Entitlements would make this much simpler.

**Comment by jb55** [comment]
This seems like more of a pressing reason to get the entitlement @danieldaquino ? Otherwise our push design is much more complicated.

**Comment by jb55** [comment]
looks like this is mostly done

**Comment by jb55** [comment]
re-opening this because I still get like notifications even when I have it disabled

**Comment by danieldaquino** [comment]
> re-opening this because I still get like notifications even when I have it disabled

@jb55 was this because of https://github.com/damus-io/damus/issues/2417? If so, should we close this one?

**Comment by jb55** [comment]
Looks like this is mostly done, we can split the entitlement thing into its own issue if we don't have one yet.
