### ISSUE TITLE
Bug: Investigate crashes on 1.9 to see if there is an obvious fix

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2328]
**What happens**
When I perform action ___, _____ happens. (TBD)

**What I expect to happen**
I expect _______ to happen. (TBD)

**Link to noteID, npub**
Provide link to relevant noteID, npub etc. (TBD)

**Screenshots/video recording**
(TBD)

** Versions **
(TBD)
Damus version: [e.g. 1.7.2 (1()]
Operating system version: [e.g. iOS 17.2.1]
Device: e.g. iPhone 13 Pro

**Steps To Reproduce**
(TBD)
1. Open Damus
2. Tap on ___
3. Action ____

**Additional context**
Unknown. Look at crash logs to check if there is an obvious crash that happens regularly

**Comment by danieldaquino** [comment]
@jb55, I looked at the most common crashes on 1.9 for the last 2 weeks. Here is what I found so far:

- **The second most common crash:** The crash is reported to be due to a `nil` value being forcely unwrapped in the `ProfileName` view. It does not specify exactly the line where it occurs, but it can be inferred from the stack trace
    1. The client does a NIP-05 validation, which notifies the rest of the app of a profile update
    2. The `ProfileName` view picks up that update via `.onReceive(handle_notify(.profile_updated))` and runs a closure
    3. However, that closure assumes one optional value will not be nil, which must be where it crashed.

This diff will likely resolve this crash:

```diff
diff --git a/damus/Views/Profile/ProfileName.swift b/damus/Views/Profile/ProfileName.swift
index 140ce09d..872f9254 100644
--- a/damus/Views/Profile/ProfileName.swift
+++ b/damus/Views/Profile/ProfileName.swift
@@ -125,12 +125,11 @@ struct ProfileName: View {
                 return
             }

-            var profile: Profile!
-            var profile_txn: NdbTxn<Profile?>!
+            var profile: Profile

             switch update {
             case .remote(let pubkey):
-                profile_txn = damus_state.profiles.lookup(id: pubkey)
+                guard let profile_txn = damus_state.profiles.lookup(id: pubkey) else { return }
                 guard let prof = profile_txn.unsafeUnownedValue else { return }
                 profile = prof
             case .manual(_, let prof):
```

Without a consistent repro to test against it is hard to assert exactly the consequences of this change. But from quick code inspection it seems that it would prevent some details on the profile such as the NIP-05 badge from being displayed in cases where the crash would occur — which is still better behavior than crashing.

- **The most common crash:** This is happening around NostrDB event ingestion code, more specifically when dispatching the event json to the ingester queue, while doing a `memcpy` operation. The stack trace does not give us a reason for the crash, only the particular lines where it happened, but it is likely a memory-related error.

Here is how the last elements of the stack trace look like

```
int ndb_process_event(struct ndb *ndb, const char *json, int json_len)
{
	// Since we need to return as soon as possible, and we're not
	// making any assumptions about the lifetime of the string, we
	// definitely need to copy the json here. In the future once we
	// have our thread that manages a websocket connection, we can
	// avoid the copy and just use the buffer we get from that
	// thread.
	char *json_copy = strdupn(json, json_len);
	if (json_copy == NULL)
		return 0;

-->	return ndb_ingester_queue_event(&ndb->ingester, json_copy, json_len, 0);
}
============
static int ndb_ingester_queue_event(struct ndb_ingester *ingester,
				    char *json, unsigned len, unsigned client)
{
	struct ndb_ingester_msg msg;
	msg.type = NDB_INGEST_EVENT;

	msg.event.json = json;
	msg.event.len = len;
	msg.event.client = client;

-->	return threadpool_dispatch(&ingester->tp, &msg);
}
============
static inline int threadpool_dispatch(struct threadpool *tp, void *msg)
{
	struct thread *t = threadpool_next_thread(tp);
--->	return prot_queue_push(&t->inbox, msg);
}
============
static int prot_queue_push(struct prot_queue* q, void *data)
{
	int cap;

	pthread_mutex_lock(&q->mutex);

	cap = prot_queue_capacity(q);
	if (q->count == cap) {
		// only signal if the push was sucessful
		pthread_mutex_unlock(&q->mutex);
		return 0;
	}

--->	memcpy(&q->buf[q->tail * q->elem_size], data, q->elem_size);
	q->tail = (q->tail + 1) % cap;
	q->count++;

	pthread_cond_signal(&q->cond);
	pthread_mutex_unlock(&q->mutex);

	return 1;
}
```

This one will require some more deep code analysis, or a reproduction of the crash with a debugger so that we can see the contents of the variables in memory to explain why it is crashing.

**Comment by jb55** [comment]
On Sat, Jul 13, 2024 at 10:53:34AM GMT, Daniel D’Aquino wrote:
>@jb55, I looked at the most common crashes on 1.9 for the last 2 weeks. Here is what I found so far:
>
>- **The second most common crash:** The crash is reported to be due to a `nil` value being forcely unwrapped in the `ProfileName` view. It does not specify exactly the line where it occurs, but it can be inferred from the stack trace
>    1. The client does a NIP-05 validation, which notifies the rest of the app of a profile update
>    2. The `ProfileName` view picks up that update via `.onReceive(handle_notify(.profile_updated))` and runs a closure
>    3. However, that closure assumes one optional value will not be nil, which must be where it crashed.
>
>This diff will likely resolve this crash:
>
>```diff
>diff --git a/damus/Views/Profile/ProfileName.swift b/damus/Views/Profile/ProfileName.swift
>index 140ce09d..872f9254 100644
>--- a/damus/Views/Profile/ProfileName.swift
>+++ b/damus/Views/Profile/ProfileName.swift
>@@ -125,12 +125,11 @@ struct ProfileName: View {
>                 return
>             }
>
>-            var profile: Profile!
>-            var profile_txn: NdbTxn<Profile?>!
>+            var profile: Profile
>
>             switch update {
>             case .remote(let pubkey):
>-                profile_txn = damus_state.profiles.lookup(id: pubkey)
>+                guard let profile_txn = damus_state.profiles.lookup(id: pubkey) else { return }

this looks right!

>                 guard let prof = profile_txn.unsafeUnownedValue else { return }
>                 profile = prof
>             case .manual(_, let prof):
>```
>
>Without a consistent repro to test against it is hard to assert exactly the consequences of this change. But from quick code inspection it seems that it would prevent some details on the profile such as the NIP-05 badge from being displayed in cases where the crash would occur — which is still better behavior than crashing.
>
>- **The most common crash:** This is happening around NostrDB event ingestion code, more specifically when dispatching the event json to the ingester queue, while doing a `memcpy` operation. The stack trace does not give us a reason for the crash, only the particular lines where it happened, but it is likely a memory-related error.
>
>--->	memcpy(&q->buf[q->tail * q->elem_size], data, q->elem_size);
>	q->tail = (q->tail + 1) % cap;
>	q->count++;
>
>	pthread_cond_signal(&q->cond);
>	pthread_mutex_unlock(&q->mutex);
>
>	return 1;
>}
>```
>
>This one will require some more deep code analysis, or a reproduction of the crash with a debugger so that we can see the contents of the variables in memory to explain why it is crashing.

hmm I always thought my protected queue code was dubious... I will do
more thorough testing. thanks!

**Comment by alltheseas** [comment]
> On Sat, Jul 13, 2024 at 10:53:34AM GMT, Daniel D’Aquino wrote: @jb55, I looked at the most common crashes on 1.9 for the last 2 weeks. Here is what I found so far: - **The second most common crash:** The crash is reported to be due to a `nil` value being forcely unwrapped in the `ProfileName` view. It does not specify exactly the line where it occurs, but it can be inferred from the stack trace 1. The client does a NIP-05 validation, which notifies the rest of the app of a profile update 2. The `ProfileName` view picks up that update via `.onReceive(handle_notify(.profile_updated))` and runs a closure 3. However, that closure assumes one optional value will not be nil, which must be where it crashed. This diff will likely resolve this crash: ```diff diff --git a/damus/Views/Profile/ProfileName.swift b/damus/Views/Profile/ProfileName.swift index 140ce09d..872f9254 100644 --- a/damus/Views/Profile/ProfileName.swift +++ b/damus/Views/Profile/ProfileName.swift @@ -125,12 +125,11 @@ struct ProfileName: View { return } - var profile: Profile! - var profile_txn: NdbTxn<Profile?>! + var profile: Profile switch update { case .remote(let pubkey): - profile_txn = damus_state.profiles.lookup(id: pubkey) + guard let profile_txn = damus_state.profiles.lookup(id: pubkey) else { return }
> this looks right!
> guard let prof = profile_txn.unsafeUnownedValue else { return } profile = prof case .manual(_, let prof): ``` Without a consistent repro to test against it is hard to assert exactly the consequences of this change. But from quick code inspection it seems that it would prevent some details on the profile such as the NIP-05 badge from being displayed in cases where the crash would occur — which is still better behavior than crashing. - **The most common crash:** This is happening around NostrDB event ingestion code, more specifically when dispatching the event json to the ingester queue, while doing a `memcpy` operation. The stack trace does not give us a reason for the crash, only the particular lines where it happened, but it is likely a memory-related error. ---> memcpy(&q->buf[q->tail * q->elem_size], data, q->elem_size); q->tail = (q->tail + 1) % cap; q->count++; pthread_cond_signal(&q->cond); pthread_mutex_unlock(&q->mutex); return 1; } ``` This one will require some more deep code analysis, or a reproduction of the crash with a debugger so that we can see the contents of the variables in memory to explain why it is crashing.
> hmm I always thought my protected queue code was dubious... I will do more thorough testing. thanks!

- [ ] https://github.com/damus-io/damus/issues/2331

**Comment by danieldaquino** [comment]
The "second most common" crash was fixed last Sunday, and the "most common" one is tracked on #2331. Both bugs are tracked/addressed elsewhere, so we can close this ticket.
