### ISSUE TITLE
iOS 18 compilation error

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2332]
@tyiu reported

might be fixed by iOS team as 18 beta progresses - 18 launch planned for September 2024

@jb55 recommended to wait & see

adding tentatively to 1.10

**Comment by jb55** [comment]
This is a runtime error not a compilation error, so its way more critical

**Comment by tyiu** [comment]
> This is a runtime error not a compilation error, so its way more critical

Sorry, I misspoke. Yes, it's a runtime error, and I agree.
