### ISSUE TITLE
Image Carousel broken iOS 18 beta

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2342]
Reported by @tyiu 

> Is the image carousel broken for anyone? I’m on iOS 18 beta 3. Tapping on an image doesn’t bring up the carousel.

> Seems like this was happening only on the latest build from master, not TestFlight.

**Comment by danieldaquino** [comment]
This is still an issue on the official (non-beta) iOS 18.0 release

**Device:** iPhone 13 mini (physical device)
**iOS:** 18.0
**Damus:** Current tip of 1.10 `dfa72fceb10dc0cd6867870acfc1f2b69c890722`

**Comment by danieldaquino** [comment]
Implemented https://github.com/damus-io/damus/pull/2498 as a tentative PR which improves the iOS 18 situation. Not a final fix, but improves the behavior here somewhat. 

I will keep investigating to find a better fix.
