### ISSUE TITLE
Feature Request: When I zap the wallet get's picked automatically. I would like to get option to choose the wallet!

### ISSUE THREAD

**Issue by Prashanth004** [damus-io/damus#2344]
As a Damus user, Prashanth, I would like to select the wallet so that I can achieve zapping from my own LN client app. 

I am frustrated that I can not choose the wallet. First, it automatically opened Bitkit. After I did that, I uninstalled assuming it would ask me to select the wallet. Then it asked me to open Breez. I want to choose the LN wallet from which I want to zap.

**Alternate solution**
Allow users to choose all the LN wallets that allow them to zap. Display the list of apps that will enable zapping.

**Comment by jb55** [comment]
turn on wallet selector in settings

**Comment by Prashanth004** [comment]
It worked thanks!
