### ISSUE TITLE
Bug: non-aligned return button in profile view iOS 18 beta

### ISSUE THREAD

**Issue by tkhumush** [damus-io/damus#2351]
**What happens**
When I view a profile by clicking a users profile picture or name, the Back button and more options buttons are centered at the top, and only snap into place after sliding to go back. 

**What I expect to happen**
The Back and options buttons should be located at the top ends of the screen left and right. 

**Screenshots/video recording**
https://github.com/user-attachments/assets/955cc9d9-819a-4377-a71e-5307a430b78a

** Versions **
Damus version: 1.9 (14)
Operating system version: iOS18 Beta 4
Device: iPhone Pro 14 Max

**Steps To Reproduce**
1. Open profile
2. Slide back, but don't go to previous screen. 

**Additional context**
This only started on iOS18.

**Comment by alltheseas** [comment]
Thanks @tkhumush for the concise report. 

Lets wait for apple's final September iOS 18 release to see if this remains open

**Comment by alltheseas** [comment]
I cannot recreate on iOS 17. Seems like iOS 18 as stated by @tkhumush

**Comment by tkhumush** [comment]
I saw this was fixed by @tyiu

**Comment by alltheseas** [comment]
Yes. PR here: https://github.com/damus-io/damus/pull/2355

**Comment by alltheseas** [comment]
Adding to 1.11 pending @danieldaquino thumbs up 🙏

**Comment by danieldaquino** [comment]
@alltheseas thanks for adding it to 1.11, I agree with that 👍

**Comment by jb55** [comment]
Closing since this is fixed
