### ISSUE TITLE
Bug: iOS 18 cannot upload media

### ISSUE THREAD

**Issue by tkhumush** [damus-io/damus#2359]
**What happens**
Certain photos when selected, Damus doesn't prompt for an upload. Others work fine. 

**What I expect to happen**
When a photo is selected, Damus should ask if I want to upload the photo. 

**Screenshots/video recording**
https://github.com/user-attachments/assets/0993a241-5fe0-41f3-8852-e2e7acf05d6f

**Versions**
Damus version: 1.9 (14)
Operating system version: iOS18 Beta 4
Device: iPhone 14 Max

**Steps To Reproduce**
No clear steps to reproduce. 

**Additional context**
GitHub didn't upload the photo as well and gave an error uploading image. 
Primal uploaded the photo as expected, though Primal has Full access to photos library, unlike Damus and GitHub which have limited access. But this was never an issue in the past.

**Comment by alltheseas** [comment]
This might be an iOS 18 beta bug. Lets revisit in september on iOS 18 launch

**Comment by alltheseas** [comment]
Whats the file size of the media that wont upload?

**Comment by jb55** [comment]
I this still an issue? I haven't noticed it on latest 18
