### ISSUE TITLE
iOS 18 beta 5 post input issues

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2366]
https://damus.io/nevent1qqsreyf8z8m3k9s0qhx5q2vs0pnwmk8egc5em7kftqqendh24ng5srgpp4mhxue69uhkummn9ekx7mqpz9mhxue69uhkummnw3eryvfwvdhk6qg5waehxw309aex2mrp0yhxgctdw4eju6t0qyvhwumn8ghj7ur4wfshv6tyvyhxummnw3ezumrpdejqhxjg4x

> don’t know what Apple is doing with each update on the new iOS, but they seem to change how things work with every update, and now replies in @damus  don’t work well anymore. 

> The text box area gets covered by the keyboard and you cant see what you are typing. 🧐

> Yes Beta 5 broke something with the keyboard. 
The add photo/camera options now are always aligned to the bottom of the screen even if the keyboard is on. And same for text fields. 

> I’m guessing both are caused by the same issue.

**Comment by alltheseas** [comment]
![image](https://github.com/user-attachments/assets/5fc8c5b6-3476-4088-8b31-e6ed97d252a8)

Reported by @tyiu 

> Keyboard cuts off the text with no recourse on the latest iOS 18 beta. Not sure if this is new but this is a pretty annoying bug.

**Comment by jb55** [comment]
man swiftui is a dumpster fire

**Comment by jb55** [comment]
Fixed in beta 8
