### ISSUE TITLE
iOS 18: clicking profile picture sometime does nothing

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2370]
Noticing this sometimes, its likey an iOS 18 issue

**Comment by jb55** [comment]
It seems this happens if there is no profile or no lightning address ?

**Comment by alltheseas** [comment]
I may have experienced this on iOS 17

**Comment by danieldaquino** [comment]
This is still an issue on the official (non-beta) iOS 18.0 release

**Device:** iPhone 13 mini (physical device)
**iOS:** 18.0
**Damus:** Current tip of 1.10 dfa72fceb10dc0cd6867870acfc1f2b69c890722

**Comment by alltheseas** [comment]
I've asked previously if anyone experiences a similar cannot tape on share note externally icon (bottom right of any note)

**Comment by danieldaquino** [comment]
Looking into this

**Comment by danieldaquino** [comment]
I traced back the issue to `KFAnimatedImage`. When I replace that with SwiftUI's `AsyncImage` the tap gesture is recognized. It seems like that view is not capturing tap gestures on iOS 18.

Very likely https://github.com/damus-io/damus/issues/2342 has the exact same root cause and fix

**Comment by danieldaquino** [comment]
I tried updating Kingfisher (the library that defines `KFAnimatedImage`) to see if they have fixed this on their end:
- The latest version of Kingfisher (8.0.2) is not compatible with our implementation _(I won't try to fix compatibility issues yet to save time for the release)_
- The latest 7.x Kingfisher version (7.12.0) also has the same issue.

I will try implementing a quick solution on our end that should fix the issue while we don't fix this on the Kingfisher side

**Comment by danieldaquino** [comment]
Implemented https://github.com/damus-io/damus/pull/2498 as a tentative PR which improves the iOS 18 situation. Not a final fix, but addresses this if we can't get a proper fix in on time.

**Comment by danieldaquino** [comment]
I will keep investigating to find a better fix.

**Comment by danieldaquino** [comment]
I created a minimal reproducible Xcode project that shows the issue is present on the latest Kingfisher version too (8.0.2).

Not actively debugging this right now, I am focusing on https://github.com/damus-io/damus/issues/2458
