### ISSUE TITLE
This is a tracking issue for all of the issues in iOS18. Most of them are super annoying.

### ISSUE THREAD

**Issue by Kasucode101** [damus-io/damus#2372]
This is a tracking issue for all of the issues in iOS18. Most of them are super annoying.

- [ ] https://github.com/damus-io/damus/issues/2342
- [ ] #2366 
- [ ] #2359 
- [ ] https://github.com/damus-io/damus/issues/2370

_Originally posted by @jb55 in https://github.com/damus-io/damus/issues/2371_

**Comment by jb55** [comment]
what
