### ISSUE TITLE
iOS 18 - Opening Video player changes theme to black, and can't be switched afterwards

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2373]

**Comment by alltheseas** [comment]
Jack reported dark mode during day randomly. Unclear if Jack is using the video player at this time. 

I suspect Jack is on iOS 18 beta.

https://damus.io/note1teu2tgvluv4p3q2hme2axd73jqcsu75xnl6xncfuz3rrfga72f3q6eggec

**Comment by alltheseas** [comment]
@cr0bar to investigate

**Comment by jb55** [comment]
this is so random. like seriously wtf ios

**Comment by jb55** [comment]
> I suspect Jack is on iOS 18 beta.

he is according to internal testflight logs

**Comment by danieldaquino** [comment]
Fixed and merged to 1.10: https://github.com/damus-io/damus/commit/6fa2e8b5c635a31e765b908e94b370b0b9b88fb3

**Comment by danieldaquino** [comment]
cc @jb55
