### ISSUE TITLE
Damoose: Highlighter

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2375]

**Comment by alltheseas** [comment]
Related; highlights in long form notes https://github.com/damus-io/damus/issues/822

**Comment by danieldaquino** [comment]
@jb55 @alltheseas does the current highlighter extension meet the acceptance criteria for this ticket?

**Comment by alltheseas** [comment]
I can create a highlight in safari, see the highlight, click 
 on the link / website url.

One nit, which I can add as a separate add-on ticket is to explore adding something after "highlighted ______" in the case of a safari highlight.


See comparison below with highlight made directly on nostr 

![image](https://github.com/user-attachments/assets/642780ab-a6b1-4bf8-8779-dbf139b140c1)

**Comment by alltheseas** [comment]
> note107eta5s3jdlfkhcewuf68fnymxlhp68epsmr25y8tf8fgt3ystlsy08hzq

LGTM!

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/issues/2428

**Comment by danieldaquino** [comment]
> > does the current highlighter extension meet the acceptance criteria for this ticket?
> 
> LGTM!

@jb55 closing this ticket as we have a highlighter implemented. Please feel free to reopen if you disagree. Thanks!
