### ISSUE TITLE
Deploy push notifications with notepush

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2384]

**Comment by danieldaquino** [comment]
@jb55 noteguard does not seem to be forwarding notes to the push notification relay, but I have not been able to check which version of noteguard is running on the server (I want to check if it has no note forwarding support, or if the issue is elsewhere).

I want to update noteguard over there but I am concerned that the server might be running a newer version than master (e.g. a version with https://github.com/damus-io/noteguard/pull/12/files)

Which version of noteguard is running on the relay? If it's an older version, is it ok if I make a new noteguard build on the tip of master (noteguard@8e1bb0363f1c7729195a560ba1cd91f5b1c657c8) and deploy that to the damus relay?

**Comment by jb55** [comment]
On Mon, Aug 19, 2024 at 04:51:20PM -0700, Daniel D’Aquino wrote:
>@jb55 noteguard does not seem to be forwarding notes to the push notification relay, but I have not been able to check which version of noteguard is running on the server (I want to check if it has no note forwarding support, or if the issue is elsewhere).

I will forward it once its up and running, is it deployed already?

**Comment by danieldaquino** [comment]
> I will forward it once its up and running, is it deployed already?

Yes! I will send you the details via DM

**Comment by danieldaquino** [comment]
@jb55 it's working! I have a deployment up and running for our prototype testing.

As part of this effort, I ended up submitting two PRs:
- https://github.com/damus-io/noteguard/issues/13 (Enables TLS support)
- https://github.com/damus-io/damus/pull/2386 (Trivial PR to update the notification server address)

I also made some tweaks to notepush, but I pushed those directly since that project is not in production yet
