### ISSUE TITLE
QR scan iOS 18 black screen

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2393]
**What happens**
When I try to scan QR I see a black screen. 

Changing camera iOS permissions does not fix. 

**What I expect to happen**
I expect to scan QR on damus to work. 

Reported by @tyiu 

** Versions **
Damus version: Damus 1.10 (3) e70cfbbe

Operating system: iOS 18 beta 7, I think. (22A5346a)

**Comment by alltheseas** [comment]
@tyiu 

> Debugged it a bit. Doesn't seem like the UI lifecycle is going all the way through. `viewDidLoad` is called but `viewWillAppear` is not.
https://github.com/damus-io/damus/blob/7f00ef5d9d61be9b968862bb9e93bcf4c561e1d6/damus/Views/CodeScanner/ScannerViewController.swift#L202

> I managed to fix the issue by folding the latter into the former, but I actually have no clue why

**Comment by alltheseas** [comment]
![image](https://github.com/user-attachments/assets/6819c1de-9381-45b6-9188-37f763513e9f)

https://damus.io/nevent1qqs2g4hm9wfmewm0plxcfy97rlsx0zcld5g35rj5j4rmq3yq7ed9eqsyjpwdu

**Comment by jb55** [comment]
I'm not sure it makes sense to cherry-pick this to the 1.10 release
branch, because I haven't tested it on iOS17. we should confirm this
doesn't break that.

**Comment by tyiu** [comment]
> I'm not sure it makes sense to cherry-pick this to the 1.10 release branch, because I haven't tested it on iOS17. we should confirm this doesn't break that.

Sounds like it's already broken on iOS 17 per the screenshot from @alltheseas, so I feel that cherry-picking the change won't make the situation any worse.

**Comment by jb55** [comment]
On Wed, Aug 28, 2024 at 06:09:31AM -0700, Terry Yiu wrote:
>> I'm not sure it makes sense to cherry-pick this to the 1.10 release branch, because I haven't tested it on iOS17. we should confirm this doesn't break that.
>
>Sounds like it's already broken on iOS 17 per the screenshot from @alltheseas, so I feel that cherry-picking the change won't make the situation any worse.

really? I just tested the scanner on vanessas phone and it seemed ok.
