### ISSUE TITLE
Bug: Error Configuring Push Notifications (Request timed out)

### ISSUE THREAD

**Issue by easyuxd** [damus-io/damus#2401]
When I try to change Notifications mode from Local to Push, I get the following error:

"Error configuring push notifications with the server: The request timed out."

Please advise?

** Screenshot **
![image](https://github.com/user-attachments/assets/2860d594-ba43-4111-aeec-115578116102)

** Versions **
Damus version: 1.9.1 (4)
Operating system version: iOS 17.6.1
Device: iPhone 15

**Comment by alltheseas** [comment]
@easyuxd thanks for the interest & report.

Push notifications are being tested on 1.10, and should be rolled out TestFlight shortly. 

Push notifications are not available on older versions. Apologize for the confusion.

**Comment by easyuxd** [comment]
Thanks @alltheseas! Been eagerly following your development on it for a long time and must have gotten my hopes up. ;)

**Comment by alltheseas** [comment]
If you want to be the first to test out the new features, and you are not already, consider joining damus.io/purple.

Purple subscribers get to test out new updates & features before everyone else.

**Comment by alltheseas** [comment]
P.s. @easyuxd  as a FOSS enthusiast I left seedsigner feedback on improving confidence in the stateless model below:

https://github.com/SeedSigner/seedsigner/issues/391#issuecomment-1599256650

Lmk if I can offer further clarification on my feedback 🙏

**Comment by easyuxd** [comment]
Cheers, @alltheseas!
