### ISSUE TITLE
phantom DM notifications

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2402]
**What happens**
Sometimes phantom DM notifications occur

https://damus.io/nevent1qqsrwn9d0ypphv5lrh7vjpg3ec43sd96j3hzge5qfz4dy7sqwy55zpspz9mhxue69uhh2mn0wd68ytnnd96x2qgewaehxw309ankzmrp0punzvewdehhxarjxyhxxmmdqyvhwumn8ghj7cn0wd68ytnvv43hgatjd9n8jtnwv46qzxmhwden5te0w35x2cmfw3skgetv9ehx7um5wgcjucm0d5p6fpy6

**Comment by alltheseas** [comment]
I wonder if this is related to #1441

**Comment by jb55** [comment]
can't say I've ever seen this
