### ISSUE TITLE
Notepush intermittent deliverability issues

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2427]
Sometimes we stop sending push notifications for a brief time window.

**Comment by danieldaquino** [comment]
I believe there is some statefulness in the connection between noteguard and notepush, and it is reaching some form of error that breaks the connection temporarily

**Comment by jb55** [comment]
noteguard's forwarder will reconnect, if there are any issues with the forwarder or queued notes we should open the issue there
