### ISSUE TITLE
Extend friend filter notification to cover push notifications and sync setting

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2480]
Spammers are evolving

![image](https://github.com/user-attachments/assets/35fcf531-48fd-4356-9bf8-4eb11fbb2487)

@danieldaquino

**Comment by alltheseas** [comment]
See customer feedback

https://github.com/damus-io/damus/issues/2478

**Comment by alltheseas** [comment]
- [ ] Also tie to setting ![image](https://github.com/user-attachments/assets/f95c442b-5ea4-41bc-b4ca-b1352f553bbf)

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, I created and tested a patch to address this: https://github.com/damus-io/damus/pull/2483

Please let me know if you have any questions or concerns, thanks!

**Comment by alltheseas** [comment]
-no explainer
-label 'show only from friends of friends'
-sheet <-> setting 1:1
-settings switch/toggle?


@danieldaquino

**Comment by danieldaquino** [comment]
@jb55 @alltheseas created a PR with things we discussed: https://github.com/damus-io/damus/pull/2487

I did not make the separation between the "friends" filter and the "friends-of-friends" filter at this time to keep it simple. We can revisit when we get Rob involved in designing better and more advanced filter options.

**Comment by danieldaquino** [comment]
Merged to 1.10
