### ISSUE TITLE
v1.10 release tasks

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2493]
1. [x] Make sure we are good to go
2. [x] Automated test checks
3. [x] Generate release archive build
4. [x] Submit new version to the App Store
5. [x] Mark version in git with a tag
6. [x] Write changelog
7. [x] Publish App store release
8. [ ] Publish changelog
9. [ ] Prepare next release branch

**Comment by danieldaquino** [comment]
CI tests passing: https://github.com/damus-io/damus/runs/30350593181

**Comment by danieldaquino** [comment]
Tagged: https://github.com/damus-io/damus/releases/tag/v1.10-9

**Comment by danieldaquino** [comment]
Submitted to AppStore for review

**Comment by danieldaquino** [comment]
Wrote changelog draft: https://github.com/damus-io/damus/pull/2494

**Comment by tkhumush** [comment]
@danieldaquino we lost a very cool feature with this update. 

We no longer can tap into a photo and zoom.

**Comment by danieldaquino** [comment]
> @danieldaquino we lost a very cool feature with this update.
> 
> We no longer can tap into a photo and zoom.

@tkhumush thank you for reaching out about this! 

I believe you are referring to a bug that was introduced on iOS 18 (https://github.com/damus-io/damus/issues/2342). Unfortunately it also affects the current app store release (1.9.1) on iOS 18 devices, but don't worry, we plan to fix this and make another 1.10 release soon (probably next week) to address this!
