### ISSUE TITLE
1.10 iOS 18 poor network/relay connectivity

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2496]
No bueno. See relay numbers top right

https://github.com/user-attachments/assets/7f7106d0-b4e0-4b41-acae-97faf03852a3

**Comment by alltheseas** [comment]
Related: https://github.com/damus-io/damus/issues/2343

**Comment by alltheseas** [comment]
![image](https://github.com/user-attachments/assets/1d00eb18-38d3-4e95-b8ac-526a40bbba72)

**Comment by danieldaquino** [comment]
Since we have a fix and this seems serious, I added this to the 1.10 milestone.

cc @jb55 @alltheseas

**Comment by alltheseas** [comment]
> Since we have a fix and this seems serious, I added this to the 1.10 milestone.
> 
> 
> 
> cc @jb55 @alltheseas 

Agree

**Comment by jb55** [comment]
Fixed in 1e85bb946d14 (release-1.10) and 51ee4046a047 (master)
