### ISSUE TITLE
Expand search results in profile search

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2547]
**What happens**
When I search for someone I follow, they are not the top result and others I dont follow are at the top of my results.

1.10.1(1) 

![image](https://github.com/user-attachments/assets/02f32a91-8fb1-47c7-ae01-96b39ea37505)

https://damus.io/note1rnwj9m9fwq9kw048wxp798a5x06gvfgreaslg9xr3rat6ktky8dq7clppv

IOS 18.1 dev beta 4 I believe and the latest Public release of Damus

### implementation
Solution per @jb55 

- [ ] Expand search results

Context
> I think we show 20
> And profiles are sorted by most recently updated pretty sure

**Comment by alltheseas** [comment]
Related https://github.com/damus-io/damus/issues/1784

**Comment by jb55** [comment]
working on this today

**Comment by alltheseas** [comment]
@jb55 is it also possible to rank search results according to WOT score (if damus has such a metric today) or some other heuristic (e.g. rank results by count of people I follow)?

https://github.com/damus-io/damus/issues/2127

**Comment by jb55** [comment]
we don't have wot scoring yet, we just have friend and friend of friend

**Comment by alltheseas** [comment]
Can we do:

Friends first
Friends of friends counter second - i.e. show me the npub result to my search first is followed by 100 of my friends first
-//- by 10 of my friends second
-//- by 3 of my friends third

**Comment by jb55** [comment]
> Friends first
> Friends of friends counter second - i.e. show me the npub result to my search first is followed by 100 of my friends first

it already works this way btw, its just hard to notice with 20 results cap. it's 128 now.

**Comment by alltheseas** [comment]
Nice, looking forward to testing
