### ISSUE TITLE
Long press is more sensitive

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2577]

**Comment by jb55** [comment]
This is the most irritating thing about damus atm :(

**Comment by danieldaquino** [comment]
I may have been mistaken on the root cause here. There seems to be more SwiftUI weirdness to it than I thought. The interaction between the swipe actions and long press does not seem to be the only thing at play in this issue. Tracking down the problem

**Comment by danieldaquino** [comment]
> I may have been mistaken on the root cause here. There seems to be more SwiftUI weirdness to it than I thought. The interaction between the swipe actions and long press does not seem to be the only thing at play in this issue. Tracking down the problem

Nevermind, I think I found the second part of the root cause!

**Comment by danieldaquino** [comment]
Fixed! Feels much better now, submitted a PR: https://github.com/damus-io/damus/pull/2590

@jb55 Please let me know if you have any questions or concerns. Thank you!
