### ISSUE TITLE
Carousel on thread comment cannot be navigated

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2578]

**Comment by jb55** [comment]
Is this still an issue?

**Comment by danieldaquino** [comment]
I don't remember the details of this one, but upon testing it now, I am able to navigate to a thread comment when it contains an image carousel — as long as I click on the text instead of the images. This seems to be the expected behaviour to me, so I will assume this was fixed via another ticket and close this one.

**Device:** iPhone 16 simulator
**iOS:** 18.1
**Damus:** 1.12 `1072c5a3848ffee49c494ed328807bcb47261291`
