### ISSUE TITLE
Bug: TabBar buttons do not trigger a transition when already selected

### ISSUE THREAD

**Issue by jeffthibault** [damus-io/damus#26]
The buttons on the TabBar are not doing their intended transition when they are clicked while already selected.

Steps to reproduce:

1. Open Damus. The home tab button is selected by default and the home timeline is shown.
2. From the home timeline, click on a user and go to their profile. The home tab button is still selected.
3. While viewing the user's profile, click the home tab button and nothing happens.

I was expecting to be taken back to the home timeline as this is how it works on Twitter.

If this is indeed a bug, it applies to the other three tab buttons as well.

**Comment by jb55** [comment]
> While viewing the user's profile, click the home tab button and nothing happens

Which version are you testing on? Clicking home dismisses the profile view on master.

**Comment by jeffthibault** [comment]
I'm testing on 0.1.2

**Comment by jeffthibault** [comment]
Closing. It is fixed in 0.1.3
