### ISSUE TITLE
Bug: Edit banner image button not clickable

### ISSUE THREAD

**Issue by danieldaquino** [damus-io/damus#2636]
**What happens**
When I try to edit a profile banner image, I can't click on the image selector. It only seems clickable at a very small hit area at the bottom of the button.

**What I expect to happen**
I expect the  banner edit button to be clickable

**Link to noteID, npub**
N/A

**Screenshots/video recording**
N/A

**Versions**
Damus version: 1.10.x, 1.11.x, possibly others
Operating system version: iOS 18
Device: Any device? Unsure

**Steps To Reproduce**
1. Open Damus
2. Try to edit profile banner image

**Additional context**
iOS 18 introduced some gesture behaviour changes.

**Comment by danieldaquino** [comment]
Created a draft PR which I believe will solve the problem: https://github.com/damus-io/damus/pull/2705

However, I want to try writing an automated UI test to see if we can get this under automated test coverage for our CI.

**Comment by danieldaquino** [comment]
So I am working on those now

**Comment by jb55** [comment]
On Mon, Nov 11, 2024 at 07:14:26PM GMT, Daniel D’Aquino wrote:
>Created a draft PR which I believe will solve the problem: https://github.com/damus-io/damus/pull/2705
>
>However, I want to try writing an automated UI test to see if we can get this under automated test coverage for our CI.

awesome! thx

**Comment by danieldaquino** [comment]
This is basically done! I wrote the automated tests and they seem to be working as expected and passing in multiple iPhone models (I also did some negative testing to ensure the test fails without the fix).

I wrote a draft PR which I will merge soon: https://github.com/damus-io/damus/pull/2735

Only problem left is that the new UI tests don't seem to run on CI at all, they are hanging and quit before running.

Since UI tests tend to be slower than unit tests, and are more prone to flakiness in general, I am wondering if it's a good idea leaving them enabled in CI at all.

@jb55 any thoughts on whether we want the UI tests to be included in CI? Or if perhaps we can run these UI automated tests less frequently on release candidates?

**Comment by jb55** [comment]
On Mon, Nov 18, 2024 at 10:40:31PM GMT, Daniel D’Aquino wrote:
>This is basically done! I wrote the automated tests and they seem to be working as expected and passing in multiple iPhone models (I also did some negative testing to ensure the test fails without the fix).
>
>I wrote a draft PR which I will merge soon: https://github.com/damus-io/damus/pull/2735
>
>Only problem left is that the new UI tests don't seem to run on CI at all, they are hanging and quit before running.
>
>Since UI tests tend to be slower than unit tests, and are more prone to flakiness in general, I am wondering if it's a good idea leaving them enabled in CI at all.
>
>@jb55 any thoughts on whether we want the UI tests to be included in CI? Or if perhaps we can run these UI automated tests less frequently on release candidates?

it sucks that they don't work on CI, but I suspected they wouldn't.
let's disable them on CI for now I guess, but their usefulness is
greatly reduced now.

**Comment by danieldaquino** [comment]
> it sucks that they don't work on CI, but I suspected they wouldn't. let's disable them on CI for now I guess, but their usefulness is greatly reduced now.

I did a quick search this morning to see if other people use Xcode cloud for running UI tests, and there is some evidence that people have done it in the past ([1](https://forums.developer.apple.com/forums/thread/748426) [2](https://www.reddit.com/r/swift/comments/1g9nt6a/xcode_cloud_ui_testing/) [3](https://medium.com/@skr19872/xcode-cloud-c21c9377be5b)), which means it can probably be done with some extra work — it's probably just a matter of figuring out the environment differences and making some test or config changes.

Here is a plan: I can timebox 2 hours to debug and fix this, and if I can't, I delegate this to another ticket to free me to work on the other sprint items, and in that case I can run UI tests on release candidates until we have them on CI. Does that sound like a good plan?

**Comment by danieldaquino** [comment]
@jb55 I fixed the issue with CI. The UI tests are now successfully running (and passing!) on our Xcode cloud CI.

I also performed a negative test, where I locally reverted the fix and re-ran the automated test to ensure that it fails. _(This ensures that we are not simply getting blind positive results)_

I will merge the changes and close this ticket!

**Comment by danieldaquino** [comment]
merged
