### ISSUE TITLE
GIF links dont render

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2750]
See Tenor:

note1gl4u7etzccvm8q9my8w53cve99ayrh4mwlrnrah3dvwmxdy5kwfshy6rk6

note10j574gfqsxr8t3srqa8d4dl649ujtjmc6yuulpmdgqq4jxxslkks3z5ya6

**Comment by alltheseas** [comment]
note1axsgkemgsvtvmp2pm0ctlunlxjylq8ggaux8gu0c7lapvhvgukgsaqwqkz

**Comment by alltheseas** [comment]
added to 1.11 cc @danieldaquino

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqsz285crk0k5fljrf8t30ga6qgjah6udyr2r5hqya0dmtlvuf7mkmspz4mhxue69uhk2er9dchxummnw3ezumrpdejqzyrhwden5te0dehhxarj9emkjmn9qy28wumn8ghj7un9d3shjtnyv9kh2uewd9hszrthwden5te0dehhxtnvdakqexzf3g

**Comment by alltheseas** [comment]
note19j89mvnq824fh2j7s3yw65ag2nnawdtwtyup6h90ekazcdrn995sk6d3rw appears static

**Comment by jb55** [comment]
This is a tenor issue
