### ISSUE TITLE
Home button returns to Followers view after profile is selected from list

### ISSUE THREAD

**Issue by jeffthibault** [damus-io/damus#28]
Steps to reproduce:

1. Go to a user profile, for example, fiatjaf
2. Click on Followers
3. Click on a follower and go to their profile
4. Click the home button and you return to fiatjaf's Followers list

I was expecting to return to the home timeline. If this is actually a bug, it applies to the Following view as well.

Testing on Damus version 0.1.3

**Comment by bebopkid** [comment]
referenced in #27

**Comment by jeffthibault** [comment]
@bebopkid I would not say this and #27 are duplicates. Although they are similar.

**Comment by bebopkid** [comment]
You're right, I reread and see what you're saying now.

**Comment by alltheseas** [comment]
This is fixed in 1.5
