### ISSUE TITLE
Feature request: Add Ads, share the revenue with users and and an option to pay to not see Ads

### ISSUE THREAD

**Issue by bitcoinuser** [damus-io/damus#280]
Hi,

I think Damus could implement Ads in the same way that https://tweetoshi.com/ implemented it.
They share the revenue of Ads with their users and they implemented an option to pay to not see the Ads.

Quote from Tweetoshi site:

"Our business model is actually very simple!
We get revenue from ads and then share it with you - the user! You can buy premium to turn off the ads completely.

We do NOT sell any of the user's data."

**Comment by jb55** [comment]
I will not be adding ads
