### ISSUE TITLE
[bug] @note refs that appear after an image link aren't clickable

### ISSUE THREAD

**Issue by kdmukai** [damus-io/damus#288]
see: `note1lqgmxnutef5sum478wl82qvuzp3ccew8u963qqakqu043dldqhnq7edstg`

**Comment by olheadinternet** [comment]
leaving this comment so this is cross referenced on this list of note link issues https://github.com/damus-io/damus/issues/169

**Comment by jb55** [comment]
should be fixed as a long time ago
