### ISSUE TITLE
Overcoming Twitter's Network Effect Advantage

### ISSUE THREAD

**Issue by LukeParker** [damus-io/damus#29]
I know Damus isn't quite there yet but I just had a great idea to help it compete with Twitter. Overcoming the network effects (everyone's already there so it's hard to go elsewhere) will be very hard, but perhaps this idea can help Damus have a chance of growing larger than a few nerds:

 1. Set up a twitter post bot so that posts you make on Damus get auto-posted on twitter. I believe Mastodon and Gab already do this. 

 2. Forward port all all the tweets from twitter users that you follow on twitter over into Damus. This way your users can just log into Damus to read both sites' worth of content, and reply too. 

 3. Once you've got the tweet stream in Damus, you can do better with it. Make it so that users can re-order them with a better priority, because frankly twitter's algo sucks at showing you what you want to see. Therefore, you can market Damus as a way to read Twitter the way you want to read it, all the while building a better network of Damus users! The improved experience & added customization will keep users in Damus as long as they feel they aren't missing any content from twitter. Then, over time, they won't even need twitter as everyone will have come over for an improved experience.

 4. Attend twitter's funeral. Elon will be giving a touching eulogy. ;)

**Comment by jcarucci27** [comment]
What about an import feature that pulls their info from Twitter and just automatically fills out their Damus account?
