### ISSUE TITLE
post / post & replies button issue

### ISSUE THREAD

**Issue by olheadinternet** [damus-io/damus#299]
this video shows the end of the issue 

https://imgur.com/a/CioV1m3

analysis of the uncut version

start on post and replies
opens thread from post and replies
tabs over to global
scrolls randomly on global
opens a thread on global
closes thread (back to global)
returns home via bottom nav
still on post and replies
hits post - the button shows post, but the content is still post and replies
hits posts and replies - content still post and replies
hits posts again - content is now just posts

**Comment by olheadinternet** [comment]
on further testing it seems that it's simply anytime you leave home  (dm, search, notifications) when on post & replies and return back home.

**Comment by olheadinternet** [comment]
still an issue as of 1.0.0 (6)

**Comment by tyiu** [comment]
Haven't seen this happen or be reported lately. Closing for now.
