### ISSUE TITLE
Drawer is graphically buggy on macOS

### ISSUE THREAD

**Issue by hsjoberg** [damus-io/damus#317]
Hey.
The new drawer does not work properly when running the app on macOS.
Likely to not work correctly on iPads either considering the issue is related to the window width, but I cannot confirm this.

https://user-images.githubusercontent.com/3824379/212441361-427f43ae-5629-4d0d-aa1c-137b53e5c518.mov

Cheers
Hampus

**Comment by newtonick** [comment]
Can confirm same issue on MacOS.

https://user-images.githubusercontent.com/127377/212450700-9b049a85-fd87-4417-adb3-3bda14eb390a.mov

**Comment by jb55** [comment]
ugh annoying... shouldn't have assumed this would just work on macos

**Comment by hsjoberg** [comment]
Fixed in #338. Thank you @JohnBethancourt.
