### ISSUE TITLE
Unable to contine and create login

### ISSUE THREAD

**Issue by Ben-Jarvie** [damus-io/damus#34]
Testing on iphone 10xs - when I go to first create an account, I type the inputs into the form but can't exit out of the open key pad. 

This means I can't press continue and actually create the account, only re-edit filled fields or back to the starting page. 
![DAACF35A-8A9F-46A1-A3D1-CC63673E8471](https://user-images.githubusercontent.com/112665215/207679131-100c2f52-6bc7-4c11-99c8-d4b6c87e8e60.png)

**Comment by BenGWeeks** [comment]
I believe this is because you HAVE to copy to nPub to then see the nSec and continue. I agree it's not that intuitive.

**Comment by ericholguin** [comment]
The onboarding view has been updated and this no longer applies
