### ISSUE TITLE
Can no longer add insecure relay

### ISSUE THREAD

**Issue by nevets963** [damus-io/damus#344]
This [commit](https://github.com/damus-io/damus/commit/b688fa98a5498ebd7d27e59d8709af10e7b88ce2#diff-a38dacb1a8a41057dff5e3331305ea3d5cf329d2cdb9f5734c663a05850b3477R141-R144) introduces a bug where we can no longer add insecure relays. Ie. those relays using the protocol: `ws://`.

I enter: `ws://192.168.0.10`, and this gets added as: `wss://ws://192.168.0.10`.

This line:
```
if relay.starts(with: "wss://") == false {
```

Needs to be changed to something like:
```
if relay.starts(with: "wss://") == false && relay.starts(with: "ws://") == false {
```

Keep up the awesome work!

**Comment by jb55** [comment]
should be fixed as a long time ago
