### ISSUE TITLE
Insert media in notes compose screen

### ISSUE THREAD

**Issue by p2xcode** [damus-io/damus#363]
Feature request: add button in note compose screen to insert image, sound or video (from Photos or Files app) in notes, with automated upload to an http post url (configurable in settings) . 

![A22D9032-7156-4E75-B259-1F2A9A3798F2](https://user-images.githubusercontent.com/72944649/213873070-2c8473b1-50eb-4c7b-b1cd-3bec904b4cea.jpeg)

![12BA5DB5-34B2-40FC-A364-8184B5C35166](https://user-images.githubusercontent.com/72944649/213873430-718a0f0c-f7d5-42df-a2df-1c7276d00370.jpeg)

That way people can use their own server or a paid service to store the media they want to share.

**Comment by quentintaranpino** [comment]
As I say in the other issue.

https://github.com/damus-io/damus/issues/724

> "As other nsotr clients (like nostrid.app), add the option to upload files to several media servers.

[Example on nostrid.app](https://nostrcheck.me/media/quentin/65870501677748207.webp)

This is the API documentantion for nostrcheck.me public media server.

https://stitch-volcano-ac0.notion.site/Public-gallery-Rest-API-22f869bc96be4aa5a50d95364cda30ec

I think it is easy to develop and greatly improve the user experience."

On nostrcheck.me we have a public API to make it possible.

**Comment by alltheseas** [comment]
@p2xcode you happy with upload media feature on notes?

**Comment by p2xcode** [comment]
> @p2xcode you happy with upload media feature on notes?

Yes @alltheseas it’s so nice to have that!  Thanks so much!
