### ISSUE TITLE
Little quirk (<br>) in FR translation

### ISSUE THREAD

**Issue by p2xcode** [damus-io/damus#369]
<img width="534" alt="Capture d’écran, le 2023-01-22 à 15 05 31" src="https://user-images.githubusercontent.com/72944649/213937782-e59eb48d-863c-4acf-a495-81e13ffcf5ac.png">

**Comment by BenGWeeks** [comment]
FYI @tyiu

**Comment by tyiu** [comment]
Closing as fixed. I don't see `<br>` in the French translation and this issue is four months old.
