### ISSUE TITLE
Account creation: Strange number in translations

### ISSUE THREAD

**Issue by pgerstbach** [damus-io/damus#370]
When using another language than the default en_US there is a strange number shown, when creating a new account.
Du to the number the formatting is strange as well.

It seems to be there in every language other than en_US.
Here shown with language set to de_DE:

![damus-new-account-translation](https://user-images.githubusercontent.com/10688467/213938743-fc586c5f-364b-4a01-a889-597719c9aad9.jpg)

Testflight Build: 1.0.0 (9)

**Comment by jb55** [comment]
holy hell this is old lol
