### ISSUE TITLE
[FEATURE REQUEST] Undo Shaka

### ISSUE THREAD

**Issue by jblachly** [damus-io/damus#387]
Occasionally while scrolling, I (and I have heard others) have hit the Shaka/Like button inadvertently. Now, nostr being an immutable (mostly) platform, there are no take-backs (modulo NIP-09 event deletion).

However, many applications dealing with write-only systems implement "undo" functionality by delaying the commitment action for a specified period if time.

For example, if I hit the Shaka button, a request to send a signed kind 7 event can be queued up in a thread 5 seconds hence. The UI might provide immediate feedback that it's completed (or pending, but this is slightly more UI cognitive burden for the user). if the user clicks again to remove within the time window, the event can be removed from the send queue successfully.

**Comment by alltheseas** [comment]
See https://github.com/damus-io/damus/issues/932
