### ISSUE TITLE
Sometimes you can't add a relay

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#4]
I manually created this contact note with nostril so maybe I screwed something up... need to investigate.

https://nostr.com/p/3efdaebb1d8923ebd99c9e7ace3b4194ab45512e2be79c1b7d68d9243e0d2681

**Comment by bebopkid** [comment]
This is still an issue even after 0.1.8 updates to relays/settings

**Comment by alltheseas** [comment]
> I debug'd this and it seems you can't add a relay if its on the bootstrap relay list. derp. the bootstrap relay list should not be hardcoded and you should be able to remove it from your configured relays.

Adding and removing relay from bootstrap list works for me on 1.5
