### ISSUE TITLE
Zap Polls [1.2MM sats]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#402]
## User Story ##
As a pleb using Damus who would like to test a question with the other plebs AND have other plebs put sats where their mouth is, I would like to create a Zap Poll, so that I can learn the preference and sage wisdom of the plebs by testing their resolve to part with their precious sats.

### Acceptance Criteria ###
1. Pleb has capability to create a poll that allows pleb to specify a single question, and
2. Poll has two (2) to four (4) choices, and
3. Poll sports a default time out timer of 144 blocks (approximately 24 hours in fiat time), and
4. Time out timer is displayed (12 hours remaining til poll close), and
5. Poll does not show results prior to voting (as not to influence the independent judgment of the plebs), and
6. Poll contains answer counter ["55 plebs have voted"], and
7. Upon expiration of timer, poll is labeled "finished", and results are displayed [A: 80%; B: 16%; C: 3%; D: 1%], and
8. Plebs Zap voting on the poll must part with one (1) satoshi if they vote, and
9. Zap poll & one (1) sat per vote price is clearly displayed to the voting plebs, and
10. Sats go to the poll creator.

This story relates to Free Polls #401

**Comment by alltheseas** [comment]
@toadlyBroodle interested in implementing zaps for damus ser 🙏

**Comment by alltheseas** [comment]
Polls on amethyst PR:

https://github.com/vitorpamplona/amethyst/pull/321

**Comment by alltheseas** [comment]
Feedback from amethyst polls user sersleepy:

> can polls have their own notifications tab like zaps do 🙏 just seen it’s a mess on amethyst notifications

https://damus.io/note1y7pwa9ye3gx4uqcwu6vefek3mdfh7c588uf493c5hwmpc97epy7s595rm4

**Comment by alltheseas** [comment]
200k sats bounty added by Gek on nostr: https://damus.io/note12tdvrnwn56yh7s0ysuf6tlhekdk5eplu9xxpwfx80zzv2xk9kndqkydqc6

**Comment by alltheseas** [comment]
Unclear if apple allows zapping polls due to zap ban

**Comment by jb55** [comment]
On Mon, Jun 26, 2023 at 01:02:55PM -0700, alltheseas wrote:
>Unclear if apple allows zapping polls due to zap ban

anything zapping content is not allowed. this includes zap polls
