### ISSUE TITLE
Global #hashtag Search [Feature Request][Enhancement]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#406]
## User Story ##
As a Damus pleb user who is looking to search for a particular topic, I would like the capability to search for a term of interest (e.g. #bitcoin), so that I can review the targeted information I am seeking.

### Acceptance Criteria ###
1. I can search globally for a specific term (e.g. #bitcoin)
2. Damus returns all posts containing said term (e.g. #bitcoin)
3. Sort order option: reverse chronological (i.e. newest to oldest)
4. Sort order option: most zapped (i.e. most sats zapped to least sats zapped)

**Comment by joelklabo** [comment]
That should make them all tappable and you can then see posts with that tag but I didn't modify any search related things. Glad it's working though!
