### ISSUE TITLE
Read More (long notes) [Feature Request][Enhancement]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#410]
## User Story ##
As a pleb Damus user who is looking to manage my signal/noise ratio on Damus, I would like Damus to automatically cut-off notes over a certain character limit (for instance, [280](https://developer.twitter.com/en/docs/counting-characters), or 140), AND I would like the capability to click on "Read More", so that I can only obtain additional information where I am interested.

### Acceptance Criteria ###
1. Damus cuts off notes over ~280~ 140 characters in length, and
2. Damus provides capability for Damus user to click "Read More", and where
3. By clicking on "Read More" the note text is expanded beyond ~280~ 140 characters.
4. Damus user has capability to click on "Read Less" after clicking on "Read More" button to compress text.

_Sample implementations_
https://medium.com/@sdkcodes/quick-vue-how-to-implement-read-more-feature-a116b1ba48a8
https://www.w3schools.com/howto/howto_js_read_more.asp

https://damus.io/note1d49rlunaznlnttln8xv5709ymcz54yraakkffs50vcn7pxl5ty4qgs4hdt
h/t Shap npub18ax5a5qcdjrvcl0f7ehlfxhy25wrz2n597ugtgqwlyak2l2v2utselzgh0

**Comment by OlegAba** [comment]
My PR does not implement the read more feature if that's what you're asking.

**Comment by OlegAba** [comment]
@alltheseas working on this now
