### ISSUE TITLE
Improve contrast/visibility of image carousel UI [enhancement][UI/UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#415]
On posting a note with multiple images, visibility is low that there is a sideswipe option. See current state, and an example revision from a non-designer:
![old vis multi image](https://user-images.githubusercontent.com/64376233/215192405-73b2d780-77ea-4de1-ab13-77dabcf2f671.png)

![proposed new vis multi image](https://user-images.githubusercontent.com/64376233/215192307-ff172086-8e45-46cb-a6ce-e1c5d30098e9.png)

**Comment by AruneshSingh** [comment]
Hey, I recently came across damus and think it could really benefit from good design to make it more user friendly. I would love to contribute to this in any capacity. 

I am building up on your approach to make the UI more prominent. I am not sure about the guidelines for contributing, but I think I can help in this ideation. Please let me know if there's a set protocol to help with design or where is a better place to contribute. Here are my thoughts on this issue.

![Idea1](https://user-images.githubusercontent.com/43724007/215979480-022cf56f-a6d0-45ae-ad24-51cf54104398.png)
![Idea2](https://user-images.githubusercontent.com/43724007/215979473-33171465-ef78-47c0-8183-679f1fc34a28.png)

**Comment by AruneshSingh** [comment]
Will do! Thanks. How do we progress with issues like this though? Should I create more iterations?

**Comment by alltheseas** [comment]
Improved in 1.5
