### ISSUE TITLE
Display app version [Feature Request][Enhancement]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#449]
## User Story ##
As a user who is troubleshooting Damus, I want to have an easy to way to look up the app version/release, so I can know and report which app version/release I am using.

### Acceptance Criteria ###
1. As user I can look up app version/release (this could happen in settings menu: about)

![Version](https://user-images.githubusercontent.com/64376233/215810321-5bb3a482-add2-44e0-826e-4962c2f69c8b.png)

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on this issue, is it available?

**Comment by 2022H1030042G** [comment]
Do I have to fetch the app version from somewhere or I just have to display it under the settings?
