### ISSUE TITLE
Relationship between username field and NIP-05 verification field 

### ISSUE THREAD

**Issue by aChrisYouKnow** [damus-io/damus#459]
Currently as long as the NIP-05 Verification field resolves to the correct public key, the profile receives a purple verification checkmark. However, there is no way to know (as far as I can tell) if the username displayed in Damus matches the username in the NIP-05 Verification field.

As long as I have some username registered at GetAlby.com for example, I can throw that in the NIP-05 field, and then make my username whatever I want and I will still show up with a purple checkmark. 

Is this a bug, or, is this how the NIP-05 Verification is meant to work and I am just not fully understanding the intent?

Example screenshot: https://i.imgur.com/AothIcw.jpeg

**Comment by jb55** [comment]
damus should now show the full nip05 if it doesn't match the user's `name` field
