### ISSUE TITLE
Missing translation label for "Delete Account"

### ISSUE THREAD

**Issue by jesterhodl** [damus-io/damus#470]
After translating all labels this one remains in english.
![B5AC6088-45E6-4F48-97A5-9A96A6C90D44](https://user-images.githubusercontent.com/103882255/216004916-7764299f-e646-453f-ad40-cf3d5a765b3c.jpeg)

**Comment by tyiu** [comment]
https://github.com/damus-io/damus/pull/515 should enable it to be translated.
