### ISSUE TITLE
中國人 Damus Strings Chinese Translation [Enhancement]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#473]
h/t @tyiu 

_I’m seeing a good percentage of notes in Chinese on the global feed. Anyone want to volunteer to translate #Damus app strings to Chinese? I’m unfortunately and embarrassingly not fluent in the slightest despite my background._ 

https://explore.transifex.com/damus/damus-ios/

https://damus.io/note1rqrc0l6klu3d69vzx5n5n58cpjcv0wvasref5l7chd5s96zhsxus9q6ypu

**Comment by tyiu** [comment]
https://github.com/damus-io/damus/pull/483

**Comment by qsgy** [comment]
你们是如何下载app的？我在国内，显示所在国家不提供此APP
