### ISSUE TITLE
home page spins infinitely 

### ISSUE THREAD

**Issue by murdawkmedia** [damus-io/damus#48]
After login in damus.io/web with either public or private hex key everything is blank. The home page just spins and spins. All other tabs are plain empty.

I use Firefox but did also try a private tab and even... Microsoft edge. Same result.

Originally created on:
Astral ninja

Managed to upload picture using:
Anigma

My pubkey:
045a6fa0da5d278ac1c3aee79df23b7372ea03ee4da04ad4b8db9a5967f32334

![Screenshot_20221217-140630](https://user-images.githubusercontent.com/119478503/208267733-6d201356-3da1-47d5-8ccf-21ce36dd939c.jpg)

**Comment by jb55** [comment]
this repo is for damus-ios, could you reopen this in https://github.com/damus/website? thanks!
