### ISSUE TITLE
Search Notes for Keyword [NIP-50][500,000 sats]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#493]
## User Story ##
As a Damus user looking to search for a particular keyword, I would like the capability to search all notes for that keyword, so that I can filter to notes with the keyword I am searching for.

### Acceptance Criteria ###
1. User can search all notes for a particular keyword
2. Damus returns a reverse chronological order filter view with notes containing that keyword
3. Damus highlights keyword
4. Support option for multiple NIP-50 providers
5. Local search https://github.com/damus-io/damus/issues/1760

See NIP-50: https://github.com/nostr-protocol/nips/blob/master/50.md

mockup:
![global note search](https://user-images.githubusercontent.com/64376233/216435692-c1ef62f2-55d7-41a1-a11d-38738b9775c9.png)

**Comment by brugeman** [comment]
There is a bounty here now: https://nostrbounties.com/b/naddr1qq9rzd3cxgungwfjxcmqygpn2m0xrvukg7f3e69jzs9jh2ur0cypps8029dmayk7qfyqgzutm5psgqqqw4rssvx9yw

**Comment by alltheseas** [comment]
https://damus.io/note1k3g32usmezhkgmjrxv39qu6rt6g6eahwkeywltg8603mnltelzmscz29h9

**Comment by jb55** [comment]
Will be able to do this locally with fulltext search in nostrdb

**Comment by alltheseas** [comment]
See search relay by semisol currently for kind1 only

https://damus.io/note1jr7dgwn98da30wynwkunhy8kgslqey6qknhfm576ppq4ceftpcmqalye7f

> relay.noswhere.com
real time, 👀

**Comment by jb55** [comment]
We can search notes for keywords, lets create more granular tasks for the remaining things (nip-50 remote search, highlighting keywords, etc)
