### ISSUE TITLE
can't follow, can't manage relays

### ISSUE THREAD

**Issue by mrhopelee** [damus-io/damus#506]
my account can't follow any one and can't manage relays.
but it's work when i switch to other account on same phone,same network.
my account(issue): npub1acghm944nnkszg3exnshv0wdk522lk7amt4hc9caldrljquau82qyqzysq

other account(work): npub1p7ly9d5ywlc85fhjr7t02dpep7w7hu3645twmykkv94hvdylzdusy82u8t

device: iPhone12 ios16.2

**Comment by olsen-sorensen** [comment]
same

**Comment by lukehoersten** [comment]
Same issue on the App Store version

**Comment by 35pe** [comment]
had the same issue. a possible workaround is to login via a web client. specifically, snort.social reset my relay list with its own default relays and after that damus was working as expected.

**Comment by olsen-sorensen** [comment]
Figured that out as well, that solves the issue. Btw: I had to try two different web clients.

**Comment by mrhopelee** [comment]
> had the same issue. a possible workaround is to login via a web client. specifically, snort.social reset my relay list with its own default relays and after that damus was working as expected.

thank for your answer. 
i try to use other nostr client (like https://astral.ninja), it is work now.

The first time I used the NOSTR network client, in the setting page(https://astral.ninja/settings), found some relays in the list that are read-only. change all relays from read-only to read-write, and then follow and manage relay is work on damus app.
