### ISSUE TITLE
Is this app only made for ios?

### ISSUE THREAD

**Issue by Designer247** [damus-io/damus#508]
Hi ,I think it's a very nice application, I hope you can design cilents for desktop and android. Thank you!

**Comment by tyiu** [comment]
@Designer247 Damus is for iOS, iPadOS, and macOS. Damus is only one of many clients that implement the nostr protocol.

Please try these ones.

Desktop: https://snort.social/
Android: https://play.google.com/store/apps/details?id=com.vitorpamplona.amethyst
