### ISSUE TITLE
Support NIP-10 for client interoperability (thread rendering) (50,000 sats)

### ISSUE THREAD

**Issue by ok300** [damus-io/damus#528]
Damus currently uses positional "e" tags to mark the root and the parent in threads.

Other clients like Gossip already support NIP-10[^1], which deprecates positional "e" tags in favor of marked tags.

This leads to different rendering across clients for threads or standalone notes referencing another note.

---

Here is an [example](https://www.nostr.guru/e/994a81e7d5137c6fb2e663c91d9436aa32c247f1ae5105c34de924b76cdf51f2).

The note JSON is

```json
{
  "id": "994a81e7d5137c6fb2e663c91d9436aa32c247f1ae5105c34de924b76cdf51f2",
  "pubkey": "00000000827ffaa94bfea288c3dfce4422c794fbb96625b6b31e9049f729d700",
  "created_at": 1675572483,
  "kind": 1,
  "tags": [
    [ "p", "d5bd2aedd006cf7eda5f39a84c0c1bb98e5f9ac97094631b0ef533d67a0d3896" ],
    [ "e", "ec37c20a54921f48586b4314ea324d499c61649d923615f679684f721c4438c7" ]
  ],
  "content": "Follow #[0] if you haven’t yet and stay tuned to all things Nostr Land!\n\n#[1]",
  "sig": "ce5b4c1dbc844b8e7da96f5061be174ea0f46227a5550574cde2bc4f1380f1ba56fa2fb5ce189ecc2a186fd76deffe0483612a72c6f6dbdbdd12a078901eab7b"
}
```

In Damus, Cameri's comment appears as standalone note referencing another note:

![damus-reply](https://user-images.githubusercontent.com/106775972/216808870-27f71895-741b-4c14-9611-2f73053ddb51.png)

In Gossip, it appears as a reply in a thread:

![Screenshot from 2023-02-05 09-19-10](https://user-images.githubusercontent.com/106775972/216808888-f7763603-dc6a-408c-bf17-faffb87a3f29.png)

In iris.to it also appears as a reply in a thread: 

![iris-reply](https://user-images.githubusercontent.com/106775972/216809372-12853219-52a0-4b95-bca0-a5d5ba66419d.png)

[^1]: https://github.com/nostr-protocol/nips/blob/master/10.md

**Comment by alltheseas** [comment]
@tyiu advised

https://github.com/nostr-protocol/nips/blob/master/10.md

> The issue is that Damus supports only the old deprecated way of positional event tags, which is that the last tagged event tag is the event that is being replied to. Amethyst supports the new way, which is that each event tag explicitly defines what kind of marker (reply, root, or mention) without needing to rely on event tag ordering. Damus just needs to be fixed to support the new way.

**Comment by alltheseas** [comment]
https://damus.io/note1pvr9wpcqmv5089naln5rsjw2ev6klxnqsn9klrrr3ekdgvzqt9cq4klw9u 50,000 sats bounty posted by Daniel

**Comment by jb55** [comment]
PR open:

- #2190

Just need a few more tests before we merge
