### ISSUE TITLE
[Join the waitlist]  in the web is fail

### ISSUE THREAD

**Issue by Huang-Seven** [damus-io/damus#536]
Hi, sir,  thanks
![image](https://user-images.githubusercontent.com/22721677/216873091-7f707add-e9c3-4007-8a66-aec786d25fad.png)

![image](https://user-images.githubusercontent.com/22721677/216872882-4ceab572-ed4d-439a-bfc8-37d6571e347d.png)

**Comment by alltheseas** [comment]
Try damus.io/testflight
