### ISSUE TITLE
Also provide keys in hex

### ISSUE THREAD

**Issue by dbuytaert** [damus-io/damus#579]
I created a key-pair using Damus, and want to use it with other Nostr tools like `noscl`.  

Damus shares my keys using `npub` and `nsec` (bech32), but most tools expect keys in hex.  

NIP-05 identification/verification also requires hex (https://github.com/nostr-protocol/nips/blob/master/05.md).

It would be great if Damus also shared my keys in hex, as I haven't found a quick way to convert them yet.

**Comment by alltheseas** [comment]
> I created a key-pair using Damus, and want to use it with other Nostr tools like `noscl`.
> 
> Damus shares my keys using `npub` and `nsec` (bech32), but most tools expect keys in hex.
> 
> NIP-05 identification/verification also requires hex (https://github.com/nostr-protocol/nips/blob/master/05.md).
> 
> It would be great if Damus also shared my keys in hex, as I haven't found a quick way to convert them yet.

@dbuytaert does this tool on damus website solve your issue: https://damus.io/key/
