### ISSUE TITLE
Profile view: Can't see LN button and DM button icons when in dark mode

### ISSUE THREAD

**Issue by domegabri** [damus-io/damus#59]
#### Version

- Running 0.1.7

#### How to repro

- Set dark mode in iOS settings
- Navigate to profile view

![signal-2022-12-19-193349_002](https://user-images.githubusercontent.com/42006886/208495962-f4e63e9b-ef72-4e79-b8b9-4800d4689f2e.jpeg)

**Comment by joelklabo** [comment]
This should be closed now I think @jb55

**Comment by domegabri** [comment]
fixed in eb0b1061d8f97d0cd4e8adc5bf5e9574e9f81e1d
