### ISSUE TITLE
Minor spacing issue on welcome screen carousel

### ISSUE THREAD

**Issue by jeffthibault** [damus-io/damus#6]
Nice job with Damus! 😃 
I noticed this small bug while testing it out.

On the welcome screen, the third item in the carousel is tight to the indicator dots while the others have some spacing.

<img src="https://user-images.githubusercontent.com/30011264/180872136-0e304524-a55c-4731-a08a-cb8ed4f25e9e.jpg" width=25% height=25%>

**Comment by jb55** [comment]
yes I've noticed this as well... I'm still a swiftui noob and not sure what the best solution is here. not sure if I'll get to this anytime soon so if someone wants to take a stab at this that would be great :)

**Comment by RandyMcMillan** [comment]
I am taking a look at this now
