### ISSUE TITLE
View Followed Hashtags

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#606]
## User Story ##
As a pleb Damus user who is excited to follow a particular #hashtag, I want the ability to follow a #hashtag, so that Damus feeds me instantaneous updates of this #hashtag to my feed

### Acceptance Criteria ###
1. ~User can follow a hashtag~ ✅
2. ~Notes with hashtag displayed on home view~ ✅
3. *User can see all their followed hashtags*
4. ~User can unfollow a hashtag~ ✅

"_`Can we have follow feature for hashtags? Instagram has similar feature already 👀`_"
-bitcoinbull@nostrplebs.com

"_`Ya we should`_"
-Will

https://damus.io/note1qj7wtx86824fydvum2kanyq57dmq00622nqgkcjpql0mhgjswu3qpp5afd

_Questions_
1. Should there be a hashtag view, separate from home view? ✅
2. Where can user see, and edit all their followed hashtags?  ✅

**Comment by alltheseas** [comment]
cc @garyray-k

**Comment by alltheseas** [comment]
@jb55 implemented 1. 2. And 4.

3. See all followed hashtags remaining

**Comment by danieldaquino** [comment]
Created a patch for this!

Discussion, testing report, and code changes can be viewed at: https://groups.google.com/a/damus.io/g/patches/c/O2C2N8AuHHY

@robagreda, I was not 100% sure whether to make the follow/unfollow button pink (in the style of the hashtag page), or black (to match the current person follow button).

The Figma reference designs seemed to indicate that these buttons should be pink, and I also thought it looked better, so I chose pink. I attached a screenshot to [the patch I sent on the group](https://groups.google.com/a/damus.io/g/patches/c/O2C2N8AuHHY). I believe you can also view it in [this link](https://11334440997308283206.googlegroups.com/attach/22823e8b71e5c7/Simulator%20Screenshot%20-%20iPhone%2014%20Pro%20-%202023-09-20%20at%2015.02.28.png?part=0.1&view=1&vt=ANaJVrFrWPo8ScJ8TWOpdS9ShhHg5rYJ67MZBk2H6hB2DWnqs93j6qnweiZcYvegpy81dHU33DRCLiAytiZ7dIskRdVa-QPPL18Kj9NZaf_YO1egm-ZaP_E)

Please let me know if you have any suggestions. Thank you!
