### ISSUE TITLE
Home button should focus on top of most recent post, not bottom

### ISSUE THREAD

**Issue by Synesso** [damus-io/damus#610]
If the most recent post is greater than one screen in length, tapping home will align to the bottom of the post, making the top of the post above the fold

It should focus on the top of the post so it can be read without further scrolling

**Comment by Synesso** [comment]
When
https://damus.io/note1xnjwatav5ehm9hlezz830paway86xpd7mpydzeqm70cxrvchj4sshs0wpa
was most recent in my feed. Iphone 8

**Comment by OlegAba** [comment]
Fixed in #570
