### ISSUE TITLE
Multi-threaded incoming event refactor 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#618]
### Multi-threaded incoming event refactor

In context of [verifying incoming nostr events](https://github.com/damus-io/damus/issues/617) by Damus battery drain, performance, UX (stutter, lag), and multi-threaded support are all related. 

_"might be ok once i have a multithreaded event ingress setup, but its a non trivial refactor and would definitely use more battery. Not saying I don't want to verify everything but i had it on before and you could barely even scroll the view."_

https://damus.io/note129nzwd8tpquvsz5vh3s372tq9sxnnhqsvr0qme7eqvwq6pezgs8svjcwjd

See related ticket https://github.com/damus-io/damus/issues/617.

**Comment by alltheseas** [comment]
Did you make progress on this @jb55 ?

**Comment by jb55** [comment]
yes nostrdb does multithreaded note processing

**Comment by alltheseas** [comment]
nostrdb https://github.com/damus-io/damus/issues/1406 

> yes nostrdb does multithreaded note processing

any other places where you will add multi-threaded support? should we close this ticket?

**Comment by jb55** [comment]
On Thu, Nov 16, 2023 at 09:15:07PM -0800, alltheseas wrote:
>nostrdb https://github.com/damus-io/damus/issues/1406
>
>> yes nostrdb does multithreaded note processing
>
>any other places where you will add multi-threaded support? should we close this ticket?

sure, I'm not sure what this ticket is for tbh
