### ISSUE TITLE
Going back to Global feed from a note sends you to top instead of where left off

### ISSUE THREAD

**Issue by bebopkid** [damus-io/damus#62]
While scrolling the Global Feed, if I click a note, then go back to the Global Feed (whether swiping back or clicking `< Global`) it sends me to the top of the feed, and then I have to scroll all the way back down to pick up where I left off. This doesn't happen in the personal feed which is nicer and more like what I expected.

**Comment by alltheseas** [comment]
fixed in 1.7 (or earlier versions)
