### ISSUE TITLE
Singular Zap (remove "s" when only 1 zap) [fix][grammar]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#647]
Remove "s" when there is only one zap.

![image](https://user-images.githubusercontent.com/64376233/219885266-5e403618-d16e-4180-9501-20445a12f6eb.png)

https://damus.io/note17ljlpfqsr9n56vj0qhxxwtfp36dw5n33k80phffftd0aj27wruhswzpdsm

**Comment by tyiu** [comment]
Fixed with https://github.com/damus-io/damus/commit/06a1a9aba6f9ee54350d9a64d6897193c2e18f23
