### ISSUE TITLE
In multi-comment thread, same user is tagged multiple time in replies [Bug][UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#673]
In a multi-comment thread where a single user replies in multiple comments, if Damus user replies several comments down in thread, the other user is tagged more than once.

No user should be tagged more than once in replies to notes.

See video:

https://user-images.githubusercontent.com/64376233/220706184-96a0ef5a-fc30-44a7-986e-c82b9d4af891.mp4

**Comment by joelklabo** [comment]
Thanks! @alltheseas

**Comment by joelklabo** [comment]
Just put up a PR 🤙

**Comment by joelklabo** [comment]
This got merged, I think we can close it @alltheseas
