### ISSUE TITLE
https://damus.io/note link in damus opens up Snort.social, and not in Damus 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#690]
_What happens_
When clicking on a https://damus.io/etc link in Damus app, the default behavior is to open snort.social, and not open the link in Damus app same as @note type link.

_What I think should happen_
https://damus.io/etc note link should open in Damus app, not in an external browser client like snort.

Video:
https://user-images.githubusercontent.com/64376233/221256564-11411c2c-f99f-4988-841e-0460c9c48462.mp4

Link:
https://damus.io/note1hgdgp4wc8kmvc2ya63pxa27n4yyc8wz44v359xknht6wekgsk7nslp4z3t

**Comment by bryanmontz** [comment]
@alltheseas I'm working on this. 🙂

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/896

**Comment by alltheseas** [comment]
Issue persists

**Comment by bryanmontz** [comment]
Fixed in this PR, but initially Will wanted to fix it a different way. I wonder if he'd reconsider, at least for now.

https://github.com/damus-io/damus/pull/896

**Comment by alltheseas** [comment]
https://ogp.me/

**Comment by jb55** [comment]
> Fixed in this PR, but initially Will wanted to fix it a different way. I wonder if he'd reconsider, at least for now.
> 
> #896

now that we parse urls we can just check if its a damus url and render a mention link instead. this should be super simple. doing this now

**Comment by jb55** [comment]
we have two options:

1. leave the links as in and render them as mentions
2. convert them to actual mentions during post composition and parsing.

maybe 2 is better

**Comment by jb55** [comment]
the downside of 2 is that you can't share damus links over DMs and stuff... but at least you can always go to the note and then click share from there.
