### ISSUE TITLE
Add support for webp files

### ISSUE THREAD

**Issue by quentintaranpino** [damus-io/damus#704]
When you paste a URL into Damus with a webp extension file, it is not displayed by the application's internal viewer and takes you to the original image server.

**Comment by quentintaranpino** [comment]
Hello @alltheseas 

As you can see the webp shows the entire URL before the image, and also when you click the image don't load as a popup (inside Damus), but it goes to the URL server destination, as a normal URL.

I don't know if I'm explaining myself :)

**Comment by dmnyc** [comment]
Seconding this. Webp is already supported on web clients like snort.social. Damus should display webp images the same way as gifs and jpegs.

**Comment by dmnyc** [comment]
The same issue is present for MP4 files.

**Comment by jb55** [comment]
Fixed in 1.4.3-20
