### ISSUE TITLE
Hashtags should be case insensitive [bug][UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#708]
What happened:
Hashtag's are case insensitive.

What should happen:
Hashtag search should be case insensitive. #DAMUS should return same results as #damus, as #Damus etc.

Example: https://damus.io/note17zcpfrevs0ug9frr2nt0lkcv4t8z4gcl2ksahsqzv4ykuzxlrpusd00y04
Origin: @RandyMcMillan 
<img width="779" alt="Screenshot 2023-02-28 at 2 36 11 PM" src="https://user-images.githubusercontent.com/64376233/221973379-3d301cba-c1dc-499e-90de-e860d26e6c06.png">

#damus (lowercase)
![image](https://user-images.githubusercontent.com/64376233/221972121-4842e03a-ac78-49b4-86c4-da83ac3320ff.png)

#DAMUS (ALLCAPS)
![image](https://user-images.githubusercontent.com/64376233/221972152-447e7ee6-3782-4f16-bc15-35b58e51f93e.png)

#Damus (proper capitalization)
![image](https://user-images.githubusercontent.com/64376233/221972178-93229595-ab06-41e2-bc1d-1ba75eac2e51.png)

**Comment by RandyMcMillan** [comment]
just noticed this... taking a look.

**Comment by RandyMcMillan** [comment]
https://github.com/damus-io/damus/commit/06c2741bf4637c7697bc03aef0196824c481f6c4
