### ISSUE TITLE
Cursors jumps when writing a note when pressing "Return" [Bug][UX]

### ISSUE THREAD

**Issue by lima46zulu** [damus-io/damus#728]
When clicking on "return" the cursor jumps to the end of the text. See video. 

This also happens when selecting say the last sentence of a paragraph and hitting enter. The text will be removed, as expected, but then after the cursor will jump to the end of the text. 

https://user-images.githubusercontent.com/109115349/222574168-84d762f6-4c57-48ca-986b-047b157e940b.mp4

**Comment by dmnyc** [comment]
Confirmed - same issue in replies.
https://github.com/damus-io/damus/issues/747
