### ISSUE TITLE
Phantom Scrolling in Context Menu [bug][UX]

### ISSUE THREAD

**Issue by lima46zulu** [damus-io/damus#730]
First, the context menu should show all rows as there's clearly space on the screen to display 2 more rows. 

But When scrolling is required (ex: smaller screens), there's an issue with the context menu. When trying to scroll to show "block" for example, the context menu returns to the top on its own. 

The scrolling issue appears to be limited to the Universe screen. I have not been able to replicate in my feed. 

https://user-images.githubusercontent.com/109115349/222802676-b465e9d4-574a-436d-9c33-f86598a37725.mov

**Comment by jb55** [comment]
This is an ios thing and not anything we have control over
