### ISSUE TITLE
In reply thread of long notes: "Show more" does nothing [bug][UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#745]
_What happens_
In reply threads to long notes, "`Show more`" is displayed as an option. However, tapping on "`Show more`" does nothing.

_What I think should happen_
1) If there is a "`Show more`" option, then tapping on "`Show more`" should expand the note
2) There should be an easy way to go back to reply compose/keyboard and draft note view from "`Show more`" view

Alternative: remove "`Show more`" from replies in thread

See screen record:
https://nostr.build/av/nostr.build_f8871e7cf8a416c37060cd4add1079d054e56047e83b3c2e31cc9146ab4cae56.mov

Example long note:
https://damus.io/note1ac6y9nga6e0k3vqc5k8dqfjtxa2kkpty7dv9umk9z4778msfg4fsc4twl5

_Related to_
#715 
#410 

cc @OlegAba

**Comment by BenGWeeks** [comment]
Yeah, this goes to a screen with the post, however, I think default action should expand it. On the list to do shortly.
