### ISSUE TITLE
Mentions don't work in the middle of a note when writing a new note 

### ISSUE THREAD

**Issue by lima46zulu** [damus-io/damus#769]
When adding a mention in the middle of the note, adding the @ won't trigger the username list to appear and the @username will just be text. 

For example, if I type: 

> Hello
> How are you fren?

Then adding a mention after Hello will not work. The workaround is to delete all the text after the mention and rewrite or past it. Mentions only seem to work when the @ is the last character of a note. 

![IMG_5137](https://user-images.githubusercontent.com/109115349/224406837-22a57630-aba1-4152-8936-84a6acf27fef.jpeg)

**Comment by dmnyc** [comment]
I recorded an example of the issue I mentioned above.
https://nostr.build/av/nostr.build_b7306f9831d2db9e1237ff9a2fa386374be36ed475bb785277f88e699a775866.mov

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/775

**Comment by alltheseas** [comment]
This seems resolved in 1.6 (19)
