### ISSUE TITLE
Need UI to show relay was added successfully 

### ISSUE THREAD

**Issue by bebopkid** [damus-io/damus#78]
Only 4 relays are displayed and there is no way to know if a 5th or more are added successfully

**Comment by StevenBlack** [comment]
I'm seeing seven relays, which is the number of relays I've got.

The issue appears to be, need to navigate away from the Settings screen, then come back, for that list to refresh.

**Comment by bebopkid** [comment]
I've been using Damus for a week and a half and have never seen more than 4 relays. I've added and removed and it's not changed.

**Comment by StevenBlack** [comment]
Tyler @bebopkid have you pulled latest from TestFlight?  

![IMG_EF592D505318-1](https://user-images.githubusercontent.com/80144/208979238-32462f97-42f0-4b1f-8ba7-13697755e085.jpg)

**Comment by bebopkid** [comment]
Yes, running 0.1.7. Ok, so I've been losing relays but the ratio near the gear icon was saying 9/10 so was assuming that relays were missing from settings. Realizing that 9/10 doesn't mean 9 out of 10 relays are running...😅
