### ISSUE TITLE
Multiple QR scans [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#791]
_What happens_

When I scan a QR with a npub on it, and I scan a second QR what another npub on it Damus takes me to the first npub's profile (or another screen if I clicked out of npub/profile view), and does _not_ take me to the second npub's profile page.

Closing and opening Damus fixes this.

_What I think should happen_

When I scan a QR with a npub on it, and I scan a second QR what another npub on it Damus should take me to the second/latest npub's profile page.

**Comment by alltheseas** [comment]
@tyiu PR https://github.com/damus-io/damus/pull/1130

**Comment by danieldaquino** [comment]
@alltheseas I believe this one is not applicable anymore. The QR code scanner no longer takes the user directly to a profile page, and instead shows them a profile sheet with quick actions (follow/dm), and dismissing that sheet immediately allows the user to scan another QR code.

**Comment by danieldaquino** [comment]
@alltheseas please feel free to reopen if you disagree
