### ISSUE TITLE
Support hls streaming files

### ISSUE THREAD

**Issue by futurepaul** [damus-io/damus#798]
Damus could support self-published video streams if it could understand .m3u8 extension. Should be able to use the native OS. Here's a test case using an example from Apple:

https://developer.apple.com/streaming/examples/

note1tp0r3jn49u785vqp7jgr7un0p60ud9kcnqkfnkmx7pm3pdzuj4dqc5h087

Here's the underlying video the .ts file directs to:

note1a0akhl7e3rf80qtx5xzaxpdvnlva6hwxqzm2xqmwhwh45u6n3enqcj8sum

So it plays fine it's just understanding the format so the native player can take over

**Comment by bmewj** [comment]
To provide a little more context, the video player built into iOS supports Apple HLS by default. Any valid `.m3u8` file can be attached as a source and it will be handled properly, adaptive bitrate and all. All that’s needed on the implementation side is to recognise the extension alongside regular `.mov`,`.mp4`, etc… as a video file and instantiate a video player

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/1372

**Comment by alltheseas** [comment]
Confirmed livestream worked today.
