### ISSUE TITLE
Prevent Damus from displaying blank lines when multiple images are linked in a note

### ISSUE THREAD

**Issue by dmnyc** [damus-io/damus#812]
In notes containing more than one image, each URL requires a blank line to be displayed above the image gallery. 

If possible, these should be hidden from the user. 

Example note ID:
note1sxqtanrxpalhgx624qny2x7lfdag76wjgvs4pzdm0plreu6v275s2jgm6n
![image](https://user-images.githubusercontent.com/3638467/227822616-c9e6888f-43e8-4ba6-8526-c14bcb3140a3.jpeg)

**Comment by dmnyc** [comment]
I'm pasting links directly from nostr.build, not using the Damus image upload button.

**Comment by jb55** [comment]
I think this is fixed?
