### ISSUE TITLE
Add PFP upload shortcut capability in profile edit screen [feature request][UX][newbies][onboarding]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#813]
## User Story
As a new Damus user who is onboarding to Damus, I would like a way to easily upload a profile picture of mine in the profile edit screen, so that I don’t have to leave the app to use a third party service to upload my profile picture.

_Acceptance Criteria_
1. In profile edit view, there is a visible, and easy way to upload a profile picture (I.e. same as upload media icon in create post view)
2. This capability is adjacent to the profile picture URL box
3. When user taps the media icon, they can upload a PGP from their device
4. Damus utilizes default third party service to host PFP (e.g. nostr.build)
5. Utilize specific PFP upload link from nostr.build: https://nostr.build/profilepic.php 
API link to follow from nostr.build

_Mockup_
![PFP UPLOAD](https://user-images.githubusercontent.com/64376233/227993156-98108ab9-27d6-4c5d-af66-8ba686a0178d.png)

**Comment by joelklabo** [comment]
#849
