### ISSUE TITLE
Allow selection of notification content

### ISSUE THREAD

**Issue by h3zjp** [damus-io/damus#817]
Currently, all content (replies, likes, DMs, Zaps, etc.) are notified regardless of the content of the notification, but we would like to be able to select what to notify.
I would like to hide items that do not notify me from the notification field as well, so that I can use the system comfortably.
Thank you for your response.

**Comment by h3zjp** [comment]
Example：Twitter
![https://ul.h3z.jp/j4MIcy9Y.jpeg](https://ul.h3z.jp/j4MIcy9Y.jpeg)

Instagram
![https://ul.h3z.jp/2npL1IxB.jpeg](https://ul.h3z.jp/2npL1IxB.jpeg)
![https://ul.h3z.jp/fpuQ53ih.jpeg](https://ul.h3z.jp/fpuQ53ih.jpeg)

**Comment by h3zjp** [comment]
👍
We look forward to your release! 🎉

**Comment by h3zjp** [comment]
Newly implemented notification settings, but is there no setting item for the notification field in the lower right corner of the screen instead of push notification settings?
Changing the settings in the notification field is more important than push notifications.
(I don't care about push notifications, so please implement changing the notification field settings as a priority.)

**Comment by h3zjp** [comment]
Newly implemented notification settings, but is there no setting item for the notification field in the lower right corner of the screen instead of push notification settings?
Changing the settings in the notification field is more important than push notifications.
(I don't care about push notifications, so please implement changing the notification field settings as a priority.)

**Comment by alltheseas** [comment]
Thanks for opening up the issue again. Sorry for the misunderstanding. 

You say 
> notification field

Can you kindly provide a screenshot of `notification field` to make sure I do not understand your request 🙏 .

**Comment by h3zjp** [comment]
Sorry for the confusing wording here.
I meant the "bell mark" icon in the lower right corner of the screen, which you can see on the notification screen.
Thank you for your response.
![https://ul.h3z.jp/AmHtYADr.jpeg](https://ul.h3z.jp/AmHtYADr.jpeg)

**Comment by alltheseas** [comment]
Does the notification dots setting resolve your issue?

**Comment by h3zjp** [comment]
Thank you for implementing this new feature!
Now I can use it without worrying about notifications because it is no longer marked!
Thank you for your support.
