### ISSUE TITLE
Cache Translations [performance][technical]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#820]
Caching translations should reduce the number of API calls users use to translate foreign languages on Damus. DeepL has a monthly API limit, which may be triggered if there are inefficient translations. For instance, one user participating in a thread with multiple replies over previous periods in time may use many API credits for translating the same note over again.

> it also looks like damus doesn’t cache translations, we should do otherwise it translates things more than it needs > to @tyiu 
-Will

Damus.io/note16awggkz7xuq5emlfz0ug3p3w9z7v4cufr2u92rsrq6ftfwk5ytvqsudzum

![User on Iris it also looks like damus doesn’t cache translations, we should do otherwise it translates things more than it nee](https://user-images.githubusercontent.com/64376233/228355534-3999c6e9-c765-424e-b26d-49c91164dbdb.png)

**Comment by tyiu** [comment]
#843 was reverted due to crash bugs and superseded by https://github.com/damus-io/damus/commit/c5341ba3378ca6b17589cfdd16fd369863f109d5
