### ISSUE TITLE
Integrate nostr.build login to Damus for creators [NIP-98]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#823]
## User Story
As a Damus, and nostr.build premium user/creator, I would like a capability to directly log in & remain logged in to nostr.build while using Damus, so that when I upload images & videos via Damus they are automagically added to my paid nostr.build account.

### Acceptance Criteria
1. Damus user can log in to nostr.build using their credentials via Damus, and
2. After log in, when uploading media directly through Damus sends information to nostr.build, that allows nostr.build to associate uploaded media with the logged in account

**Comment by quentintaranpino** [comment]
In nostrcheck we have a field called apikey (which is generated when a user creates his account), if a file is uploaded using a user's apikey it is placed in the corresponding gallery. Something similar could be applied for them. 

By the way, it would be very interesting to integrate with us as we have it all set up :)

**Comment by alltheseas** [comment]
@fishcakeday investigating NIP-98 integration for nostr.build

**Comment by jb55** [comment]
On Mon, Jul 31, 2023 at 06:01:56PM -0700, Fishcake wrote:
>I’ll be working on this one in the coming days

I've added you to devs, so if you want to assign yourself to the task and join the current sprint you can do so now.

**Comment by jb55** [comment]
Fixed in c464a26151046e17cd469f390a3212b8af1c9c8e
