### ISSUE TITLE
Dont cut off portrait pictures [UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#825]
_what happens_ 
Portrait pictures are cut off vertically 

_what I think should happen_
Portrait pictures should not be cut off vertically. 

![image](https://user-images.githubusercontent.com/64376233/228379612-38b464e9-ce93-4b76-81b7-d394fa356423.jpeg)

Cc @BenGWeeks @tyiu

**Comment by kristapsk** [comment]
Agree on this, I would also prefer that way.
