### ISSUE TITLE
[Feature Request] Option to change the font size

### ISSUE THREAD

**Issue by kdmukai** [damus-io/damus#83]
Bonus: wire up `CMD +` and `CMD -` hotkeys (same as browser font size adjustment).

**Comment by bryanmontz** [comment]
Since this would affect views all over the app, I'd prefer to get @jb55 to weigh in and make sure this is desired before taking it on.

**Comment by alltheseas** [comment]
3 million sats bounty will do it


https://damus.io/note19r377z58mww5w9s5mygatx4g4qcnum3kgac5f7fcgdfkcr9fwmxsp58796

https://damus.io/note1uvstn69c4wv4kyvfakavy8s4w55fmmfmdvqfm5psjvym68jn24zsgy2q42
