### ISSUE TITLE
Share link on device without Damus is broken on snort [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#831]
> Having trouble opening Damus share links on devices that don’t have Damus. They try to open in the Snort web client, but then show this error:

Recreated bug: 
![image](https://user-images.githubusercontent.com/64376233/228629661-9342e146-b5b6-4e99-ac3d-0090b7101d6d.jpeg)

https://nostr.build/i/nostr.build_d13c29b8f4476e890d167979607d1d256b0191d56e90098aaa602aad2f6e81da.jpg

https://damus.io/note1kgm95qx3kghnsp09l7t7ssws7zpt604pdaqgeqnj75c63ezzv0pq8zyqxt

**Comment by v0l** [comment]
Fixed in https://github.com/v0l/snort/commit/d24fc579629de1ea91c3d2116e7b33445e33360d
