### ISSUE TITLE
"Repost" does not work with Damus 1.4.0

### ISSUE THREAD

**Issue by kristapsk** [damus-io/damus#841]
Ever since I updated to v1.4.0, "Repost" does not work. Icon turns green, confirmation dialogue for repost appears and when I confirm repost by clicking "Repost", app just crashes. Have tried it multiple times with multiple different notes.

iPhone 7, iOS 15.7.3.

**Comment by OlegAba** [comment]
@kristapsk what's your npub?

**Comment by kristapsk** [comment]
> > @kristapsk what's your npub?
> 
> npub1vxpwwydpmmc4usmxf2zkr8shdjq888g532ydyls3nadxxd9wyx5ssjq5nd

Yes, that's correct!

**Comment by OlegAba** [comment]
Hmm I'm not able to reproduce. Maybe @jb55 has more information in the logs?

**Comment by kristapsk** [comment]
It is fixed in 1.4.2.

**Comment by kristapsk** [comment]
No, it is not. App does not crash, but repost is not saved.

**Comment by alltheseas** [comment]
In what views does repost not work for you?

**Comment by kristapsk** [comment]
Today I tried both by opening profile and reposting from there and by opening post (note) directly. It shows it as reposted, but then I go to my profile and it's not there, and when I go back to the profile which post I tried to repost, repost icon isn't green anymore too.

**Comment by kristapsk** [comment]
Could it be possibly related to #767?

**Comment by alltheseas** [comment]
Can you go to profile -> posts & replies. Do you see the reposts there?

**Comment by kristapsk** [comment]
> Can you go to profile -> posts & replies. Do you see the reposts there?

They aren't there. That's where I checked. Even restarted app.

**Comment by alltheseas** [comment]
> > Can you go to profile -> posts & replies. Do you see the reposts there?
> 
> 
> 
> They aren't there. That's where I checked. Even restarted app.

@scoder1747 confirmed this is an iOS 15 bug

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/935

**Comment by kristapsk** [comment]
@alltheseas Just upgraded to 1.4.3, will test when I will notice some repostable content.

**Comment by kristapsk** [comment]
It's working now.
