### ISSUE TITLE
Current client log-in interferes with Damus contacts, and deletes them [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#842]
## User Story
As a Damus user who uses or tinkers with multiple clients, I would like Damus to make sure that other clients do not wipe my contacts list, so that I do not lose my contacts list on Damus, and don’t have to build it up from scratch again.

### Acceptance Criteria
1. When Damus user logs into Current (or other clients), Damus should *not* lose contact list

**Comment by jb55** [comment]
Closing in favor of 

- #1855
