### ISSUE TITLE
Damus icon in app directs user to Damus merch webpage

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#845]
Damus icon takes user to Damus merch webpage

![merch](https://github.com/damus-io/damus/assets/64376233/9ef48634-07a4-4308-96e3-572a59858d1c)

‌

====
# OLD: cannot tip in app per app store guidelines

## User Story
As a happy Damus user who wants to support Damus, I would like an easy way to send sats to the Damus Devs, so I can show my appreciation for the value I am receiving.

### Acceptance Criteria

1. Damus user can tap the Damus icon on the main timeline page
2. If Damus user taps the Damus icon, the zap screen appears
5. Damus user can zap, non-zap, anonymous zap and/or send sats to the Damus dev fund
‌
_Implementation details_
Could be a LNURL/static LN address

Related
#659

**Comment by alltheseas** [comment]
Nostr wallet connect rollout allows for donation of 1-100% of zap amount

**Comment by alltheseas** [comment]
<img width="678" alt="Screenshot 2023-06-28 at 12 53 34 AM" src="https://github.com/damus-io/damus/assets/64376233/44f915cd-83b9-47fc-a377-7cebb4e46d44">

**Comment by alltheseas** [comment]
@robagreda how might we design the "zap damus devs" feature?

**Comment by alltheseas** [comment]
@jb55 from side menu instead of Damus icon

**Comment by robagreda** [comment]
> @jb55 from side menu instead of Damus icon

So from the side menu will say: Store? and then open the damus store website?

**Comment by jb55** [comment]
On Mon, Oct 02, 2023 at 10:09:00AM -0700, Roberto wrote:
>> @jb55 from side menu instead of Damus icon
>
>So from the side menu will say: Store? and then open the damus store website?

"Merch" probably ? but yeah would open the store website

**Comment by robagreda** [comment]
Added the Mercha item to the side nav: https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=1147%3A27979&mode=design&t=gK2LCYQnWG2XFldF-1

![image](https://github.com/damus-io/damus/assets/3373850/52c64bef-277f-4619-8932-7310308ca81a)

**Comment by jb55** [comment]
On Mon, Oct 02, 2023 at 06:38:48PM -0700, Roberto wrote:
>Added the Mercha item to the side nav: https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=1147%3A27979&mode=design&t=gK2LCYQnWG2XFldF-1

thanks!

**Comment by danieldaquino** [comment]
Started working on this

**Comment by danieldaquino** [comment]
Sent a tentative patch for this over email: https://groups.google.com/a/damus.io/g/patches/c/3ihKeKvdSi0

The tentative patch uses a shopping basket instead of the store icon seen on @robagreda's design. That was the closest supported SF Symbol I could find.

I can try to import the actual icon used in Figma if needed, but I sent this simpler patch in case the shopping basket is suitable. Just let me know!


![Simulator Screenshot - iPhone 14 Pro - 2023-10-06 at 12 42 20](https://github.com/damus-io/damus/assets/24692108/b7e2fa66-4e7a-4e07-a151-dbff3f467431)
