### ISSUE TITLE
Pulling follower count/event count is super inefficient and bandwidth intensive [NIP-45][Bounty 300,000 sats]

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#85]
We probably shouldn't do this automatically when you open a profile anymore until we have a way to do stats on the protocol

**Comment by StevenBlack** [comment]
A manual refresh button would do it.

You could normalize it, display `---  ---` at the outset, every time. If and when the user cares, hit the button, pull the tallies. Pay-as-you-go behavior.

**Comment by BenGWeeks** [comment]
Until API, partial resolution in pull request https://github.com/damus-io/damus/pull/203 (see icon in screenshot).

**Comment by jblachly** [comment]
there is pending NIP PR for COUNT function which will be helpful: https://github.com/nostr-protocol/nips/pull/144

**Comment by brugeman** [comment]
There is a bounty here now, and NIP-45.
https://nostrbounties.com/b/naddr1qq9rzd3cxgungwf58yesygpn2m0xrvukg7f3e69jzs9jh2ur0cypps8029dmayk7qfyqgzutm5psgqqqw4rsquugx2

**Comment by alltheseas** [comment]
> We probably shouldn't do this automatically when you open a profile anymore until we have a way to do stats on the protocol

Original issue is fixed, as follower count pull is no longer automatic.

Issue is renamed to NIP-45 bounty per @brugeman suggestion.

**Comment by jb55** [comment]
> We probably shouldn't do this automatically when you open a profile anymore until we have a way to do stats on the protocol

yeah we did this a long time ago
