### ISSUE TITLE
Cannot tap on hashtag, while in note in hashtag view [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#850]
_what happens_
When I've clicked on a #hashtag in thread view, and I go to a post with another hashtag, and I click on the other hashtag nothing happens

_what I think should happen_

When I've clicked on a #hashtag in thread view, and I go to a post with another hashtag, and I click on the other hashtag I should be taken to the other #hashtag view. 

Video
https://user-images.githubusercontent.com/64376233/229264076-197592fb-892f-41e8-872d-9eafb6e2a41f.MOV

**Comment by jb55** [comment]
This should be fixed with the new nav changes

**Comment by alltheseas** [comment]
Confirmed
