### ISSUE TITLE
Add support for Zap Target [NIP-57][Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#875]
## User Story
As a Damus user who wants to benefit someone else, I would like the capability to add a zap target, so that I can dedicate all zaps from a particular note to one other nostr profile (npub).

### Acceptance Criteria
1. Damus user can set an optional zap target for each note, where Damus user can choose to send all (100%) of zaps to a given note to one other npub. 
2. If anyone zaps the zap target note, all zaps proceed to the zap target. 
3. The specified zap target is clearly visible to all in note. 

_implementation details_
Zap targets NIP: https://github.com/nostr-protocol/nips/pull/402#issuecomment-1494471771

Cc @ericholguin

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/888

**Comment by alltheseas** [comment]
@kiwiidb can you please help define zap tag for me outside of the spec for me 🙏 . 

Internally in damus we are defining "zap target" as 100% of zap goes to one (1) user who is specified in a note. 

Is this what you mean by "zap tag"?

**Comment by kiwiidb** [comment]
There is a user, let's call them kiwiidb, who has a Lightning Address in their profile `lud16`field: kiwiidb@getalby.com
This user then posts a note that has the following tag `[ "zap", "pablo@f7z.io", "lud16" ]`.
According to the spec, zaps on this note should go to `pablo@f7z.io`.
However it has been reported to me that if you use Damus (App Store version), zaps are in this case still going to `kiwiidb@getalby.com`.

**Comment by alltheseas** [comment]
Got you. Yes, we have not yet implemented this feature. I'll bring up with team.

**Comment by jb55** [comment]
lud16 zap targets are insecure, just because it's spec'd doesn't mean it is a good spec or damus will implement it. Damus will likely only do pubkey targets.

**Comment by jb55** [comment]
can't do this anymore
