### ISSUE TITLE
Add nostr over Tor Relay Support [feature request]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#876]
## User Story
As an advanced Damus user who is configuring relays, I would like to connect to nostr relays over tor on Damus, so that I can increase my privacy/censorship resistance. 

### Acceptance Criteria
1. Damus supports connecting to nostr relays over Tor network

@BenGWeeks

**Comment by BenGWeeks** [comment]
Related: https://github.com/iCepa/Tor.framework/issues/78#issuecomment-1521468571

**Comment by alltheseas** [comment]
Tor relays nostr:

ws://2pbkpndvpeebljfvjew6auq63lndzszqnntct5aqfmazslerzxe75kad.onion

From relayable

npub16fcy8ynknssdv7s487nh4p2h4vr3aun64lpfea45d7h4sts9jheqevshg

One more: note1fl7fx63spk2jgwhk2zacrh7fct8mg88uvjx346e3qhjeqm0q2gxqlg3507

**Comment by BenGWeeks** [comment]
Related: https://github.com/daltoniam/Starscream/issues/971

**Comment by alltheseas** [comment]
@jb55 advised connection to Damus relay can take place over Tor. 

I don't know the steps to join Damus relay via Tor, and I dont know if the same process might work for other relays.

**Comment by jb55** [comment]
On Sat, Sep 30, 2023 at 01:24:15PM -0700, alltheseas wrote:
>@jb55 advised connection to Damus relay can take place over Tor.

some users like Snowden are still having issues connecting to the damus
relay via Amethyst, even though I turned off all cloudflare tor
blocking. Still need to debug this... might remove cloudflare altogether
soon since I'm not getting much out of it.

**Comment by alltheseas** [comment]
> On Sat, Sep 30, 2023 at 01:24:15PM -0700, alltheseas wrote: @jb55 advised connection to Damus relay can take place over Tor.
> some users like Snowden are still having issues connecting to the damus relay via Amethyst, even though I turned off all cloudflare tor blocking. Still need to debug this... might remove cloudflare altogether soon since I'm not getting much out of it.

What are the steps to test connecting to Damus relay over Tor?

**Comment by alltheseas** [comment]
@TheSameCat2 has a Tor relay tested over Damus 

https://damus.io/note12us7mynfdfluvyh9t028czxmfylys432t92ul92yafwndfsc2knqk0g6sn

**Comment by TheSameCat2** [comment]
@alltheseas @jb55 note that this relay is on CloudFlare, but with DNS proxy disabled. 

There still seem to be some issues allowing signup with a paid relay, since the URL is different (callbacks, etc) but from the client end the connection has remained stable once added. 

Let me know if any team devs would like free access for testing.

**Comment by alltheseas** [comment]
https://damus.io/note1ncyzyxpdysm2sw57wantxzmsceqftp42rzseky53jfslwyg2a9dq3f8ta0

Tor cloudflare relay settings discussion

**Comment by alltheseas** [comment]
> > > On Sat, Sep 30, 2023 at 01:24:15PM -0700, alltheseas wrote: @jb55 advised connection to Damus relay can take place over Tor.
> > 
> > 
> > > some users like Snowden are still having issues connecting to the damus relay via Amethyst, even though I turned off all cloudflare tor blocking. Still need to debug this... might remove cloudflare altogether soon since I'm not getting much out of it.
> > 
> > 
> > What are the steps to test connecting to Damus relay over Tor?
> 
> Download Orbot, and allow it to add a VPN configuration. Tor on iOS uses the VPN to intercept traffic. Once connected, add an onion addressed relay, using insecure websockets (ws://).
> 
> Other relays should also work if they don't block exit node traffic. Out of my list, I believe all but two worked.

@BenGWeeks

**Comment by alltheseas** [comment]
https://damus.io/note1552mcx9qdu9r2cg8tpc0fzpktecut6g25s56s2z9a8mlp4ntvyvsrp9tep

One more tor relay

**Comment by alltheseas** [comment]
@alltheseas to test post relay fix update

note1qqqqrtx7hrzz4sfxgmt76magzw7n595nt8agt7qef4ayp0eetcgq2yc0n6

https://damus.io/nevent1qqsqqqqp4n0t33p2cynyd4ldd75p80f6z6f4n759lqv567jqhuu4uyqpp4mhxue69uhkummn9ekx7mqpz4mhxue69uhkummnw3ezu6twdaehgcfwvd3sz8rhwden5te0dehhxarj9e3xjarrda5kuetj9eek7cmfv9kqzxrhwden5te0wajkccm0d4jjumn0wd68ytnhd9hx2dr956y

**Comment by alltheseas** [comment]
@BenGWeeks tor relays are reported as working 

https://damus.io/nevent1qqszsp83mqv4llm3kq3kdz3nn2euff2hetqm8zuuex3nnl5nkql9glgpgdmhxw309ahx7um5wfkxzmnyxfnkgaehvuehjdehvd6xvar0wemxjmphxem8zatfwpuk6mehw3ekxarv0pcxjamtdejhv7nxd9jzummwd9hkuqfawaen5te0vf5hgcm0d9h8ydnyv56kc6mk0q68gurhv3kh5unyvej8qmrpx4ehjcfjv9n8wurrv93x5atsxfu8q6f4v36kccnpvsq5xamn8ghj7mmcw3exgetkv9mrvdr6xc68jc3h0qm8y6n8x3h8g7n3df5x2erdx43r27n2w96kcat8ddhxs7njxsmxu7fjw93xzepwdahxjmmwq9phwue69uhny6nndekxsenwv4kxjee4v93hzdnfv93hjerd0fjxyerdvumhsam4dekng7rvxechwcnk0fskxae5d3mhy6ndd3ukgtn0de5k7ms3ajvtr
