### ISSUE TITLE
How can we stop hell-thread spam?

### ISSUE THREAD

**Issue by 0xtrr** [damus-io/damus#885]
### Description
As a Damus user, it would be great to be able to "mute" a hell thread (a thread with a lot of people tagged). On the top of my head, I have two viable solutions.

### Possible solutions
1. Let a user mute the root event id and all events referencing that event id should do the trick. 
2. Give users a setting where they can select the maximum amount of referenced pubkeys in an event that they want notifications from. So if they set it to e.g. 20, any kind 1 event that has 21 or more "p" tags will not show up in their notifications.

I don't have sufficient knowledge with Swift and iOS dev so I'm not able to contribute this myself unfortunately.

**Comment by alltheseas** [comment]
Thanks for the suggestions. 

Here are the feature requests we have lined up:

1) Auto-mute hellthread https://github.com/damus-io/damus/issues/862
2) Mute this conversation https://github.com/damus-io/damus/issues/642
3) Mute note with presence of keyword https://github.com/damus-io/damus/issues/856

I think your 1. Maps to 2), and your 2. Maps to 1). 

If I didn’t get this wrong, and the previous feature requests capture your suggestions, can you kindly close this issue 🙏

**Comment by 0xtrr** [comment]
I agree, my request is basically a mix of both 1 and 2. I did try to check if there was a similar request before I made this one but I must have overlooked these.
