### ISSUE TITLE
Damus doesn't work completely at Maldives

### ISSUE THREAD

**Issue by Perlover** [damus-io/damus#889]
Yesterday I installed the Damus at Maldives man and it doesn't work completely (cannot edit profile, cannot add relay and etc...). Uninstalled and installed didn't help. Everything worked as if there was no Internet on the phone. Although if he specified my public key in the search, he found me and could read my posts (he sees my blurry images until he clicks on them). He couldn't update his profile, and if I tried to add relays from my profile to him from the relay tab, nothing just happened. Amethyst also works perfectly on my phone from the same network. I even connected it through my access point - the Damus app just behaved like a broken program. I still haven't figured out how I can help him.

Today other man from Maldives installed the Damus at iPhone and the app doesn't work too - the problem looks as if the application does not work the Internet. But all the other apps are working. I am sending screenshots of the versions iOs and Damus app:

https://i.imgur.com/iytWflz.jpg

https://i.imgur.com/JjsA615.jpg

https://i.imgur.com/cp3mkza.jpg

![IMG_20230407_143128_256.jpg](https://user-images.githubusercontent.com/574333/230575038-975bda6e-cae1-444c-8aad-155c247de5ee.jpg)
![IMG_20230407_143128_156.jpg](https://user-images.githubusercontent.com/574333/230575078-97778964-0bbf-4eb8-bb16-39f1472eaa27.jpg)
![IMG_20230407_143127_975.jpg](https://user-images.githubusercontent.com/574333/230575091-84ef8bd9-0466-47c9-a854-2f01fec49587.jpg)

**Comment by alltheseas** [comment]
Which Damus version & build are you on? 

Is this your first time using the app?

**Comment by Perlover** [comment]
> Which Damus version & build are you on? 
> 
> Is this your first time using the app?
> 
> Can you share your npub 🙏 ?

The versions - in first messages

I use not first time

Npub will not help to you - no posts from Damus and profile not added to Network. But if you very want to have a npub of Damus user: npub1eq0cn0y8lmfa93m9ymhyxvsud7r90vq56gle0cxrj4qr3zmxxnusy5pxyz

P.S. Did you read my first message before your post here?

**Comment by alltheseas** [comment]
> The versions - in first messages

Thank you for providing. 

> I use not first time
When did you first install Damus? 

> Npub will not help to you - no posts from Damus and profile not added to Network. But if you very want to have a npub of Damus user: npub1eq0cn0y8lmfa93m9ymhyxvsud7r90vq56gle0cxrj4qr3zmxxnusy5pxyz

In the first post you mentioned 
> Although if he specified my public key in the search, he found me and could read my posts 

Did you create two npubs, where the first one was published on nostr, and not the second?

**Comment by Perlover** [comment]
>  
> > The versions - in first messages
> 
> Thank you for providing. 
> 
> > I use not first time
> 
> When did you first install Damus?

I have Android and the Amethyst.
I installed the Damus at phone at Maldivian man

> 
> > Npub will not help to you - no posts from Damus and profile not added to Network. But if you very want to have a npub of Damus user: npub1eq0cn0y8lmfa93m9ymhyxvsud7r90vq56gle0cxrj4qr3zmxxnusy5pxyz
> 
> In the first post you mentioned

I installed at iPhone and have read my posts from there.
My npub is npub1p5ls8993zlhwfqet6v0wg9tn85pcdy5v0k4wq4f9fqll3j0tq34s6e8lw9

> > Although if he specified my public key in the search, he found me and could read my posts 

My posts - 1npub1p5ls8993zlhwfqet6v0wg9tn85pcdy5v0k4wq4f9fqll3j0tq34s6e8lw9

> 
> Did you create two npubs, where the first one was published on nostr, and not the second? 

Explained above.

P.S. The Damus doesn't work at another iPhone at second Maldivian man. They don't have problems with other apps at iPhone.

Maybe Apple is blocking websockets in the Maldives? Let me remind you that this does not depend on the network connection. I put another person in the Maldives Amethyst on Android and did not notice any problems. Therefore, I assume that the problem is either in the iPhone system and the country of Maldives, or

**Comment by Perlover** [comment]
I have decided to close this ticket as I have no further opportunity to test this issue. Also, I understand that Damus development on iPhone is being discontinued.

**Comment by jb55** [comment]
> I have decided to close this ticket as I have no further opportunity to test this issue. Also, I understand that Damus development on iPhone is being discontinued.

not true

**Comment by Perlover** [comment]
I may have gotten the wrong impression about the closure. I think I've seen messages in Nostr or in Twitter from you in recent months that you're leaving the iOS platform. Maybe I misunderstood your messages. I myself use Android.

But the lack of the app working in Maldives I observed for sure (no messages loaded). Even VPN didn't help. Maybe it had something to do with the country of the account (apple account) of the 
of the person I was trying to get Damus working (It was a hotel employee, but I think a local resident)
