### ISSUE TITLE
Good first issues?

### ISSUE THREAD

**Issue by mattsats** [damus-io/damus#890]
More of a meta issue -- I noticed there aren't any issues labeled "good first issue".

I just successfully compiled the damus master branch and am excited to start help contributing.

It is my first time using Swift, but not my first time hacking on an App. What are some good but low priority dev-related issues I can start with?

**Comment by alltheseas** [comment]
👋 @mattsats. Try recreating, and debugging this one:

https://github.com/damus-io/damus/issues/884

If you need help just reply here. Cc @tyiu

**Comment by alltheseas** [comment]
Another good first issue is fixing URLs: https://github.com/damus-io/damus/issues/278#issuecomment-1500561534

**Comment by mattsats** [comment]
I recreated the reaction bug. Where should I start throwing print statements? On first glance maybe ReactionModel or ReactionView

**Comment by tyiu** [comment]
> I recreated the reaction bug. Where should I start throwing print statements? On first glance maybe ReactionModel or ReactionView

Not sure. When in doubt, do it everywhere. Also, make use of breakpoints -- they help a lot.

**Comment by alltheseas** [comment]
How are you doing with this @mattsats ?
