### ISSUE TITLE
Share from other iOS apps to Damus (iOS Share Extension) 

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#906]
## User Story
As a Damus user who uses other iOS apps with share-able content, I want to be able to use the apple share capability, so that I can easily share from other apps (e.g. photos) to Damus.

### Acceptance Criteria
1. iOS user can use apple share extension functionality to share from other apps to Damus

_implementation details_
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html

Origin: @bryanmontz

**Comment by urza** [comment]
+1  would like to be able to share URL from safari and images from photos

**Comment by jb55** [comment]
Now that we have the basic template from our highlight share extension we can adapt it for this.

**Comment by alltheseas** [comment]
Customer feedback

https://damus.io/nevent1qqsyj022h5yghkhm6yfrapsjpkzx72lfgeeufdhdn09whrnwls53e8qpremhxue69uhkummnw3ez6un9d3shjtnyv4ex26mjdaehxtndv5q32amnwvaz7tmhda6zumn0wd68ytnsv9e8g7gpzpmhxue69uhkummnw3ezuamfdejsz9thwden5te0dehhxarjv4kxjar9wvhx7un8ffg6m5

> I’ve been using Damus on my bhiPhone, and I noticed that it doesn’t appear in the iOS share menu. Are there any apps that supports this feature?

**Comment by alltheseas** [comment]
@scoder1747 👀

**Comment by alltheseas** [comment]
@scoder1747 to tackle :eyes:

**Comment by alltheseas** [comment]
@jb55 advised

> we already have a safari highlight share extension, we just need to take that code and use it in a real share extension

**Comment by scoder1747** [comment]
I have marked this as closed since the implementation has been completed.
