### ISSUE TITLE
Render @nevent

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#909]
Example 

https://damus.io/note1n682gaw3vzs4uydut7mlq2gtkhx0t9zmppg2l4tyr82xqt9kefyqgrevtw

![image](https://user-images.githubusercontent.com/64376233/231346015-74e114b4-79c7-480d-a891-c378f965582e.jpeg)

**Comment by alltheseas** [comment]
nostr:nevent works

https://damus.io/note1v4dhvcedu00kl294693n5re3et5vtwm97cne7ynltt2uscc8x6nq734fcv

"nostr:nevent1qqsvkyhk69gp4awxlnmwra6kw3jksm0v0zgdtmra092xzgwyf9lldvs5nhqaq"

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/019baaf0-7a8f-4c70-963e-26ea154d10c5)

**Comment by kernelkind** [comment]
> ![image](https://private-user-images.githubusercontent.com/64376233/240051031-019baaf0-7a8f-4c70-963e-26ea154d10c5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDE5MTIsIm5iZiI6MTcwMzcwMTYxMiwicGF0aCI6Ii82NDM3NjIzMy8yNDAwNTEwMzEtMDE5YmFhZjAtN2E4Zi00YzcwLTk2M2UtMjZlYTE1NGQxMGM1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxODI2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTc4OWRlMjcyMjI4NmRmNmI0MmY5MjRiNDc5ZWE0ZmVhNDE5MzA1NzVjMGE5OGJlNDFmZTk0Y2I3ZTFkODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3dqXxI66HbwCh06723JHCzMY8vXgX-Sw1fqxSQdTOzQ)

Is this supposed to render the event where the "Could not find the user you're looking for" section is before posting?

**Comment by alltheseas** [comment]
Looks like nevent is rendered in post now. 

Damus user should be able to search in universe view for nevent. Creating new issue for this shortly.

**Comment by alltheseas** [comment]
@kernelkind see search for nevent ticket:

https://github.com/damus-io/damus/issues/1650

**Comment by jb55** [comment]
we currently don't use the relays in nevent to lookup the mentioned event though. this should be a new ticket

**Comment by alltheseas** [comment]
> we currently don't use the relays in nevent to lookup the mentioned event though. this should be a new ticket

Is the above different than https://github.com/damus-io/damus/issues/1650?
