### ISSUE TITLE
[Feature Request] Add IPFS support for images and files

### ISSUE THREAD

**Issue by thegamebegins25** [damus-io/damus#91]
Let files/images load from IPFS when a post contains `ipfs://[cid]`. First, check if the file is an image, then add a button in the post to load the image. If it is a file, add a download button that will download it to Files. All of this can be done by using an external gateway _or_ a local node. This would help with Nostr's vision of decentralization, as having files always link to external sources using DNS is centralized. 

If Damus includes a local IPFS node, then there could be a built-in file uploader that stores files not only on your machine, but with a pinning service as well. Damus could also run its own gateway just like it runs its own relay.

Hope this is a reasonable idea!

**Comment by kdunn926** [comment]
The same idea under discussion in [Amethyst](https://github.com/vitorpamplona/amethyst/issues/66) - it would be great to see `ipfs://` support in both clients.

It seems there is a lightweight IOS [IPFS client](https://github.com/textileio/ios-ipfs-lite) that can do media `get`/`put` without needing a full IPFS node.

**Comment by jb55** [comment]
not a fan of ipfs tbh
