### ISSUE TITLE
Multiple mentions break hyperlinks of @username (@npub display as #[3], #[4] etc.) [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#922]
_what happens_
Instead of names, or hyperlinks, only  #[3], #[4] is displayed

![image](https://user-images.githubusercontent.com/64376233/232161457-0f27f14d-1fc4-406b-b6e8-58ee1a3bd849.jpeg)

https://damus.io/note1rttctwwvhyclchzctc5f3d0076ynp97zdw2m59qlar24n2n6lufqn24u0z

_what I think should happen_
There should be no #[3], #[4] displayed in lieu of hyperlinked @ names

**Comment by alltheseas** [comment]
> benweeks9: Suspect lack of spaces caused it.
> Tyiu: Funny thing is that I got the notification in Damus even though my mention doesn’t render

**Comment by tyiu** [comment]
This looks fixed.
