### ISSUE TITLE
Enable Private Relays [500,000 sats] NIP-42

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#940]
## User Story
As a Damus user who wants to connect with a particular group of nostriches privately, I want to be able to connect to a private relay, so that I can read and share notes only with a specific group of nostriches. 

### Acceptance Criteria
1. Damus user can connect to a private relay
2. Damus user has a method to provide authentication details to a private relay
3. Damus user can check visually if they are successfully connected to the private relay
4. Damus user can remove a private relay
4. Damus user can de-authenticate from a private relay

_implementation details_
[NIP-42](https://github.com/nostr-protocol/nips/blob/master/42.md)

_relates to_
https://github.com/damus-io/damus/issues/453

Origin: https://damus.io/note1c6khgk6phxzhq7hh2v32nhzrvlyn4y2ctk6h0kgtgfrgrh7y7e5qma8ykl

**Comment by nostr-wine** [comment]
We'll offer a 500k sats bounty per client for this feature.

**Comment by LouisSaberhagen** [comment]
Is there a private relay where we can test out the implementation?

**Comment by nostr-wine** [comment]
Yes! You can use wss://filter.nostr.wine or wss://nostr.kollider.xyz

**Comment by nostr-wine** [comment]
Any takers?

**Comment by jb55** [comment]
I’ll do this soon

**Comment by nostr-wine** [comment]
Thanks Will! Much appreciated.

**Comment by fishcharlie** [comment]
@jb55 You mentioned that you'll do this soon a while back. Are you working on this?

If not, I'd love to take a shot at contributing and trying to implement this. I'll keep everyone updated on my progress here.

But I don't wanna step on your toes @jb55 if you're already working on it.

**Comment by alltheseas** [comment]
Go for it @fishcharlie

**Comment by fishcharlie** [comment]
Awesome. I'll start looking into this this evening and hopefully will have something sometime this week to show.

**Comment by fishcharlie** [comment]
https://groups.google.com/a/damus.io/g/patches/c/vDHayh8vRhA

**Comment by jb55** [comment]
it looks pretty good! I just need a way to test it.

**Comment by nostr-wine** [comment]
If you're looking for relays, here are two different AUTH flows:

wss://filter.nostr.wine - AUTH on connect, only allows paid pubkeys are accepted
wss://nostr.wine - AUTH on kind 4 REQs, allows all pubkeys

**Comment by jb55** [comment]
@fishcharlie maybe we could have some tests for these relays?

**Comment by fishcharlie** [comment]
@jb55 Open to that idea. My question would be does Damus have any tests currently that depend on 3rd party relays? Not saying that @nostr-wine won't survive for a long time to come. But that is a pretty major dependency that we'd be introducing to the Damus test suite.

It might be better to just mock the requests and replies. But I'm open to creating a connection to those relays if you want.

**Comment by fishcharlie** [comment]
For the time being I'm currently working on writing a test that verifies that based on the objects that the correct message is generated.

Similar to RequestTests.swift testMakeUnsubscribeRequest (but for the auth).

**Comment by jb55** [comment]
On Thu, Dec 21, 2023 at 06:05:17PM -0800, Charlie Fish wrote:
>@jb55 Open to that idea. My question would be does Damus have any tests
>currently that depend on 3rd party relays? Not saying that @nostr-wine
>won't survive for a long time to come. But that is a pretty major
>dependency that we'd be introducing to the Damus test suite.

I'm not against network tests. we had one for nostrscript at one point

They tend to be flaky, but it would be nice to see it working against a
non-mocked target for the first release.

**Comment by fishcharlie** [comment]
@jb55 Sounds good. I'll work on that and let you know when I have an update.

**Comment by fishcharlie** [comment]
@jb55 Added some tests: https://groups.google.com/a/damus.io/g/patches/c/2qtxxQysAEM. Also added NIP-42 to the README since I forgot to do that originally.

Let me know what you think 😃

**Comment by jb55** [comment]
bounties can be paid to: fishcharlie@strike.me 

@nostr-wine

**Comment by nostr-wine** [comment]
Paid! Awesome work @fishcharlie, thanks for merging @jb55.

**Comment by fishcharlie** [comment]
Thank you @nostr-wine! 🎉
