### ISSUE TITLE
Unfollow requires app restart or reconnect

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#942]
![image](https://user-images.githubusercontent.com/64376233/232346377-eb887bf6-6781-4a83-b657-b274ccb044d9.jpeg)

https://damus.io/note1fsc8genj00y8lz7cgd3d5zrjtc48r67w88md7wvwrf8kjes8fx0q9ykdvg

**Comment by jb55** [comment]
Duplicate of 

- #92
