### ISSUE TITLE
Hashtags in foreign languages 

### ISSUE THREAD

**Issue by lima46zulu** [damus-io/damus#949]
Damus doesn't render hashtags in foreign languages properly. Same issue with accented characters. 

Many countries are using english hashtags, but most if not all popular hashtags in Japan are in Japanese. For example [写真好きな人と繋がりたい](https://twitter.com/hashtag/%E5%86%99%E7%9C%9F%E5%A5%BD%E3%81%8D%E3%81%AA%E4%BA%BA%E3%81%A8%E7%B9%8B%E3%81%8C%E3%82%8A%E3%81%9F%E3%81%84?src=hashtag_click).

Link to test note: https://damus.io/note10l0fzzkwfk45ckyc6swkyddeplc62xhqqxe4faln2c9g3fgv6ftqqvl06r

![IMG_5284](https://user-images.githubusercontent.com/109115349/232501949-c99913d8-0584-4938-b6e8-4e0722b663a9.jpeg)

**Comment by alltheseas** [comment]
Thank you for submitting. This is in the backlog 🙏

**Comment by garyray-k** [comment]
https://forums.swift.org/t/how-to-include-accented-characters-in-swift-url-without-percent-encoding/39215

**Comment by garyray-k** [comment]
After digging into this for a bit, I think the bug lies somewhere in `damus.c`'s `parse_hashtag` function. Specifically the `consume_until_boundary` -> `is_boundary(c)` call. `is_boundary` uses `isalnum(c)` which does not account for symbols or non-English characters.

Noting these things here so I can draft a PR sometime later. My only hesitation is if this "boundary" checking is used elsewhere, there may be second/third order effects from changing this that are not accounted for yet.

**Comment by alltheseas** [comment]
@lima46zulu can you correct issue title to correct spelling of `Hashtags`, so this ticket is searchable 🙏

**Comment by velram** [comment]
Is anyone working on this issue? If not shall I pickup this issue?

**Comment by velram** [comment]
> After digging into this for a bit, I think the bug lies somewhere in `damus.c`'s `parse_hashtag` function. Specifically the `consume_until_boundary` -> `is_boundary(c)` call. `is_boundary` uses `isalnum(c)` which does not account for symbols or non-English characters.
> 
> ~Noting these things here so I can draft a PR sometime later. My only hesitation is if this "boundary" checking is used elsewhere, there may be second/third order effects from changing this that are not accounted for yet.~
> 
> Edit: I lack the C experience/knowledge to complete this.

Hi. Are you working on this issue?

**Comment by alltheseas** [comment]
@tyiu you working on this one?

**Comment by alltheseas** [comment]
> ..there may be some difficulties in searching for notes with international hashtags. This is because not all the clients set the 't' tag in their #nostr  events using non-english hashtags

https://damus.io/note1yhqwzx9tkt2q5xund6a724cww9zwjd5xqsg6lp804hf3a9kq62fq32hd79

**Comment by vivganes** [comment]
I wrote a proposal for a possible fix at https://damus.io/note1a0s2ezrffdpqef9p5eapwj37fgvd6w4qgzqzm6554s6zyvzyk0ssujwvnn

Unfortunately, I dont have a dev setup for iOS.  So, I cant do a PR.  If the proposal I outlined here looks good, anyone can put in a PR :) 

This may unlock the power of hashtags for all languages 💙💙💙
