### ISSUE TITLE
Close (x) image on Mac does nothing [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#972]
> Will , my friend! Damus in a Mac is having an odd bug when I click a photo, the cross icon to shut the image does not work at all :)

https://damus.io/note144lfksahqu68yf5ppgqqvglame2wvyp3ar6nkkqlrudqqu8xpexsgqzrgd

**Comment by jb55** [comment]
can't reproduce :(

**Comment by alltheseas** [comment]
Resolved 1.4.3
