### ISSUE TITLE
Cannot update profile

### ISSUE THREAD

**Issue by flyingisawol** [damus-io/damus#98]
Not sure if this is isolated or if others are experiencing the same issue.. ?

Damus iOS client v0.17 running iOS 16.1.2

once i click top right and view profile show page, there is no way of adding an image, editing name, or adding any info whatsoever

**Comment by lionello** [comment]
See also #38

**Comment by bebopkid** [comment]
See also #13

**Comment by alltheseas** [comment]
Does not remain an issue in 1.5
