### ISSUE TITLE
Add Morse Code Support [feature request][localization][UX]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#989]
## User Story

As a worldly Damus enjoyer, I woud like to read morse code in my language, so that I can converse with the morse code speakers.

### Acceptance Criteria
1. Damus detects morse code
2. Damus supports translate from morse code

cc @tyiu 😁

_implementation example_
https://codereview.stackexchange.com/questions/259634/simple-morse-code-converter-python

**Comment by jb55** [comment]
not sure about this one lol

**Comment by alltheseas** [comment]
🤠
