### ISSUE TITLE
In search when typing username, keep getting kicked back to search

### ISSUE THREAD

**Issue by bebopkid** [damus-io/damus#99]
Typing out a username > click it > see the profile and then immediately get punted back to search? Happens several times before finally letting me get to the profile

**Comment by 0xtlt** [comment]
I can't reproduce the bug, can you retry ?
And maybe screen record to have more context

**Comment by deankroker** [comment]
@0xtlt I was able to repro. Here's a video https://user-images.githubusercontent.com/9809445/209515496-e4ffda3e-1b49-45bd-afa2-aad1f0d46950.MOV

**Comment by ericholguin** [comment]
This has been fixed
